### ISSUE TITLE
Found with fuzzer: "placing %s over %s at <%d,%d>, mstates:%lx %lx on %s?"

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#10]
Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7365859 in __GI_abort () at abort.c:79
#2  0x0000555555a44c60 in NH_abort () at end.c:236
#3  0x0000555555a4ba5c in panic (str=0x55555651b6c0 "%s") at end.c:802
#4  0x0000555555f98c03 in impossible (
    s=0x555556570620 "placing %s over %s at <%d,%d>, mstates:%lx %lx on %s?") at pline.c:518
#5  0x000055555618d513 in place_monster (mon=0x61100096e8c0, x=16, y=10) at steed.c:1164
#6  0x0000555555bfec74 in gulpmm (magr=0x61100096e8c0, mdef=0x6110009d6d80, mattk=0x0)
    at mhitm.c:1177
#7  0x0000555555be7011 in mattackm (magr=0x61100096e8c0, mdef=0x7fffffffccf0) at mhitm.c:739
#8  0x0000555555e52c5d in m_move_aggress (mtmp=0x61100096e8c0, x=16 '\020', y=10 '\n')
    at monmove.c:2056
#9  0x0000555555e44a9c in m_move (mtmp=0x61100096e8c0, after=1) at monmove.c:1690
#10 0x0000555555e373a6 in dochug (mtmp=0x61100096e8c0) at monmove.c:912
#11 0x0000555555e23336 in dochugw (mtmp=0x61100096e8c0) at monmove.c:122
#12 0x0000555555d92b75 in movemon () at mon.c:1509
#13 0x000055555575b28a in moveloop (resuming=0 '\000') at allmain.c:244
#14 0x00005555563b4127 in main (argc=0, argv=0x7fffffffe658) at ../sys/unix/unixmain.c:353
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {0, 0, 0, 0, 0, 140737337632192, 93824997411122, 335544320, 
            140737341055120, 1073741824, 0, 140737342801568, 4294967295, 140737337360384, 
            140737342784672, 12720683612702088960}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007ffff7365859 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0xffffffff, sa_sigaction = 0xffffffff}, 
          sa_mask = {__val = {140737337360384, 140737342784672, 12720683612702088960, 
              140737488342512, 140737342801568, 18446744073709547520, 140737327112192, 
              140737345470680, 140737488343584, 140737488343584, 140737344339986, 
              17592186042814, 140737488334848, 140737341055120, 12720683612702088960, 
              140737488342912}}, sa_flags = 1128111872, sa_restorer = 0x7fffffffd140}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x0000555555a44c60 in NH_abort () at end.c:236
        gdb_prio = 1
        libc_prio = 2
        aborting = 1 '\001'
#3  0x0000555555a4ba5c in panic (str=0x55555651b6c0 "%s") at end.c:802
        the_args = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7fffffffd210, 
            reg_save_area = 0x7fffffffd140}}
#4  0x0000555555f98c03 in impossible (
    s=0x555556570620 "placing %s over %s at <%d,%d>, mstates:%lx %lx on %s?") at pline.c:518
        pbuf = "placing energy vortex <16,10> over dungeon fern sprout <16,10> at <16,10>, mstates:0 0 on Dlvl:4  ?\000\377\377\377\377\n\000\000\030\000\000\000\000\263\212\265A\000\000\000\000\340kMVUU\000\000\277\325\333UUU\000\000\000\237=C\000\362\210\260\020\n\000\000\000\000\000\000\200m\235\000\020a\000\000\n\000\000\000\000\000\000\000\001\000\000\000\v\000\000\000\240\324\377\377\377\177\000\000\000\000\000\000\000\000\000\000\n\000\000\000\000\000\000\000"...
        the_args = {{gp_offset = 48, fp_offset = 48, overflow_arg_area = 0x7fffffffd910, 
            reg_save_area = 0x7fffffffd820}}
#5  0x000055555618d513 in place_monster (mon=0x61100096e8c0, x=16, y=10) at steed.c:1164
        othermon = 0x6110009d73c0
        monnm = 0x5555567c03a0 <bufs+768> "energy vortex <16,10>"
        othnm = 0x5555567c04a0 <bufs+1024> "dungeon fern sprout <16,10>"
        buf = "Dlvl:4  ", '\000' <repeats 72 times>, "\340\331\377\377\377\177\000\000\036\004\217UUU\000\000\000\000\000\000\272\022\000\000\n\000\000\000\020", '\000' <repeats 18 times>
#6  0x0000555555bfec74 in gulpmm (magr=0x61100096e8c0, mdef=0x6110009d6d80, mattk=0x0)
    at mhitm.c:1177
        ax = 17 '\021'
        ay = 10 '\n'
        dx = 16 '\020'
        dy = 10 '\n'
        status = 2
        buf = "0\334\377\377\377\177\000\000\rk\315UUU\000\000\377\377\377\377\377\377\377\377\200\333\377\377\377\177\000\000\300\346_VUU\000\000\000\360\232\000\020a\000\000\263\212\265A\000\000\000\000\377\377\377\377\000\000\000\000\a\037\346UUU\000\000j\033\346UUU\000\000\000\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\000\000\000\000", '\377' <repeats 12 times>, "\300\236=\001\300`\000\000\000\237=CY\362\210\260\000\000\000\000\000\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\001\000\000\000\000\000\000\000\377\377\377\377\263\212\265A\000\000\000\000\260oLVUU\000\000y\030\314UUU\000\000\020\202rVUU\000\000\300\333\377\377\377\177\000\000"...
        obj = 0x0
        otmp = 0x7fffffffdb80
        msteed = 0x0
#7  0x0000555555be7011 in mattackm (magr=0x61100096e8c0, mdef=0x7fffffffccf0) at mhitm.c:739
        i = 0
        tmp = 14
        strike = 1
        attk = 1
        struck = 0
        res = {0, 32767, 1440797221, 21845, 9, 7}
        k = 0
        dieroll = 0
        saved_mhp = 3
        mattk = 0x5555565fb4c8 <mons+29864>
        alt_attk = {aatyp = 96 '`', adtyp = 222 '\336', damn = 255 '\377', damd = 0 '\000'}
        mwep = 0x0
        marmf = 0x0
        pa = 0x5555565fb4b8 <mons+29848>
#8  0x0000555555e52c5d in m_move_aggress (mtmp=0x61100096e8c0, x=16 '\020', y=10 '\n')
    at monmove.c:2056
        mtmp2 = 0x6110009d6d80
        mstatus = 24848
#9  0x0000555555e44a9c in m_move (mtmp=0x61100096e8c0, after=1) at monmove.c:1690
        appr = <optimized out>
        gx = 5 '\005'
        gy = 10 '\n'
        nix = 16 '\020'
        niy = 10 '\n'
        chcnt = 0 '\000'
        i = 1
        j = 0
        chi = 0
        likegold = 0 '\000'
        likegems = 0 '\000'
        likeobjs = 0 '\000'
        likemagic = 0 '\000'
        conceals = 0 '\000'
        likerock = 0 '\000'
        can_tunnel = 0 '\000'
        can_open = 0 '\000'
        can_unlock = 0 '\000'
        doorbuster = 0 '\000'
        uses_items = 0 '\000'
        setlikes = 1 '\001'
        avoid = 0 '\000'
        better_with_displacing = 0 '\000'
        sawmon = 0 '\000'
        ptr = 0x5555565fb4b8 <mons+29848>
        mtoo = 0x200000007
        mmoved = 1 '\001'
        info = {2621440, 0, -1, 4294967296, 21474836490, 106721357260992, 21484990474, 
          93825010926096, 140737488347408}
        flag = 268697600
        omx = 17
        omy = 10
        offer = 32767
#10 0x0000555555e373a6 in dochug (mtmp=0x61100096e8c0) at monmove.c:912
        mdat = 0x5555565fb4b8 <mons+29848>
        tmp = <optimized out>
        mdummy = 0x0
        inrange = 0
        nearby = 0
        scared = 0
        oldx = 0
        oldy = 0
        mwalk_sewage = 0 '\000'
#11 0x0000555555e23336 in dochugw (mtmp=0x61100096e8c0) at monmove.c:122
        x = 17
        y = 10
        already_saw_mon = 0 '\000'
        rd = 300
#12 0x0000555555d92b75 in movemon () at mon.c:1509
        mtmp = 0x61100096e8c0
        nmtmp = 0x61100096ea00
        somebody_can_move = 1 '\001'
#13 0x000055555575b28a in moveloop (resuming=0 '\000') at allmain.c:244
        moveamt = 12
        wtcap = 0
        change = 0
        monscanmove = 0 '\000'
        timeout_start = 25641
        past_clock = 60351
        elf_regen = 1 '\001'
        orc_regen = 1 '\001'
        vamp_regen = 1 '\001'
#14 0x00005555563b4127 in main (argc=0, argv=0x7fffffffe658) at ../sys/unix/unixmain.c:353
        fd = -1
        dir = 0x0
        exact_username = 0 '\000'
        resuming = 0 '\000'
        plsel_once = 1 '\001'

**Comment by elunna** [comment]
Popped up again with a green slime
