### ISSUE TITLE
LeakSanitizer: Memory leaks in Black Market (Only in the Unnethack version)

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#101]
```
==26222==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 160 byte(s) in 10 object(s) allocated from:
    #0 0x7ff1d9134808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x55c2ade42496 in alloc /home/lunatunez/hackem/src/alloc.c:46
    #2 0x55c2ae81fc2d in opvar_clone /home/lunatunez/hackem/src/sp_lev.c:455
    #3 0x55c2ae84e264 in sp_level_coder /home/lunatunez/hackem/src/sp_lev.c:5653
    #4 0x55c2ae8532f4 in load_special /home/lunatunez/hackem/src/sp_lev.c:6340
    #5 0x55c2ae42b038 in makemaz /home/lunatunez/hackem/src/mkmaze.c:1028
    #6 0x55c2ae41498d in makelevel /home/lunatunez/hackem/src/mklev.c:924
    #7 0x55c2ae418027 in mklev /home/lunatunez/hackem/src/mklev.c:1379
    #8 0x55c2adfeebba in goto_level /home/lunatunez/hackem/src/do.c:1914
    #9 0x55c2adff2460 in deferred_goto /home/lunatunez/hackem/src/do.c:2284
    #10 0x55c2ade3edab in moveloop /home/lunatunez/hackem/src/allmain.c:829
    #11 0x55c2aeab026a in main ../sys/unix/unixmain.c:353
    #12 0x7ff1d8e00082 in __libc_start_main ../csu/libc-start.c:308

Indirect leak of 30 byte(s) in 10 object(s) allocated from:
    #0 0x7ff1d9134808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x55c2ade42496 in alloc /home/lunatunez/hackem/src/alloc.c:46
    #2 0x55c2ade42555 in dupstr /home/lunatunez/hackem/src/alloc.c:162
    #3 0x55c2ae81fd76 in opvar_clone /home/lunatunez/hackem/src/sp_lev.c:469
    #4 0x55c2ae84e264 in sp_level_coder /home/lunatunez/hackem/src/sp_lev.c:5653
    #5 0x55c2ae8532f4 in load_special /home/lunatunez/hackem/src/sp_lev.c:6340
    #6 0x55c2ae42b038 in makemaz /home/lunatunez/hackem/src/mkmaze.c:1028
    #7 0x55c2ae41498d in makelevel /home/lunatunez/hackem/src/mklev.c:924
    #8 0x55c2ae418027 in mklev /home/lunatunez/hackem/src/mklev.c:1379
    #9 0x55c2adfeebba in goto_level /home/lunatunez/hackem/src/do.c:1914
    #10 0x55c2adff2460 in deferred_goto /home/lunatunez/hackem/src/do.c:2284
    #11 0x55c2ade3edab in moveloop /home/lunatunez/hackem/src/allmain.c:829
    #12 0x55c2aeab026a in main ../sys/unix/unixmain.c:353
    #13 0x7ff1d8e00082 in __libc_start_main ../csu/libc-start.c:308

SUMMARY: AddressSanitizer: 190 byte(s) leaked in 20 allocation(s).
```

**Comment by elunna** [comment]
To reproduce: Start a new game, warp to the black market, enter the portal to the Unnethack version, then save out.

**Comment by elunna** [comment]
Disabled the Un black market until memory leak is debugged.
