### ISSUE TITLE
Found with fuzzer: timer sanity: melt timer 29777 on non-ice 17 <77,6>

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#104]
I thought I had fixed this in issue #23, but I guess not.

```
Suddenly, the dungeon collapses.
timer sanity: melt timer 29777 on non-ice 17 <77,6>
Generating more information you may report:

[0] /lib/x86_64-linux-gnu/libasan.so.5(+0x6cd40) [0x7ffff75f8d40]
[1] /home/lunatunez/games/hackemdir/hackem(+0x50abf3) [0x555555a5ebf3]
[2] /home/lunatunez/games/hackemdir/hackem(+0x50aae6) [0x555555a5eae6]
[3] /home/lunatunez/games/hackemdir/hackem(panic+0x6ab) [0x555555a6599b]
[4] /home/lunatunez/games/hackemdir/hackem(impossible+0x2c8) [0x555555fcc31a]
[5] /home/lunatunez/games/hackemdir/hackem(timer_sanity_check+0x36f) [0x5555561fa0d1]
[6] /home/lunatunez/games/hackemdir/hackem(sanity_check+0x12) [0x555555872b12]
[7] /home/lunatunez/games/hackemdir/hackem(moveloop+0x6c1c) [0x555555771842]
[8] /home/lunatunez/games/hackemdir/hackem(main+0xdda) [0x555556402cae]
[9] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7ffff7365083]
[10] /home/lunatunez/games/hackemdir/hackem(_start+0x2e) [0x555555768ace]


Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7363859 in __GI_abort () at abort.c:79
#2  0x0000555555a5eb0c in NH_abort () at end.c:236
#3  0x0000555555a6599b in panic (str=0x555556575b60 "%s") at end.c:802
#4  0x0000555555fcc31a in impossible (
    s=0x5555565d5900 "timer sanity: melt timer %ld on non-ice %d <%d,%d>") at pline.c:518
#5  0x00005555561fa0d1 in timer_sanity_check () at timeout.c:2476
#6  0x0000555555872b12 in sanity_check () at cmd.c:4886
#7  0x0000555555771842 in moveloop (resuming=0 '\000') at allmain.c:795
#8  0x0000555556402cae in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {0, 0, 0, 0, 0, 140737335783280, 93824997517278, 335544320, 
            140737341046928, 1073741824, 0, 140737342793376, 4294967295, 140737337360384, 
            140737342776480, 1652449290637586944}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007ffff7363859 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0xffffffff, sa_sigaction = 0xffffffff}, 
          sa_mask = {__val = {140737337360384, 140737342776480, 1652449290637586944, 
              140737488345296, 140737342793376, 18446744073709547520, 140737327104000, 
              140737345462488, 140737488346368, 140737488346368, 140737344331794, 
              17592186043162, 140737488338944, 140737341046928, 1652449290637586944, 
              140737488345696}}, sa_flags = -238243328, sa_restorer = 0x7fffffffdc20}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x0000555555a5eb0c in NH_abort () at end.c:236
        gdb_prio = 1
        libc_prio = 2
        aborting = 1 '\001'
#3  0x0000555555a6599b in panic (str=0x555556575b60 "%s") at end.c:802
        the_args = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7fffffffdcf0, 
            reg_save_area = 0x7fffffffdc20}}
#4  0x0000555555fcc31a in impossible (
    s=0x5555565d5900 "timer sanity: melt timer %ld on non-ice %d <%d,%d>") at pline.c:518
        pbuf = "timer sanity: melt timer 29777 on non-ice 17 <77,6>", '\000' <repeats 661 times>...
        the_args = {{gp_offset = 40, fp_offset = 48, overflow_arg_area = 0x7fffffffe3e0, 
            reg_save_area = 0x7fffffffe300}}
#5  0x00005555561fa0d1 in timer_sanity_check () at timeout.c:2476
        where = 5046278
        x = 77 'M'
        y = 6 '\006'
        curr = 0x604003d33290
#6  0x0000555555872b12 in sanity_check () at cmd.c:4886
No locals.
#7  0x0000555555771842 in moveloop (resuming=0 '\000') at allmain.c:795
        moveamt = 3
        wtcap = 4
        change = 0
        monscanmove = 0 '\000'
        elf_regen = 1 '\001'
        orc_regen = 1 '\001'
        vamp_regen = 1 '\001'
#8  0x0000555556402cae in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
        fd = -1
        dir = 0x0
        exact_username = 0 '\000'
        resuming = 0 '\000'
        plsel_once = 1 '\001'
```

**Comment by elunna** [comment]
Steps to reproduce:

- Make sure "sanity_check" option is ON.
- Wish for wand of cold and wand of digging.
- Wish for a pool/moat
- Freeze the moat with the wand of cold
- Walk onto the ice, zap down with the wand of digging. 
- Return to the level if necessary.

This bug is present in HackEM and EvilHack, maybe in vanilla as well but as of now I have not tested that.
