### ISSUE TITLE
Found with fuzzer: eel hiding out of water (fmon)

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#106]
```
eel hiding out of water (fmon)
Generating more information you may report:

[0] /lib/x86_64-linux-gnu/libasan.so.5(+0x6cd40) [0x7ffff75f8d40]
[1] /home/lunatunez/games/hackemdir/hackem(+0x5093e4) [0x555555a5d3e4]
[2] /home/lunatunez/games/hackemdir/hackem(+0x5092d7) [0x555555a5d2d7]
[3] /home/lunatunez/games/hackemdir/hackem(panic+0x6ab) [0x555555a6418c]
[4] /home/lunatunez/games/hackemdir/hackem(impossible+0x2c8) [0x555555fc8e77]
[5] /home/lunatunez/games/hackemdir/hackem(+0x83302b) [0x555555d8702b]
[6] /home/lunatunez/games/hackemdir/hackem(mon_sanity_check+0x5b) [0x555555d87300]
[7] /home/lunatunez/games/hackemdir/hackem(sanity_check+0x17) [0x55555587341c]
[8] /home/lunatunez/games/hackemdir/hackem(moveloop+0x6cab) [0x5555557728d1]
[9] /home/lunatunez/games/hackemdir/hackem(main+0xdda) [0x5555563fcecc]
[10] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7ffff7365083]
[11] /home/lunatunez/games/hackemdir/hackem(_start+0x2e) [0x555555769ace]


Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7363859 in __GI_abort () at abort.c:79
#2  0x0000555555a5d2fd in NH_abort () at end.c:236
#3  0x0000555555a6418c in panic (str=0x55555656ff80 "%s") at end.c:802
#4  0x0000555555fc8e77 in impossible (s=0x555556525960 "eel hiding out of water (%s)")
    at pline.c:518
#5  0x0000555555d8702b in sanity_check_single_mon (mtmp=0x61100000e3c0, chk_geno=1 '\001', 
    msg=0x555556525ac0 "fmon") at mon.c:123
#6  0x0000555555d87300 in mon_sanity_check () at mon.c:147
#7  0x000055555587341c in sanity_check () at cmd.c:4889
#8  0x00005555557728d1 in moveloop (resuming=0 '\000') at allmain.c:795
#9  0x00005555563fcecc in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {0, 0, 0, 0, 0, 140737335783280, 93824997511119, 335544320, 
            140737341046928, 1073741824, 0, 140737342793376, 4294967295, 140737337360384, 
            140737342776480, 327789088951663872}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007ffff7363859 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0xffffffff, sa_sigaction = 0xffffffff}, 
          sa_mask = {__val = {140737337360384, 140737342776480, 327789088951663872, 
              140737488345200, 140737342793376, 18446744073709547520, 140737327104000, 
              140737345462488, 140737488346272, 140737488346272, 140737344331794, 
              17592186043150, 140737488338944, 140737341046928, 327789088951663872, 
              140737488345600}}, sa_flags = -1875477248, sa_restorer = 0x7fffffffdbc0}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x0000555555a5d2fd in NH_abort () at end.c:236
        gdb_prio = 1
        libc_prio = 2
        aborting = 1 '\001'
#3  0x0000555555a6418c in panic (str=0x55555656ff80 "%s") at end.c:802
        the_args = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7fffffffdc90, 
            reg_save_area = 0x7fffffffdbc0}}
#4  0x0000555555fc8e77 in impossible (s=0x555556525960 "eel hiding out of water (%s)")
    at pline.c:518
        pbuf = "eel hiding out of water (fmon)", '\000' <repeats 50 times>, "p\335\377\377\377\177\000\000\000\000\000\000\003\000\000\000\300.RVUU\000\000\000)RVUU\000\000\263\212\265A\000\000\000\000\300\266OVUU\000\000]\202\260UUU\000\000\000\000\000\000\000\000\000\000\001\001\000\000\000\000\001\000\000\001\000\000\001\000\001\002\000\000\001\001\001\000\000\000\000\001", '\000' <repeats 39 times>...
        the_args = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7fffffffe380, 
            reg_save_area = 0x7fffffffe2a0}}
#5  0x0000555555d8702b in sanity_check_single_mon (mtmp=0x61100000e3c0, chk_geno=1 '\001', 
    msg=0x555556525ac0 "fmon") at mon.c:123
        t = 0x15
        mptr = 0x55555665efc0 <mons+73632>
        mx = 26
        my = 13
#6  0x0000555555d87300 in mon_sanity_check () at mon.c:147
        x = 33
        y = 5
        mtmp = 0x61100000e3c0
        m = 0x61100000f680
#7  0x000055555587341c in sanity_check () at cmd.c:4889
No locals.
#8  0x00005555557728d1 in moveloop (resuming=0 '\000') at allmain.c:795
        moveamt = 12
        wtcap = 0
        change = 0
        monscanmove = 0 '\000'
        elf_regen = 1 '\001'
        orc_regen = 1 '\001'
        vamp_regen = 1 '\001'
#9  0x00005555563fcecc in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
        fd = -1
        dir = 0x0
        exact_username = 0 '\000'
        resuming = 0 '\000'
        plsel_once = 1 '\001'
```

**Comment by elunna** [comment]
Updated maybe_unhide_at to also deal with swimmers .
