### ISSUE TITLE
Found with fuzzer: ucastm: invalid magic spell

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#11]
`Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {0, 0, 0, 0, 0, 140737337632192, 93824997411122, 335544320, 
            140737341055120, 1073741824, 0, 140737342801568, 4294967295, 140737337360384, 
            140737342784672, 10705601216412169728}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007ffff7365859 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0xffffffff, sa_sigaction = 0xffffffff}, 
          sa_mask = {__val = {140737337360384, 140737342784672, 10705601216412169728, 
              140737488342576, 140737342801568, 18446744073709547520, 140737327112192, 
              140737345470680, 140737488343648, 140737488343648, 140737344339986, 
              17592186042822, 140737488334848, 140737341055120, 10705601216412169728, 
              140737488342976}}, sa_flags = -348342784, sa_restorer = 0x7fffffffd180}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x0000555555a44c60 in NH_abort () at end.c:236
        gdb_prio = 1
        libc_prio = 2
        aborting = 1 '\001'
#3  0x0000555555a4ba5c in panic (str=0x55555651b6c0 "%s") at end.c:802
        the_args = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7fffffffd250, 
            reg_save_area = 0x7fffffffd180}}
#4  0x0000555555f98c03 in impossible (s=0x5555564ba400 "ucastm: invalid magic spell (%d)")
    at pline.c:518
        pbuf = "ucastm: invalid magic spell (18)\000\000\000\000\000\000\000\000\020\001\000\000\320`\000\000 \323\377\377\377\177\000\000a\000<VUU\000\000\021\000\000\000\000\000\000\000 \324\377\377\377\177\000\000\000\324\377\377\377\177\000\000 \324\377\377\377\177\000\000P\323\377\377\377\177\000\000\251\n<VUU\000\000\200\323\377\377\377\377\377\377\020\001\000\000\320`\000\000\020\001\000\000\320`\000\000\000\324\377\377\377\177\000\000\240\323\377\377\377\177\000\000\024\071=VUU\000\000 \324\377\377\377\177\000\000\000\000\000\000\001\000\000\000\000\324\377\377\000\000\000\000\025\000\000\000\000\000\000\000\320\323\377\377\377\177\000\000"...
        the_args = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7fffffffd940, 
            reg_save_area = 0x7fffffffd860}}
#5  0x0000555555bb17a3 in ucast_wizard_spell (mattk=0x5555567b8fc0 <youmonst>, 
    mtmp=0x611000375f40, dmg=52, spellnum=18) at mcastu.c:2315
        resisted = 0 '\000'
        yours = 1 '\001'
#6  0x0000555555ba5412 in castum (mtmp=0x611000375f40, mattk=0x5555565f7440 <mons+13344>)
    at mcastu.c:1965
        dmg = 52
        ml = 26
        ret = 1
        spellnum = 18
        directed = 0 '\000'
#7  0x000055555629f160 in hmonas (mon=0x611000375f40, as=-1, weapon_attacks=1 '\001')
    at uhitm.c:4091
        mattk = 0x5555565f7440 <mons+13344>
        alt_attk = {aatyp = 96 '`', adtyp = 220 '\334', damn = 255 '\377', damd = 255 '\377'}
        weapon = 0x0
        originalweapon = 0x5555567baa60 <uarmg>
        altwep = 0 '\000'
        weapon_used = 1 '\001'
        stop_attacking = 0 '\000'
        i = 4
        tmp = 56
        armorpenalty = 0
        sum = {1, 1, 1, 1, 0, 32767}
        dhit = 1
        attknum = 4
        dieroll = 10
        monster_survived = 1 '\001'
        Old_Upolyd = 1 '\001'
#8  0x0000555556249413 in attack (mtmp=0x611000375f40) at uhitm.c:577
        mdat = 0x5555565f7bd8 <mons+15288>
        maxweight = 20
#9  0x0000555555ac70ee in domove_core () at hack.c:1813
        mtmp = 0x611000375f40
        tmpr = <optimized out>
        x = 13 '\r'
        y = 4 '\004'
        trap = 0x0
        wtcap = 0
        recharged = 0 '\000'
        walk_sewage = 0 '\000'
        chainx = 0 '\000'
        chainy = 0 '\000'
        ballx = 0 '\000'
        bally = 0 '\000'
        bc_control = 0
        cause_delay = 0 '\000'
        u_with_boulder = 0 '\000'
#10 0x0000555555ab0ab6 in domove () at hack.c:1516
        ux1 = 12
        uy1 = 3
#11 0x0000555555862ec2 in rhack (cmd=0x55555679b640 <in_line> "2") at cmd.c:5477
        spkey = 0
        prefix_seen = 0 '\000'
        bad_command = 85 'U'
        firsttime = 1 '\001'
#12 0x0000555555761c00 in moveloop (resuming=0 '\000') at allmain.c:798
        moveamt = 9
        wtcap = 0
        change = 0
        monscanmove = 0 '\000'
        timeout_start = 28593
        past_clock = 163138
        elf_regen = 1 '\001'
        orc_regen = 1 '\001'
        vamp_regen = 1 '\001'
#13 0x00005555563b4127 in main (argc=0, argv=0x7fffffffe658) at ../sys/unix/unixmain.c:353
        fd = -1
        dir = 0x0
        exact_username = 0 '\000'
        resuming = 0 '\000'
        plsel_once = 1 '\001'
`

**Comment by elunna** [comment]
impossible("ucastm: invalid magic spell (%d)", spellnum);
spellnum = 18
17 and 18 are MGC_CREATE_POOL, MGC_CALL_UNDEAD

I set MGC_CALL_UNDEAD to be a useless spell in uspell_would_be_useless()

I enabled make pool for players. Tested in wizmode and seems to work fine - might be an issue where the monster hangs for a turn or two before drowning, but I added mintrap(mtmp) to help deal with that, remains to be seen if that will be a problem.
