### ISSUE TITLE
Found with fuzzer: Couldn't place lregion type 1!

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#113]
```
Suddenly, the dungeon collapses.
Couldn't place lregion type 1!
Generating more information you may report:

[0] /lib/x86_64-linux-gnu/libasan.so.5(+0x6cd40) [0x7ffff75f8d40]
[1] /home/lunatunez/games/hackemdir/hackem(+0x50b5b0) [0x555555a5f5b0]
[2] /home/lunatunez/games/hackemdir/hackem(+0x50b4a3) [0x555555a5f4a3]
[3] /home/lunatunez/games/hackemdir/hackem(panic+0x6ab) [0x555555a66358]
[4] /home/lunatunez/games/hackemdir/hackem(impossible+0x2c8) [0x555555fceab7]
[5] /home/lunatunez/games/hackemdir/hackem(place_lregion+0x216) [0x555555d58cf8]
[6] /home/lunatunez/games/hackemdir/hackem(+0x80668b) [0x555555d5a68b]
[7] /home/lunatunez/games/hackemdir/hackem(makemaz+0x908) [0x555555d5f030]
[8] /home/lunatunez/games/hackemdir/hackem(+0x7f546c) [0x555555d4946c]
[9] /home/lunatunez/games/hackemdir/hackem(mklev+0x86) [0x555555d4ca4a]
[10] /home/lunatunez/games/hackemdir/hackem(+0x2f2b6d) [0x555555846b6d]
[11] /home/lunatunez/games/hackemdir/hackem(rhack+0x1b5f) [0x555555878ea1]
[12] /home/lunatunez/games/hackemdir/hackem(moveloop+0x7144) [0x555555774d6a]
[13] /home/lunatunez/games/hackemdir/hackem(main+0xdda) [0x555556404297]
[14] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7ffff7365083]
[15] /home/lunatunez/games/hackemdir/hackem(_start+0x2e) [0x55555576bace]



Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7363859 in __GI_abort () at abort.c:79
#2  0x0000555555a5f4c9 in NH_abort () at end.c:236
#3  0x0000555555a66358 in panic (str=0x555556578040 "%s") at end.c:802
#4  0x0000555555fceab7 in impossible (s=0x555556527b60 "Couldn't place lregion type %d!")
    at pline.c:518
#5  0x0000555555d58cf8 in place_lregion (lx=1 '\001', ly=3 '\003', hx=20 '\024', hy=19 '\023', 
    nlx=21 '\025', nly=3 '\003', nhx=60 '<', nhy=18 '\022', rtype=1 '\001', lev=0x7fffffffdef0)
    at mkmaze.c:320
#6  0x0000555555d5a68b in fixup_special () at mkmaze.c:502
#7  0x0000555555d5f030 in makemaz (s=0x603000000e8a "minetn") at mkmaze.c:1029
#8  0x0000555555d4946c in makelevel () at mklev.c:922
#9  0x0000555555d4ca4a in mklev () at mklev.c:1363
#10 0x0000555555846b6d in wiz_makemap () at cmd.c:902
#11 0x0000555555878ea1 in rhack (cmd=0x55555680c460 <in_line> "v") at cmd.c:5574
#12 0x0000555555774d6a in moveloop (resuming=0 '\000') at allmain.c:826
#13 0x0000555556404297 in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {0, 0, 0, 0, 0, 140737335783280, 93824997519771, 335544320, 
            140737341046928, 1073741824, 0, 140737342793376, 4294967295, 140737337360384, 
            140737342776480, 8240731013232304896}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007ffff7363859 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0xffffffff, sa_sigaction = 0xffffffff}, 
          sa_mask = {__val = {140737337360384, 140737342776480, 8240731013232304896, 
              140737488343808, 140737342793376, 18446744073709547520, 140737327104000, 
              140737345462488, 140737488344880, 140737488344880, 140737344331794, 
              17592186042976, 140737488338944, 140737341046928, 8240731013232304896, 
              140737488344208}}, sa_flags = -46030080, sa_restorer = 0x7fffffffd650}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x0000555555a5f4c9 in NH_abort () at end.c:236
        gdb_prio = 1
        libc_prio = 2
        aborting = 1 '\001'
#3  0x0000555555a66358 in panic (str=0x555556578040 "%s") at end.c:802
        the_args = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7fffffffd720, 
            reg_save_area = 0x7fffffffd650}}
#4  0x0000555555fceab7 in impossible (s=0x555556527b60 "Couldn't place lregion type %d!")
    at pline.c:518
        pbuf = "Couldn't place lregion type 1!\000\000\000", '\001' <repeats 11 times>, "\000\001\000\000\000\330\377\377\377\177\000\000\000\243A\375\061\365\\r\230uyVUU\000\000p\331\377\377\377\177\000\000\320\330\377\377\377\177\000\000\032\373\377\377\377\017\000\000\240\336\377\377\377\177\000\000\000\243A\375\061\365\\r0\330\377\377\377\177\000\000\220myVUU\000\000\060\330\377\377\377\177\000\000H\002\rVUU\000\000`\330\377\377\377\177\000\000\000\243A\375\061\365\\rp\375]\000 `\000\000p\331\377\377\377\177\000\000\320\330\377\377\377\177\000\000\032\373\377\377\377\017\000\000\200\330\377\377\377\177\000\000"...
        the_args = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7fffffffde10, 
            reg_save_area = 0x7fffffffdd30}}
#5  0x0000555555d58cf8 in place_lregion (lx=1 '\001', ly=3 '\003', hx=20 '\024', hy=19 '\023', 
    nlx=21 '\025', nly=3 '\003', nhx=60 '<', nhy=18 '\022', rtype=1 '\001', lev=0x7fffffffdef0)
    at mkmaze.c:320
        trycnt = 200
        oneshot = 0 '\000'
        x = 21 '\025'
        y = 20 '\024'
#6  0x0000555555d5a68b in fixup_special () at mkmaze.c:502
        r = 0x604001d58e10
        lev = {dnum = 0 '\000', dlevel = -128 '\200'}
        x = 0
        y = 30749264
        croom = 0xffffffffbea
        added_branch = 0 '\000'
#7  0x0000555555d5f030 in makemaz (s=0x603000000e8a "minetn") at mkmaze.c:1029
        x = 0
        y = 0
        protofile = "minetn-6.lev\000\000\000\000\260\342\377\377"
        sp = 0x603000000e80
        mm = {x = 16 '\020', y = -32 '\340'}
#8  0x0000555555d4946c in makelevel () at mklev.c:922
        slev = 0x603000000e80
        croom = 0x603000000e80
        troom = <optimized out>
        tryct = -7184
        i = -7184
        tmonst = 0x55555648d540
        branchp = 0x41b58ab3
        room_threshold = -8016
        boxtype = 32767
        pos = {x = -69 '\273', y = 117 'u'}
#9  0x0000555555d4ca4a in mklev () at mklev.c:1363
        croom = 0xffffffffc6e
        ridx = 32767
#10 0x0000555555846b6d in wiz_makemap () at cmd.c:902
        mtmp = 0x0
        was_in_W_tower = 0 '\000'
#11 0x0000555555878ea1 in rhack (cmd=0x55555680c460 <in_line> "v") at cmd.c:5574
        tlist = 0x5555566c3200 <extcmdlist+5184>
        res = 688
        func = 0x55555584668e <wiz_makemap>
        spkey = 0
        prefix_seen = 0 '\000'
        bad_command = 49 '1'
        firsttime = 1 '\001'
#12 0x0000555555774d6a in moveloop (resuming=0 '\000') at allmain.c:826
        moveamt = 12
        wtcap = 0
        change = 0
        monscanmove = 0 '\000'
        elf_regen = 1 '\001'
        orc_regen = 1 '\001'
        vamp_regen = 1 '\001'
#13 0x0000555556404297 in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
        fd = -1
        dir = 0x0
        exact_username = 0 '\000'
        resuming = 0 '\000'
        plsel_once = 1 '\001'
```

**Comment by elunna** [comment]
At first this looks like an issue with the Monk's health food store in minetown.
The issue occurs in minetown as a monk, not polyd as anything.

I tried spamming wizmakemap in minetown for a few minutes, but did not encounter problems.

**Comment by elunna** [comment]
Stale issue.
