### ISSUE TITLE
Found with fuzzer: new_light_source:  illegal range 22

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#115]
```
Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7363859 in __GI_abort () at abort.c:79
#2  0x0000555555a5f696 in NH_abort () at end.c:236
#3  0x0000555555a66525 in panic (str=0x55555657c7e0 "%s") at end.c:802
#4  0x0000555555fd1976 in impossible (s=0x55555650d4c0 "new_light_source:  illegal range %d")
    at pline.c:518
#5  0x0000555555b364ba in new_light_source (x=35 '#', y=14 '\016', range=22, type=0, 
    id=0x555556831d60 <tmp_anything>) at light.c:66
#6  0x00005555561fd294 in begin_burn (obj=0x60c0009c6d00, already_lit=0 '\000') at timeout.c:2100
#7  0x000055555579c539 in use_lamp (obj=0x60c0009c6d00) at apply.c:1597
#8  0x000055555579853f in use_candle (optr=0x7fffffffe270) at apply.c:1336
#9  0x00005555557cc5a6 in doapply () at apply.c:4936
#10 0x0000555555879078 in rhack (cmd=0x555556811d20 <in_line> "a") at cmd.c:5601
#11 0x0000555555774d6a in moveloop (resuming=0 '\000') at allmain.c:826
#12 0x0000555556407e96 in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {0, 0, 0, 0, 0, 140737335783280, 93824997520232, 335544320, 
            140737341046928, 1073741824, 0, 140737342793376, 4294967295, 140737337360384, 
            140737342776480, 13415165176011141120}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007ffff7363859 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0xffffffff, sa_sigaction = 0xffffffff}, 
          sa_mask = {__val = {140737337360384, 140737342776480, 13415165176011141120, 
              140737488343616, 140737342793376, 18446744073709547520, 140737327104000, 
              140737345462488, 140737488344688, 140737488344688, 140737344331794, 
              17592186042952, 140737488338944, 140737341046928, 13415165176011141120, 
              140737488344016}}, sa_flags = -1487556608, sa_restorer = 0x7fffffffd590}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x0000555555a5f696 in NH_abort () at end.c:236
        gdb_prio = 1
        libc_prio = 2
        aborting = 1 '\001'
#3  0x0000555555a66525 in panic (str=0x55555657c7e0 "%s") at end.c:802
        the_args = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7fffffffd660, 
            reg_save_area = 0x7fffffffd590}}
#4  0x0000555555fd1976 in impossible (s=0x55555650d4c0 "new_light_source:  illegal range %d")
    at pline.c:518
        pbuf = "new_light_source:  illegal range 22\000\000\000\000\000*\000\000\000*\000\000\000\263\212\265A\000\000\000\000\027\301WVUU\000\000\240\356\374UUU\000\000\000\260U\247\246=,\272Your tallow candles' flames burn brightly!\000\000\000\000\000\000\030тVUU\000\000O\000\000\000\000\000\000\000l\267BVUU\000\000d\000\000\000\000\000\000\000\220\327\377\377\377\177\000\000<\236\202UUU\000\000'\000\000\000\000\000\000\000\025\000\000\000\000\000\000\000\340\327\377\377\377\177\000\000\177"...
        the_args = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7fffffffdd50, 
            reg_save_area = 0x7fffffffdc70}}
#5  0x0000555555b364ba in new_light_source (x=35 '#', y=14 '\016', range=22, type=0, 
    id=0x555556831d60 <tmp_anything>) at light.c:66
        ls = 0x60c0009c6d00
#6  0x00005555561fd294 in begin_burn (obj=0x60c0009c6d00, already_lit=0 '\000') at timeout.c:2100
        x = 35 '#'
        y = 14 '\016'
        radius = 22
        turns = 125
        do_timer = 1 '\001'
#7  0x000055555579c539 in use_lamp (obj=0x60c0009c6d00) at apply.c:1597
        buf = '\000' <repeats 32 times>, "a voice say, \"%s, Jim.\"", '\000' <repeats 41 times>, " mostly", '\000' <repeats 121 times>...
#8  0x000055555579853f in use_candle (optr=0x7fffffffe270) at apply.c:1336
        obj = 0x60c0009c6d00
        otmp = 0x0
        s = 0x555556478da0 "candles"
        qbuf = "\000\000\000\000\000\000\000\000\000\260U\247\246=,\272\263\212\265A\000\000\000\000\340\364RVUU\000\000j\332\327UUU\000\000,\374\377\377\377\017\000\000`\341\377\377\377\177\000\000\006\000\000\000\000\000\000\000\020\341\377\377\377\177\000\000\312\021\203UUU\000\000\220\367\200VUU\000\000\020\360\200V5\000\000\000\060\341\377\377\377\177\000\000\220\367\200UUU\000\000`\341\377\377\377\177\000\000\000\260U\247\246=,\272"
        qsfx = "J\374\377\377\377\017\000\000\360\343\377\377\377\177\000\000\340\341\377\377\377\177\000\000ͪ|UUU\000\000\240\341\377\377\r\177\000\000\220\342\377\377\377\177\000\000\263\212\265A\000\000\000\000\350\374GVUU\000\000\256\251|UUU\000\000\000\000\000\000\000\000\000\000\r", '\000' <repeats 31 times>, "\300\341\377\377\377\177\000\000\000\260U\247\246=,\272"
        q = 0x0
        was_lamplit = 0 '\000'
#9  0x00005555557cc5a6 in doapply () at apply.c:4936
        obj = 0x60c0009c6d00
        otmp = 0x0
        res = 1
        class_list = "\025\006\002\v\r\000\000\000\000\251JVUU\000\000\005\064\210UU"
#10 0x0000555555879078 in rhack (cmd=0x555556811d20 <in_line> "a") at cmd.c:5601
        tlist = 0x5555566c7020 <extcmdlist+192>
        res = 688
        func = 0x5555557cb4c9 <doapply>
        spkey = 0
        prefix_seen = 0 '\000'
        bad_command = -90 '\246'
        firsttime = 1 '\001'
#11 0x0000555555774d6a in moveloop (resuming=0 '\000') at allmain.c:826
        moveamt = 12
        wtcap = 0
        change = 0
        monscanmove = 0 '\000'
        elf_regen = 1 '\001'
        orc_regen = 1 '\001'
        vamp_regen = 1 '\001'
#12 0x0000555556407e96 in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
        fd = -1
        dir = 0x0
        exact_username = 0 '\000'
        resuming = 0 '\000'
        plsel_once = 1 '\001'
```

**Comment by elunna** [comment]
Able to reproduce by wishing for 450 candles and lighting them.
