### ISSUE TITLE
Found with fuzzer: What an interesting effect (552)

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#12]
```
Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7365859 in __GI_abort () at abort.c:79
#2  0x0000555555a44c60 in NH_abort () at end.c:236
#3  0x0000555555a4ba5c in panic (str=0x55555651b6c0 "%s") at end.c:802
#4  0x0000555555f98c03 in impossible (s=0x5555565a4080 "What an interesting effect (%d)")
    at pline.c:518
#5  0x0000555556350c9e in bhitm (mtmp=0x611000090140, otmp=0x60c000259c00) at zap.c:740
#6  0x00005555557ba027 in do_break_wand (obj=0x60c000259c00) at apply.c:4758
#7  0x00005555557bb340 in doapply () at apply.c:4920
#8  0x00005555558633d1 in rhack (cmd=0x55555679b640 <in_line> "a") at cmd.c:5515
#9  0x0000555555761c00 in moveloop (resuming=0 '\000') at allmain.c:798
#10 0x00005555563b4127 in main (argc=0, argv=0x7fffffffe658) at ../sys/unix/unixmain.c:353
Undefined command: "stacktrace".  Try "help".
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {0, 0, 0, 0, 0, 140737337632192, 93824997411122, 335544320, 
            140737341055120, 1073741824, 0, 140737342801568, 4294967295, 140737337360384, 
            140737342784672, 7705769226148311552}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007ffff7365859 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0xffffffff, sa_sigaction = 0xffffffff}, 
          sa_mask = {__val = {140737337360384, 140737342784672, 7705769226148311552, 
              140737488343280, 140737342801568, 18446744073709547520, 140737327112192, 
              140737345470680, 140737488344352, 140737488344352, 140737344339986, 
              17592186042910, 140737488338944, 140737341055120, 7705769226148311552, 
              140737488343680}}, sa_flags = -977997312, sa_restorer = 0x7fffffffd440}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x0000555555a44c60 in NH_abort () at end.c:236
        gdb_prio = 1
        libc_prio = 2
        aborting = 1 '\001'
#3  0x0000555555a4ba5c in panic (str=0x55555651b6c0 "%s") at end.c:802
        the_args = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7fffffffd510, 
            reg_save_area = 0x7fffffffd440}}
#4  0x0000555555f98c03 in impossible (s=0x5555565a4080 "What an interesting effect (%d)")
    at pline.c:518
        pbuf = "What an interesting effect (552)\000\212\265A\000\000\000\000\340\225FVUU\000\000p2\223UUU", '\000' <repeats 810 times>...
        the_args = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7fffffffdc00, 
            reg_save_area = 0x7fffffffdb20}}
#5  0x0000555556350c9e in bhitm (mtmp=0x611000090140, otmp=0x60c000259c00) at zap.c:740
        wake = 1 '\001'
        reveal_invis = 0 '\000'
        learn_it = 0 '\000'
        visible = 0 '\000'
        dbldam = 0 '\000'
        skilled_spell = 0 '\000'
        helpful_gesture = 0 '\000'
        dmg = 24768
        otyp = 552
        zap_type_text = 0x5555565a30c0 "spell"
        obj = 0x60c000259c00
        mdat = 0x5555565f9090 <mons+20592>
        disguised_mimic = 0 '\000'
#6  0x00005555557ba027 in do_break_wand (obj=0x60c000259c00) at apply.c:4758
        nothing_else_happens = "But nothing else happens..."
        i = 6
        x = 48
        y = 13
        mon = <optimized out>
        dmg = 20
        damage = 0
        affects_objects = 0 '\000'
        shop_damage = 0 '\000'
        fillmsg = 0 '\000'
        expltype = 5
        confirm = <optimized out>
        buf = <optimized out>
        is_fragile = 0 '\000'
#7  0x00005555557bb340 in doapply () at apply.c:4920
        obj = 0x60c000259c00
        otmp = 0x0
        res = 1
        class_list = "\006\002\v\000\000\000\000\000\340\032EVUU\000\000\314׆U"
#8  0x00005555558633d1 in rhack (cmd=0x55555679b640 <in_line> "a") at cmd.c:5515
        tlist = 0x55555665b920 <extcmdlist+192>
        res = 1450818532
        func = 0x5555557bb0f6 <doapply>
        spkey = 0
        prefix_seen = 0 '\000'
        bad_command = 85 'U'
        firsttime = 1 '\001'
#9  0x0000555555761c00 in moveloop (resuming=0 '\000') at allmain.c:798
        moveamt = 12
        wtcap = 0
        change = 0
        monscanmove = 0 '\000'
        timeout_start = 34966
        past_clock = -23055
        elf_regen = 1 '\001'
        orc_regen = 1 '\001'
        vamp_regen = 1 '\001'
#10 0x00005555563b4127 in main (argc=0, argv=0x7fffffffe658) at ../sys/unix/unixmain.c:353
        fd = -1
        dir = 0x0
        exact_username = 0 '\000'
        resuming = 0 '\000'
        plsel_once = 1 '\001'
```

**Comment by elunna** [comment]
This could be related to wands of acid - found this while playtesting:
```
Raising your wand of acid high above your head, you break it in two!
The green slime is caught in the torrent of acid!  (0 pts.)
You are caught in the torrent of acid!  What an interesting effect (558)
```
Wand of acid doesn't have handling in the following yet.
zap:718 	bhitm(mtmp, otmp)	149		(no WAN_ACID listed)
zap:2509 	bhito(obj, otmp)	2203	(no WAN_ACID listed)

Also, the otyp = 552 in the original comment is for wand of cold - this might have changed since I changed the order of wand of water...

**Comment by elunna** [comment]
Can't repro, stale.
