### ISSUE TITLE
Found with fuzzer: Too many spells memorized!

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#120]
```

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7d94859 in __GI_abort () at abort.c:79
#2  0x00005555556b2bf9 in NH_abort () at end.c:236
#3  0x00005555556b538d in panic (str=0x555555a80ac8 "%s") at end.c:802
#4  0x00005555558a80df in impossible (s=0x555555a958d2 "Too many spells memorized!")
    at pline.c:518
#5  0x000055555594a64f in learn () at spell.c:401
#6  0x00005555555ae1ba in moveloop (resuming=0 '\000') at allmain.c:776
#7  0x0000555555a18e8b in main (argc=4, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {0, 0, 0, 0, 0, 93824993677584, 93824993667538, 335544320, 
            140737351733392, 1073741824, 140737488349278, 93824992231424, 0, 
            2312861950361370624, 140737488345680, 93824995720878}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007ffff7d94859 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {
              2312861950361370624, 140737488345680, 93824995720878, 93824992341990, 
              93824997508501, 206158430232, 140737488345696, 140737488345504, 
              2312861950361370624, 140737353865712, 8, 93824998819110, 335544320, 
              140737351733392, 2312861950361370624, 4294967295}}, sa_flags = 1433086830, 
          sa_restorer = 0x5555555ab540 <_start>}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00005555556b2bf9 in NH_abort () at end.c:236
        gdb_prio = 1
        libc_prio = 2
        aborting = 1 '\001'
#3  0x00005555556b538d in panic (str=0x555555a80ac8 "%s") at end.c:802
        the_args = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7fffffffdd60, 
            reg_save_area = 0x7fffffffdca0}}
#4  0x00005555558a80df in impossible (s=0x555555a958d2 "Too many spells memorized!")
    at pline.c:518
        pbuf = "Too many spells memorized!", '\000' <repeats 806 times>...
        the_args = {{gp_offset = 8, fp_offset = 48, overflow_arg_area = 0x7fffffffe360, 
            reg_save_area = 0x7fffffffe2a0}}
#5  0x000055555594a64f in learn () at spell.c:401
        i = 62
        booktype = 518
        splname = "\"wizard lock\"\000\000\000\030\070\263UUU", '\000' <repeats 18 times>, "x\004\340\367\377\177\000\000\030\070\263UUU\000\000\360\235\264UUU\000\000\320\343\377\377\377\177\000\000\240\366\365\367\377\177\000\000\240\264\365\367\377\177\000\000\306C\337\367\377\177\000\000 \344\377\377\377\377\377\377\060K\265UUU\000\000 \344\377\377\377\177\000\000/O\242UUU\000\000\336\373\221\000\000\000\000\000\000\000\000\000\003\000\000\000P\344\377\377\377\177\000\000\060K\265UUU\000\000\000\000\000\000\000\000\000\000\025\000\000\000\000\000\000\000p\344\377\377\377\177\000\000\356\330cUUU\000\000\017\000\000\000\000\000\000\000"...
        costly = 1 '\001'
        book = 0x555555bb08a0
#6  0x00005555555ae1ba in moveloop (resuming=0 '\000') at allmain.c:776
        moveamt = 12
        wtcap = 0
        change = 0
        monscanmove = 0 '\000'
        elf_regen = 1 '\001'
        orc_regen = 1 '\001'
        vamp_regen = 1 '\001'
#7  0x0000555555a18e8b in main (argc=4, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
        fd = -1
        dir = 0xffffffff <error: Cannot access memory at address 0xffffffff>
        exact_username = 0 '\000'
        resuming = 0 '\000'
        plsel_once = 1 '\001'

```

**Comment by gebulmer** [comment]
Do you have spells that aren't learnt from spellbooks? If so you could look at `util/makedefs.c` where it defines MAX_SPELL and increase that from nspell+1 to nspell+1+whatever

**Comment by elunna** [comment]
Yes the Necromancer currently get up to 6 spells by reaching certain levels.
MAXSPELLS is set to 62 (a-z, A-Z, 0-9)
I have 58 spellbooks.

So a possible solution is just adding something like:
#DEFINE INNATE_SPELLS 6
Fprintf(ofp, "#define\tMAXSPELL\t%d\n", nspell + 1 + INNATE_SPELLS);

I'm just not sure how the spell count could go over 58 if there are only 58 spells.

**Comment by elunna** [comment]
Using rr I was able to get a listing of spells at the time of the crash

```
3 = {
{sp_id = 515, sp_lev = 3 '\003', sp_know = 0}, 
{sp_id = 512, sp_lev = 4 '\004', sp_know = 0}, 
{sp_id = 512, sp_lev = 4 '\004', sp_know = 0}, 
{sp_id = 512, sp_lev = 4 '\004', sp_know = 0}, 
{sp_id = 512, sp_lev = 4 '\004', sp_know = 0}, 
{sp_id = 515, sp_lev = 3 '\003', sp_know = 0}, 
{sp_id = 515, sp_lev = 3 '\003', sp_know = 0}, 
{sp_id = 515, sp_lev = 3 '\003', sp_know = 0}, 
{sp_id = 513, sp_lev = 2 '\002', sp_know = 0}, 
{sp_id = 512, sp_lev = 4 '\004', sp_know = 0}, 
{sp_id = 516, sp_lev = 5 '\005', sp_know = 0}, 
{sp_id = 516, sp_lev = 5 '\005', sp_know = 0}, 
{sp_id = 514, sp_lev = 1 '\001', sp_know = 0}, 
{sp_id = 512, sp_lev = 4 '\004', sp_know = 0}, 
{sp_id = 514, sp_lev = 1 '\001', sp_know = 0}, 
{sp_id = 513, sp_lev = 2 '\002', sp_know = 0}, 
{sp_id = 514, sp_lev = 1 '\001', sp_know = 0}, 
{sp_id = 513, sp_lev = 2 '\002', sp_know = 0}, 
{sp_id = 513, sp_lev = 2 '\002', sp_know = 0}, 
{sp_id = 537, sp_lev = 2 '\002', sp_know = 0}, 
{sp_id = 514, sp_lev = 1 '\001', sp_know = 0}, 
{sp_id = 512, sp_lev = 4 '\004', sp_know = 0}, 
{sp_id = 513, sp_lev = 2 '\002', sp_know = 0}, 
{sp_id = 512, sp_lev = 4 '\004', sp_know = 0}, 
{sp_id = 512, sp_lev = 4 '\004', sp_know = 0}, 
{sp_id = 514, sp_lev = 1 '\001', sp_know = 0}, 
{sp_id = 513, sp_lev = 2 '\002', sp_know = 0}, 
{sp_id = 513, sp_lev = 2 '\002', sp_know = 0}, 
{sp_id = 514, sp_lev = 1 '\001', sp_know = 0}, 
{sp_id = 523, sp_lev = 1 '\001', sp_know = 0}, 
{sp_id = 512, sp_lev = 4 '\004', sp_know = 0}, 
{sp_id = 513, sp_lev = 2 '\002', sp_know = 0}, 
{sp_id = 514, sp_lev = 1 '\001', sp_know = 0}, 
{sp_id = 513, sp_lev = 2 '\002', sp_know = 0}, 
{sp_id = 512, sp_lev = 4 '\004', sp_know = 0}, 
{sp_id = 513, sp_lev = 2 '\002', sp_know = 0}, 
{sp_id = 512, sp_lev = 4 '\004', sp_know = 0}, 
{sp_id = 514, sp_lev = 1 '\001', sp_know = 0}, 
{sp_id = 555, sp_lev = 1 '\001', sp_know = 0}, 
{sp_id = 512, sp_lev = 4 '\004', sp_know = 0}, 
{sp_id = 513, sp_lev = 2 '\002', sp_know = 0}, 
{sp_id = 551, sp_lev = 2 '\002', sp_know = 0}, 
{sp_id = 527, sp_lev = 3 '\003', sp_know = 0}, 
{sp_id = 515, sp_lev = 3 '\003', sp_know = 0}, 
{sp_id = 515, sp_lev = 3 '\003', sp_know = 0}, 
{sp_id = 515, sp_lev = 3 '\003', sp_know = 0}, 
{sp_id = 514, sp_lev = 1 '\001', sp_know = 0}, 
{sp_id = 513, sp_lev = 2 '\002', sp_know = 0}, 
{sp_id = 513, sp_lev = 2 '\002', sp_know = 0}, 
{sp_id = 512, sp_lev = 4 '\004', sp_know = 0}, 
{sp_id = 512, sp_lev = 4 '\004', sp_know = 0}, 
{sp_id = 517, sp_lev = 1 '\001', sp_know = 0}, 
{sp_id = 512, sp_lev = 4 '\004', sp_know = 0}, 
{sp_id = 510, sp_lev = 2 '\002', sp_know = 0}, 
{sp_id = 513, sp_lev = 2 '\002', sp_know = 0}, 
{sp_id = 513, sp_lev = 2 '\002', sp_know = 0}, 
{sp_id = 512, sp_lev = 4 '\004', sp_know = 0}, 
{sp_id = 516, sp_lev = 5 '\005', sp_know = 0}, 
{sp_id = 513, sp_lev = 2 '\002', sp_know = 0}, 
{sp_id = 515, sp_lev = 3 '\003', sp_know = 0}, 
{sp_id = 513, sp_lev = 2 '\002', sp_know = 0}, 
{sp_id = 536, sp_lev = 1 '\001', sp_know = 0}, 
{sp_id = 516, sp_lev = 5 '\005', sp_know = 100000}}
(rr) 


512 COMMAND UNDEAD
513 RAISE ZOMBIES
515 ANIMATE DEAD
516 SPIRIT BOMB
```
