### ISSUE TITLE
AddressSanitizer: heap-buffer-overflow with run_regions 

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#124]
```
=================================================================
==32566==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60300017b98c at pc 0x5555560c6774 bp 0x7fffffffe3e0 sp 0x7fffffffe3d0
READ of size 4 at 0x60300017b98c thread T0
    #0 0x5555560c6773 in run_regions /home/lunatunez/hackem/src/region.c:417
    #1 0x55555576ffc7 in moveloop /home/lunatunez/hackem/src/allmain.c:384
    #2 0x55555640a7a4 in main ../sys/unix/unixmain.c:353
    #3 0x7ffff7365082 in __libc_start_main ../csu/libc-start.c:308
    #4 0x55555576cacd in _start (/home/lunatunez/games/hackemdir/hackem+0x218acd)

0x60300017b98c is located 4 bytes to the left of 20-byte region [0x60300017b990,0x60300017b9a4)
allocated by thread T0 here:
    #0 0x7ffff7699808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x555555779496 in alloc /home/lunatunez/hackem/src/alloc.c:46
    #2 0x5555560c4e3e in add_mon_to_reg /home/lunatunez/hackem/src/region.c:180
    #3 0x5555560c7d2a in m_in_out_region /home/lunatunez/hackem/src/region.c:522
    #4 0x555555e7742f in m_move /home/lunatunez/hackem/src/monmove.c:1738
    #5 0x555555e69c97 in dochug /home/lunatunez/hackem/src/monmove.c:933
    #6 0x555555e54a2a in dochugw /home/lunatunez/hackem/src/monmove.c:126
    #7 0x555555dbf089 in movemon /home/lunatunez/hackem/src/mon.c:1565
    #8 0x55555576f228 in moveloop /home/lunatunez/hackem/src/allmain.c:244
    #9 0x55555640a7a4 in main ../sys/unix/unixmain.c:353
    #10 0x7ffff7365082 in __libc_start_main ../csu/libc-start.c:308

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/lunatunez/hackem/src/region.c:417 in run_regions
Shadow bytes around the buggy address:
  0x0c06800276e0: fd fd fa fa fd fd fd fa fa fa fa fa fa fa fa fa
  0x0c06800276f0: fa fa fa fa fa fa fd fd fd fd fa fa fa fa fa fa
  0x0c0680027700: fa fa fd fd fd fd fa fa fd fd fd fd fa fa fd fd
  0x0c0680027710: fd fd fa fa fd fd fd fa fa fa fd fd fd fd fa fa
  0x0c0680027720: fd fd fd fd fa fa fd fd fd fa fa fa fd fd fd fa
=>0x0c0680027730: fa[fa]00 00 04 fa fa fa fd fd fd fa fa fa fd fd
  0x0c0680027740: fd fa fa fa fd fd fd fa fa fa fd fd fd fa fa fa
  0x0c0680027750: fd fd fd fd fa fa fd fd fd fd fa fa fd fd fd fd
  0x0c0680027760: fa fa 00 00 00 05 fa fa fd fd fd fa fa fa fd fd
  0x0c0680027770: fd fa fa fa fd fd fd fd fa fa fd fd fd fa fa fa
  0x0c0680027780: fd fd fd fd fa fa fd fd fd fd fa fa fd fd fd fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==32566==ABORTING
```

**Comment by elunna** [comment]
Stale issue
