### ISSUE TITLE
fuzzer: attempting to rename an invalid spellbook?

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#126]
```
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140526607226816) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140526607226816) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140526607226816, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007fcee641a476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007fcee64007f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x000055ec9e4c5d8e in NH_abort () at end.c:236
#6  0x000055ec9e4c5b76 in panictrace_handler (sig_unused=11) at end.c:161
#7  <signal handler called>
#8  __strlen_sse2 () at ../sysdeps/x86_64/multiarch/strlen-vec.S:126
#9  0x00007fcee69c1e58 in __interceptor_strcat (to=0x55ec9f287ed0 <obufs+1360> "spellbook of ", from=0x0)
    at ../../../../src/libsanitizer/asan/asan_interceptors.cpp:388
#10 0x000055ec9e993ec4 in xname_flags (obj=0x7ffddee6dbd0, cxn_flags=0) at objnam.c:957
#11 0x000055ec9e98f7e0 in xname (obj=0x7ffddee6dbd0) at objnam.c:581
#12 0x000055ec9e3af408 in docall_xname (obj=0x7ffddee6e1e0) at do_name.c:1530
#13 0x000055ec9e99d5a3 in short_oname (obj=0x7ffddee6e1e0, func=0x55ec9e3aec0c <docall_xname>, 
    altfunc=0x55ec9e99f637 <simpleonames>, lenlimit=121) at objnam.c:1975
#14 0x000055ec9e9b3065 in safe_qbuf (qbuf=0x7ffddee6df20 "Call ", qprefix=0x55ec9ef15f80 "Call ", 
    qsuffix=0x55ec9ef15f40 ":", obj=0x7ffddee6e1e0, func=0x55ec9e3aec0c <docall_xname>, 
    altfunc=0x55ec9e99f637 <simpleonames>, lastR=0x55ec9ef15fc0 "thing") at objnam.c:5559
#15 0x000055ec9e3af7a5 in docall (obj=0x7ffddee6e1e0) at do_name.c:1549
#16 0x000055ec9e98d2e1 in rename_disco () at o_init.c:751
#17 0x000055ec9e3aeb83 in docallcmd () at do_name.c:1491
#18 0x000055ec9e2e1a7b in rhack (cmd=0x55ec9f2658e0 <in_line> "C") at cmd.c:5661
#19 0x000055ec9e1dbdce in moveloop (resuming=0 '\000') at allmain.c:826
#20 0x000055ec9ee5b1b4 in main (argc=0, argv=0x7ffddee6e6d8) at ../sys/unix/unixmain.c:353


#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140526607226816) at ./nptl/pthread_kill.c:44
        tid = <optimized out>
        ret = 0
        pd = 0x7fcee68157c0
        old_mask = {__val = {140526603052320, 1073741824, 0, 140526604986240, 4294967295, 140526598750208, 
            140526604969472, 3736061704693913344, 140728343119840, 140526604986240, 0, 3736061704693913344, 
            17591042889980, 140728343119840, 17591042889980, 140728343119840}}
        ret = <optimized out>
        pd = <optimized out>
        old_mask = <optimized out>
        ret = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
        resultvar = <optimized out>
        resultvar = <optimized out>
        __arg3 = <optimized out>
        __arg2 = <optimized out>
        __arg1 = <optimized out>
        _a3 = <optimized out>
        _a2 = <optimized out>
        _a1 = <optimized out>
        __futex = <optimized out>
        resultvar = <optimized out>
        __arg3 = <optimized out>
        __arg2 = <optimized out>
        __arg1 = <optimized out>
        _a3 = <optimized out>
        _a2 = <optimized out>
        _a1 = <optimized out>
        __futex = <optimized out>
        __private = <optimized out>
        __oldval = <optimized out>
        result = <optimized out>
#1  __pthread_kill_internal (signo=6, threadid=140526607226816) at ./nptl/pthread_kill.c:78
No locals.
#2  __GI___pthread_kill (threadid=140526607226816, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
No locals.
#3  0x00007fcee641a476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
        ret = <optimized out>
#4  0x00007fcee64007f3 in __GI_abort () at ./stdlib/abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x55ec9f287ed0 <obufs+1360>, 
            sa_sigaction = 0x55ec9f287ed0 <obufs+1360>}, sa_mask = {__val = {0, 94474769094304, 140526609503423, 
              140526604969472, 3736061704693913344, 140728343119840, 140526604986240, 18446744073709547520, 
              140526590853120, 140526610731736, 140526609540781, 94474769094304, 140526609526806, 17591042889980, 
              140728343113728, 140526603052320}}, sa_flags = 1865979648, sa_restorer = 0x55ec9f287ed0 <obufs+1360>}
        sigs = {__val = {32, 140728343123984, 140526609026062, 94474756447864, 94474756447592, 94474756447094, 
            140526603052320, 140526603545082, 140526608981592, 94474761486020, 94474761467872, 3736061704693913344, 
            94474761524643, 140728343124944, 140728343124944, 140728343120192}}
#5  0x000055ec9e4c5d8e in NH_abort () at end.c:236
        gdb_prio = 1
        libc_prio = 2
        aborting = 1 '\001'
#6  0x000055ec9e4c5b76 in panictrace_handler (sig_unused=11) at end.c:161
        f2 = 18
#7  <signal handler called>
No locals.
#8  __strlen_sse2 () at ../sysdeps/x86_64/multiarch/strlen-vec.S:126
No locals.
#9  0x00007fcee69c1e58 in __interceptor_strcat (to=0x55ec9f287ed0 <obufs+1360> "spellbook of ", from=0x0)
    at ../../../../src/libsanitizer/asan/asan_interceptors.cpp:388
        from_length = <optimized out>
        to_length = <optimized out>
        ctx = <optimized out>
        _ctx = <optimized out>
#10 0x000055ec9e993ec4 in xname_flags (obj=0x7ffddee6dbd0, cxn_flags=0) at objnam.c:957
        buf = 0x55ec9f287ed0 <obufs+1360> "spellbook of "
        obufp = 0x0
        typ = 560
        ocl = 0x55ec9f0d56a0 <objects+22400>
        nn = 1
        omndx = 0
        orig_opknwn = 0
        actualn = 0x0
        dn = 0x55ec9eec4520 "big"
        un = 0x0
        pluralize = 0 '\000'
        known = 1 '\001'
        dknown = 1 '\001'
        bknown = 0 '\000'
#11 0x000055ec9e98f7e0 in xname (obj=0x7ffddee6dbd0) at objnam.c:581
No locals.
#12 0x000055ec9e3af408 in docall_xname (obj=0x7ffddee6e1e0) at do_name.c:1530
        otemp = <error reading variable otemp (Cannot access memory at address 0xffffffffffffff40)>
#13 0x000055ec9e99d5a3 in short_oname (obj=0x7ffddee6e1e0, func=0x55ec9e3aec0c <docall_xname>, 
    altfunc=0x55ec9e99f637 <simpleonames>, lenlimit=121) at objnam.c:1975
        save_obj = {nobj = 0x0, v = {v_nexthere = 0x0, v_ocontainer = 0x0, v_ocarry = 0x0}, cobj = 0x0, o_id = 0, 
          ox = 0 '\000', oy = 0 '\000', otyp = 0, owt = 0, quan = 0, spe = 0 '\000', oclass = 0 '\000', 
          invlet = 0 '\000', oartifact = 0 '\000', altmode = 0 '\000', oprops = 0, oprops_known = 0, where = 109 'm', 
          timed = 47 '/', cursed = 0, blessed = 1, unpaid = 1, no_charge = 0, known = 0, dknown = 0, bknown = 1, 
          rknown = 0, oeroded = 2, oeroded2 = 1, oerodeproof = 0, olocked = 1, oticking = 1, obroken = 1, 
          otrapped = 0, recharged = 7, lamplit = 0, globby = 0, greased = 1, nomerge = 1, was_thrown = 1, 
          odrained = 1, material = 31, in_use = 0, bypass = 0, cknown = 0, lknown = 0, yours = 0, corpsenm = 0, 
          
        to_length = <optimized out>
        ctx = <optimized out>
        _ctx = <optimized out>
#10 0x000055ec9e993ec4 in xname_flags (obj=0x7ffddee6dbd0, cxn_flags=0) at objnam.c:957
        buf = 0x55ec9f287ed0 <obufs+1360> "spellbook of "
        obufp = 0x0
        typ = 560
        ocl = 0x55ec9f0d56a0 <objects+22400>
        nn = 1
        omndx = 0
        orig_opknwn = 0
        actualn = 0x0
        dn = 0x55ec9eec4520 "big"
        un = 0x0
        pluralize = 0 '\000'
        known = 1 '\001'
        dknown = 1 '\001'
        bknown = 0 '\000'
#11 0x000055ec9e98f7e0 in xname (obj=0x7ffddee6dbd0) at objnam.c:581
No locals.
#12 0x000055ec9e3af408 in docall_xname (obj=0x7ffddee6e1e0) at do_name.c:1530
        otemp = <error reading variable otemp (Cannot access memory at address 0xffffffffffffff40)>
#13 0x000055ec9e99d5a3 in short_oname (obj=0x7ffddee6e1e0, func=0x55ec9e3aec0c <docall_xname>, 
    altfunc=0x55ec9e99f637 <simpleonames>, lenlimit=121) at objnam.c:1975
        save_obj = {nobj = 0x0, v = {v_nexthere = 0x0, v_ocontainer = 0x0, v_ocarry = 0x0}, cobj = 0x0, o_id = 0, 
          ox = 0 '\000', oy = 0 '\000', otyp = 0, owt = 0, quan = 0, spe = 0 '\000', oclass = 0 '\000', 
          invlet = 0 '\000', oartifact = 0 '\000', altmode = 0 '\000', oprops = 0, oprops_known = 0, where = 109 'm', 
          timed = 47 '/', cursed = 0, blessed = 1, unpaid = 1, no_charge = 0, known = 0, dknown = 0, bknown = 1, 
          rknown = 0, oeroded = 2, oeroded2 = 1, oerodeproof = 0, olocked = 1, oticking = 1, obroken = 1, 
          otrapped = 0, recharged = 7, lamplit = 0, globby = 0, greased = 1, nomerge = 1, was_thrown = 1, 
          odrained = 1, material = 31, in_use = 0, bypass = 0, cknown = 0, lknown = 0, yours = 0, corpsenm = 0, 
          dknown = 1, bknown = 0, rknown = 0, oeroded = 0, oeroded2 = 0, oerodeproof = 0, olocked = 0, oticking = 0, 
          obroken = 0, otrapped = 0, recharged = 0, lamplit = 0, globby = 0, greased = 0, nomerge = 0, 
          was_thrown = 0, odrained = 0, material = 0, in_use = 0, bypass = 0, cknown = 0, lknown = 0, yours = 0, 
          corpsenm = 0, usecount = 0, oeaten = 0, age = 0, owornmask = 0, oextra = 0x0}
        i = 676
        dis = 560
        ct = 380
        mn = 331
        sl = 1
        s = 0x55ec9f27a660 <flags+96> ""
        oclass = 16 '\020'
        prev_class = 17 '\021'
        tmpwin = 6
        any = {a_void = 0x251, a_obj = 0x251, a_monst = 0x251, a_int = 593, a_char = 81 'Q', a_schar = 81 'Q', 
          a_uchar = 81 'Q', a_uint = 593, a_long = 593, a_ulong = 593, a_iptr = 0x251, a_lptr = 0x251, 
          a_ulptr = 0x251, a_uptr = 0x251, a_string = 0x251 <error: Cannot access memory at address 0x251>, 
          a_nfunc = 0x251, a_mask32 = 593}
        selected = 0x602000acc050
#17 0x000055ec9e3aeb83 in docallcmd () at do_name.c:1491
        obj = 0x100000000
        win = 6
        any = {a_void = 0x61, a_obj = 0x61, a_monst = 0x61, a_int = 97, a_char = 97 'a', a_schar = 97 'a', 
          a_uchar = 97 'a', a_uint = 97, a_long = 97, a_ulong = 97, a_iptr = 0x61, a_lptr = 0x61, a_ulptr = 0x61, 
          a_uptr = 0x61, a_string = 0x61 <error: Cannot access memory at address 0x61>, a_nfunc = 0x61, a_mask32 = 97}
        pick_list = 0x602000ac3830
        ch = 100 'd'
        allowall = "M"
        abc = 0 '\000'
#18 0x000055ec9e2e1a7b in rhack (cmd=0x55ec9f2658e0 <in_line> "C") at cmd.c:5661
        tlist = 0x55ec9f11a290 <extcmdlist+336>
        res = 688
        win = 6
        any = {a_void = 0x61, a_obj = 0x61, a_monst = 0x61, a_int = 97, a_char = 97 'a', a_schar = 97 'a', 
          a_uchar = 97 'a', a_uint = 97, a_long = 97, a_ulong = 97, a_iptr = 0x61, a_lptr = 0x61, a_ulptr = 0x61, 
          a_uptr = 0x61, a_string = 0x61 <error: Cannot access memory at address 0x61>, a_nfunc = 0x61, a_mask32 = 97}
        pick_list = 0x602000ac3830
        ch = 100 'd'
        allowall = "M"
        abc = 0 '\000'
#18 0x000055ec9e2e1a7b in rhack (cmd=0x55ec9f2658e0 <in_line> "C") at cmd.c:5661
        tlist = 0x55ec9f11a290 <extcmdlist+336>
        res = 688
--Type <RET> for more, q to quit, c to continue without paging--
        func = 0x55ec9e3ae2dd <docallcmd>
        spkey = 0
        prefix_seen = 0 '\000'
        bad_command = 83 'S'
        firsttime = 1 '\001'
#19 0x000055ec9e1dbdce in moveloop (resuming=0 '\000') at allmain.c:826
        moveamt = 10
        wtcap = 0
        change = 0
        monscanmove = 0 '\000'
        elf_regen = 1 '\001'
        orc_regen = 1 '\001'
        vamp_regen = 1 '\001'
#20 0x000055ec9ee5b1b4 in main (argc=0, argv=0x7ffddee6e6d8) at ../sys/unix/unixmain.c:353
        fd = -1
        dir = 0x0
        exact_username = 0 '\000'
        resuming = 0 '\000'
        plsel_once = 1 '\001'
    
´´´

**Comment by elunna** [comment]
At stack point 10, obj is 560, which corresponds to the Wide spellbook appearance.

**Comment by elunna** [comment]
another example here, but with the scroll class

```
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=139868726777792) at ./nptl/pthread_kill.c:44
        tid = <optimized out>
        ret = 0
        pd = 0x7f35b9c657c0
        old_mask = {__val = {139868722275616, 1073741824, 0, 139868724209536, 4294967295, 139868713779200, 
            139868724192768, 4137531658533373952, 140724122777312, 139868724209536, 0, 4137531658533373952, 
            17590515347164, 140724122777312, 17590515347164, 140724122777312}}
        ret = <optimized out>
        pd = <optimized out>
        old_mask = <optimized out>
        ret = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
        resultvar = <optimized out>
        resultvar = <optimized out>
        __arg3 = <optimized out>
        __arg2 = <optimized out>
        __arg1 = <optimized out>
        _a3 = <optimized out>
        _a2 = <optimized out>
        _a1 = <optimized out>
        __futex = <optimized out>
        resultvar = <optimized out>
        __arg3 = <optimized out>
        __arg2 = <optimized out>
        __arg1 = <optimized out>
        _a3 = <optimized out>
        _a2 = <optimized out>
        _a1 = <optimized out>
        __futex = <optimized out>
        __private = <optimized out>

        __oldval = <optimized out>
        result = <optimized out>
#1  __pthread_kill_internal (signo=6, threadid=139868726777792) at ./nptl/pthread_kill.c:78
No locals.
#2  __GI___pthread_kill (threadid=139868726777792, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
No locals.
#3  0x00007f35b981a476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
        ret = <optimized out>
#4  0x00007f35b98007f3 in __GI_abort () at ./stdlib/abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x5624cbf79670 <obufs+2384>, 
            sa_sigaction = 0x5624cbf79670 <obufs+2384>}, sa_mask = {__val = {0, 94716039027360, 139868729054399, 
              139868724192768, 4137531658533373952, 140724122777312, 139868724209536, 18446744073709547520, 
              139868726718464, 139868730282712, 139868729091757, 94716039027360, 139868729077782, 17590515347164, 
              140724122771456, 139868722275616}}, sa_flags = 835749888, sa_restorer = 0x5624cbf79670 <obufs+2384>}
        sigs = {__val = {32, 140724122781456, 139868728577038, 94716026367416, 94716026367144, 94716026366646, 
            139868722275616, 139868722768378, 139868728532568, 94716031409819, 94716031392416, 4137531658533373952, 
            94716031449187, 140724122782384, 140724122782384, 140724122777664}}
#5  0x00005624cb1b2cce in NH_abort () at end.c:236
        gdb_prio = 1
        libc_prio = 2
        aborting = 1 '\001'
#6  0x00005624cb1b2ab6 in panictrace_handler (sig_unused=11) at end.c:161
        f2 = 18
#7  <signal handler called>
No locals.
#8  __strlen_sse2 () at ../sysdeps/x86_64/multiarch/strlen-vec.S:126
No locals.
#9  0x00007f35b9e11e58 in __interceptor_strcat (to=0x5624cbf79670 <obufs+2384> "scroll of ", from=0x0)
    at ../../../../src/libsanitizer/asan/asan_interceptors.cpp:388
        from_length = <optimized out>
        to_length = <optimized out>
        ctx = <optimized out>
        _ctx = <optimized out>
#10 0x00005624cb681e9b in xname_flags (obj=0x7ffce3598ab0, cxn_flags=0) at objnam.c:918
        buf = 0x5624cbf79670 <obufs+2384> "scroll of "
        obufp = 0x0
        typ = 488
        ocl = 0x5624cbdc5aa0 <objects+19520>
        nn = 1
        omndx = 0
        orig_opknwn = 0
        actualn = 0x0
        dn = 0x5624cbbb4a20 "HZLRC KSTSBD MPFNG"
        un = 0x0
        pluralize = 0 '\000'
        known = 1 '\001'
        dknown = 1 '\001'
        bknown = 0 '\000'
#11 0x00005624cb67daa0 in xname (obj=0x7ffce3598ab0) at objnam.c:581
No locals.
#12 0x00005624cb09c4fa in docall_xname (obj=0x7ffce35990c0) at do_name.c:1543
        otemp = <error reading variable otemp (Cannot access memory at address 0xffffffffffffff40)>
#13 0x00005624cb68b863 in short_oname (obj=0x7ffce35990c0, func=0x5624cb09bcfe <docall_xname>, 
    altfunc=0x5624cb68d8f7 <simpleonames>, lenlimit=121) at objnam.c:1975
        save_obj = {nobj = 0x0, v = {v_nexthere = 0x0, v_ocontainer = 0x0, v_ocarry = 0x0}, cobj = 0x0, o_id = 0, 
          ox = 0 '\000', oy = 0 '\000', otyp = 0, owt = 0, quan = 0, spe = 0 '\000', oclass = 0 '\000', 
          invlet = 0 '\000', oartifact = 0 '\000', altmode = 0 '\000', oprops = 0, oprops_known = 0, where = 109 'm', 
          timed = 47 '/', cursed = 0, blessed = 1, unpaid = 1, no_charge = 0, known = 0, dknown = 0, bknown = 0, 
          rknown = 1, oeroded = 1, oeroded2 = 2, oerodeproof = 1, olocked = 1, oticking = 0, obroken = 1, 
          otrapped = 1, recharged = 2, lamplit = 1, globby = 1, greased = 0, nomerge = 0, was_thrown = 1, 
          odrained = 1, material = 31, in_use = 0, bypass = 0, cknown = 0, lknown = 0, yours = 0, corpsenm = 0, 
          usecount = 0, oeaten = 3114215296, age = 226, owornmask = 94716040848544, oextra = 0xd68}
        unamebuf = "\340\215Y\343\374\177\000\000\030", <incomplete sequence \346\271>
        onamebuf = "\000\000\000\000\000\000\000\000\200'\237\271"
        save_oname = 0x0
        save_uname = 0x0
        outbuf = 0x0
#14 0x00005624cb6a1289 in safe_qbuf (qbuf=0x7ffce3598e00 "Call ", qprefix=0x5624cbc06de0 "Call ", 
    qsuffix=0x5624cbc06da0 ":", obj=0x7ffce35990c0, func=0x5624cb09bcfe <docall_xname>, 
    altfunc=0x5624cb68d8f7 <simpleonames>, lastR=0x5624cbc06e20 "thing") at objnam.c:5562
        bufp = 0x1553206568 ""
        endp = 0x7ffce3598e7f ""
        len = 6
        lenlimit = 127
        len_qpfx = 5
        len_qsfx = 1
        len_lastR = 5
#15 0x00005624cb09c897 in docall (obj=0x7ffce35990c0) at do_name.c:1562
        buf = "\377\377\377\377\000\000\000\000\000\000\000\271\065\177\000\000\000枹5\177\000\000\000\210\320\061\037wk9\260\002\000\000\320`\000\000\200'\237\271\065\177", '\000' <repeats 11 times>, "\210\320\061\037wk90\217Y\343\377\377\377\377\025\000\000\000\000\000\000\000X \367\313$V\000\000O\000\000\000\000\000\000\000l\004\267\313$V\000\000x\002\000\000\000\000\000\000\060\217Y\343\374\177\000\000\216\344\367\312$V\000\000\f\000\000\000\000\000\000\000\025\000\000\000\000\000\000\000\200\217Y\343\374\177\000\000^\263\005\313$V\000\000P\217Y\343\374\177\000\000\250K'\313\001\000\000\000\200\217Y\343\374\177\000\000\f\240\005\313\025\000\000\000pi\a\000\320`\000\000\000\000\000\000\000\000\000\000"...
        qbuf = "Call ", '\000' <repeats 122 times>
        str1 = 0x0
#16 0x00005624cb67b5a1 in rename_disco () at o_init.c:751
        odummy = {nobj = 0x0, v = {v_nexthere = 0x0, v_ocontainer = 0x0, v_ocarry = 0x0}, cobj = 0x0, o_id = 0, 
          ox = 0 '\000', oy = 0 '\000', otyp = 488, owt = 0, quan = 1, spe = 0 '\000', oclass = 9 '\t', 
          invlet = 0 '\000', oartifact = 0 '\000', altmode = 0 '\000', oprops = 0, oprops_known = 0, 
          where = 0 '\000', timed = 0 '\000', cursed = 0, blessed = 0, unpaid = 0, no_charge = 0, known = 1, 
          dknown = 1, bknown = 0, rknown = 0, oeroded = 0, oeroded2 = 0, oerodeproof = 0, olocked = 0, oticking = 0, 
          obroken = 0, otrapped = 0, recharged = 0, lamplit = 0, globby = 0, greased = 0, nomerge = 0, 
          was_thrown = 0, odrained = 0, material = 0, in_use = 0, bypass = 0, cknown = 0, lknown = 0, yours = 0, 
          corpsenm = 0, usecount = 0, oeaten = 0, age = 0, owornmask = 0, oextra = 0x0}
        i = 632
        dis = 488
        ct = 363
        mn = 314
        sl = 1
        s = 0x5624cbf6ba00 <flags+96> ""
        oclass = 11 '\v'
        prev_class = 11 '\v'
        tmpwin = 6
        any = {a_void = 0x245, a_obj = 0x245, a_monst = 0x245, a_int = 581, a_char = 69 'E', a_schar = 69 'E', 
          a_uchar = 69 'E', a_uint = 581, a_long = 581, a_ulong = 581, a_iptr = 0x245, a_lptr = 0x245, 
          a_ulptr = 0x245, a_uptr = 0x245, a_string = 0x245 <error: Cannot access memory at address 0x245>, 
          a_nfunc = 0x245, a_mask32 = 581}
        selected = 0x602000256870
#17 0x00005624cb09bc75 in docallcmd () at do_name.c:1504
        obj = 0x100000000
        win = 6
        any = {a_void = 0x61, a_obj = 0x61, a_monst = 0x61, a_int = 97, a_char = 97 'a', a_schar = 97 'a', 
          a_uchar = 97 'a', a_uint = 97, a_long = 97, a_ulong = 97, a_iptr = 0x61, a_lptr = 0x61, a_ulptr = 0x61, 
          a_uptr = 0x61, a_string = 0x61 <error: Cannot access memory at address 0x61>, a_nfunc = 0x61, a_mask32 = 97}
        pick_list = 0x602000256f10
        ch = 100 'd'
        allowall = "`\222"
        abc = 0 '\000'
#18 0x00005624cafce9d4 in rhack (cmd=0x5624cbf56c80 <in_line> <incomplete sequence \356>) at cmd.c:5661
        tlist = 0x5624cbe0b7b0 <extcmdlist+1872>
        res = -480668912
        func = 0x5624cb09b3cf <docallcmd>
        spkey = 0
        prefix_seen = 0 '\000'
        bad_command = 36 '$'
        firsttime = 1 '\001'
#19 0x00005624caec8dce in moveloop (resuming=0 '\000') at allmain.c:826
        moveamt = 12
        wtcap = 0
        change = 0
        monscanmove = 0 '\000'
        elf_regen = 1 '\001'
        orc_regen = 1 '\001'
        vamp_regen = 1 '\001'
#20 0x00005624cbb4c8ca in main (argc=0, argv=0x7ffce35995b8) at ../sys/unix/unixmain.c:353
        fd = -1
        dir = 0x0
        exact_username = 0 '\000'
        resuming = 0 '\000'
        plsel_once = 1 '\001'
