### ISSUE TITLE
Found with fuzzer: dmonsfree: 6 removed doesn't match 8 pending on Dlvl:1

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#127]
```
Suddenly, the dungeon collapses.
dmonsfree: 6 removed doesn't match 8 pending on Dlvl:1
Generating more information you may report:

[0] /lib/x86_64-linux-gnu/libasan.so.5(+0x6cd40) [0x7ffff75f8d40]
[1] /home/lunatunez/games/hackemdir/hackem(+0x508fda) [0x555555a5cfda]
[2] /home/lunatunez/games/hackemdir/hackem(+0x508ecd) [0x555555a5cecd]
[3] /home/lunatunez/games/hackemdir/hackem(panic+0x6ab) [0x555555a63d82]
[4] /home/lunatunez/games/hackemdir/hackem(impossible+0x2c8) [0x555555fbf27c]
[5] /home/lunatunez/games/hackemdir/hackem(dmonsfree+0x3b5) [0x555555dd1a92]
[6] /home/lunatunez/games/hackemdir/hackem(movemon+0x1918) [0x555555dbe0e8]
[7] /home/lunatunez/games/hackemdir/hackem(moveloop+0x603) [0x55555576f229]
[8] /home/lunatunez/games/hackemdir/hackem(main+0xdda) [0x5555563e7a06]
[9] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7ffff7365083]
[10] /home/lunatunez/games/hackemdir/hackem(_start+0x2e) [0x55555576cace]


Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7363859 in __GI_abort () at abort.c:79
#2  0x0000555555a5cef3 in NH_abort () at end.c:236
#3  0x0000555555a63d82 in panic (str=0x55555655d1a0 "%s") at end.c:802
#4  0x0000555555fbf27c in impossible (
    s=0x555556514720 "dmonsfree: %d removed doesn't match %d pending on %s") at pline.c:518
#5  0x0000555555dd1a92 in dmonsfree () at mon.c:3022
#6  0x0000555555dbe0e8 in movemon () at mon.c:1579
#7  0x000055555576f229 in moveloop (resuming=0 '\000') at allmain.c:244
#8  0x00005555563e7a06 in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {0, 0, 0, 0, 0, 140737335783280, 93824997510085, 335544320, 
            140737341046928, 1073741824, 0, 140737342793376, 4294967295, 140737337360384, 
            140737342776480, 7850552889579315712}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007ffff7363859 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0xffffffff, sa_sigaction = 0xffffffff}, 
          sa_mask = {__val = {140737337360384, 140737342776480, 7850552889579315712, 
              140737488345008, 140737342793376, 18446744073709547520, 140737327104000, 
              140737345462488, 140737488346080, 140737488346080, 140737344331794, 
              17592186043126, 140737488338944, 140737341046928, 7850552889579315712, 
              140737488345408}}, sa_flags = 1372234240, sa_restorer = 0x7fffffffdb00}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x0000555555a5cef3 in NH_abort () at end.c:236
        gdb_prio = 1
        libc_prio = 2
        aborting = 1 '\001'
#3  0x0000555555a63d82 in panic (str=0x55555655d1a0 "%s") at end.c:802
        the_args = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7fffffffdbd0, 
            reg_save_area = 0x7fffffffdb00}}
#4  0x0000555555fbf27c in impossible (
    s=0x555556514720 "dmonsfree: %d removed doesn't match %d pending on %s") at pline.c:518
        pbuf = "dmonsfree: 6 removed doesn't match 8 pending on Dlvl:1  \000#\232UUU\000\000@\337H\000\020a\000\000\300\211\067\000\020a\000\000\200\200\000\000\v\000\000\000H\364\377\377\377\377\377\377\360\334\377\377\377\177\000\000\005+\232UUU\000\000\360\335\377\377\377\177\000\000\000\242\312QB\304\362l\340\334\377\377\377\177\000\000\300\211\067\000\020a\000\000\020\337\377\377\377\177\000\000|\241!VUU\000\000\020\335\377\377\377\177\000\000 Y\220UUU\000\000\020\337\377\377\240\003\000\000\004\000\000\000\062\000\000\000\300\335\377\000\377\177\000\000"...
        the_args = {{gp_offset = 32, fp_offset = 48, overflow_arg_area = 0x7fffffffe2c0, 
            reg_save_area = 0x7fffffffe1e0}}
#5  0x0000555555dd1a92 in dmonsfree () at mon.c:3022
        mtmp = 0x6110003789c0
        freetmp = 0x6110003789c0
        count = 6
        buf = "Dlvl:1  \000\270\254U@\000\000\000P\343\377\377\377\177\000\000]\022\201UUU\000\000 \344\377\377\377\177\000\000\000\000\000\000\004\000\000\000\364-\177VUU\000\000\nx\200VUU\000\000p\343\377\377\377\177\000\000\236\201\210UUU\000\000\240\343\377\377\377\177\000\000\003\000\000\000\062\000\000\000\024\000\000\000\000\000\000\000\211\001\000\000\000\000\000\031\240\343\377\377\377\177\000\000\000\242\312QB\304\362l"
#6  0x0000555555dbe0e8 in movemon () at mon.c:1579
        mtmp = 0x0
        nmtmp = 0x0
        somebody_can_move = 0 '\000'
#7  0x000055555576f229 in moveloop (resuming=0 '\000') at allmain.c:244
        moveamt = 12
        wtcap = 0
        change = 0
        monscanmove = 0 '\000'
        elf_regen = 1 '\001'
        orc_regen = 1 '\001'
        vamp_regen = 1 '\001'
#8  0x00005555563e7a06 in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
        fd = -1
        dir = 0x0
        exact_username = 0 '\000'
        resuming = 0 '\000'
        plsel_once = 1 '\001'

```

**Comment by elunna** [comment]
Likely the same issue as fixed in fdaafb93a - we don't have a recording to check so we'll assume so until this reappears.
