### ISSUE TITLE
Found with fuzzer: worn mask (multiple) 0x 

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#131]
```
Suddenly, the dungeon collapses.
worn mask (multiple) 0x       600 obj 60c00095bf00 invent: an uncursed +0 chakram (alternate weapon; not wielded) (at the ready)
Generating more information you may report:

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7363859 in __GI_abort () at abort.c:79
#2  0x0000555555a5cdb5 in NH_abort () at end.c:236
#3  0x0000555555a63c44 in panic (str=0x5555565621e0 "%s") at end.c:802
#4  0x0000555555fbf746 in impossible (s=0x555556514180 <ofmt0> "%s obj %s %s: %s")
    at pline.c:518
#5  0x0000555555d7dfb1 in insane_object (obj=0x60c00095bf00, 
    fmt=0x555556514180 <ofmt0> "%s obj %s %s: %s", 
    mesg=0x7fffffffdf70 "worn mask (multiple) 0x       600", mon=0x0) at mkobj.c:2869
#6  0x0000555555d7f3f8 in sanity_check_worn (obj=0x60c00095bf00) at mkobj.c:3025
#7  0x0000555555d7d334 in objlist_sanity (objlist=0x60c00095bf00, wheretype=3, 
    mesg=0x555556514380 "invent sanity") at mkobj.c:2756
#8  0x0000555555d7cd1e in obj_sanity_check () at mkobj.c:2701
#9  0x0000555555876d17 in sanity_check () at cmd.c:4979
#10 0x00005555557758d1 in moveloop (resuming=0 '\000') at allmain.c:795
#11 0x00005555563ecd1d in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353


#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {0, 0, 0, 0, 0, 140737335783280, 93824997509767, 335544320, 
            140737341046928, 1073741824, 0, 140737342793376, 4294967295, 140737337360384, 
            140737342776480, 4325236530291961600}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007ffff7363859 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0xffffffff, sa_sigaction = 0xffffffff}, 
          sa_mask = {__val = {140737337360384, 140737342776480, 4325236530291961600, 
              140737488343488, 140737342793376, 18446744073709547520, 140737327104000, 
              140737345462488, 140737488344560, 140737488344560, 140737344331794, 
              17592186042936, 140737488338944, 140737341046928, 4325236530291961600, 
              140737488343888}}, sa_flags = 1301835520, sa_restorer = 0x7fffffffd510}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x0000555555a5cdb5 in NH_abort () at end.c:236
        gdb_prio = 1
        libc_prio = 2
        aborting = 1 '\001'
#3  0x0000555555a63c44 in panic (str=0x5555565621e0 "%s") at end.c:802
        the_args = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7fffffffd5e0, 
            reg_save_area = 0x7fffffffd510}}
#4  0x0000555555fbf746 in impossible (s=0x555556514180 <ofmt0> "%s obj %s %s: %s")
    at pline.c:518
        pbuf = "worn mask (multiple) 0x       600 obj 60c00095bf00 invent: an uncursed +0 chakram (alternate weapon; not wielded) (at the ready)\000\327\377\377\377\177\063\066\000o\230M\265S\006<\345\001\000\000p`\000\000  V\367\377\177\000\000 \327\377\377\377\177\000\000\240\000\000\000\200`\000\000 \341\377\377\377\177\000\000\000\000\000\000\000\000\000\000\345\001\000\000p`\000\000"...
        the_args = {{gp_offset = 40, fp_offset = 48, overflow_arg_area = 0x7fffffffdcd0, 
            reg_save_area = 0x7fffffffdbf0}}
#5  0x0000555555d7dfb1 in insane_object (obj=0x60c00095bf00, 
    fmt=0x555556514180 <ofmt0> "%s obj %s %s: %s", 
    mesg=0x7fffffffdf70 "worn mask (multiple) 0x       600", mon=0x0) at mkobj.c:2869
        objnm = 0x55555681b841 <obufs+2625> "an uncursed +0 chakram (alternate weapon; not wielded) (at the ready)"
        monnm = 0x555556514a80 "null!"
        altfmt = '\000' <repeats 105 times>, "o\230M\265S\006<\000\000\000\000\000\000\000\000\342\373\377\377\377\017\000\000\020\337\377\377\377\177\000\000\360\337\377\377\377\177\000\000\020\337\377\377\377\177\000\000\000\000\000\000\000\000\000\000\020\340\377\377\377\177\000\000߫b\367\377\177", '\000' <repeats 18 times>, "\030\000\000\000\060\000\000\000\320"...
#6  0x0000555555d7f3f8 in sanity_check_worn (obj=0x60c00095bf00) at mkobj.c:3025
        wearbits = {1, 2, 4, 8, 16, 32, 64, 256, 512, 1024, 65536, 131072, 262144, 524288, 
          1048576, 2097152, 4194304, 8388608, 0}
        maskbuf = "worn mask (multiple) 0x       600", '\000' <repeats 26 times>
        what = 0x0
        owornmask = 1536
        allmask = 16713599
        embedded = 0 '\000'
        i = 18
        n = 2
#7  0x0000555555d7d334 in objlist_sanity (objlist=0x60c00095bf00, wheretype=3, 
    mesg=0x555556514380 "invent sanity") at mkobj.c:2756
        maskbuf = '\000' <repeats 39 times>
        bc_ok = 0 '\000'
        obj = 0x60c00095bf00
#8  0x0000555555d7cd1e in obj_sanity_check () at mkobj.c:2701
        x = 80
        y = 21
        obj = 0x0
#9  0x0000555555876d17 in sanity_check () at cmd.c:4979
No locals.
#10 0x00005555557758d1 in moveloop (resuming=0 '\000') at allmain.c:795
        moveamt = 12
        wtcap = 0
        change = 0
        monscanmove = 0 '\000'
        elf_regen = 1 '\001'
        orc_regen = 1 '\001'
        vamp_regen = 1 '\001'
#11 0x00005555563ecd1d in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
        fd = -1
        dir = 0x0
        exact_username = 0 '\000'
        resuming = 0 '\000'
        plsel_once = 1 '\001'
```

**Comment by elunna** [comment]
Haven't been able to reproduce yet: Tried messing around with chakrams, wielding, offhanding, readying.

Could be related to upgrading boomerangs?

**Comment by elunna** [comment]
I informed the devteam about this issue and they have a fix (for 3.7): https://github.com/NetHack/NetHack/commit/9a9f2d596d2e1b5f7581da1c2b8be25668540eaf

and here: https://github.com/NetHack/NetHack/commit/a294fdf1795565fb9200a30e18d28b588b671171

**Comment by elunna** [comment]
Closed - Issue is not able to be ported easily to 3.6 from 3.7 fix.

**Comment by elunna** [comment]
Reopening to try using the 3.7 solution.
