### ISSUE TITLE
Found with fuzzer: Bad spider_parts during mcastu

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#14]
```
=================================================================
==11841==ERROR: AddressSanitizer: global-buffer-overflow on address 0x555556709ff8 at pc 0x555555fb489b bp 0x7fffffffda50 sp 0x7fffffffda40
READ of size 8 at 0x555556709ff8 thread T0
    #0 0x555555fb489a in mbodypart /home/lunatunez/hackem/src/polyself.c:2085
    #1 0x555555fb4cee in body_part /home/lunatunez/hackem/src/polyself.c:2107
    #2 0x555555b8ec11 in cast_cleric_spell /home/lunatunez/hackem/src/mcastu.c:1206
    #3 0x555555b75a7c in castmu /home/lunatunez/hackem/src/mcastu.c:511
    #4 0x555555ca3f3f in mattacku /home/lunatunez/hackem/src/mhitu.c:1189
    #5 0x555555e37ec5 in dochug /home/lunatunez/hackem/src/monmove.c:964
    #6 0x555555e23335 in dochugw /home/lunatunez/hackem/src/monmove.c:122
    #7 0x555555d92b74 in movemon /home/lunatunez/hackem/src/mon.c:1509
    #8 0x55555575b289 in moveloop /home/lunatunez/hackem/src/allmain.c:244
    #9 0x5555563b4126 in main ../sys/unix/unixmain.c:353
    #10 0x7ffff7367082 in __libc_start_main ../csu/libc-start.c:308
    #11 0x555555758b0d in _start (/home/lunatunez/games/hackemdir/hackem+0x204b0d)

0x555556709ff8 is located 0 bytes to the right of global variable 'spider_parts' defined in 'polyself.c:1992:10' (0x555556709f60) of size 152
0x555556709ff8 is located 40 bytes to the left of global variable 'sphere_parts' defined in 'polyself.c:1960:10' (0x55555670a020) of size 160
SUMMARY: AddressSanitizer: global-buffer-overflow /home/lunatunez/hackem/src/polyself.c:2085 in mbodypart
Shadow bytes around the buggy address:
  0x0aab2acd93a0: f9 f9 f9 f9 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aab2acd93b0: 00 00 00 00 00 00 00 00 f9 f9 f9 f9 00 00 00 00
  0x0aab2acd93c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aab2acd93d0: f9 f9 f9 f9 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aab2acd93e0: 00 00 00 00 00 00 00 00 f9 f9 f9 f9 00 00 00 00
=>0x0aab2acd93f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00[f9]
  0x0aab2acd9400: f9 f9 f9 f9 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aab2acd9410: 00 00 00 00 00 00 00 00 f9 f9 f9 f9 00 00 00 00
  0x0aab2acd9420: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aab2acd9430: f9 f9 f9 f9 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aab2acd9440: 00 00 00 00 00 00 00 00 f9 f9 f9 f9 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==11841==ABORTING
```

**Comment by elunna** [comment]
Spiders did not have a body part for skin; this seemed to be causing an issue with the vulnerability spell monsters have. Added "cuticle" for the spider skin.
