### ISSUE TITLE
dmonsfree: 3 removed doesn't match 4 pending on Fort Ludios

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#154]
```
Suddenly, the dungeon collapses.
dmonsfree: 3 removed doesn't match 4 pending on Fort Ludios
Generating more information you may report:

#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7363859 in __GI_abort () at abort.c:79
#2  0x0000555555a579a1 in NH_abort () at end.c:236
#3  0x0000555555a5e830 in panic (str=0x55555655f4a0 "%s") at end.c:802
#4  0x0000555555fbac35 in impossible (
    s=0x555556516a60 "dmonsfree: %d removed doesn't match %d pending on %s") at pline.c:518
#5  0x0000555555dcdda3 in dmonsfree () at mon.c:3023
#6  0x0000555555dba3fe in movemon () at mon.c:1580
#7  0x000055555576f229 in moveloop (resuming=0 '\000') at allmain.c:244
#8  0x00005555563ea323 in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353

#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {0, 0, 0, 0, 0, 140737335783280, 93824997488243, 335544320,
            140737341046928, 1073741824, 0, 140737342793376, 4294967295, 140737337360384,
            140737342776480, 1577293532716846336}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007ffff7363859 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0xffffffff, sa_sigaction = 0xffffffff},
          sa_mask = {__val = {140737337360384, 140737342776480, 1577293532716846336,
              140737488345008, 140737342793376, 18446744073709547520, 140737327104000,
              140737345462488, 140737488346080, 140737488346080, 140737344331794,
              17592186043126, 140737488338944, 140737341046928, 1577293532716846336,
              140737488345408}}, sa_flags = 1947979008, sa_restorer = 0x7fffffffdb00}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x0000555555a579a1 in NH_abort () at end.c:236
        gdb_prio = 1
        libc_prio = 2
        aborting = 1 '\001'
#3  0x0000555555a5e830 in panic (str=0x55555655f4a0 "%s") at end.c:802
        the_args = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7fffffffdbd0,
            reg_save_area = 0x7fffffffdb00}}
--Type <RET> for more, q to quit, c to continue without paging--
#4  0x0000555555fbac35 in impossible (
    s=0x555556516a60 "dmonsfree: %d removed doesn't match %d pending on %s") at pline.c:518
        pbuf = "dmonsfree: 3 removed doesn't match 4 pending on Fort Ludios \000`\000\000\263\212\265A\000\000\000\000X PVUU\000\000<\023\313UUU\000\000Xs\177VUU\000\000\300\334\377\377\377\177\000\000\342\377\240UUU\000\000\000\000\000\000\000\000\000\000\200\251\a\000\027\000\000\000\020\337\377\377\377\177\000\000\377\254!VUU\000\000\263\212\265A\000\000\000\000`\335\377\377\377\177", '\000' <repeats 27 times>, "\242\a\000\020a\000\000 \336\377\377\377\177\000\000"...
        the_args = {{gp_offset = 32, fp_offset = 48, overflow_arg_area = 0x7fffffffe2c0,
            reg_save_area = 0x7fffffffe1e0}}
#5  0x0000555555dcdda3 in dmonsfree () at mon.c:3023
        mtmp = 0x61100007a980
        freetmp = 0x61100007a980
        count = 3
        buf = "Fort Ludios \000\000\000\000P\343\377\377\377\177\000\000\301\016\201UUU\000\000 \344\377\377\377\177\000\000\000\000\000\000\004\000\000\000\024Z\177VUU\000\000*\244\200VUU\000\000p\343\377\377\377\177\000\000\326}\210UUU\000\000\240\343\377\377\377\177\000\000\016\000\000\000\016\000\000\000\v\000\000\000\000\000\000\000k\003\000\000\000\000\000\031\240\343\377\377\377\177\000\000\000\315\033t\034\254\343\025"
#6  0x0000555555dba3fe in movemon () at mon.c:1580
        mtmp = 0x0
        nmtmp = 0x0
        somebody_can_move = 1 '\001'
#7  0x000055555576f229 in moveloop (resuming=0 '\000') at allmain.c:244
--Type <RET> for more, q to quit, c to continue without paging--
        moveamt = 16
        wtcap = 0
        change = 0
        monscanmove = 0 '\000'
        elf_regen = 1 '\001'
        orc_regen = 1 '\001'
        vamp_regen = 1 '\001'
#8  0x00005555563ea323 in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
        fd = -1
        dir = 0x0
        exact_username = 0 '\000'
        resuming = 0 '\000'
        plsel_once = 1 '\001'
```

**Comment by elunna** [comment]
Possibly connected to issue #169
