### ISSUE TITLE
Bag of tricks; extract_nobj: object lost

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#155]
```
Suddenly, the dungeon collapses.
extract_nobj: object lost
Generating more information you may report:

#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7363859 in __GI_abort () at abort.c:79
#2  0x0000555555a579a1 in NH_abort () at end.c:236
#3  0x0000555555a5e830 in panic (str=0x555556510d80 "extract_nobj: object lost") at end.c:802
#4  0x0000555555d761ed in extract_nobj (obj=0x60c0002b3180, head_ptr=0x55555680b6a0 <invent>)
    at mkobj.c:2402
#5  0x0000555555b0ff8a in freeinv (obj=0x60c0002b3180) at invent.c:1216
#6  0x000055555591df40 in dropx (obj=0x60c0002b3180) at do.c:1065
#7  0x0000555555b81a72 in bagotricks (bag=0x60c0002b3180) at makemon.c:4608
#8  0x0000555555fb68a8 in tipcontainer_checks (box=0x60c0002b3180, targetbox=0x0,
    allowempty=0 '\000') at pickup.c:3949
#9  0x0000555555fb4188 in tipcontainer (box=0x60c0002b3180) at pickup.c:3663
#10 0x0000555555fb0e6c in dotip () at pickup.c:3417
#11 0x000055555587a201 in rhack (cmd=0x5555567f5480 <in_line> <incomplete sequence \324>)
    at cmd.c:5661
#12 0x0000555555775d6a in moveloop (resuming=0 '\000') at allmain.c:826
#13 0x00005555563ea323 in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353

#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {0, 0, 0, 0, 0, 140737335783280, 93824997488243, 335544320,
            140737341046928, 1073741824, 0, 140737342793376, 4294967295, 140737337360384,
            140737342776480, 16657669130522443520}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007ffff7363859 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0xffffffff, sa_sigaction = 0xffffffff},
          sa_mask = {__val = {140737337360384, 140737342776480, 16657669130522443520,
              140737488344704, 140737342793376, 18446744073709547520, 140737327104000,
              140737345462488, 17592186043240, 140737488346128, 140737344331794, 17592186043088,
              140737488338944, 140737341046928, 16657669130522443520, 140737488345104}},
          sa_flags = 1858584320, sa_restorer = 0x7fffffffd9d0}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x0000555555a579a1 in NH_abort () at end.c:236
        gdb_prio = 1
        libc_prio = 2
        aborting = 1 '\001'
#3  0x0000555555a5e830 in panic (str=0x555556510d80 "extract_nobj: object lost") at end.c:802
        the_args = {{gp_offset = 8, fp_offset = 48, overflow_arg_area = 0x7fffffffdaa0,
            reg_save_area = 0x7fffffffd9d0}}
--Type <RET> for more, q to quit, c to continue without paging--
#4  0x0000555555d761ed in extract_nobj (obj=0x60c0002b3180, head_ptr=0x55555680b6a0 <invent>)
    at mkobj.c:2402
        curr = 0x0
        prev = 0x60c0002b81c0
#5  0x0000555555b0ff8a in freeinv (obj=0x60c0002b3180) at invent.c:1216
No locals.
#6  0x000055555591df40 in dropx (obj=0x60c0002b3180) at do.c:1065
No locals.
#7  0x0000555555b81a72 in bagotricks (bag=0x60c0002b3180) at makemon.c:4608
        gotone = 1 '\001'
        cnt = -1
        mtmp = 0x736b636972742066
        otmp = 0x0
        choice = 2
#8  0x0000555555fb68a8 in tipcontainer_checks (box=0x60c0002b3180, targetbox=0x0,
    allowempty=0 '\000') at pickup.c:3949
        maybeshopgoods = 0 '\000'
        oy = 6 '\006'
        res = 0
        bag = 1 '\001'
        old_spe = 18
        ox = 71 'G'
#9  0x0000555555fb4188 in tipcontainer (box=0x60c0002b3180) at pickup.c:3663
--Type <RET> for more, q to quit, c to continue without paging--
        ox = 71 'G'
        oy = 6 '\006'
        held = 0 '\000'
        maybeshopgoods = 0 '\000'
        targetbox = 0x0
        cancelled = 0 '\000'
#10 0x0000555555fb0e6c in dotip () at pickup.c:3417
        cobj = 0x60c0002b3180
        nobj = 0x0
        cc = {x = 71 'G', y = 6 '\006'}
        boxes = 1
        c = 121 'y'
        buf = "You can't tip it while carrying so much.", '\000' <repeats 112 times>, "\340\270T\367\377\177\000\000p#?VUU", '\000' <repeats 89 times>
        qbuf = "There is a bag of tricks (15 aum) here, tip it?", '\000' <repeats 81 times>, "P\342\377\377\377\177\000\000\212\006\202VUU\000\000@\342\377\377\377\177\000\000\336#?VUU\000\000@\342\377\377\377\177\000\000\020\001\000\000\320`\000\000\200\342\377\377\377\177\000\000\003\070@VUU\000\000\020\344\377\377\377\177\000\000\000"...
        spillage = 0x0
#11 0x000055555587a201 in rhack (cmd=0x5555567f5480 <in_line> <incomplete sequence \324>)
    at cmd.c:5661
        tlist = 0x5555566aafe0 <extcmdlist+4032>
        res = 688
--Type <RET> for more, q to quit, c to continue without paging--
        func = 0x555555fb010d <dotip>
        spkey = 0
        prefix_seen = 0 '\000'
        bad_command = -47 '\321'
        firsttime = 1 '\001'
#12 0x0000555555775d6a in moveloop (resuming=0 '\000') at allmain.c:826
        moveamt = 18
        wtcap = 0
        change = 0
        monscanmove = 0 '\000'
        elf_regen = 1 '\001'
        orc_regen = 1 '\001'
        vamp_regen = 1 '\001'
#13 0x00005555563ea323 in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
        fd = -1
        dir = 0x0
        exact_username = 0 '\000'
        resuming = 0 '\000'
        plsel_once = 1 '\001'
```

**Comment by elunna** [comment]
This is caused by tipping a bag of tricks on the ground. Case 2 assumes that you are holding the bag, and attempts to drop the bag from your possession. It then tries to free the bag from your inventory, which is impossible.
```
case 2:
            pline_The("bag wriggles away from you!");
            dropx(bag);
            break;
```
