### ISSUE TITLE
mon (6110002c0780) at <75,3> is not there!

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#159]
```
"The seemingly dead giant louse suddenly reconstitutes and rises as a\ndoppelganger!"

Suddenly, the dungeon collapses.
mon (6110002c0780) at <75,3> is not there!
Generating more information you may report:

#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140073081329600)
    at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140073081329600)
    at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140073081329600, signo=signo@entry=6)
    at ./nptl/pthread_kill.c:89
#3  0x00007f654e01a476 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/posix/raise.c:26
#4  0x00007f654e0007f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00005616c0c49d45 in NH_abort () at end.c:236
#6  0x00005616c0c50c3e in panic (str=0x5616c175ba00 "%s") at end.c:802
#7  0x00005616c11b2bf0 in impossible (
    s=0x5616c1711600 "mon (%s) at <%d,%d> is not there!") at pline.c:518
#8  0x00005616c0f7fbd3 in mon_sanity_check () at mon.c:165
#9  0x00005616c0a6729f in sanity_check () at cmd.c:4981
#10 0x00005616c0964957 in moveloop (resuming=0 '\000') at allmain.c:796
#11 0x00005616c15e6f6f in main (argc=0, argv=0x7ffea3461188)

```

**Comment by elunna** [comment]
Analysis in rr shows that an antimatter vortex killed a doppelganger while engulfing it.
When killed, this is set in mondead
```
mtmp->cham = NON_PM;
```

I was able to reproduce with these steps
1. turn on sanity checking
2. wish up a doppelganger and antimatter vortex
3. wish for a ring of conflict and wear it
4. manipulate the antimatter vortex into engulfing and killing the doppelganger while it is polymorphed into a different form.

**Comment by elunna** [comment]
**Testing in evil:** If a doppelganger had already been killed and turned back into it's base form permanently, this bug doesn't trigger.

I also got this both these errors in evil when reproducing it as normal:
```
placing antimatter vortex <34,4> over itself at <34,4>, mstates:0 0 on Dlvl:1  ?
mon (6110000039c0) at <34,4> is not there!
```
after a few turns the doppelganger came back.
