### ISSUE TITLE
segfault: Guardian angel on astral plane hunger issue

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#163]
```
0x00005555559a2802 in dog_hunger (mtmp=0x61100000be40, edog=0x0) at dogmove.c:756
756         if (monstermoves > edog->hungrytime + 500) {
(gdb) bthe Sniveler            St:17 Dx:8 Co:10 In:9 Wi:16 Ch:17 Chaotic
#0  0x00005555559a2802 in dog_hunger (mtmp=0x61100000be40, edog=0x0) at dogmove.c:756
#1  0x00005555559a8a36 in dog_move (mtmp=0x61100000be40, after=0) at dogmove.c:1392
#2  0x0000555555e71018 in m_move (mtmp=0x61100000be40, after=0) at monmove.c:1253
#3  0x0000555555e6a93e in dochug (mtmp=0x61100000be40) at monmove.c:944
#4  0x0000555555e555bf in dochugw (mtmp=0x61100000be40) at monmove.c:126
#5  0x0000555555dc1a4d in movemon () at mon.c:1568
#6  0x0000555555773229 in moveloop (resuming=0 '\000') at allmain.c:245
#7  0x00005555563f7fae in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353

#1  0x00005555559a8a36 in dog_move (mtmp=0x61100000be40, after=0) at dogmove.c:1392
        omx = 33
        omy = 16
        appr = 0
        whappr = 0
        udist = 0
        i = 0
        j = 0
        k = 0
        edog = <optimized out>
        obj = 0x0
        otyp = 0 '\000'
        has_edog = 0 '\000'
        cursemsg = "\000\000\000\000\000\000\000\000"
        summoned = 1 '\001'
        do_eat = 0 '\000'
        better_with_displacing = 0 '\000'
        nix = 0 '\000'
        niy = 0 '\000'
        nx = -7312
        ny = -970
        cnt = 0 '\000'
        uncursedcnt = 0 '\000'
        chcnt = 0 '\000'
        chi = -1
        nidist = 0
        ndist = 0
        poss = {{x = 0 '\000', y = 0 '\000'}, {x = 0 '\000', y = 0 '\000'}, {x = 0 '\000', 
            y = 0 '\000'}, {x = 0 '\000', y = 0 '\000'}, {x = 0 '\000', y = 0 '\000'}, {
            x = 0 '\000', y = 0 '\000'}, {x = 0 '\000', y = 0 '\000'}, {x = 0 '\000', 
            y = 0 '\000'}, {x = 0 '\000', y = 0 '\000'}}
        info = {0, 0, 0, 0, 0, 0, 0, 0, 0}
        allowflags = 0
#2  0x0000555555e71018 in m_move (mtmp=0x61100000be40, after=0) at monmove.c:1253
        appr = <optimized out>
        gx = 0 '\000'
        gy = 64 '@'
        nix = -66 '\276'
        niy = 0 '\000'
        chcnt = 0 '\000'
        i = 0
        j = 0
        chi = 0
        likegold = 0 '\000'
        likegems = 0 '\000'
        likeobjs = 0 '\000'
        likemagic = 0 '\000'
        conceals = 0 '\000'
        likerock = 0 '\000'
        can_tunnel = 0 '\000'
        can_open = 1 '\001'
        can_unlock = 0 '\000'
        doorbuster = 0 '\000'
        uses_items = 0 '\000'
        setlikes = 0 '\000'
        avoid = 0 '\000'
        better_with_displacing = 0 '\000'
        sawmon = 1 '\001'
        ptr = 0x555556657288 <mons+33384>
        mtoo = 0x7fffffffe120
        spirit = 0x61100000be40
        mmoved = 0 '\000'
        info = {-4294967296, -1, 4956392259584, 140737488347312, 137438953488, 141733920784, 
          4294967297, -4294967296, -1}
        flag = 140737488347072
        omx = 33
        omy = 16
        offer = 21845
#3  0x0000555555e6a93e in dochug (mtmp=0x61100000be40) at monmove.c:944
        mdat = 0x555556657288 <mons+33384>
        tmp = <optimized out>
        mdummy = 0x0
        inrange = 1
        nearby = 1
        scared = 0
        oldx = 0
        oldy = 0
        mwalk_sewage = 0 '\000'
#4  0x0000555555e555bf in dochugw (mtmp=0x61100000be40) at monmove.c:126
        x = 33
        y = 16
        already_saw_mon = 0 '\000'
        rd = 24848
#5  0x0000555555dc1a4d in movemon () at mon.c:1568
        mtmp = 0x61100000be40
        nmtmp = 0x61100000bd00
        somebody_can_move = 0 '\000'
#6  0x0000555555773229 in moveloop (resuming=0 '\000') at allmain.c:245
        pobj = 0x0
        moveamt = 12
        wtcap = 0
        change = 0
        monscanmove = 0 '\000'
        elf_regen = 1 '\001'
        orc_regen = 1 '\001'
        vamp_regen = 1 '\001'
#7  0x00005555563f7fae in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
        fd = -1
        dir = 0x0
        exact_username = 0 '\000'
        resuming = 0 '\000'
        plsel_once = 1 '\001'

```

**Comment by elunna** [comment]
Fixed in 7f59c6c4
