### ISSUE TITLE
Too many spells memorized! (Necromancer)

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#173]
```
Suddenly, the dungeon collapses.
Too many spells memorized!
Generating more information you may report:

#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140239348287424)
    at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140239348287424)
    at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140239348287424, signo=signo@entry=6)
    at ./nptl/pthread_kill.c:89
#3  0x00007f8c0441a476 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/posix/raise.c:26
#4  0x00007f8c044007f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x000055adde08d5b8 in NH_abort () at end.c:236
#6  0x000055adde0944b1 in panic (str=0x55addeba6780 "%s") at end.c:802
#7  0x000055adde5f96db in impossible (
    s=0x55addebf9fe0 "Too many spells memorized!") at pline.c:582
#8  0x000055adde7cc0a1 in learn () at spell.c:402
#9  0x000055adddda5bda in moveloop (resuming=0 '\000') at allmain.c:816
#10 0x000055addea2fa68 in main (argc=0, argv=0x7ffd2fd04688)

```

**Comment by elunna** [comment]
list of spells the necro had at time of bug

```
{{sp_id = 531, sp_lev = 3 '\003', sp_know = 0},
{sp_id = 516, sp_lev = 4 '\004', sp_know = 0},
{sp_id = 508, sp_lev = 4 '\004', sp_know = 0},
{sp_id = 515, sp_lev = 5 '\005', sp_know = 0},
{sp_id = 535, sp_lev = 4 '\004', sp_know = 0},
{sp_id = 520, sp_lev = 5 '\005', sp_know = 0},
{sp_id = 517, sp_lev = 2 '\002', sp_know = 0},
{sp_id = 544, sp_lev = 4 '\004', sp_know = 0},
{sp_id = 518, sp_lev = 1 '\001', sp_know = 0},
{sp_id = 540, sp_lev = 1 '\001', sp_know = 0},
{sp_id = 516, sp_lev = 4 '\004', sp_know = 0},
{sp_id = 550, sp_lev = 2 '\002', sp_know = 0},
{sp_id = 506, sp_lev = 1 '\001', sp_know = 0},
{sp_id = 517, sp_lev = 2 '\002', sp_know = 0},
{sp_id = 527, sp_lev = 1 '\001', sp_know = 0},
{sp_id = 513, sp_lev = 1 '\001', sp_know = 0},
{sp_id = 542, sp_lev = 1 '\001', sp_know = 0}, {
sp_id = 549, sp_lev = 1 '\001', sp_know = 0},
{sp_id = 521, sp_lev = 1 '\001', sp_know = 0},
{sp_id = 554, sp_lev = 3 '\003', sp_know = 0},
{sp_id = 517, sp_lev = 2 '\002', sp_know = 0},
{sp_id = 526, sp_lev = 1 '\001', sp_know = 12013}, {
sp_id = 519, sp_lev = 3 '\003', sp_know = 0},
{sp_id = 517, sp_lev = 2 '\002', sp_know = 0},
{sp_id = 502, sp_lev = 3 '\003', sp_know = 0},
{sp_id = 541, sp_lev = 2 '\002', sp_know = 0},
{sp_id = 562, sp_lev = 1 '\001', sp_know = 0},
{sp_id = 516, sp_lev = 4 '\004', sp_know = 0},
{sp_id = 516, sp_lev = 4 '\004', sp_know = 0},
{sp_id = 503, sp_lev = 2 '\002', sp_know = 0},
{sp_id = 517, sp_lev = 2 '\002', sp_know = 0},
{sp_id = 534, sp_lev = 3 '\003', sp_know = 0},
{sp_id = 547, sp_lev = 3 '\003', sp_know = 0},
{sp_id = 533, sp_lev = 1 '\001', sp_know = 0},
{sp_id = 524, sp_lev = 3 '\003', sp_know = 0},
{sp_id = 517, sp_lev = 2 '\002', sp_know = 0},
{sp_id = 517, sp_lev = 2 '\002', sp_know = 0},
{sp_id = 518, sp_lev = 1 '\001', sp_know = 0},
{sp_id = 517, sp_lev = 2 '\002', sp_know = 0},
{sp_id = 519, sp_lev = 3 '\003', sp_know = 0},
{sp_id = 516, sp_lev = 4 '\004', sp_know = 0},
{sp_id = 519, sp_lev = 3 '\003', sp_know = 0},
{sp_id = 530, sp_lev = 1 '\001', sp_know = 530},
{sp_id = 518, sp_ lev = 1 '\001', sp_know = 0},
{sp_id = 518, sp_lev = 1 '\001', sp_know = 0},
{sp_id = 511, sp_lev = 4 '\004', sp_know = 0},
{sp_id = 546, sp_lev = 4 '\004', sp_know = 0},
{sp_id = 517, sp_lev = 2 '\002', sp_know = 0},
{sp_id = 519, sp_lev = 3 '\003', sp_know = 0},
{sp_id = 532, sp_lev = 4 '\004', sp_know = 0},
{sp_id = 543, sp_lev = 2 '\002', sp_know = 0},
{sp_id = 552, sp_lev = 2 '\002', sp_know = 0},
{sp_id = 538, sp_lev = 2 '\002', sp_know = 0},
{sp_id = 553, sp_lev = 3 '\003', sp_know = 0},
{sp_id = 556, sp_lev = 3 '\003', sp_know = 0},
{sp_id = 520, sp_lev = 5 '\005', sp_know = 0},
{sp_id = 520, sp_lev = 5 '\005', sp_know = 0},
{sp_id = 516, sp_lev = 4 '\004', sp_know = 0},
{sp_id = 539, sp_lev = 2 '\002', sp_know = 0},
{sp_id = 545, sp_lev = 3 '\003', sp_know = 0},
{sp_id = 522, sp_lev = 2 '\002', sp_know = 0},
{sp_id = 555, sp_lev = 2 '\002', sp_know = 0},
{sp_id = 514, sp_lev = 2 '\002', sp_know = 0},
{sp_id = 518, sp_lev = 1 '\001', sp_know = 0},
{sp_id = 518, sp_lev = 1 '\001', sp_know = 0}, 
{sp_id = 0, sp_lev = 0 '\000', sp_know = 0}}

```
