### ISSUE TITLE
Memory leaks in oracle level

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#175]
```
=================================================================
==21137==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 96 byte(s) in 6 object(s) allocated from:
    #0 0x7feff7046808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x5603424aa806 in alloc /home/lunatunez/hackem/src/alloc.c:46
    #2 0x560342e90276 in opvar_clone /home/lunatunez/hackem/src/sp_lev.c:455
    #3 0x560342ebe8ad in sp_level_coder /home/lunatunez/hackem/src/sp_lev.c:5653
    #4 0x560342ec393d in load_special /home/lunatunez/hackem/src/sp_lev.c:6340
    #5 0x560342a97c64 in makemaz /home/lunatunez/hackem/src/mkmaze.c:1027
    #6 0x560342a80c3d in makelevel /home/lunatunez/hackem/src/mklev.c:925
    #7 0x560342a842d7 in mklev /home/lunatunez/hackem/src/mklev.c:1380
    #8 0x56034265adcc in goto_level /home/lunatunez/hackem/src/do.c:1963
    #9 0x56034274452a in next_level /home/lunatunez/hackem/src/dungeon.c:1179
    #10 0x5603426582df in dodown /home/lunatunez/hackem/src/do.c:1545
    #11 0x5603425af803 in rhack /home/lunatunez/hackem/src/cmd.c:5674
    #12 0x5603424a70d9 in moveloop /home/lunatunez/hackem/src/allmain.c:868
    #13 0x56034312912d in main ../sys/unix/unixmain.c:353
    #14 0x7feff6d12082 in __libc_start_main ../csu/libc-start.c:308

Indirect leak of 54 byte(s) in 6 object(s) allocated from:
    #0 0x7feff7046808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x5603424aa806 in alloc /home/lunatunez/hackem/src/alloc.c:46
    #2 0x5603424aa8c5 in dupstr /home/lunatunez/hackem/src/alloc.c:162
    #3 0x560342e903bf in opvar_clone /home/lunatunez/hackem/src/sp_lev.c:469
    #4 0x560342ebe8ad in sp_level_coder /home/lunatunez/hackem/src/sp_lev.c:5653
    #5 0x560342ec393d in load_special /home/lunatunez/hackem/src/sp_lev.c:6340
    #6 0x560342a97c64 in makemaz /home/lunatunez/hackem/src/mkmaze.c:1027
    #7 0x560342a80c3d in makelevel /home/lunatunez/hackem/src/mklev.c:925
    #8 0x560342a842d7 in mklev /home/lunatunez/hackem/src/mklev.c:1380
    #9 0x56034265adcc in goto_level /home/lunatunez/hackem/src/do.c:1963
    #10 0x56034274452a in next_level /home/lunatunez/hackem/src/dungeon.c:1179
    #11 0x5603426582df in dodown /home/lunatunez/hackem/src/do.c:1545
    #12 0x5603425af803 in rhack /home/lunatunez/hackem/src/cmd.c:5674
    #13 0x5603424a70d9 in moveloop /home/lunatunez/hackem/src/allmain.c:868
    #14 0x56034312912d in main ../sys/unix/unixmain.c:353
    #15 0x7feff6d12082 in __libc_start_main ../csu/libc-start.c:308

SUMMARY: AddressSanitizer: 150 byte(s) leaked in 12 allocation(s).
```

**Comment by elunna** [comment]
Caused by this: 
```
  $numbers = { 1, 2, 3,4 }
  
  SHUFFLE: $numbers
  $orthopool = { (5,1), (2,4), (8,4), (5,7) }
  $fountain = { (5,2), (3,4), (7,4), (5,6) }
  POOL: $orthopool[$numbers[0]]
  POOL: $orthopool[$numbers[1]]
  POOL: $orthopool[$numbers[2]]
  FOUNTAIN: $fountain[$numbers[0]]
  FOUNTAIN: $fountain[$numbers[1]]
  FOUNTAIN: $fountain[$numbers[2]]
```
