### ISSUE TITLE
Fuzzer: Attempting to revive tin of scorpion meat?

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#182]
```
Suddenly, the dungeon collapses.
Attempting to revive tin of scorpion meat?
Generating more information you may report:

#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7363859 in __GI_abort () at abort.c:79
#2  0x0000555555a66958 in NH_abort () at end.c:236
#3  0x0000555555a6d7e7 in panic (str=0x55555657b960 "%s") at end.c:802
#4  0x0000555555fcd9f8 in impossible (s=0x55555660b8c0 "Attempting to revive %s?") at pline.c:654
#5  0x000055555639ce4f in revive (corpse=0x60c000330880, by_hero=1 '\001') at zap.c:1018
#6  0x000055555609ead8 in seffects (sobj=0x60c000331480) at read.c:2290
#7  0x00005555561a63a1 in spelleffects (spell=22, atme=0 '\000', wiz_cast=0 '\000') at spell.c:1388
#8  0x00005555561a17bb in docast () at spell.c:798
#9  0x0000555555886d31 in rhack (cmd=0x55555681ac80 <in_line> "Y") at cmd.c:5674
#10 0x000055555577e0da in moveloop (resuming=0 '\000') at allmain.c:868
#11 0x000055555640182d in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353

Full: 

#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {0, 0, 0, 0, 0, 140737335783280, 93824997549610, 335544320, 140737341046928, 
            1073741824, 0, 140737342793376, 4294967295, 140737337360384, 140737342776480, 
            15971354522019425536}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007ffff7363859 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0xffffffff, sa_sigaction = 0xffffffff}, sa_mask = {
            __val = {140737337360384, 140737342776480, 15971354522019425536, 140737488341840, 
              140737342793376, 18446744073709547520, 140737327104000, 140737345462488, 
              140737488342912, 140737488342912, 140737344331794, 17592186042730, 140737488334848, 
              140737341046928, 15971354522019425536, 140737488342240}}, sa_flags = 1657531648, 
          sa_restorer = 0x7fffffffcea0}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x0000555555a66958 in NH_abort () at end.c:236
        gdb_prio = 1
        libc_prio = 2
        aborting = 1 '\001'
#3  0x0000555555a6d7e7 in panic (str=0x55555657b960 "%s") at end.c:802
        the_args = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7fffffffcf70, 
            reg_save_area = 0x7fffffffcea0}}
#4  0x0000555555fcd9f8 in impossible (s=0x55555660b8c0 "Attempting to revive %s?") at pline.c:654
        pbuf = "Attempting to revive tin of scorpion meat?\000\000\000\000\000\000\340\200c\366\377\177\000\000\320փVUU\000\000\000\257YVUU\000\000\000\355\313bQ\246\245\335`\320\377\377\377\177\000\000\200\b3\000\300`\000\000\240\326\377\377\377\177\000\000\231\001\000\000\000\000\000\000\000\257YVUU\000\000\000\001NVUU\000\000\320\326\377\377\377\177\000\000\000\355\313bQ\246\245\335\034\372\377\377\377\017\000\000\340\320\377\377\377\177\000\000\034\372\377\377\377\017\000\000`\322\377\377\377\177\000\000\340\320\377\377\377\177\000\000\000\326\377\377\377\177\000\000\200\322\377\377\377\177\000\000;"...
        the_args = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7fffffffd660, 
            reg_save_area = 0x7fffffffd580}}
#5  0x000055555639ce4f in revive (corpse=0x60c000330880, by_hero=1 '\001') at zap.c:1018
        mtmp = 0x0
        mptr = 0xdda5a65162cbed00
        container = 0x7fffffffd6b0
        xy = {x = 84 'T', y = 2 '\002'}
        x = 16 '\020'
        y = 16 '\020'
        one_of = 86 'V'
        montype = -72515583
        container_nesting = 0
        is_zomb = 0 '\000'
#6  0x000055555609ead8 in seffects (sobj=0x60c000331480) at read.c:2290
        obj = 0x60c000330880
        cost = 95
        cval = 0
        otyp = 522
        confused = 0 '\000'
        sblessed = 0 '\000'
        scursed = 0 '\000'
        already_known = 1 '\001'
        old_erodeproof = 0 '\000'
        new_erodeproof = 0 '\000'
        otmp = 0x0
        mtmp = 0x7fffffffdb40
        mtmp2 = 0x7fffffffdaf0
        pseudo = 0x7fffffffdab0
#7  0x00005555561a63a1 in spelleffects (spell=22, atme=0 '\000', wiz_cast=0 '\000') at spell.c:1388
        energy = 15
        damage = 0
        chance = 100
        n = 0
        intell = 10
        otyp = 522
        skill = 34
        role_skill = 4
        res = 0
        confused = 0 '\000'
        physical_damage = 0 '\000'
        pseudo = 0x60c000331480
        otmp = 0x0
        cc = {x = 0 '\000', y = 0 '\000'}
#8  0x00005555561a17bb in docast () at spell.c:798
        spell_no = 22
#9  0x0000555555886d31 in rhack (cmd=0x55555681ac80 <in_line> "Y") at cmd.c:5674
        tlist = 0x5555566c9d00 <extcmdlist+384>
        res = 688
        func = 0x5555561a16e0 <docast>
        spkey = 0
        prefix_seen = 0 '\000'
        bad_command = 81 'Q'
        firsttime = 1 '\001'
#10 0x000055555577e0da in moveloop (resuming=0 '\000') at allmain.c:868
        pobj = 0x0
        moveamt = 12
        wtcap = 0
        change = 0
        monscanmove = 0 '\000'
        elf_regen = 1 '\001'
        orc_regen = 1 '\001'
        vamp_regen = 1 '\001'
#11 0x000055555640182d in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
        fd = -1
        dir = 0x0
        exact_username = 0 '\000'
        resuming = 0 '\000'
        plsel_once = 1 '\001'

```

**Comment by elunna** [comment]
The animate dead spell is using floorfood as the means to get which corpse to revive. It is also including tins in this query.
