### ISSUE TITLE
dopay: not to shopkeeper?

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#184]
```
Suddenly, the dungeon collapses.
dopay: not to shopkeeper?
Generating more information you may report:

#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140209469872064)
    at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140209469872064)
    at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140209469872064, signo=signo@entry=6)
    at ./nptl/pthread_kill.c:89
#3  0x00007f850f61a476 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/posix/raise.c:26
#4  0x00007f850f6007f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x000055761e846c95 in NH_abort () at end.c:236
#6  0x000055761e84db8e in panic (str=0x55761f364500 "%s") at end.c:802
#7  0x000055761edb2ea9 in impossible (
    s=0x55761f399a00 "dopay: not to shopkeeper?") at pline.c:656
#8  0x000055761eef030f in dopay () at shk.c:1617
#9  0x000055761e665451 in rhack (cmd=0x55761f603a60 <in_line> "p")
    at cmd.c:5674
#10 0x000055761e559141 in moveloop (resuming=0 '\000') at allmain.c:868
#11 0x000055761f1eb67a in main (argc=0, argv=0x7ffe0c13c508)
    at ../sys/unix/unixmain.c:353


```

**Comment by elunna** [comment]
Data appears to be corrupted when shk turns from peaceful to nonpeaceful

```
(rr) p *mtmp
$11 = {nmon = 0x0, data = 0x55761f454f40 <mons+65312>, m_id = 9761309, 
  mnum = 628, cham = -1, movement = 24, m_lev = 23 '\027', 
  malign = -15 '\361', mx = 46 '.', my = 6 '\006', mux = 52 '4', 
  muy = 3 '\003', mtrack = {{x = 45 '-', y = 5 '\005'}, {x = 44 ',', 
      y = 4 '\004'}, {x = 45 '-', y = 4 '\004'}, {x = 46 '.', y = 4 '\004'}}, 
  mhp = 134, mhpmax = 134, mappearance = 0, rider_id = 0, 
  m_ap_type = 0 '\000', mtame = 0 '\000', mintrinsics = 0, mextrinsics = 0, 
  mspec_used = 0, seen_resistance = 0, female = 1, minvis = 0, invis_blkd = 0, 
  perminvis = 0, mcan = 0, mburied = 0, mundetected = 0, mcansee = 1, 
  mspeed = 0, permspeed = 0, mrevived = 0, mcloned = 0, mavenge = 0, 
  mflee = 0, mfleetim = 0, msleeping = 0, mblinded = 0, mstun = 0, 
  mfrozen = 0, mcanmove = 1, mconf = 0, mreflect = 1, msick = 3, msickbyu = 1, 
  mdiseased = 1, mdiseabyu = 0, mpeaceful = 1, mtrapped = 0, mleashed = 1, 
  uexp = 1, mtraitor = 1, isshk = 1, isminion = 1, isgd = 0, ispriest = 1, 
  isqldr = 0, iscerberus = 1, isvecna = 1, isgrund = 1, iswiz = 1, 
  wormno = 30, mwither_from_u = 1, mstonebyu = 0, mstone = 5, mberserk = 1, 
  mwither = 190 '\276', vuln_fire = 190 '\276', vuln_cold = 190 '\276', 
  vuln_elec = 190 '\276', vuln_acid = 190 '\276', 
  mstrategy = 13744632839234567870, mtrapseen = -4702111234474983746, 
  mlstmv = -4702111234474983746, mspare1 = -4702111234474983746, 
  minvent = 0xbebebebebebebebe, mw = 0xbebebebebebebebe, 
  misc_worn_check = -4702111234474983746, weapon_check = -66 '\276', 
  meating = -1094795586, msummoned = -1094795586, msicktime = -1094795586, 
mdiseasetime = -1094795586, mreflecttime = -1094795586, 
  mprotection = 190 '\276', mprottime = 190 '\276', former_rank = {
    lev = -1094795586, mnum = -16706, female = -66 '\276'}, 
  mextra = 0xbebebebebebebebe}
```
