### ISSUE TITLE
LeakSanitizer: new_oname 

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#195]
```
Be seeing you...

=================================================================
==14418==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 56 byte(s) in 3 object(s) allocated from:
    #0 0x7f4a5bb3e808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x55765015194d in alloc /home/lunatunez/hackem/src/alloc.c:46
    #2 0x55765031c98f in new_oname /home/lunatunez/hackem/src/do_name.c:1035
    #3 0x557650325187 in oname /home/lunatunez/hackem/src/do_name.c:1325
    #4 0x55765077d91f in make_corpse /home/lunatunez/hackem/src/mon.c:929
    #5 0x5576507d584b in xkilled /home/lunatunez/hackem/src/mon.c:4454
    #6 0x5576507d082c in killed /home/lunatunez/hackem/src/mon.c:4297
    #7 0x557650c8a3b5 in hmon_hitmon /home/lunatunez/hackem/src/uhitm.c:2227
    #8 0x557650c67111 in hmon /home/lunatunez/hackem/src/uhitm.c:959
    #9 0x557650c63e49 in known_hitum /home/lunatunez/hackem/src/uhitm.c:641
    #10 0x557650c657eb in hitum /home/lunatunez/hackem/src/uhitm.c:835
    #11 0x557650c6086e in attack /home/lunatunez/hackem/src/uhitm.c:586
    #12 0x5576504c0608 in domove_core /home/lunatunez/hackem/src/hack.c:1739
    #13 0x5576504a9cc1 in domove /home/lunatunez/hackem/src/hack.c:1445
    #14 0x55765025a1bc in rhack /home/lunatunez/hackem/src/cmd.c:5713
    #15 0x55765014e0c0 in moveloop /home/lunatunez/hackem/src/allmain.c:870
    #16 0x557650e05cfb in main ../sys/unix/unixmain.c:353
    #17 0x7f4a5b80a082 in __libc_start_main ../csu/libc-start.c:308

Direct leak of 37 byte(s) in 2 object(s) allocated from:
    #0 0x7f4a5bb3e808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x55765015194d in alloc /home/lunatunez/hackem/src/alloc.c:46
    #2 0x55765031c98f in new_oname /home/lunatunez/hackem/src/do_name.c:1035
    #3 0x557650325187 in oname /home/lunatunez/hackem/src/do_name.c:1325
    #4 0x55765077d91f in make_corpse /home/lunatunez/hackem/src/mon.c:929
    #5 0x5576507ce37b in mondied /home/lunatunez/hackem/src/mon.c:4067
    #6 0x5576507cf3b4 in monkilled /home/lunatunez/hackem/src/mon.c:4211
    #7 0x557650664dac in mdamagem /home/lunatunez/hackem/src/mhitm.c:2700
    #8 0x5576505f31d9 in hitmm /home/lunatunez/hackem/src/mhitm.c:995
    #9 0x5576505e3349 in mattackm /home/lunatunez/hackem/src/mhitm.c:639
    #10 0x557650386dbe in dog_move /home/lunatunez/hackem/src/dogmove.c:1568
    #11 0x55765085082d in m_move /home/lunatunez/hackem/src/monmove.c:1253
    #12 0x55765084a0e7 in dochug /home/lunatunez/hackem/src/monmove.c:944
    #13 0x557650834d51 in dochugw /home/lunatunez/hackem/src/monmove.c:126
    #14 0x5576507a0a55 in movemon /home/lunatunez/hackem/src/mon.c:1568
    #15 0x5576501472ca in moveloop /home/lunatunez/hackem/src/allmain.c:247
    #16 0x557650e05cfb in main ../sys/unix/unixmain.c:353
    #17 0x7f4a5b80a082 in __libc_start_main ../csu/libc-start.c:308

Direct leak of 19 byte(s) in 1 object(s) allocated from:
    #0 0x7f4a5bb3e808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x55765015194d in alloc /home/lunatunez/hackem/src/alloc.c:46
    #2 0x55765031c98f in new_oname /home/lunatunez/hackem/src/do_name.c:1035
    #3 0x557650a9f0b4 in restobj /home/lunatunez/hackem/src/restore.c:228
    #4 0x557650a9f67a in restobjchn /home/lunatunez/hackem/src/restore.c:278
    #5 0x557650aa4339 in getlev /home/lunatunez/hackem/src/restore.c:1141
    #6 0x557650306440 in goto_level /home/lunatunez/hackem/src/do.c:1978
    #7 0x5576503f0e5c in prev_level /home/lunatunez/hackem/src/dungeon.c:1202
    #8 0x557650304238 in doup /home/lunatunez/hackem/src/do.c:1608
    #9 0x55765025a6cb in rhack /home/lunatunez/hackem/src/cmd.c:5751
    #10 0x55765014e0c0 in moveloop /home/lunatunez/hackem/src/allmain.c:870
    #11 0x557650e05cfb in main ../sys/unix/unixmain.c:353
    #12 0x7f4a5b80a082 in __libc_start_main ../csu/libc-start.c:308

Direct leak of 8 byte(s) in 1 object(s) allocated from:
    #0 0x7f4a5bb3e808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x55765015194d in alloc /home/lunatunez/hackem/src/alloc.c:46
    #2 0x55765031c98f in new_oname /home/lunatunez/hackem/src/do_name.c:1035
    #3 0x557650a9f0b4 in restobj /home/lunatunez/hackem/src/restore.c:228
    #4 0x557650a9f67a in restobjchn /home/lunatunez/hackem/src/restore.c:278
    #5 0x557650aa4339 in getlev /home/lunatunez/hackem/src/restore.c:1141
    #6 0x557650306440 in goto_level /home/lunatunez/hackem/src/do.c:1978
    #7 0x5576503f0a0a in next_level /home/lunatunez/hackem/src/dungeon.c:1179
    #8 0x5576503037e6 in dodown /home/lunatunez/hackem/src/do.c:1545
    #9 0x55765025a6cb in rhack /home/lunatunez/hackem/src/cmd.c:5751
    #10 0x55765014e0c0 in moveloop /home/lunatunez/hackem/src/allmain.c:870
    #11 0x557650e05cfb in main ../sys/unix/unixmain.c:353
    #12 0x7f4a5b80a082 in __libc_start_main ../csu/libc-start.c:308

SUMMARY: AddressSanitizer: 120 byte(s) leaked in 7 allocation(s).
```

**Comment by elunna** [comment]
From non-wizmode human pirate

**Comment by elunna** [comment]
Stale issue - Come back to later if it pops up.

**Comment by elunna** [comment]
This looks related and was from a recent fuzzing session:

```
Direct leak of 12 byte(s) in 2 object(s) allocated from:
    #0 0x7fdc828eb867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x564ccbfdb9a5 in alloc /home/erik/Documents/hackem/src/alloc.c:46
    #2 0x564ccc1ae9fe in new_oname /home/erik/Documents/hackem/src/do_name.c:1036
    #3 0x564ccc1b76d9 in oname /home/erik/Documents/hackem/src/do_name.c:1338
    #4 0x564ccc1b731d in do_oname /home/erik/Documents/hackem/src/do_name.c:1311
    #5 0x564ccc1b99e0 in docallcmd /home/erik/Documents/hackem/src/do_name.c:1493
    #6 0x564ccc0e8e68 in rhack /home/erik/Documents/hackem/src/cmd.c:5771
    #7 0x564ccbfd7fb0 in moveloop /home/erik/Documents/hackem/src/allmain.c:870
    #8 0x564ccccc9c2b in main ../sys/unix/unixmain.c:353
    #9 0x7fdc823a7d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
```

**Comment by elunna** [comment]
```
Direct leak of 20 byte(s) in 1 object(s) allocated from:
    #0 0x7fd7dc4c0867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x55fb1c6fd9a5 in alloc /home/erik/Documents/hackem/src/alloc.c:46
    #2 0x55fb1c8d0b1e in new_oname /home/erik/Documents/hackem/src/do_name.c:1036
    #3 0x55fb1c8d97f9 in oname /home/erik/Documents/hackem/src/do_name.c:1338
    #4 0x55fb1cd3d4ae in make_corpse /home/erik/Documents/hackem/src/mon.c:932
    #5 0x55fb1cd971ee in xkilled /home/erik/Documents/hackem/src/mon.c:4513
    #6 0x55fb1d27cb4e in damageum /home/erik/Documents/hackem/src/uhitm.c:3288
    #7 0x55fb1d293ec9 in hmonas /home/erik/Documents/hackem/src/uhitm.c:4319
    #8 0x55fb1d23b858 in hitum /home/erik/Documents/hackem/src/uhitm.c:979
    #9 0x55fb1d234cb6 in attack /home/erik/Documents/hackem/src/uhitm.c:608
    #10 0x55fb1ca79150 in domove_core /home/erik/Documents/hackem/src/hack.c:1740
    #11 0x55fb1ca61d23 in domove /home/erik/Documents/hackem/src/hack.c:1445
    #12 0x55fb1c6f9eda in moveloop /home/erik/Documents/hackem/src/allmain.c:861
    #13 0x55fb1d3ebf0c in main ../sys/unix/unixmain.c:353
    #14 0x7fd7dbe01d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

Direct leak of 18 byte(s) in 2 object(s) allocated from:
    #0 0x7fd7dc4c0867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x55fb1c6fd9a5 in alloc /home/erik/Documents/hackem/src/alloc.c:46
    #2 0x55fb1c8d0b1e in new_oname /home/erik/Documents/hackem/src/do_name.c:1036
    #3 0x55fb1c8d97f9 in oname /home/erik/Documents/hackem/src/do_name.c:1338
    #4 0x55fb1c8d943d in do_oname /home/erik/Documents/hackem/src/do_name.c:1311
    #5 0x55fb1c8dbb00 in docallcmd /home/erik/Documents/hackem/src/do_name.c:1493
    #6 0x55fb1c80af88 in rhack /home/erik/Documents/hackem/src/cmd.c:5771
    #7 0x55fb1c6f9fb0 in moveloop /home/erik/Documents/hackem/src/allmain.c:870
    #8 0x55fb1d3ebf0c in main ../sys/unix/unixmain.c:353
    #9 0x7fd7dbe01d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

```

**Comment by elunna** [comment]
More leaks from a recent fuzz:

```
Direct leak of 384 byte(s) in 3 object(s) allocated from:
    #0 0x7fc803907867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x559c9d971a9e in alloc /home/erik/Documents/hackem/src/alloc.c:46
    #2 0x559c9df8938f in mksobj /home/erik/Documents/hackem/src/mkobj.c:844
    #3 0x559c9df851f3 in mkobj /home/erik/Documents/hackem/src/mkobj.c:288
    #4 0x559c9e2d11f2 in punish /home/erik/Documents/hackem/src/read.c:3455
    #5 0x559c9e262fbe in angrygods /home/erik/Documents/hackem/src/pray.c:768
    #6 0x559c9e27be56 in prayer_done /home/erik/Documents/hackem/src/pray.c:2618
    #7 0x559c9dd0ede7 in unmul /home/erik/Documents/hackem/src/hack.c:3499
    #8 0x559c9d96a310 in moveloop /home/erik/Documents/hackem/src/allmain.c:647
    #9 0x559c9e66c9c3 in main ../sys/unix/unixmain.c:353
    #10 0x7fc8033cfd8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

Direct leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x7fc803907867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x559c9d971a9e in alloc /home/erik/Documents/hackem/src/alloc.c:46
    #2 0x559c9df8938f in mksobj /home/erik/Documents/hackem/src/mkobj.c:844
    #3 0x559c9df851f3 in mkobj /home/erik/Documents/hackem/src/mkobj.c:288
    #4 0x559c9e2d11f2 in punish /home/erik/Documents/hackem/src/read.c:3455
    #5 0x559c9e262fbe in angrygods /home/erik/Documents/hackem/src/pray.c:768
    #6 0x559c9e26e357 in gods_upset /home/erik/Documents/hackem/src/pray.c:1642
    #7 0x559c9e27bc9e in prayer_done /home/erik/Documents/hackem/src/pray.c:2614
    #8 0x559c9dd0ede7 in unmul /home/erik/Documents/hackem/src/hack.c:3499
    #9 0x559c9d96a310 in moveloop /home/erik/Documents/hackem/src/allmain.c:647
    #10 0x559c9e66c9c3 in main ../sys/unix/unixmain.c:353
    #11 0x7fc8033cfd8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

Direct leak of 41 byte(s) in 2 object(s) allocated from:
    #0 0x7fc803907867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x559c9d971a9e in alloc /home/erik/Documents/hackem/src/alloc.c:46
    #2 0x559c9db43267 in new_oname /home/erik/Documents/hackem/src/do_name.c:1036
    #3 0x559c9db4bf42 in oname /home/erik/Documents/hackem/src/do_name.c:1338
    #4 0x559c9dfb59a1 in make_corpse /home/erik/Documents/hackem/src/mon.c:933
    #5 0x559c9e008115 in mondied /home/erik/Documents/hackem/src/mon.c:4136
    #6 0x559c9e0bae7f in ohitmon /home/erik/Documents/hackem/src/mthrowu.c:682
    #7 0x559c9e0bedb0 in m_throw /home/erik/Documents/hackem/src/mthrowu.c:836
    #8 0x559c9e0b3d16 in monshoot /home/erik/Documents/hackem/src/mthrowu.c:406
    #9 0x559c9e0cad4e in thrwmu /home/erik/Documents/hackem/src/mthrowu.c:1353
    #10 0x559c9dede705 in mattacku /home/erik/Documents/hackem/src/mhitu.c:1155
    #11 0x559c9e085cb5 in dochug /home/erik/Documents/hackem/src/monmove.c:892
    #12 0x559c9e0714aa in dochugw /home/erik/Documents/hackem/src/monmove.c:163
    #13 0x559c9dfd9156 in movemon /home/erik/Documents/hackem/src/mon.c:1573
    #14 0x559c9d96722b in moveloop /home/erik/Documents/hackem/src/allmain.c:247
    #15 0x559c9e66c9c3 in main ../sys/unix/unixmain.c:353
    #16 0x7fc8033cfd8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

Direct leak of 36 byte(s) in 2 object(s) allocated from:
    #0 0x7fc803907867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x559c9d971a9e in alloc /home/erik/Documents/hackem/src/alloc.c:46
    #2 0x559c9db43267 in new_oname /home/erik/Documents/hackem/src/do_name.c:1036
    #3 0x559c9db4bf42 in oname /home/erik/Documents/hackem/src/do_name.c:1338
    #4 0x559c9dfb59a1 in make_corpse /home/erik/Documents/hackem/src/mon.c:933
    #5 0x559c9e00f84f in xkilled /home/erik/Documents/hackem/src/mon.c:4523
    #6 0x559c9e4fabd4 in damageum /home/erik/Documents/hackem/src/uhitm.c:3297
    #7 0x559c9e51295d in hmonas /home/erik/Documents/hackem/src/uhitm.c:4356
    #8 0x559c9e4b9998 in hitum /home/erik/Documents/hackem/src/uhitm.c:982
    #9 0x559c9e4b2df6 in attack /home/erik/Documents/hackem/src/uhitm.c:611
    #10 0x559c9dcee654 in domove_core /home/erik/Documents/hackem/src/hack.c:1740
    #11 0x559c9dcd7227 in domove /home/erik/Documents/hackem/src/hack.c:1445
    #12 0x559c9da7cfcd in rhack /home/erik/Documents/hackem/src/cmd.c:5733
    #13 0x559c9d96e044 in moveloop /home/erik/Documents/hackem/src/allmain.c:871
    #14 0x559c9e66c9c3 in main ../sys/unix/unixmain.c:353
    #15 0x7fc8033cfd8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

Direct leak of 34 byte(s) in 2 object(s) allocated from:
    #0 0x7fc803907867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x559c9d971a9e in alloc /home/erik/Documents/hackem/src/alloc.c:46
    #2 0x559c9db43267 in new_oname /home/erik/Documents/hackem/src/do_name.c:1036
    #3 0x559c9e2e8380 in restobj /home/erik/Documents/hackem/src/restore.c:228
    #4 0x559c9e2e8946 in restobjchn /home/erik/Documents/hackem/src/restore.c:278
    #5 0x559c9e2ed6ac in getlev /home/erik/Documents/hackem/src/restore.c:1143
    #6 0x559c9db2c98c in goto_level /home/erik/Documents/hackem/src/do.c:1964
    #7 0x559c9db3024d in deferred_goto /home/erik/Documents/hackem/src/do.c:2319
    #8 0x559c9d96e086 in moveloop /home/erik/Documents/hackem/src/allmain.c:874
    #9 0x559c9e66c9c3 in main ../sys/unix/unixmain.c:353
    #10 0x7fc8033cfd8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

Direct leak of 27 byte(s) in 1 object(s) allocated from:
    #0 0x7fc803907867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x559c9d971a9e in alloc /home/erik/Documents/hackem/src/alloc.c:46
    #2 0x559c9db43267 in new_oname /home/erik/Documents/hackem/src/do_name.c:1036
    #3 0x559c9db4bf42 in oname /home/erik/Documents/hackem/src/do_name.c:1338
    #4 0x559c9dfb59a1 in make_corpse /home/erik/Documents/hackem/src/mon.c:933
    #5 0x559c9e008115 in mondied /home/erik/Documents/hackem/src/mon.c:4136
    #6 0x559c9e00915a in monkilled /home/erik/Documents/hackem/src/mon.c:4280
    #7 0x559c9dc9cc2c in explode /home/erik/Documents/hackem/src/explode.c:555
    #8 0x559c9ddb40d2 in cast_wizard_spell /home/erik/Documents/hackem/src/mcastu.c:887
    #9 0x559c9dda634e in castmu /home/erik/Documents/hackem/src/mcastu.c:507
    #10 0x559c9e086a12 in dochug /home/erik/Documents/hackem/src/monmove.c:961
    #11 0x559c9e0714aa in dochugw /home/erik/Documents/hackem/src/monmove.c:163
    #12 0x559c9dfd9156 in movemon /home/erik/Documents/hackem/src/mon.c:1573
    #13 0x559c9d96722b in moveloop /home/erik/Documents/hackem/src/allmain.c:247
    #14 0x559c9e66c9c3 in main ../sys/unix/unixmain.c:353
    #15 0x7fc8033cfd8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

Direct leak of 26 byte(s) in 1 object(s) allocated from:
    #0 0x7fc803907867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x559c9d971a9e in alloc /home/erik/Documents/hackem/src/alloc.c:46
    #2 0x559c9db43267 in new_oname /home/erik/Documents/hackem/src/do_name.c:1036
    #3 0x559c9db4bf42 in oname /home/erik/Documents/hackem/src/do_name.c:1338
    #4 0x559c9dfb59a1 in make_corpse /home/erik/Documents/hackem/src/mon.c:933
    #5 0x559c9e008115 in mondied /home/erik/Documents/hackem/src/mon.c:4136
    #6 0x559c9e00915a in monkilled /home/erik/Documents/hackem/src/mon.c:4280
    #7 0x559c9e620392 in dobuzz /home/erik/Documents/hackem/src/zap.c:5565
    #8 0x559c9e619d2b in buzz /home/erik/Documents/hackem/src/zap.c:5408
    #9 0x559c9e105595 in use_offensive /home/erik/Documents/hackem/src/muse.c:2643
    #10 0x559c9dedce07 in mattacku /home/erik/Documents/hackem/src/mhitu.c:958
    #11 0x559c9e085cb5 in dochug /home/erik/Documents/hackem/src/monmove.c:892
    #12 0x559c9e0714aa in dochugw /home/erik/Documents/hackem/src/monmove.c:163
    #13 0x559c9dfd9156 in movemon /home/erik/Documents/hackem/src/mon.c:1573
    #14 0x559c9d96722b in moveloop /home/erik/Documents/hackem/src/allmain.c:247
    #15 0x559c9e66c9c3 in main ../sys/unix/unixmain.c:353
    #16 0x7fc8033cfd8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

Direct leak of 23 byte(s) in 1 object(s) allocated from:
    #0 0x7fc803907867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x559c9d971a9e in alloc /home/erik/Documents/hackem/src/alloc.c:46
    #2 0x559c9db43267 in new_oname /home/erik/Documents/hackem/src/do_name.c:1036
    #3 0x559c9db4bf42 in oname /home/erik/Documents/hackem/src/do_name.c:1338
    #4 0x559c9dfb59a1 in make_corpse /home/erik/Documents/hackem/src/mon.c:933
    #5 0x559c9e008115 in mondied /home/erik/Documents/hackem/src/mon.c:4136
    #6 0x559c9e00915a in monkilled /home/erik/Documents/hackem/src/mon.c:4280
    #7 0x559c9e620392 in dobuzz /home/erik/Documents/hackem/src/zap.c:5565
    #8 0x559c9e619d2b in buzz /home/erik/Documents/hackem/src/zap.c:5408
    #9 0x559c9e4581cf in mintrap /home/erik/Documents/hackem/src/trap.c:3254
    #10 0x559c9e095262 in m_move /home/erik/Documents/hackem/src/monmove.c:1855
    #11 0x559c9e086aa2 in dochug /home/erik/Documents/hackem/src/monmove.c:970
    #12 0x559c9e0714aa in dochugw /home/erik/Documents/hackem/src/monmove.c:163
    #13 0x559c9dfd9156 in movemon /home/erik/Documents/hackem/src/mon.c:1573
    #14 0x559c9d96722b in moveloop /home/erik/Documents/hackem/src/allmain.c:247
    #15 0x559c9e66c9c3 in main ../sys/unix/unixmain.c:353
    #16 0x7fc8033cfd8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

Direct leak of 21 byte(s) in 1 object(s) allocated from:
    #0 0x7fc803907867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x559c9d971a9e in alloc /home/erik/Documents/hackem/src/alloc.c:46
    #2 0x559c9db43267 in new_oname /home/erik/Documents/hackem/src/do_name.c:1036
    #3 0x559c9db4bf42 in oname /home/erik/Documents/hackem/src/do_name.c:1338
    #4 0x559c9dfb59a1 in make_corpse /home/erik/Documents/hackem/src/mon.c:933
    #5 0x559c9e00f84f in xkilled /home/erik/Documents/hackem/src/mon.c:4523
    #6 0x559c9e00a6a1 in killed /home/erik/Documents/hackem/src/mon.c:4366
    #7 0x559c9e4e18d8 in hmon_hitmon /home/erik/Documents/hackem/src/uhitm.c:2336
    #8 0x559c9e4b9c82 in hmon /home/erik/Documents/hackem/src/uhitm.c:1005
    #9 0x559c9e4b654d in known_hitum /home/erik/Documents/hackem/src/uhitm.c:666
    #10 0x559c9e4b801d in hitum /home/erik/Documents/hackem/src/uhitm.c:863
    #11 0x559c9e4b2df6 in attack /home/erik/Documents/hackem/src/uhitm.c:611
    #12 0x559c9dcee654 in domove_core /home/erik/Documents/hackem/src/hack.c:1740
    #13 0x559c9dcd7227 in domove /home/erik/Documents/hackem/src/hack.c:1445
    #14 0x559c9da7cfcd in rhack /home/erik/Documents/hackem/src/cmd.c:5733
    #15 0x559c9d96e044 in moveloop /home/erik/Documents/hackem/src/allmain.c:871
    #16 0x559c9e66c9c3 in main ../sys/unix/unixmain.c:353
    #17 0x7fc8033cfd8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

Direct leak of 19 byte(s) in 1 object(s) allocated from:
    #0 0x7fc803907867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x559c9d971a9e in alloc /home/erik/Documents/hackem/src/alloc.c:46
    #2 0x559c9db43267 in new_oname /home/erik/Documents/hackem/src/do_name.c:1036
    #3 0x559c9db4bf42 in oname /home/erik/Documents/hackem/src/do_name.c:1338
    #4 0x559c9dfb59a1 in make_corpse /home/erik/Documents/hackem/src/mon.c:933
    #5 0x559c9e008115 in mondied /home/erik/Documents/hackem/src/mon.c:4136
    #6 0x559c9e00915a in monkilled /home/erik/Documents/hackem/src/mon.c:4280
    #7 0x559c9dc9cc2c in explode /home/erik/Documents/hackem/src/explode.c:555
    #8 0x559c9ddb40d2 in cast_wizard_spell /home/erik/Documents/hackem/src/mcastu.c:887
    #9 0x559c9dda634e in castmu /home/erik/Documents/hackem/src/mcastu.c:507
    #10 0x559c9dedee5c in mattacku /home/erik/Documents/hackem/src/mhitu.c:1205
    #11 0x559c9e087619 in dochug /home/erik/Documents/hackem/src/monmove.c:1020
    #12 0x559c9e0714aa in dochugw /home/erik/Documents/hackem/src/monmove.c:163
    #13 0x559c9dfd9156 in movemon /home/erik/Documents/hackem/src/mon.c:1573
    #14 0x559c9d96722b in moveloop /home/erik/Documents/hackem/src/allmain.c:247
    #15 0x559c9e66c9c3 in main ../sys/unix/unixmain.c:353
    #16 0x7fc8033cfd8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

Direct leak of 18 byte(s) in 1 object(s) allocated from:
    #0 0x7fc803907867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x559c9d971a9e in alloc /home/erik/Documents/hackem/src/alloc.c:46
    #2 0x559c9db43267 in new_oname /home/erik/Documents/hackem/src/do_name.c:1036
    #3 0x559c9db4bf42 in oname /home/erik/Documents/hackem/src/do_name.c:1338
    #4 0x559c9dfb59a1 in make_corpse /home/erik/Documents/hackem/src/mon.c:933
    #5 0x559c9e008115 in mondied /home/erik/Documents/hackem/src/mon.c:4136
    #6 0x559c9e00915a in monkilled /home/erik/Documents/hackem/src/mon.c:4280
    #7 0x559c9e620392 in dobuzz /home/erik/Documents/hackem/src/zap.c:5565
    #8 0x559c9e619d2b in buzz /home/erik/Documents/hackem/src/zap.c:5408
    #9 0x559c9e105595 in use_offensive /home/erik/Documents/hackem/src/muse.c:2643
    #10 0x559c9dedce07 in mattacku /home/erik/Documents/hackem/src/mhitu.c:958
    #11 0x559c9e087619 in dochug /home/erik/Documents/hackem/src/monmove.c:1020
    #12 0x559c9e0714aa in dochugw /home/erik/Documents/hackem/src/monmove.c:163
    #13 0x559c9dfd9156 in movemon /home/erik/Documents/hackem/src/mon.c:1573
    #14 0x559c9d96722b in moveloop /home/erik/Documents/hackem/src/allmain.c:247
    #15 0x559c9e66c9c3 in main ../sys/unix/unixmain.c:353
    #16 0x7fc8033cfd8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

Direct leak of 16 byte(s) in 3 object(s) allocated from:
    #0 0x7fc803907867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x559c9d971a9e in alloc /home/erik/Documents/hackem/src/alloc.c:46
    #2 0x559c9db43267 in new_oname /home/erik/Documents/hackem/src/do_name.c:1036
    #3 0x559c9db4bf42 in oname /home/erik/Documents/hackem/src/do_name.c:1338
    #4 0x559c9db4bb86 in do_oname /home/erik/Documents/hackem/src/do_name.c:1311
    #5 0x559c9db4e249 in docallcmd /home/erik/Documents/hackem/src/do_name.c:1493
    #6 0x559c9da7d4d9 in rhack /home/erik/Documents/hackem/src/cmd.c:5771
    #7 0x559c9d96e044 in moveloop /home/erik/Documents/hackem/src/allmain.c:871
    #8 0x559c9e66c9c3 in main ../sys/unix/unixmain.c:353
    #9 0x7fc8033cfd8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

SUMMARY: AddressSanitizer: 773 byte(s) leaked in 19 allocation(s).
```

**Comment by elunna** [comment]
Attempts to reproduce:
Created a valkyrie mplayer (named), killed it
Created a warg, named it x, killed it.
Created a tame dog, named it " ", killed it.
Wished for a dog named spike, killed it. (It didn't seem to work to name it that way)
Sacrified for a neutral minion (gray unicorn), killed it.
