### ISSUE TITLE
Unknown type of gloves (208)

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#211]
```
Program received signal SIGKILL, Killed.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140284403611584) at ./nptl/pthread_kill.c:44
44	in ./nptl/pthread_kill.c
(rr) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140284403611584) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140284403611584) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140284403611584, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007f96821e8476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007f96821ce7f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x0000556f1b91dedc in NH_abort () at end.c:236
#6  0x0000556f1b924f3a in panic (str=0x556f1c491ca0 "%s") at end.c:802
#7  0x0000556f1be9c107 in impossible (s=0x556f1c52d300 "Unknown type of gloves (%d)") at pline.c:689
#8  0x0000556f1c2e487f in ma_break () at tech.c:883
#9  0x0000556f1b626bca in moveloop (resuming=0 '\000') at allmain.c:820
#10 0x0000556f1c316938 in main (argc=0, argv=0x7ffdd3f81ca8) at ../sys/unix/unixmain.c:353
```

208 is gauntlets of swimming

**Comment by elunna** [comment]
Cause: boulder break ability with the monk, has handling for all glove types
