### ISSUE TITLE
timer sanity: melt timer 5576 on non-ice 21 <73,8>

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#220]
```
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140123440490432) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140123440490432) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140123440490432, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007f7107a1a476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007f7107a007f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x000055eac795be94 in NH_abort () at end.c:236
#6  0x000055eac7962ef2 in panic (str=0x55eac84cfd00 "%s") at end.c:802
#7  0x000055eac7eda28e in impossible (s=0x55eac8532440 "timer sanity: melt timer %ld on non-ice %d <%d,%d>")
    at pline.c:689
#8  0x000055eac810865f in timer_sanity_check () at timeout.c:2489
#9  0x000055eac7771ac1 in sanity_check () at cmd.c:5071
#10 0x000055eac7664c9d in moveloop (resuming=0 '\000') at allmain.c:839
#11 0x000055eac8354ab5 in main (argc=0, argv=0x7ffc3e374068) at ../sys/unix/unixmain.c:353
```

**Comment by elunna** [comment]
moves: 307825
Tile 21 is a lavapool

move 307824: Goes from 36 (ice) to 21
This is an interesting surprise, a monster that was imported from splicehack, the magma elemental, actually dissolves into a pile of magma creating a lava pool on the square it died on. So when a magma elemental dies on an ice square with a timer, it is not handling the previous ice melting timer correctly
