### ISSUE TITLE
"double buffering unexpected"

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#229]
Reported by mobileuser.

```
Core was generated by `/hackem-1.1.0/hackem -u mobileuser'.
Program terminated with signal SIGABRT, Aborted.
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140377004642304) at ./nptl/pthread_kill.c:44
44      ./nptl/pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140377004642304) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140377004642304) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140377004642304, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007fac11834476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007fac1181a7f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00005595303f4372 in NH_abort () at end.c:236
#6  0x00005595303f69b3 in panic (str=0x5595307f3cb5 "double buffering unexpected") at end.c:736
#7  0x0000559530653a99 in def_bufon (fd=5) at save.c:743
#8  0x00005595306539d9 in bufon (fd=5) at save.c:692
#9  0x000055953079eba5 in store_version (fd=5) at version.c:331
#10 0x0000559530652b1a in dosave0 () at save.c:229
#11 0x00005595303f6b05 in panic (str=0x559530800296 "obj_is_local") at end.c:779
#12 0x00005595306b8dfd in obj_is_local (obj=0x55953161a580) at timeout.c:2865
#13 0x00005595306b8ec8 in timer_is_local (timer=0x5595316137d0) at timeout.c:2903
#14 0x00005595306b8f5c in maybe_write_timer (fd=4, range=0, write_it=0 '\000') at timeout.c:2936
#15 0x00005595306b8ffc in save_timers (fd=4, mode=6, range=0) at timeout.c:2971
#16 0x00005595306537e0 in savelev (fd=4, lev=81 'Q', mode=6) at save.c:601
#17 0x0000559530652c2d in dosave0 () at save.c:244
#18 0x0000559530652848 in dosave () at save.c:96
#19 0x000055953034f3da in rhack (cmd=0x559530884bc0 <in_line> "S") at cmd.c:5756
#20 0x00005595302e9489 in moveloop (resuming=1 '\001') at allmain.c:870
#21 0x000055953077ebf7 in main (argc=3, argv=0x7ffc7ec428e8) at ../sys/unix/unixmain.c:353
```

**Comment by elunna** [comment]
Throwing a bomb downwards makes it disappear, saving afterwards causes this crash.
