### ISSUE TITLE
Memory leak in shk_other_services 

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#27]
```
=================================================================
==8123==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7f378c59e808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x560ef5cabf69 in alloc /home/lunatunez/hackem/src/alloc.c:46
    #2 0x560ef6924a10 in tty_select_menu ../win/tty/wintty.c:3149
    #3 0x560ef66121dc in shk_other_services /home/lunatunez/hackem/src/shk.c:1941
    #4 0x560ef660b977 in dopay /home/lunatunez/hackem/src/shk.c:1569
    #5 0x560ef5da80a0 in rhack /home/lunatunez/hackem/src/cmd.c:5524
    #6 0x560ef5ca8bf0 in moveloop /home/lunatunez/hackem/src/allmain.c:798
    #7 0x560ef6902407 in main ../sys/unix/unixmain.c:353
    #8 0x7f378c26a082 in __libc_start_main ../csu/libc-start.c:308

SUMMARY: AddressSanitizer: 16 byte(s) leaked in 1 allocation(s).
```

**Comment by elunna** [comment]
Commit da801b357 In the shopkeeper services menu, the selection pointer was not being freed - leading to a memory leak. Fixed.
