### ISSUE TITLE
Found with fuzzer: The figurine writhes and then shatters into pieces!

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#28]
```

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7363859 in __GI_abort () at abort.c:79
#2  0x0000555555a466e1 in NH_abort () at end.c:236
#3  0x0000555555a464c9 in panictrace_handler (sig_unused=11) at end.c:161
#4  <signal handler called>
#5  0x00005555557bbfba in doapply () at apply.c:5040
#6  0x000055555586420c in rhack (cmd=0x5555567aba20 <in_line> "a") at cmd.c:5529
#7  0x0000555555764bf9 in moveloop (resuming=0 '\000') at allmain.c:798
#8  0x00005555563bf0bb in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {1024, 0, 0, 0, 0, 140737335783280, 93824997417907, 335544320, 
            140737341046928, 1073741824, 0, 140737342793376, 4294967295, 140737337360384, 
            140737342776480, 8972467680509121536}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007ffff7363859 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0xffffffff, sa_sigaction = 0xffffffff}, 
          sa_mask = {__val = {140737337360384, 140737342776480, 8972467680509121536, 
              140737488345824, 140737342793376, 18446744073709547520, 140737327104000, 
              140737345462488, 140737488347744, 17592186043468, 140737344331794, 
              17592186043228, 140737488338944, 140737341046928, 8972467680509121536, 1}}, 
          sa_flags = 929780736, sa_restorer = 0x7fffffffe300}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x0000555555a466e1 in NH_abort () at end.c:236
        gdb_prio = 1
        libc_prio = 2
        aborting = 1 '\001'
#3  0x0000555555a464c9 in panictrace_handler (sig_unused=11) at end.c:161
        f2 = 18
#4  <signal handler called>
No locals.
#5  0x00005555557bbfba in doapply () at apply.c:5040
        obj = 0x0
        otmp = 0x0
        res = 1
        class_list = "\006\002\v\000\000\000\000\000@\322EVUU\000\000\a\346\206UU"
#6  0x000055555586420c in rhack (cmd=0x5555567aba20 <in_line> "a") at cmd.c:5529
        tlist = 0x55555666a060 <extcmdlist+192>
        res = 688
        func = 0x5555557b9bf7 <doapply>
        spkey = 0
        prefix_seen = 0 '\000'
        bad_command = -47 '\321'
        firsttime = 1 '\001'
#7  0x0000555555764bf9 in moveloop (resuming=0 '\000') at allmain.c:798
        moveamt = 12
        wtcap = 0
        change = 0
        monscanmove = 0 '\000'
        timeout_start = 27960
        past_clock = 60691
        elf_regen = 1 '\001'
        orc_regen = 1 '\001'
        vamp_regen = 1 '\001'
#8  0x00005555563bf0bb in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
        fd = -1
        dir = 0x0
        exact_username = 0 '\000'
        resuming = 0 '\000'
        plsel_once = 1 '\001'
```

**Comment by elunna** [comment]
<img width="960" alt="issue 28" src="https://user-images.githubusercontent.com/5000096/199214967-0882ac03-37fa-4b1a-a19a-af246fd4aa79.png">
