### ISSUE TITLE
Found with fuzzer: mon hiding under nonexistent obj (%s)

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#29]
```
Breakpoint 1, panic (str=0x1e <error: Cannot access memory at address 0x1e>) at end.c:730
730	VA_DECL(const char *, str)
#0  panic (str=0x1e <error: Cannot access memory at address 0x1e>) at end.c:730
#1  0x0000555555f9da67 in impossible (
    s=0x5555564e1d40 "mon hiding under nonexistent obj (%s)") at pline.c:518
#2  0x0000555555d670f3 in sanity_check_single_mon (mtmp=0x61100000cc00, chk_geno=1 '\001', 
    msg=0x5555564e1f00 "fmon") at mon.c:120
#3  0x0000555555d6757d in mon_sanity_check () at mon.c:147
#4  0x0000555555860c6f in sanity_check () at cmd.c:4856
#5  0x0000555555764ada in moveloop (resuming=0 '\000') at allmain.c:788
#6  0x00005555563c10ca in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
#0  panic (str=0x1e <error: Cannot access memory at address 0x1e>) at end.c:730
        the_args = {{gp_offset = 4294959408, fp_offset = 32767, 
            overflow_arg_area = 0x5bf4558107e1900, reg_save_area = 0x12500}}
#1  0x0000555555f9da67 in impossible (
    s=0x5555564e1d40 "mon hiding under nonexistent obj (%s)") at pline.c:518
        pbuf = "mon hiding under nonexistent obj (fmon)\000\000\336\377\377\377\177\000\000@\335\377\377\377\177\000\000\000\031~\020XE\277\005\320\307`VUU\000\000\300\202NVUU\000\000p\336\377\377\377\177\000\000\020\000\000\000\000\000\000\000\005\000\000\000\000\000\000\000\006\000\000\000\000\000\000\000\254\032\037VUU\000\000\000\000\000\000\000\000\000\000N\001", '\000' <repeats 14 times>, "\263\212\265A\000\000\000\000\340\306FVUU\000\000\217\n\215UUU", '\000' <repeats 19 times>, "\031~\020XE\277\005\020\337\377\377\377\177\000\000"...
        the_args = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7fffffffe380, 
            reg_save_area = 0x7fffffffe2a0}}
#2  0x0000555555d670f3 in sanity_check_single_mon (mtmp=0x61100000cc00, chk_geno=1 '\001', 
    msg=0x5555564e1f00 "fmon") at mon.c:120
        t = 0x0
        mptr = 0x55555660b6c0 <mons+30368>
        mx = 62
        my = 6
#3  0x0000555555d6757d in mon_sanity_check () at mon.c:147
        x = 51
        y = 19
        mtmp = 0x61100000cc00
        m = 0x61100000cd40
#4  0x0000555555860c6f in sanity_check () at cmd.c:4856
No locals.
#5  0x0000555555764ada in moveloop (resuming=0 '\000') at allmain.c:788
        moveamt = 10
        wtcap = 0
        change = 0
        monscanmove = 0 '\000'
        timeout_start = 26355
        past_clock = -21229
        elf_regen = 1 '\001'
        orc_regen = 1 '\001'
        vamp_regen = 1 '\001'
#6  0x00005555563c10ca in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
        fd = -1
        dir = 0x0
        exact_username = 0 '\000'
        resuming = 0 '\000'
        plsel_once = 1 '\001'
```

**Comment by elunna** [comment]
Caused by introducing spirits.

**Comment by elunna** [comment]
5631d0fa6 Fix for issue #29: Monsters cannot hide under spirits.

**Comment by elunna** [comment]
commit a24664a7c Another fix for issue 29: Monsters were still able to hide under spirits. I have allowed this, and handled when spirits fade now.

**Comment by elunna** [comment]
Popped up again:
```

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7363859 in __GI_abort () at abort.c:79
#2  0x0000555555a54fa4 in NH_abort () at end.c:236
#3  0x0000555555a5bda0 in panic (str=0x555556556700 "%s") at end.c:802
#4  0x0000555555fb7799 in impossible (s=0x55555650d3a0 "mon hiding under nonexistent obj (%s)")
    at pline.c:518
#5  0x0000555555d7b84e in sanity_check_single_mon (mtmp=0x6110002d2c00, chk_geno=1 '\001', 
    msg=0x55555650d560 "fmon") at mon.c:120
#6  0x0000555555d7bcd8 in mon_sanity_check () at mon.c:147
#7  0x000055555586bc5b in sanity_check () at cmd.c:4857
#8  0x000055555576b842 in moveloop (resuming=0 '\000') at allmain.c:794
#9  0x00005555563e837b in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {0, 0, 0, 0, 0, 140737335783280, 93824997477494, 335544320, 
            140737341046928, 1073741824, 0, 140737342793376, 4294967295, 140737337360384, 
            140737342776480, 703604521916172288}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007ffff7363859 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0xffffffff, sa_sigaction = 0xffffffff}, 
          sa_mask = {__val = {140737337360384, 140737342776480, 703604521916172288, 
              140737488345200, 140737342793376, 18446744073709547520, 140737327104000, 
              140737345462488, 140737488346272, 140737488346272, 140737344331794, 
              17592186043150, 140737488338944, 140737341046928, 703604521916172288, 
              140737488345600}}, sa_flags = -1221851136, sa_restorer = 0x7fffffffdbc0}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x0000555555a54fa4 in NH_abort () at end.c:236
        gdb_prio = 1
        libc_prio = 2
        aborting = 1 '\001'
#3  0x0000555555a5bda0 in panic (str=0x555556556700 "%s") at end.c:802
        the_args = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7fffffffdc90, 
            reg_save_area = 0x7fffffffdbc0}}
#4  0x0000555555fb7799 in impossible (s=0x55555650d3a0 "mon hiding under nonexistent obj (%s)")
    at pline.c:518
        pbuf = "mon hiding under nonexistent obj (fmon)", '\000' <repeats 433 times>...
        the_args = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7fffffffe380, 
            reg_save_area = 0x7fffffffe2a0}}
#5  0x0000555555d7b84e in sanity_check_single_mon (mtmp=0x6110002d2c00, chk_geno=1 '\001', 
    msg=0x55555650d560 "fmon") at mon.c:120
        t = 0x15
        mptr = 0x555556640910 <mons+55536>
        mx = 61
        my = 4
#6  0x0000555555d7bcd8 in mon_sanity_check () at mon.c:147
        x = 20
        y = 17
        mtmp = 0x6110002d2c00
        m = 0x6110002d2d40
#7  0x000055555586bc5b in sanity_check () at cmd.c:4857
No locals.
#8  0x000055555576b842 in moveloop (resuming=0 '\000') at allmain.c:794
        moveamt = 12
        wtcap = 0
        change = 0
        monscanmove = 0 '\000'
        elf_regen = 1 '\001'
        orc_regen = 1 '\001'
        vamp_regen = 1 '\001'
#9  0x00005555563e837b in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
        fd = -1
        dir = 0x0
        exact_username = 0 '\000'
        resuming = 0 '\000'
        plsel_once = 1 '\001'

```

**Comment by elunna** [comment]
This also popped up with an Undead Slayer - so it might not actually be spirits causing the problem.
