### ISSUE TITLE
LeakSanitizer: zap/mkobj

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#31]
```
=================================================================
==26345==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 120 byte(s) in 1 object(s) allocated from:
    #0 0x7fe79f4a3808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x55c878f302eb in alloc /home/lunatunez/hackem/src/alloc.c:46
    #2 0x55c879510861 in mksobj /home/lunatunez/hackem/src/mkobj.c:806
    #3 0x55c87950cdf7 in mkobj /home/lunatunez/hackem/src/mkobj.c:287
    #4 0x55c8796da5de in readobjnam /home/lunatunez/hackem/src/objnam.c:4680
    #5 0x55c879b881b5 in makewish /home/lunatunez/hackem/src/zap.c:6927
    #6 0x55c878ffa1f3 in wiz_wish /home/lunatunez/hackem/src/cmd.c:815
    #7 0x55c87902c592 in rhack /home/lunatunez/hackem/src/cmd.c:5529
    #8 0x55c878f2cf72 in moveloop /home/lunatunez/hackem/src/allmain.c:819
    #9 0x55c879b8cc23 in main ../sys/unix/unixmain.c:353
    #10 0x7fe79f16f082 in __libc_start_main ../csu/libc-start.c:308

SUMMARY: AddressSanitizer: 120 byte(s) leaked in 1 allocation(s).
```

**Comment by elunna** [comment]
This one looks similar 
```

Direct leak of 120 byte(s) in 1 object(s) allocated from:
    #0 0x7fe07f14e808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x55b8f45d60bb in alloc /home/lunatunez/hackem/src/alloc.c:46
    #2 0x55b8f4bc9632 in mksobj /home/lunatunez/hackem/src/mkobj.c:806
    #3 0x55b8f4d983df in readobjnam /home/lunatunez/hackem/src/objnam.c:4683
    #4 0x55b8f525659b in makewish /home/lunatunez/hackem/src/zap.c:6988
    #5 0x55b8f46a49b6 in wiz_wish /home/lunatunez/hackem/src/cmd.c:815
    #6 0x55b8f46d70a4 in rhack /home/lunatunez/hackem/src/cmd.c:5553
    #7 0x55b8f45d2cda in moveloop /home/lunatunez/hackem/src/allmain.c:826
    #8 0x55b8f525afbb in main ../sys/unix/unixmain.c:353
    #9 0x7fe07ee1a082 in __libc_start_main ../csu/libc-start.c:308
```

**Comment by elunna** [comment]
Can't reproduce

**Comment by elunna** [comment]
Reopening for a second look.

**Comment by elunna** [comment]
This leak has not popped up in any recent fuzzing sessions so I'm going to close it. Stale.
