### ISSUE TITLE
Memory Leak: Animate dead spell

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#32]
```

Direct leak of 120 byte(s) in 1 object(s) allocated from:
    #0 0x7fca25313808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x559b2ef0c324 in alloc /home/lunatunez/hackem/src/alloc.c:46
    #2 0x559b2f4ed124 in mksobj /home/lunatunez/hackem/src/mkobj.c:806
    #3 0x559b2f80cabb in seffects /home/lunatunez/hackem/src/read.c:2168
    #4 0x559b2f912757 in spelleffects /home/lunatunez/hackem/src/spell.c:1352
    #5 0x559b2f90decd in docast /home/lunatunez/hackem/src/spell.c:770
    #6 0x559b2f008b2a in rhack /home/lunatunez/hackem/src/cmd.c:5529
    #7 0x559b2ef08fab in moveloop /home/lunatunez/hackem/src/allmain.c:821
    #8 0x559b2fb6a0d8 in main ../sys/unix/unixmain.c:353
    #9 0x7fca24fdf082 in __libc_start_main ../csu/libc-start.c:308
```

**Comment by elunna** [comment]
The animate dead spell required creating a pseudo spellbook object. This was not being correctly freed when done with. Fixed in commit a628fc4bf.
