### ISSUE TITLE
Found with fuzzer: Two-weaponing enabled with non-existent alternate weapon causes segfault

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#321]
Extra info: PM_YEOMAN, human race, non-polyed. 
Had a chakram in the primary hand.
Crash occurred on turn 48781549
```
(rr) p toplines
$6 = "What do you want to throw?\000lly cast without energy use? v8Fx8Y O5c1", '\000' <repeats 232 times>

#0  0x0000565025611e62 in wielding_artifact (art=26) at artifact.c:4518
#1  0x000056502561ceeb in acurr (x=0) at attrib.c:1349
#2  0x000056502561d77a in acurrstr () at attrib.c:1404
#3  0x0000565025917f69 in weight_cap () at hack.c:3596
#4  0x00005650259194a2 in inv_weight () at hack.c:3676
#5  0x00005650259194cc in calc_capacity (xtra_wt=0) at hack.c:3688
#6  0x0000565025919528 in near_capacity () at hack.c:3701
#7  0x0000565025dc6748 in encumber_msg () at pickup.c:1659
#8  0x00005650255711a0 in moveloop (resuming=0 '\000') at allmain.c:243
#9  0x0000565026268816 in main (argc=0, argv=0x7fff39f356a8) at ../sys/unix/unixmain.c:353

bt -full
#0  0x0000565025611e62 in wielding_artifact (art=26) at artifact.c:4518
No locals.
#1  0x000056502561ceeb in acurr (x=0) at attrib.c:1349
        base = 16
        bonus = 0
        nobonus = 0 '\000'
        tmp = 16
#2  0x000056502561d77a in acurrstr () at attrib.c:1404
        str = 0
#3  0x0000565025917f69 in weight_cap () at hack.c:3596
        carrcap = 94902226462540
        save_ELev = 0
        save_BLev = 0
        maxcarrcap = 1000
        boots = 0x0
#4  0x00005650259194a2 in inv_weight () at hack.c:3676
        otmp = 0x0
        wt = 535
#5  0x00005650259194cc in calc_capacity (xtra_wt=0) at hack.c:3688
        cap = -1763242146
        wt = 881278720
#6  0x0000565025919528 in near_capacity () at hack.c:3701
No locals.
#7  0x0000565025dc6748 in encumber_msg () at pickup.c:1659
        oldcap = 0
        newcap = 32710
#8  0x00005650255711a0 in moveloop (resuming=0 '\000') at allmain.c:243
        pobj = 0x5650264c24d8
        moveamt = 12
        wtcap = 0
        change = 0
        monscanmove = 0 '\000'
        elf_regen = 1 '\001'
        orc_regen = 1 '\001'
        vamp_regen = 1 '\001'
#9  0x0000565026268816 in main (argc=0, argv=0x7fff39f356a8) at ../sys/unix/unixmain.c:353
        fd = -1
        dir = 0x0
        exact_username = 0 '\000'
        resuming = 0 '\000'
        plsel_once = 1 '\001'

```

**Comment by elunna** [comment]
It appears that the chakram was the object thrown

**Comment by elunna** [comment]
Can't reproduce. File might be corrupted.
