### ISSUE TITLE
Found with fuzzer: mon (6110003db0c0) at <23,20> is not there!

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#322]
```
(rr) p toplines
$2 = "Ye swim underneath the invisible Ron.  The giant eel bites!  The skeletal pirate lacerates ye!  (0 pts.)", '\000' <repeats 195 times>


Suddenly, the dungeon collapses.
mon (6110003db0c0) at <23,20> is not there!

(rr) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140052821358528) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140052821358528) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140052821358528, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007f609661a476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007f60966007f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x000055ef072d7e16 in NH_abort () at end.c:236
#6  0x000055ef072deed0 in panic (str=0x55ef07e4d380 "%s") at end.c:802
#7  0x000055ef07853ff3 in impossible (s=0x55ef07dfeb80 "mon (%s) at <%d,%d> is not there!") at pline.c:689
#8  0x000055ef0761779d in mon_sanity_check () at mon.c:165
#9  0x000055ef070ed5ea in sanity_check () at cmd.c:5091
#10 0x000055ef06fdfb18 in moveloop (resuming=0 '\000') at allmain.c:839
#11 0x000055ef07cd15e5 in main (argc=0, argv=0x7ffd5cb95948) at ../sys/unix/unixmain.c:353


Full backtrace

#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140052821358528) at ./nptl/pthread_kill.c:44
        tid = <optimized out>
        ret = 0
        pd = 0x7f6096aab7c0
        old_mask = {__val = {140052816569632, 1073741824, 0, 140052818503552, 4294967295, 140052810170368, 
            140052818486784, 5920703963207514880, 140726159100864, 140052818503552, 0, 5920703963207514880, 
            17590769887608, 140726159100864, 17590769887608, 140726159100864}}
        ret = <optimized out>
        pd = <optimized out>
        old_mask = <optimized out>
        ret = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
        resultvar = <optimized out>
        resultvar = <optimized out>
        __arg3 = <optimized out>
        __arg2 = <optimized out>
        __arg1 = <optimized out>
        _a3 = <optimized out>
        _a2 = <optimized out>
        _a1 = <optimized out>
        __futex = <optimized out>
        resultvar = <optimized out>
        __arg3 = <optimized out>
        __arg2 = <optimized out>
        __arg1 = <optimized out>
        _a3 = <optimized out>
        _a2 = <optimized out>
        _a1 = <optimized out>
        __futex = <optimized out>
        __private = <optimized out>
        __oldval = <optimized out>
        result = <optimized out>
#1  __pthread_kill_internal (signo=6, threadid=140052821358528) at ./nptl/pthread_kill.c:78
No locals.
#2  __GI___pthread_kill (threadid=140052821358528, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
No locals.
#3  0x00007f609661a476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
        ret = <optimized out>
#4  0x00007f60966007f3 in __GI_abort () at ./stdlib/abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x7ffd5cb94d50, sa_sigaction = 0x7ffd5cb94d50}, sa_mask = {
            __val = {140726159101936, 140726159101936, 140052822688959, 140052818486784, 5920703963207514880, 
              140726159100864, 140052818503552, 18446744073709547520, 140052821299200, 140052823917272, 
              140052822726317, 140726159101936, 140052822712342, 17590769887608, 140726159093760, 140052816569632}}, 
          sa_flags = -1556399360, sa_restorer = 0x7ffd5cb94d50}
        sigs = {__val = {32, 140726159101184, 140052822211598, 94485105966848, 94485105966576, 94485105995472, 
            94485111717875, 94485109372829, 94485103957482, 94485102852888, 94485116425701, 5920703963207514880, 
            140052816469568, 140726159101712, 140726159101712, 140726159101216}}
#5  0x000055ef072d7e16 in NH_abort () at end.c:236
        gdb_prio = 1
        libc_prio = 2
        aborting = 1 '\001'
#6  0x000055ef072deed0 in panic (str=0x55ef07e4d380 "%s") at end.c:802
        the_args = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7ffd5cb94fe0, 
            reg_save_area = 0x7ffd5cb94f10}}
#7  0x000055ef07853ff3 in impossible (s=0x55ef07dfeb80 "mon (%s) at <%d,%d> is not there!") at pline.c:689
        pbuf = "mon (6110003db0c0) at <23,20> is not there!\000\000\000\000\000\001\001\000\000\000\000\001\000\000\001\000\000\001\000\001\002\000\000\001\001\001\000\000\000\000\001", '\000' <repeats 39 times>, "\001\000\001\001\001\000\000\000\001\000\000\000\000\002\001\000\000\000\000\001", '\000' <repeats 68 times>...
            reg_save_area = 0x7ffd5cb94f10}}
#7  0x000055ef07853ff3 in impossible (s=0x55ef07dfeb80 "mon (%s) at <%d,%d> is not there!") at pline.c:689
        pbuf = "mon (6110003db0c0) at <23,20> is not there!\000\000\000\000\000\001\001\000\000\000\000\001\000\000\001\000\000\001\000\001\002\000\000\001\001\001\000\000\000\000\001", '\000' <repeats 39 times>, "\001\000\001\001\001\000\000\000\001\000\000\000\000\002\001\000\000\000\000\001", '\000' <repeats 68 times>...
--Type <RET> for more, q to quit, c to continue without paging--
        the_args = {{gp_offset = 32, fp_offset = 48, overflow_arg_area = 0x7ffd5cb956d0, 
            reg_save_area = 0x7ffd5cb955f0}}
#8  0x000055ef0761779d in mon_sanity_check () at mon.c:165
        x = 23
        y = 20
        mtmp = 0x6110003db0c0
        m = 0x6110003dae40
#9  0x000055ef070ed5ea in sanity_check () at cmd.c:5091
No locals.
#10 0x000055ef06fdfb18 in moveloop (resuming=0 '\000') at allmain.c:839
        pobj = 0x55ef07f2b4f8
        moveamt = 12
        wtcap = 0
        change = 0
        monscanmove = 0 '\000'
        elf_regen = 1 '\001'
        orc_regen = 1 '\001'
        vamp_regen = 1 '\001'
#11 0x000055ef07cd15e5 in main (argc=0, argv=0x7ffd5cb95948) at ../sys/unix/unixmain.c:353
        fd = -1
        dir = 0x0
        exact_username = 0 '\000'
        resuming = 0 '\000'
        plsel_once = 1 '\001'

```

**Comment by elunna** [comment]
Missing monster appears to be #define	PM_GHOST	653

**Comment by elunna** [comment]
Apparantly if you try to attack a monster while swimming and the monster is above ground you will swim under it, which also makes you switch places with it. I tried this a few times with a ghost while submerged in water, but no crash.

**Comment by elunna** [comment]
Maybe related to this EvilHack commit:  https://github.com/k21971/EvilHack/commit/442a2ac22dc4b36647bcab68695582dc97d9df2a

To attempt reproducing I tried playing as a pirate, going to medusa's level for lots of water.
First I just tried one ghost and attacking in water, which just causes you to swim under. Then I added more and more ghosts.
No results.

**Comment by elunna** [comment]
Now have 2 recordings of this issue. Both are pirates in the quest home level.
Recording 1 (#10)

Recording 2 (#43)
```
(rr) p moves = 3162392
toplines = "Ye sense a faint wave o' psychic energy.", '\000' <repeats 259 times>
(rr) p u.uz = {dnum = 0 '\000', dlevel = 11 '\v'}
(rr) p u.umonster = 756
(rr) p u.umonnum = 756
(rr) p urace.malenum = 601
(rr) p u.ux = 37 '%'
(rr) p u.uy = 11 '\v'
(rr) p u.dx = 1 '\001'
(rr) p u.dy = 1 '\001'
(rr) p uball = (struct obj *) 0x60c0007cc540
(rr) p uchain = (struct obj *) 0x60c0012f1900

mtmp: mnum = 367 (PM_RED_DRAGON), cham = -1, 
movement = 0, m_lev = 19 '\023',   malign = 5 '\005', mx = 36 '$', my = 10 '\n', mux = 37 '%', muy = 11 '\v',
mhp = 49, mhpmax = 49,
```

**Comment by elunna** [comment]
Finally was able to reproduce a few times, not sure exactly how yet. I was just swimming around in the water with ghosts.

```
Message History

           Program in disorder!  (Savin' 'n reloadin' may fix this problem.)
           mon (611000008880) at <6,11> ain't there!
           Ye swim underneath Wilmar.  Ye see 'ere a giant eel corpse.
           Ye swim underneath it.  Ye harmlessly attack the water.
           Ye feel an unseen monster!
           Ye tumble past Wilmar.  Ye fall into the water.
```

This time, I had tried moving into a hidden ghost in the water 2x in a row, and the second time it triggered the error.
```
Program in disorder!  (Savin' 'n reloadin' may fix this problem.)
            mon (611000014180) at <8,6> ain't there!
            Ye swim underneath it.  Ye harmlessly attack the water.
            Ye swim underneath it.  Ye harmlessly attack the water.
```
Same with this time:

```
Program in disorder!  (Savin' 'n reloadin' may fix this problem.)                                
                               mon (6110000142c0) at <8,6> ain't there!
                               Ye swim underneath it.  Ye harmlessly attack the water.
                               Ye feel an unseen monster!
```

My guess: When we try to attack an invisible ghost in the water, it tries to switch places because we get the "you swim underneath it" message. However, I think the attack fails because it's an invisible monster, so the ghost may be switching places to where the player is, but being displaced somewhere else or removed from the map entirely.

**Comment by elunna** [comment]
Tested in EvilHack. After trying a monk, I realized this bug doesn't occur if you can see invisible. So I switched to a tortle tourist. At level 5 tortles get warning, so I had to demote myself to 4, because I think the same thing occurs for warning as see invisible.

Anyway, after dancing with an invisible ghost in the water at Medusa's for a brief bit, a homunculus came over at a weird time and we got this error:

```
 You swim underneath the homunculus.
Program in disorder!  (Saving and reloading may fix this problem.)
placing homunculus <34,3> over ghost <35,4> at <35,4>, mstates:0 0 on Dlvl:24 ?
You swim underneath it.  You harmlessly attack the water.  The human zombie moans.  
```

**Comment by elunna** [comment]
My fix is to add another check for invisible monsters when we might swim underneath a monster.  This seems to prevent the weird position switches between us and the invisible ghost, and just results in us trying to attack the position.
