### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#33]
```
Indirect leak of 54 byte(s) in 6 object(s) allocated from:
    #0 0x7f324b966808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x5615022ab324 in alloc /home/lunatunez/hackem/src/alloc.c:46
    #2 0x5615022ab3e3 in dupstr /home/lunatunez/hackem/src/alloc.c:162
    #3 0x561502c7301a in opvar_clone /home/lunatunez/hackem/src/sp_lev.c:469
    #4 0x561502ca1d1d in sp_level_coder /home/lunatunez/hackem/src/sp_lev.c:5651
    #5 0x561502ca6dba in load_special /home/lunatunez/hackem/src/sp_lev.c:6335
    #6 0x56150287f0d4 in makemaz /home/lunatunez/hackem/src/mkmaze.c:1017
    #7 0x561502868a6f in makelevel /home/lunatunez/hackem/src/mklev.c:818
    #8 0x56150286c0a6 in mklev /home/lunatunez/hackem/src/mklev.c:1255
    #9 0x561502454a48 in goto_level /home/lunatunez/hackem/src/do.c:1905
    #10 0x56150253d3f9 in next_level /home/lunatunez/hackem/src/dungeon.c:1179
    #11 0x561502451af3 in dodown /home/lunatunez/hackem/src/do.c:1493
    #12 0x5615023a760d in rhack /home/lunatunez/hackem/src/cmd.c:5529
    #13 0x5615022a7fab in moveloop /home/lunatunez/hackem/src/allmain.c:821
    #14 0x561502f081de in main ../sys/unix/unixmain.c:353
    #15 0x7f324b632082 in __libc_start_main ../csu/libc-start.c:308
```

**Comment by elunna** [comment]
Duplicate of issue #34
