### ISSUE TITLE
Found with fuzzer: Segfault in botl update

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#333]
(rr) p toplines
$1 = 0x560a66a0e560 <toplines> "It invokes nightmarish images in your mind..."

```
(rr) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140034878015424)
    at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140034878015424)
    at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140034878015424, signo=signo@entry=6)
    at ./nptl/pthread_kill.c:89
#3  0x00007f5c68e1a476 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/posix/raise.c:26
#4  0x00007f5c68e007f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x0000560a65bcbe3c in NH_abort () at end.c:236
#6  0x0000560a65bcbc24 in panictrace_handler (sig_unused=11) at end.c:161
#7  <signal handler called>
#8  0x00007f5c694cf066 in __sanitizer::internal_strlen (
    s=s@entry=0x8948c7950f40c984 <error: Cannot access memory at address 0x8948c7950f40c984>)
    at ../../../../src/libsanitizer/sanitizer_common/sanitizer_libc.cpp:167
#9  0x00007f5c694602ee in printf_common(void *, const char *, typedef __va_list_tag __va_list_tag *) (ctx=ctx@entry=0x7fff644299b8, 
    format=format@entry=0x560a667e7140 " %s", aq=0x7fff644299c8)
    at ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors_format.inc:551
#10 0x00007f5c69461103 in __interceptor_vsprintf(char *, const char *, typedef __va_list_tag __va_list_tag *) (str=0x61100021ad80 "", format=<optimized out>, 
--Type <RET> for more, q to quit, c to continue without paging--
    =0x7fff6442a250) at ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:1687
#11 0x00007f5c6946127f in __interceptor_sprintf (str=<optimized out>, format=<optimized out>)
    at ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:1730
#12 0x0000560a665ed879 in shrink_enc (lvl=1) at ../win/tty/wintty.c:4289
#13 0x0000560a665ebed7 in make_things_fit (force_update=0 '\000') at ../win/tty/wintty.c:4052
#14 0x0000560a665eac15 in tty_status_update (fldidx=-1, ptr=0x0, chg=0, percent=0, color=8, colormasks=0x0)
    at ../win/tty/wintty.c:3909
#15 0x0000560a65999b8c in evaluate_and_notify_windowport (valsetlist=0x560a669f3ac0 <valset> "\001\001", idx=0)
    at botl.c:1114
#16 0x0000560a6599887d in bot_via_windowport () at botl.c:912
#17 0x0000560a659936cc in bot () at botl.c:250
#18 0x0000560a658d29d2 in moveloop (resuming=0 '\000') at allmain.c:773
#19 0x0000560a665c5784 in main (argc=0, argv=0x7fff6442a998) at ../sys/unix/unixmain.c:353



```

**Comment by elunna** [comment]
Tried getting as many conditions as possible: Burdened Slim Stngl Ill Blnd Def Cnf Fear Hal Fly
But not able to cause a crash yet.

**Comment by elunna** [comment]
Another hit, but this one occurred after like 90M turns.

```
(gdb) bt
#0  0x00007ffff768b066 in __sanitizer::internal_strlen (s=s@entry=0xcb36e8cf89480874 <error: Cannot access memory at address 0xcb36e8cf89480874>)
    at ../../../../src/libsanitizer/sanitizer_common/sanitizer_libc.cpp:167
#1  0x00007ffff761c2ee in printf_common(void *, const char *, typedef __va_list_tag __va_list_tag *) (ctx=ctx@entry=0x7fffffffd4c8, 
    format=format@entry=0x5555566b50c0 " %s", aq=0x7fffffffd4d8)
    at ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors_format.inc:551
#2  0x00007ffff761d103 in __interceptor_vsprintf(char *, const char *, typedef __va_list_tag __va_list_tag *) (str=0x6110003ce8c0 "", 
    format=<optimized out>, ap=0x7fffffffdd60) at ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:1687
#3  0x00007ffff761d27f in __interceptor_sprintf (str=<optimized out>, format=<optimized out>)
    at ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:1730
#4  0x00005555564b95aa in shrink_enc (lvl=1) at ../win/tty/wintty.c:4291
#5  0x00005555564b7c08 in make_things_fit (force_update=0 '\000') at ../win/tty/wintty.c:4054
#6  0x00005555564b6946 in tty_status_update (fldidx=-1, ptr=0x0, chg=0, percent=0, color=8, colormasks=0x0) at ../win/tty/wintty.c:3911
#7  0x000055555585158e in evaluate_and_notify_windowport (valsetlist=0x5555568c3c00 <valset> "\001\001", idx=0) at botl.c:1124
#8  0x000055555585027f in bot_via_windowport () at botl.c:922
#9  0x000055555584b001 in bot () at botl.c:258
#10 0x000055555578ba25 in moveloop (resuming=0 '\000') at allmain.c:774
#11 0x00005555564914b5 in main (argc=0, argv=0x7fffffffe4a8) at ../sys/unix/unixmain.c:353

```

**Comment by elunna** [comment]
Closing since it's almost impossible to reproduce and the data suggests maybe the file got corrupted after 90M turns or something.
