### ISSUE TITLE
Memory leak when manticore volleys spikes at player. 

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#347]
Could be related to memory leaks I found from a fuzzer session:

```
=================================================================
==44464==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 147968 byte(s) in 1156 object(s) allocated from:
    #0 0x7f21feca9867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x55b15b0ff9a5 in alloc /home/erik/Documents/hackem/src/alloc.c:46
    #2 0x55b15b712f1e in mksobj /home/erik/Documents/hackem/src/mkobj.c:844
    #3 0x55b15b85376e in volleymu /home/erik/Documents/hackem/src/mthrowu.c:1385
    #4 0x55b15b668306 in mattacku /home/erik/Documents/hackem/src/mhitu.c:1119
    #5 0x55b15b80dc09 in dochug /home/erik/Documents/hackem/src/monmove.c:858
    #6 0x55b15b7f9408 in dochugw /home/erik/Documents/hackem/src/monmove.c:126
    #7 0x55b15b762b4a in movemon /home/erik/Documents/hackem/src/mon.c:1571
    #8 0x55b15b0f522b in moveloop /home/erik/Documents/hackem/src/allmain.c:247
    #9 0x55b15bded706 in main ../sys/unix/unixmain.c:353
    #10 0x7f21fe601d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

Direct leak of 70272 byte(s) in 549 object(s) allocated from:
    #0 0x7f21feca9867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x55b15b0ff9a5 in alloc /home/erik/Documents/hackem/src/alloc.c:46
    #2 0x55b15b712f1e in mksobj /home/erik/Documents/hackem/src/mkobj.c:844
    #3 0x55b15b85376e in volleymu /home/erik/Documents/hackem/src/mthrowu.c:1385
    #4 0x55b15b668306 in mattacku /home/erik/Documents/hackem/src/mhitu.c:1119
    #5 0x55b15b80f56a in dochug /home/erik/Documents/hackem/src/monmove.c:988
    #6 0x55b15b7f9408 in dochugw /home/erik/Documents/hackem/src/monmove.c:126
    #7 0x55b15b762b4a in movemon /home/erik/Documents/hackem/src/mon.c:1571
    #8 0x55b15b0f522b in moveloop /home/erik/Documents/hackem/src/allmain.c:247
    #9 0x55b15bded706 in main ../sys/unix/unixmain.c:353
    #10 0x7f21fe601d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

Direct leak of 11904 byte(s) in 93 object(s) allocated from:
    #0 0x7f21feca9867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x55b15b0ff9a5 in alloc /home/erik/Documents/hackem/src/alloc.c:46
    #2 0x55b15b712f1e in mksobj /home/erik/Documents/hackem/src/mkobj.c:844
    #3 0x55b15b84c7d1 in spitmm /home/erik/Documents/hackem/src/mthrowu.c:1092
    #4 0x55b15b5a7e60 in mattackm /home/erik/Documents/hackem/src/mhitm.c:785
    #5 0x55b15b33e718 in dog_move /home/erik/Documents/hackem/src/dogmove.c:1713
    #6 0x55b15b8152ed in m_move /home/erik/Documents/hackem/src/monmove.c:1246
    #7 0x55b15b80e9f3 in dochug /home/erik/Documents/hackem/src/monmove.c:937
    #8 0x55b15b7f9408 in dochugw /home/erik/Documents/hackem/src/monmove.c:126
    #9 0x55b15b762b4a in movemon /home/erik/Documents/hackem/src/mon.c:1571
    #10 0x55b15b0f522b in moveloop /home/erik/Documents/hackem/src/allmain.c:247
    #11 0x55b15bded706 in main ../sys/unix/unixmain.c:353
    #12 0x7f21fe601d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

Direct leak of 6912 byte(s) in 54 object(s) allocated from:
    #0 0x7f21feca9867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x55b15b0ff9a5 in alloc /home/erik/Documents/hackem/src/alloc.c:46
    #2 0x55b15b712f1e in mksobj /home/erik/Documents/hackem/src/mkobj.c:844
    #3 0x55b15b84c7d1 in spitmm /home/erik/Documents/hackem/src/mthrowu.c:1092
    #4 0x55b15b5a7e60 in mattackm /home/erik/Documents/hackem/src/mhitm.c:785
    #5 0x55b15b80dc1a in dochug /home/erik/Documents/hackem/src/monmove.c:859
    #6 0x55b15b7f9408 in dochugw /home/erik/Documents/hackem/src/monmove.c:126
    #7 0x55b15b762b4a in movemon /home/erik/Documents/hackem/src/mon.c:1571
    #8 0x55b15b0f522b in moveloop /home/erik/Documents/hackem/src/allmain.c:247
    #9 0x55b15bded706 in main ../sys/unix/unixmain.c:353
    #10 0x7f21fe601d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

Direct leak of 5632 byte(s) in 44 object(s) allocated from:
    #0 0x7f21feca9867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x55b15b0ff9a5 in alloc /home/erik/Documents/hackem/src/alloc.c:46
    #2 0x55b15b712f1e in mksobj /home/erik/Documents/hackem/src/mkobj.c:844
    #3 0x55b15b84c7d1 in spitmm /home/erik/Documents/hackem/src/mthrowu.c:1092
    #4 0x55b15b5a7e60 in mattackm /home/erik/Documents/hackem/src/mhitm.c:785
    #5 0x55b15b33ce0c in dog_move /home/erik/Documents/hackem/src/dogmove.c:1513
    #6 0x55b15b8152ed in m_move /home/erik/Documents/hackem/src/monmove.c:1246
    #7 0x55b15b80e9f3 in dochug /home/erik/Documents/hackem/src/monmove.c:937
    #8 0x55b15b7f9408 in dochugw /home/erik/Documents/hackem/src/monmove.c:126
    #9 0x55b15b762b4a in movemon /home/erik/Documents/hackem/src/mon.c:1571
    #10 0x55b15b0f522b in moveloop /home/erik/Documents/hackem/src/allmain.c:247
    #11 0x55b15bded706 in main ../sys/unix/unixmain.c:353
    #12 0x7f21fe601d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

Direct leak of 512 byte(s) in 4 object(s) allocated from:
    #0 0x7f21feca9867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x55b15b0ff9a5 in alloc /home/erik/Documents/hackem/src/alloc.c:46
    #2 0x55b15b712f1e in mksobj /home/erik/Documents/hackem/src/mkobj.c:844
    #3 0x55b15b84c7eb in spitmm /home/erik/Documents/hackem/src/mthrowu.c:1095
    #4 0x55b15b5a7e60 in mattackm /home/erik/Documents/hackem/src/mhitm.c:785
    #5 0x55b15b80dc1a in dochug /home/erik/Documents/hackem/src/monmove.c:859
    #6 0x55b15b7f9408 in dochugw /home/erik/Documents/hackem/src/monmove.c:126
    #7 0x55b15b762b4a in movemon /home/erik/Documents/hackem/src/mon.c:1571
    #8 0x55b15b0f522b in moveloop /home/erik/Documents/hackem/src/allmain.c:247
    #9 0x55b15bded706 in main ../sys/unix/unixmain.c:353
    #10 0x7f21fe601d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

SUMMARY: AddressSanitizer: 243200 byte(s) leaked in 1900 allocation(s).
```

_Originally posted by @elunna in https://github.com/elunna/hackem/issues/343#issuecomment-1615301263_

**Comment by elunna** [comment]
Able to reproduce easily and verify the leaks on save with ASAN.
