### ISSUE TITLE
Found with fuzzer: "Wizard touches you"

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#35]
```

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7363859 in __GI_abort () at abort.c:79
#2  0x0000555555a4950d in NH_abort () at end.c:236
#3  0x0000555555a50309 in panic (str=0x555556533d80 "%s") at end.c:802
#4  0x0000555555fa2537 in impossible (
    s=0x55555644ef60 "uball: type %d (%s), where %d, wornmask=0x%08lx") at pline.c:518
#5  0x000055555580daf3 in bc_sanity_check () at ball.c:1090
#6  0x00005555558632b7 in sanity_check () at cmd.c:4858
#7  0x0000555555766ad3 in moveloop (resuming=0 '\000') at allmain.c:790
#8  0x00005555563ca092 in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {0, 0, 0, 0, 0, 140737335783280, 93824997429727, 335544320, 
            140737341046928, 1073741824, 0, 140737342793376, 4294967295, 140737337360384, 
            140737342776480, 2831731010208601344}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007ffff7363859 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0xffffffff, sa_sigaction = 0xffffffff}, 
          sa_mask = {__val = {140737337360384, 140737342776480, 2831731010208601344, 
              140737488345264, 140737342793376, 18446744073709547520, 140737327104000, 
              140737345462488, 140737488346336, 140737488346336, 140737344331794, 
              17592186043158, 140737488338944, 140737341046928, 2831731010208601344, 
              140737488345664}}, sa_flags = -1024387840, sa_restorer = 0x7fffffffdc00}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x0000555555a4950d in NH_abort () at end.c:236
        gdb_prio = 1
        libc_prio = 2
        aborting = 1 '\001'
#3  0x0000555555a50309 in panic (str=0x555556533d80 "%s") at end.c:802
        the_args = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7fffffffdcd0, 
            reg_save_area = 0x7fffffffdc00}}
#4  0x0000555555fa2537 in impossible (
    s=0x55555644ef60 "uball: type %d (%s), where %d, wornmask=0x%08lx") at pline.c:518
        pbuf = "uball: type 614 (heavy iron ball), where 4, wornmask=0x00400000\000\001\001\000\000\000\000\001\000\000\001\000\000\001\000\001\002\000\000\001\001\001\000\000\000\000\001", '\000' <repeats 39 times>, "\001\000\001\001\001\000\000\000\001\000\000\000\000\002\001\000\000\000\000\001", '\000' <repeats 68 times>...
        the_args = {{gp_offset = 40, fp_offset = 48, overflow_arg_area = 0x7fffffffe3c0, 
            reg_save_area = 0x7fffffffe2e0}}
#5  0x000055555580daf3 in bc_sanity_check () at ball.c:1090
        otyp = 614
        freeball = 0
        freechain = 0
        onam = 0x5555567d90c0 <obufs+512> "heavy iron ball"
#6  0x00005555558632b7 in sanity_check () at cmd.c:4858
No locals.
#7  0x0000555555766ad3 in moveloop (resuming=0 '\000') at allmain.c:790
        moveamt = 24
        wtcap = 0
        change = 0
        monscanmove = 1 '\001'
        timeout_start = 25463
        past_clock = 53757
        elf_regen = 1 '\001'
        orc_regen = 1 '\001'
        vamp_regen = 1 '\001'
#8  0x00005555563ca092 in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
        fd = -1
        dir = 0x0
        exact_username = 0 '\000'
        resuming = 0 '\000'
        plsel_once = 1 '\001'
```

**Comment by elunna** [comment]
where is 4: #define OBJ_MINVENT 4   /* object in a monster inventory */

Some monster was able to pick up our ball/chain?

**Comment by elunna** [comment]
Stale issue
