### ISSUE TITLE
Memory leak: spitmm with acid and venom

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#351]
This was part of some other memory leaks output after a fuzz session.
```
=================================================================
==229140==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 512 byte(s) in 4 object(s) allocated from:
    #0 0x7fdc828eb867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x564ccbfdb9a5 in alloc /home/erik/Documents/hackem/src/alloc.c:46
    #2 0x564ccc5eeee5 in mksobj /home/erik/Documents/hackem/src/mkobj.c:844
    #3 0x564ccc7287d2 in spitmm /home/erik/Documents/hackem/src/mthrowu.c:1092
    #4 0x564ccc483f02 in mattackm /home/erik/Documents/hackem/src/mhitm.c:785
    #5 0x564ccc6e9c1b in dochug /home/erik/Documents/hackem/src/monmove.c:859
    #6 0x564ccc6d5409 in dochugw /home/erik/Documents/hackem/src/monmove.c:126
    #7 0x564ccc63eb4b in movemon /home/erik/Documents/hackem/src/mon.c:1571
    #8 0x564ccbfd122b in moveloop /home/erik/Documents/hackem/src/allmain.c:247
    #9 0x564ccccc9c2b in main ../sys/unix/unixmain.c:353
    #10 0x7fdc823a7d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

Direct leak of 256 byte(s) in 2 object(s) allocated from:
    #0 0x7fdc828eb867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x564ccbfdb9a5 in alloc /home/erik/Documents/hackem/src/alloc.c:46
    #2 0x564ccc5eeee5 in mksobj /home/erik/Documents/hackem/src/mkobj.c:844
    #3 0x564ccc7287ec in spitmm /home/erik/Documents/hackem/src/mthrowu.c:1095
    #4 0x564ccc483f02 in mattackm /home/erik/Documents/hackem/src/mhitm.c:785
    #5 0x564ccc6e9c1b in dochug /home/erik/Documents/hackem/src/monmove.c:859
    #6 0x564ccc6d5409 in dochugw /home/erik/Documents/hackem/src/monmove.c:126
    #7 0x564ccc63eb4b in movemon /home/erik/Documents/hackem/src/mon.c:1571
    #8 0x564ccbfd122b in moveloop /home/erik/Documents/hackem/src/allmain.c:247
    #9 0x564ccccc9c2b in main ../sys/unix/unixmain.c:353
    #10 0x7fdc823a7d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
```

**Comment by elunna** [comment]
I was able to reproduce the acid attack one by using acid worms and rings of conflict to get to to spit acid at nearby monsters.
