### ISSUE TITLE
Memory leak in punish()

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#352]
Also found after a fuzz session.

```
Direct leak of 256 byte(s) in 2 object(s) allocated from:
    #0 0x7fdc828eb867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x564ccbfdb9a5 in alloc /home/erik/Documents/hackem/src/alloc.c:46
    #2 0x564ccc5eeee5 in mksobj /home/erik/Documents/hackem/src/mkobj.c:844
    #3 0x564ccc5ead49 in mkobj /home/erik/Documents/hackem/src/mkobj.c:288
    #4 0x564ccc933dd7 in punish /home/erik/Documents/hackem/src/read.c:3455
    #5 0x564ccc8c5b8d in angrygods /home/erik/Documents/hackem/src/pray.c:765
    #6 0x564ccc8d0f6b in gods_upset /home/erik/Documents/hackem/src/pray.c:1633
    #7 0x564ccc8de8ba in prayer_done /home/erik/Documents/hackem/src/pray.c:2607
    #8 0x564ccc3778ae in unmul /home/erik/Documents/hackem/src/hack.c:3500
    #9 0x564ccbfd42dc in moveloop /home/erik/Documents/hackem/src/allmain.c:647
    #10 0x564ccccc9c2b in main ../sys/unix/unixmain.c:353
    #11 0x7fdc823a7d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

```

**Comment by elunna** [comment]
Reproducing:
Tried reading an uncursed scroll of punishment
Tried reading a cursed scroll of punishment
Tried reading an uncursed scroll of punishment, then another
Tried repeated praying to anger gods and get punished.

**Comment by elunna** [comment]
Can't reproduce.
