### ISSUE TITLE
obfree: deleting worn obj (361: 3) in volleymu()

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#354]
```
Suddenly, the dungeon collapses.
obfree: deleting worn obj (361: 3)
Generating more information you may report:

#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140544020404160) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140544020404160) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140544020404160, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007fd2f421a476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007fd2f42007f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00005598eac7ae65 in NH_abort () at end.c:236
#6  0x00005598eac81f1f in panic (str=0x5598eb7f1200 "%s") at end.c:802
#7  0x00005598eb1f757c in impossible (s=0x5598eb826200 "obfree: deleting worn obj (%d: %ld)") at pline.c:685
#8  0x00005598eb31f68b in obfree (obj=0x60c000cc64c0, merge=0x0) at shk.c:1155
#9  0x00005598eb0dab2f in volleymu (mtmp=0x6110001c86c0, mattk=0x5598eb8e2728 <mons+22280>) at mthrowu.c:1390
#10 0x00005598eaeef3ee in mattacku (mtmp=0x6110001c86c0) at mhitu.c:1119
#11 0x00005598eb09668c in dochug (mtmp=0x6110001c86c0) at monmove.c:988
#12 0x00005598eb08052a in dochugw (mtmp=0x6110001c86c0) at monmove.c:126
#13 0x00005598eafe9c6c in movemon () at mon.c:1571
#14 0x00005598ea97c22c in moveloop (resuming=0 '\000') at allmain.c:247
#15 0x00005598eb674f0d in main (argc=0, argv=0x7fff40c40168) at ../sys/unix/unixmain.c:353

```

**Comment by elunna** [comment]
This was the critical tip:
```
(rr) p toplines
$4 = "The manticore fires a volley of spikes!  You are hit!  You are hit.  It misses.  The spike falls down the stairs.", '\000' <repeats 186 times>
```

Able to reproduce by standing on stairs and having manticore volley spikes until one falls down the stairs.
