### ISSUE TITLE
LeakSanitizer: mongets

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#355]
```
Direct leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x7fd7dc4c0867 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x55fb1c6fd9a5 in alloc /home/erik/Documents/hackem/src/alloc.c:46
    #2 0x55fb1cd11005 in mksobj /home/erik/Documents/hackem/src/mkobj.c:844
    #3 0x55fb1cb1d276 in mongets /home/erik/Documents/hackem/src/makemon.c:4211
    #4 0x55fb1cafa5c7 in m_initweap /home/erik/Documents/hackem/src/makemon.c:1099
    #5 0x55fb1cb0208e in setup_mon_inventory /home/erik/Documents/hackem/src/makemon.c:2306
    #6 0x55fb1cb0ff03 in makemon /home/erik/Documents/hackem/src/makemon.c:3582
    #7 0x55fb1d116aa4 in create_monster /home/erik/Documents/hackem/src/sp_lev.c:1727
    #8 0x55fb1d124fbd in spo_monster /home/erik/Documents/hackem/src/sp_lev.c:3286
    #9 0x55fb1d13ab40 in sp_level_coder /home/erik/Documents/hackem/src/sp_lev.c:5663
    #10 0x55fb1d13fcf3 in load_special /home/erik/Documents/hackem/src/sp_lev.c:6344
    #11 0x55fb1cd04379 in makemaz /home/erik/Documents/hackem/src/mkmaze.c:1027
    #12 0x55fb1cced18d in makelevel /home/erik/Documents/hackem/src/mklev.c:927
    #13 0x55fb1ccf08a6 in mklev /home/erik/Documents/hackem/src/mklev.c:1382
    #14 0x55fb1c7d72b9 in wiz_makemap /home/erik/Documents/hackem/src/cmd.c:927
    #15 0x55fb1c80af88 in rhack /home/erik/Documents/hackem/src/cmd.c:5771
    #16 0x55fb1c6f9fb0 in moveloop /home/erik/Documents/hackem/src/allmain.c:870
    #17 0x55fb1d3ebf0c in main ../sys/unix/unixmain.c:353
    #18 0x7fd7dbe01d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
```

**Comment by elunna** [comment]
I think this is the solution:

```
diff --git a/src/makemon.c b/src/makemon.c
index 37f5b24f3..84a892a06 100644
--- a/src/makemon.c
+++ b/src/makemon.c
@@ -4308,7 +4308,8 @@ int otyp;
             otmp = (struct obj *) 0;
         }
         return spe;
-    }
+    } else
+        otmp = (struct obj *) 0; /* obj wasn't able to get created? */
     return 0;
 }

```

**Comment by elunna** [comment]
Or this?
```
else {
            obj_extract_self(otmp);
            obfree(otmp, (struct obj *) 0);
        }
```
