### ISSUE TITLE
Farlook info repeats for multiple uses

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#361]
Reported by Umbire.

When farlooking via / and I select a monster, then I move to myself or a corridor, it prompts for more info about the last monster I farlooked that way.

**Comment by elunna** [comment]
Do we have this same issue in Evilhack?

**Comment by elunna** [comment]
To reproduce:
1. Farlook (/)
2. Press / again
3. Select a monster, press .
More info about "warg"? [yn] (n)  
4. Press n
5. Select an object. Notice that it still asks more info about warg, not the object.

**Comment by elunna** [comment]
**Backtrace from "More info" prompt:**

```
#0  0x00007ffff7450992 in __GI___libc_read (fd=0, buf=0x619000000f80, nbytes=1024) at ../sysdeps/unix/sysv/linux/read.c:26
#1  0x00007ffff73c8cb6 in _IO_new_file_underflow (fp=0x7ffff7555aa0 <_IO_2_1_stdin_>) at ./libio/libioP.h:947
#2  0x00007ffff73c9e16 in __GI__IO_default_uflow (fp=0x7ffff7555aa0 <_IO_2_1_stdin_>) at ./libio/libioP.h:947
#3  0x00005555564b4e5f in tty_nhgetch () at ../win/tty/wintty.c:3546
#4  0x00005555564b5101 in tty_nh_poskey (x=0x7fffffffcba0, y=0x7fffffffcbb0, mod=0x7fffffffcbc0) at ../win/tty/wintty.c:3604
#5  0x00005555558a7717 in readchar () at cmd.c:6849
#6  0x000055555649e20d in tty_yn_function (query=0x7fffffffd290 "More info about \"hell hound pup\"?", resp=0x55555653b800 <ynchars> "yn", 
    def=110 'n') at ../win/tty/topl.c:430
#7  0x00005555558a8dd5 in yn_function (query=0x7fffffffd290 "More info about \"hell hound pup\"?", resp=0x55555653b800 <ynchars> "yn", def=110 'n')
    at cmd.c:7042
#8  0x0000555555fce62d in checkfile (obj=0x0, inp=0x7fffffffdea0 "a bugle", pm=0x5555566fba20 <mons+6656>, user_typed_name=0 '\000', 
    without_asking=0 '\000', supplemental_name=0x7fffffffdfe0 "") at pager.c:2118
#9  0x0000555555fd3d3d in do_look (mode=0, click_cc=0x0) at pager.c:2787
#10 0x0000555555fd5dbb in dowhatis () at pager.c:2982
#11 0x000055555589be99 in rhack (cmd=0x5555568c5060 <in_line> "/") at cmd.c:5755
#12 0x000055555578cf41 in moveloop (resuming=0 '\000') at allmain.c:871
#13 0x0000555556490528 in main (argc=0, argv=0x7fffffffe4a8) at ../sys/unix/unixmain.c:353

```
