### ISSUE TITLE
Found with fuzzer: get_mplname global-buffer-overflow

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#38]
```
=================================================================
==8227==ERROR: AddressSanitizer: global-buffer-overflow on address 0x5555566ef0f8 at pc 0x555555e612b6 bp 0x7fffffffd3f0 sp 0x7fffffffd3e0
READ of size 8 at 0x5555566ef0f8 thread T0
    #0 0x555555e612b5 in get_mplname /home/lunatunez/hackem/src/mplayer.c:207
    #1 0x555555e631b6 in init_mplayer_erac /home/lunatunez/hackem/src/mplayer.c:410
    #2 0x555555b587e3 in makemon /home/lunatunez/hackem/src/makemon.c:3184
    #3 0x55555613f97f in create_monster /home/lunatunez/hackem/src/sp_lev.c:1720
    #4 0x55555614dd56 in spo_monster /home/lunatunez/hackem/src/sp_lev.c:3283
    #5 0x555556163b66 in sp_level_coder /home/lunatunez/hackem/src/sp_lev.c:5657
    #6 0x555556168b9f in load_special /home/lunatunez/hackem/src/sp_lev.c:6335
    #7 0x555555d3f2cb in makemaz /home/lunatunez/hackem/src/mkmaze.c:1017
    #8 0x555555d28b9e in makelevel /home/lunatunez/hackem/src/mklev.c:818
    #9 0x555555d2c1d5 in mklev /home/lunatunez/hackem/src/mklev.c:1255
    #10 0x555555834eb1 in wiz_makemap /home/lunatunez/hackem/src/cmd.c:899
    #11 0x555555866be4 in rhack /home/lunatunez/hackem/src/cmd.c:5531
    #12 0x555555766f6b in moveloop /home/lunatunez/hackem/src/allmain.c:821
    #13 0x5555563ca0e3 in main ../sys/unix/unixmain.c:353
    #14 0x7ffff7365082 in __libc_start_main ../csu/libc-start.c:308
    #15 0x55555575dacd in _start (/home/lunatunez/games/hackemdir/hackem+0x209acd)

0x5555566ef0f8 is located 0 bytes to the right of global variable 'vampiric_male_names' defined in 'mplayer.c:161:20' (0x5555566ef080) of size 120
0x5555566ef0f8 is located 40 bytes to the left of global variable 'vampiric_female_names' defined in 'mplayer.c:167:20' (0x5555566ef120) of size 120
SUMMARY: AddressSanitizer: global-buffer-overflow /home/lunatunez/hackem/src/mplayer.c:207 in get_mplname
Shadow bytes around the buggy address:
  0x0aab2acd5dc0: 00 00 00 00 00 00 00 f9 f9 f9 f9 f9 00 00 00 00
  0x0aab2acd5dd0: 00 00 00 00 00 00 00 f9 f9 f9 f9 f9 00 00 00 00
  0x0aab2acd5de0: 00 00 00 00 00 00 00 f9 f9 f9 f9 f9 00 00 00 00
  0x0aab2acd5df0: 00 00 00 00 00 00 00 00 00 00 f9 f9 f9 f9 f9 f9
  0x0aab2acd5e00: 00 00 00 00 00 00 00 00 00 00 00 00 f9 f9 f9 f9
=>0x0aab2acd5e10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00[f9]
  0x0aab2acd5e20: f9 f9 f9 f9 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aab2acd5e30: 00 00 00 f9 f9 f9 f9 f9 00 00 00 f9 f9 f9 f9 f9
  0x0aab2acd5e40: 00 00 00 f9 f9 f9 f9 f9 00 00 00 00 00 00 00 00
  0x0aab2acd5e50: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0aab2acd5e60: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==8227==ABORTING
```

**Comment by elunna** [comment]
Fixed in commit 22cf88a66 - The new vampiric male and female names were not correctly terminated with a 0, removed a few names and fixed.
