### ISSUE TITLE
invalid material 7 (otyp 214) an uncursed +0 pair of leather dwarvish boots named �992�� (weapon in hand) (9 aum)

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#381]
Found with fuzzer, unfortunately no rr recording available.

```
Suddenly, the dungeon collapses.
invalid material 7 (otyp 214) obj 60c001489d80 invent: an uncursed +0 pair of leather dwarvish boots named �992�� (weapon in hand) (9 aum)
Generating more information you may report:

[0] /lib/x86_64-linux-gnu/libasan.so.6(+0x45c0e) [0x7ffff7603c0e]
[1] /home/user/games/hackemdir/hackem(+0x53397b) [0x555555a8797b]
[2] /home/user/games/hackemdir/hackem(+0x53386b) [0x555555a8786b]
[3] /home/user/games/hackemdir/hackem(panic+0x6c0) [0x555555a8e90a]
[4] /home/user/games/hackemdir/hackem(impossible+0x2d1) [0x555556009ac2]
[5] /home/user/games/hackemdir/hackem(+0x865409) [0x555555db9409]
[6] /home/user/games/hackemdir/hackem(+0x864b3e) [0x555555db8b3e]
[7] /home/user/games/hackemdir/hackem(obj_sanity_check+0x4b9) [0x555555db80df]
[8] /home/user/games/hackemdir/hackem(sanity_check+0xd) [0x5555558986cf]
[9] /home/user/games/hackemdir/hackem(moveloop+0x6f2a) [0x55555578caa8]
[10] /home/user/games/hackemdir/hackem(main+0xe0a) [0x555556490a7a]
[11] /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7ffff7365d90]
[12] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7ffff7365e40]
[13] /home/user/games/hackemdir/hackem(_start+0x25) [0x555555783ac5]

Program received signal SIGABRT, Aborted.

Regular backtrace:
#0  __pthread_kill_implementation (no_tid=0, signo=6, 
    threadid=140737339656128) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737339656128)
    at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737339656128, signo=signo@entry=6)
    at ./nptl/pthread_kill.c:89
#3  0x00007ffff737e476 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/posix/raise.c:26
#4  0x00007ffff73647f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x0000555555a87891 in NH_abort () at end.c:236
#6  0x0000555555a8e90a in panic (str=0x55555660d240 "%s") at end.c:802
#7  0x0000555556009ac2 in impossible (
    s=0x5555565bb4a0 <ofmt0> "%s obj %s %s: %s") at pline.c:685
#8  0x0000555555db9409 in insane_object (obj=0x60c001489d80, 
    fmt=0x5555565bb4a0 <ofmt0> "%s obj %s %s: %s", 
    mesg=0x7fffffffdf20 "invalid material 7 (otyp 214)", mon=0x0)
    at mkobj.c:2924
#9  0x0000555555db8b3e in objlist_sanity (objlist=0x60c001489d80, 
    wheretype=3, mesg=0x5555565bb6a0 "invent sanity") at mkobj.c:2842
#10 0x0000555555db80df in obj_sanity_check () at mkobj.c:2751
#11 0x00005555558986cf in sanity_check () at cmd.c:5073
#12 0x000055555578caa8 in moveloop (resuming=0 '\000') at allmain.c:840
#13 0x0000555556490a7a in main (argc=0, argv=0x7fffffffe4a8)


```

**Comment by elunna** [comment]
Hypothesis: This is an upgrade issue. My first guess is that a pair of iron boots (like kicking boots) were tinkered/downgraded to dwarvish boots, but they retained the material.

**Comment by elunna** [comment]
Confirmed: To reproduce, first turn on sanity_check. Then wish for a pair of speed boots (leather) and a potion of gain level. Dip the speed boots in the gain level and they turn into leather dwarvish boots.
