### ISSUE TITLE
Found with fuzzer: remove_object: obj not on floor

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#382]
Not recorded with rr, so not much else to go on.

moves:
$1 = 4627608

Toplines:
$2 = 0x5555568d11e0 <toplines> "Ye swim underneath the mud elemental."

```
Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7360859 in __GI_abort () at abort.c:79
#2  0x0000555555a8409c in NH_abort () at end.c:236
#3  0x0000555555a8b09a in panic (str=0x5555565ad0a0 "remove_object: obj not on floor")
    at end.c:802
#4  0x0000555555daf401 in remove_object (otmp=0x60c000180100) at mkobj.c:2342
#5  0x00005555558364f3 in move_bc (before=1, control=0, ballx=35 '#', bally=9 '\t', 
    chainx=35 '#', chainy=9 '\t') at ball.c:544
#6  0x000055555583703d in drag_ball (x=35 '#', y=9 '\t', bc_control=0x7fffffffdff0, 
    ballx=0x7fffffffdfc0 "#", bally=0x7fffffffdfd0 "\t", chainx=0x7fffffffdfa0 "#", 
    chainy=0x7fffffffdfb0 "\t", cause_delay=0x7fffffffdfe0 "", allow_drag=1 '\001') at ball.c:615
#7  0x0000555555b0e9b0 in domove_core () at hack.c:2057
#8  0x0000555555af3ed4 in domove () at hack.c:1455
#9  0x0000555555899e65 in rhack (cmd=0x5555568b8e80 <in_line> "7") at cmd.c:5713
#10 0x000055555578cedb in moveloop (resuming=0 '\000') at allmain.c:871
#11 0x0000555556482e79 in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
```

Full backtrace:

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {0, 0, 0, 0, 0, 140737335736048, 93824997670254, 335544320, 
            140737341034640, 1073741824, 0, 140737342781088, 4294967295, 140737337360384, 
            140737342764192, 9541689523200508672}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007ffff7360859 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0xffffffff, sa_sigaction = 0xffffffff}, 
          sa_mask = {__val = {140737337360384, 140737342764192, 9541689523200508672, 
              140737488345568, 140737342781088, 18446744073709547520, 140737327091712, 
              140737345450200, 9, 140737488347840, 140737344319506, 17592186043196, 
              140737488338944, 140737341034640, 9541689523200508672, 140737488345968}}, 
          sa_flags = 997114624, sa_restorer = 0x7fffffffdd30}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x0000555555a8409c in NH_abort () at end.c:236
        gdb_prio = 1
        libc_prio = 2
        aborting = 1 '\001'
#3  0x0000555555a8b09a in panic (str=0x5555565ad0a0 "remove_object: obj not on floor")
    at end.c:802
        the_args = {{gp_offset = 8, fp_offset = 48, overflow_arg_area = 0x7fffffffde00, 
            reg_save_area = 0x7fffffffdd30}}
#4  0x0000555555daf401 in remove_object (otmp=0x60c000180100) at mkobj.c:2342
        x = 35 '#'
        y = 9 '\t'
#5  0x00005555558364f3 in move_bc (before=1, control=0, ballx=35 '#', bally=9 '\t', 
    chainx=35 '#', chainy=9 '\t') at ball.c:544
No locals.
#6  0x000055555583703d in drag_ball (x=35 '#', y=9 '\t', bc_control=0x7fffffffdff0, 
    ballx=0x7fffffffdfc0 "#", bally=0x7fffffffdfd0 "\t", chainx=0x7fffffffdfa0 "#", 
    chainy=0x7fffffffdfb0 "\t", cause_delay=0x7fffffffdfe0 "", allow_drag=1 '\001') at ball.c:615
        t = 0x0
        already_in_rock = 0 '\000'
#7  0x0000555555b0e9b0 in domove_core () at hack.c:2057
        mtmp = 0x611000744cc0
        tmpr = <optimized out>
        x = 35 '#'
        y = 9 '\t'
        trap = 0x0
        wtcap = 0
        recharged = 0 '\000'
        walk_sewage = 0 '\000'
        chainx = 35 '#'
        chainy = 9 '\t'
        ballx = 35 '#'
        bally = 9 '\t'
        bc_control = 0
        cause_delay = 0 '\000'
        u_with_boulder = 0 '\000'
#8  0x0000555555af3ed4 in domove () at hack.c:1455
        ux1 = 35
        uy1 = 9
#9  0x0000555555899e65 in rhack (cmd=0x5555568b8e80 <in_line> "7") at cmd.c:5713
        spkey = 0
        prefix_seen = 0 '\000'
        bad_command = 85 'U'
        firsttime = 1 '\001'
#10 0x000055555578cedb in moveloop (resuming=0 '\000') at allmain.c:871
        pobj = 0x0
        moveamt = 12
        wtcap = 0
        change = 0
        monscanmove = 0 '\000'
        elf_regen = 1 '\001'
        orc_regen = 1 '\001'
        vamp_regen = 1 '\001'
#11 0x0000555556482e79 in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
        fd = -1
        dir = 0x0
        exact_username = 0 '\000'
        resuming = 0 '\000'
        plsel_once = 1 '\001'

```

**Comment by elunna** [comment]
Reproduced:

- Went to the pirate quest home (lots of open water).
- Punished myself with a scroll of punishment, then rustproofed the ball.
- Went into the water and created a mud elemental.
- Got engulfed by the mud elemental, then tried attacking. But it tried to swim underneath while engulfed.
