### ISSUE TITLE
Memory leaks in pirate sacrifices

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#391]
```
=================================================================
==18886==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 14336 byte(s) in 112 object(s) allocated from:
    #0 0x7f01023a3808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x55c9409b48ad in alloc /home/lunatunez/hackem/src/alloc.c:46
    #2 0x55c940fc1596 in mksobj /home/lunatunez/hackem/src/mkobj.c:844
    #3 0x55c940a0f5ff in mk_artifact /home/lunatunez/hackem/src/artifact.c:290
    #4 0x55c9412a3ae9 in dosacrifice /home/lunatunez/hackem/src/pray.c:2330
    #5 0x55c940a850b2 in doextcmd /home/lunatunez/hackem/src/cmd.c:372
    #6 0x55c940abbc2f in rhack /home/lunatunez/hackem/src/cmd.c:5771
    #7 0x55c9409b0ec5 in moveloop /home/lunatunez/hackem/src/allmain.c:866
    #8 0x55c941695120 in main ../sys/unix/unixmain.c:353
    #9 0x7f010206f082 in __libc_start_main ../csu/libc-start.c:308

Indirect leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x7f01023a3808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x55c9409b48ad in alloc /home/user/hackem/src/alloc.c:46
    #2 0x55c940fc1596 in mksobj /home/user/hackem/src/mkobj.c:844
    #3 0x55c940fbd415 in mkobj /home/user/hackem/src/mkobj.c:288
    #4 0x55c940fbdb0f in mkbox_cnts /home/user/hackem/src/mkobj.c:358
    #5 0x55c940fc3cd8 in mksobj /home/user/hackem/src/mkobj.c:1042
    #6 0x55c940a0f5ff in mk_artifact /home/user/hackem/src/artifact.c:290
    #7 0x55c9412a3ae9 in dosacrifice /home/user/hackem/src/pray.c:2330
    #8 0x55c940a850b2 in doextcmd /home/user/hackem/src/cmd.c:372
    #9 0x55c940abbc2f in rhack /home/user/hackem/src/cmd.c:5771
    #10 0x55c9409b0ec5 in moveloop /home/user/hackem/src/allmain.c:866
    #11 0x55c941695120 in main ../sys/unix/unixmain.c:353
    #12 0x7f010206f082 in __libc_start_main ../csu/libc-start.c:308

Indirect leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x7f01023a3808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x55c9409b48ad in alloc /home/user/hackem/src/alloc.c:46
    #2 0x55c940fc1596 in mksobj /home/user/hackem/src/mkobj.c:844
    #3 0x55c940a0f5ff in mk_artifact /home/user/hackem/src/artifact.c:290
    #4 0x55c9412a3ae9 in dosacrifice /home/user/hackem/src/pray.c:2330
    #5 0x55c940a850b2 in doextcmd /home/user/hackem/src/cmd.c:372
    #6 0x55c940abbc2f in rhack /home/user/hackem/src/cmd.c:5771
    #7 0x55c9409b0ec5 in moveloop /home/user/hackem/src/allmain.c:866
    #8 0x55c941695120 in main ../sys/unix/unixmain.c:353
    #9 0x7f010206f082 in __libc_start_main ../csu/libc-start.c:308

SUMMARY: AddressSanitizer: 14592 byte(s) leaked in 114 allocation(s).
```

**Comment by elunna** [comment]
Fixed in 7eb431f2e.
