### ISSUE TITLE
Found with fuzzer: obj_is_local

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#392]
This one was not recorded with rr, so not much to go on here unfortunately. I have never seen this issue pop up before so I'll at least put it up for the records.
```
Suddenly, the dungeon collapses.
obj_is_local
Generating more information you may report:

Program received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737339656128) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737339656128) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737339656128) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737339656128, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff737e476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff73647f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x0000555555a8415b in NH_abort () at end.c:236
#6  0x0000555555a8b1c3 in panic (str=0x55555665e560 "obj_is_local") at end.c:802
#7  0x000055555622a42e in obj_is_local (obj=0x60c00174b200) at timeout.c:2871
#8  0x000055555622a5f3 in timer_is_local (timer=0x60400007f990) at timeout.c:2909
#9  0x000055555622a6b4 in maybe_write_timer (fd=4, range=0, write_it=0 '\000') at timeout.c:2942
#10 0x000055555622a806 in save_timers (fd=4, mode=6, range=0) at timeout.c:2977
#11 0x00005555561105b8 in savelev (fd=4, lev=16 '\020', mode=6) at save.c:601
#12 0x0000555555947f0a in goto_level (newlevel=0x7fffffffe210, at_stairs=0 '\000', falling=0 '\000', portal=1 '\001') at do.c:1887
#13 0x000055555594c249 in deferred_goto () at do.c:2307
#14 0x000055555578cf6b in moveloop (resuming=0 '\000') at allmain.c:869
#15 0x000055555647dddb in main (argc=0, argv=0x7fffffffe4a8) at ../sys/unix/unixmain.c:353

(gdb) p u.umonster
$4 = 750 (PIRATE)

toplines
$5 = "Ye feel dizzy fer a moment, but the sensation passes.", '\000' <repeats 246 times>

```

Maybe an issue with a new timer mechanic? But it could also be one of the standard timers, I would just suspect one of the new ones first...
    BOMB_BLOW,
    SPIRIT_FADE,
    FERMENT,
    FIXTURE_ACTIVATE,

At this step we are able to access the object:
#7  0x000055555622a42e in obj_is_local (obj=0x60c00174b200) at timeout.c:2871
And it's a fire bomb!

```
(gdb) p *obj
$6 = {nobj = 0x0, v = {v_nexthere = 0x0, v_ocontainer = 0x0, v_ocarry = 0x0}, cobj = 0x0, o_id = 1847462, ox = 0 '\000', oy = 0 '\000', otyp = 116, 
  owt = 10, quan = 1, spe = 0 '\000', oclass = 2 '\002', invlet = 0 '\000', oartifact = 0 '\000', altmode = 0 '\000', oprops = 0, oprops_known = 0, 
  where = 0 '\000', timed = 1 '\001', cursed = 0, blessed = 0, unpaid = 0, no_charge = 0, known = 0, dknown = 0, bknown = 0, rknown = 1, oeroded = 0, 
  oeroded2 = 0, oerodeproof = 0, olocked = 0, oticking = 1, obroken = 0, otrapped = 0, recharged = 0, lamplit = 0, globby = 0, greased = 0, 
  nomerge = 0, was_thrown = 0, material = 11, in_use = 0, bypass = 1, cknown = 0, lknown = 0, yours = 0, corpsenm = -1, wep_kills = 0, 
  spestudied = 0, newwarncnt = 0, oeaten = 0, lastwarncnt = 0, age = 3036642, owornmask = 0, oextra = 0x0}

#12 0x0000555555947f0a in goto_level (newlevel=0x7fffffffe210, at_stairs=0 '\000', falling=0 '\000', portal=1 '\001') at do.c:1887
1887	    savelev(fd, ledger_no(&u.uz),
(gdb) p *newlevel
$7 = {dnum = 3 '\003', dlevel = 1 '\001'}  QUEST HOME LEVEL

```

**Comment by elunna** [comment]
Attempts to reproduce:
I tried letting a monster throw a bomb at me (arming it and marking it as theirs), grabbing it and then going through a portal)
