### ISSUE TITLE
unpaid_cost: object wasn't on any bill.

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#394]
No rr recording.

```
Suddenly, the dungeon collapses.
unpaid_cost: object wasn't on any bill.
Generating more information you may report:

[0] /lib/x86_64-linux-gnu/libasan.so.6(+0x45c0e) [0x7ffff7603c0e]
[1] /home/erik/games/hackemdir/hackem(+0x530282) [0x555555a84282]
[2] /home/erik/games/hackemdir/hackem(+0x530172) [0x555555a84172]
[3] /home/erik/games/hackemdir/hackem(panic+0x6c0) [0x555555a8b200]
[4] /home/erik/games/hackemdir/hackem(impossible+0x2d1) [0x555555ff9760]
[5] /home/erik/games/hackemdir/hackem(unpaid_cost+0x289) [0x555556141502]
[6] /home/erik/games/hackemdir/hackem(+0xa1171b) [0x555555f6571b]
[7] /home/erik/games/hackemdir/hackem(doname+0x21) [0x555555f65d65]
[8] /home/erik/games/hackemdir/hackem(+0x5f7852) [0x555555b4b852]
[9] /home/erik/games/hackemdir/hackem(getobj+0x346c) [0x555555b45690]
[10] /home/erik/games/hackemdir/hackem(dothrow+0x2b8) [0x555555a05731]
[11] /home/erik/games/hackemdir/hackem(rhack+0x1b6d) [0x55555589959b]
[12] /home/erik/games/hackemdir/hackem(moveloop+0x73ab) [0x55555578cf29]
[13] /home/erik/games/hackemdir/hackem(main+0xe0a) [0x55555647d893]
[14] /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7ffff7365d90]
[15] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7ffff7365e40]
[16] /home/erik/games/hackemdir/hackem(_start+0x25) [0x555555783ac5]

Program received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737339656128) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737339656128) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737339656128) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737339656128, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff737e476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff73647f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x0000555555a84198 in NH_abort () at end.c:236
#6  0x0000555555a8b200 in panic (str=0x5555565f9fe0 "%s") at end.c:802
#7  0x0000555555ff9760 in impossible (s=0x555556631a40 "unpaid_cost: object wasn't on any bill.") at pline.c:685
#8  0x0000555556141502 in unpaid_cost (unp_obj=0x60c0011ee7c0, include_contents=1 '\001') at shk.c:3052
#9  0x0000555555f6571b in doname_base (obj=0x60c0011ee7c0, doname_flags=0) at objnam.c:1721
#10 0x0000555555f65d65 in doname (obj=0x60c0011ee7c0) at objnam.c:1771
#11 0x0000555555b4b852 in display_pickinv (lets=0x0, xtra_choice=0x0, query=0x7fffffffdc20 "What do you want to throw?", want_reply=1 '\001', 
    out_cnt=0x7fffffffdb60) at invent.c:2968
#12 0x0000555555b45690 in getobj (let=0x55555654efa3 <toss_objs+3> "\002", word=0x55555654f040 "throw") at invent.c:1913
#13 0x0000555555a05731 in dothrow () at dothrow.c:376
#14 0x000055555589959b in rhack (cmd=0x5555568b1b60 <in_line> "t") at cmd.c:5771
#15 0x000055555578cf29 in moveloop (resuming=0 '\000') at allmain.c:866
#16 0x000055555647d893 in main (argc=0, argv=0x7fffffffe4a8) at ../sys/unix/unixmain.c:353

Info:
(gdb) p moves
$1 = 48737279
(gdb) p u.u
There is no member named u.
(gdb) p u.uz
$2 = {dnum = 0 '\000', dlevel = 5 '\005'}
(gdb) p u.umonster
$3 = 735
(gdb) p u.umonnum
$4 = 735
(gdb) p urace.malenum
$5 = 597
(gdb) p toplines
$6 = "What do you want to throw?\000low boots (weapon in hand).", '\000' <repeats 245 times>

```

**Comment by elunna** [comment]
I know I've had this bug pop up once while playing on hardfought in a random shop, no idea how it happened though.

**Comment by elunna** [comment]
Unable to reproduce
