### ISSUE TITLE
leashed monster not on this level

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#395]
```
Suddenly, the dungeon collapses.
leashed monster not on this level
Generating more information you may report:

Program received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140192271050688) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
(rr) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140192271050688) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140192271050688) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140192271050688, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007f810e41a476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007f810e4007f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x000055c24bee4198 in NH_abort () at end.c:236
#6  0x000055c24beeb200 in panic (str=0x55c24ca59fe0 "%s") at end.c:802
#7  0x000055c24c459760 in impossible (s=0x55c24ca28840 "leashed monster not on this level") at pline.c:685
#8  0x000055c24c3c2f67 in doname_base (obj=0x60c000edf340, doname_flags=0) at objnam.c:1538
#9  0x000055c24c3c5d65 in doname (obj=0x60c000edf340) at objnam.c:1771
#10 0x000055c24bfa9b48 in xprname (obj=0x60c000edf340, txt=0x0, let=100 'd', dot=1 '\001', cost=0, quan=0) at invent.c:2684
#11 0x000055c24bfa9819 in prinv (prefix=0x55c24c9e0720 "", obj=0x60c000edf340, quan=0) at invent.c:2642
#12 0x000055c24c4bed6f in dodip () at potion.c:3490
#13 0x000055c24bcc2053 in doextcmd () at cmd.c:372
#14 0x000055c24bcf959b in rhack (cmd=0x55c24cd11b60 <in_line> "#") at cmd.c:5771
#15 0x000055c24bbecf29 in moveloop (resuming=0 '\000') at allmain.c:866
#16 0x000055c24c8dd893 in main (argc=0, argv=0x7ffc7bb2c378) at ../sys/unix/unixmain.c:353


(rr) p moves
$1 = 5800304

(rr) p u.umonster
$2 = 739
(rr) p u.umonnum
$3 = 739

(rr) p urace.malenum
$4 = 114

(rr) p toplines
$5 = "Hmm!  You don't recall dipping that into the potion.", '\000' <repeats 247 times>

(rr) p *obj
$7 = {nobj = 0x60c0008d4000, v = {v_nexthere = 0x0, v_ocontainer = 0x0, v_ocarry = 0x0}, cobj = 0x0, o_id = 3721433, ox = 65 'A', oy = 16 '\020', 
  otyp = 326, owt = 12, quan = 1, spe = 0 '\000', oclass = 6 '\006', invlet = 100 'd', oartifact = 0 '\000', altmode = 0 '\000', oprops = 0, 
  oprops_known = 4095, where = 3 '\003', timed = 0 '\000', cursed = 0, blessed = 0, unpaid = 0, no_charge = 0, known = 1, dknown = 1, bknown = 1, 
  rknown = 1, oeroded = 0, oeroded2 = 0, oerodeproof = 0, olocked = 0, oticking = 0, obroken = 0, otrapped = 0, recharged = 0, lamplit = 0, 
  globby = 0, greased = 0, nomerge = 0, was_thrown = 0, material = 7, in_use = 0, bypass = 0, cknown = 0, lknown = 0, yours = 0, corpsenm = -1, 
  wep_kills = 0, spestudied = 0, newwarncnt = 0, oeaten = 0, lastwarncnt = 0, age = 5799172, owornmask = 0, oextra = 0x60400339de10}

```

Okay, so a leash was upgraded. While a pet was attached to it?

**Comment by elunna** [comment]
Ok - found the cause. A saddle was originally created on the level. When a saddle is created it has a corpsenm of -1. When it is upgraded to a leash, it retains the -1 corpsenm which causes the game to think there is something (anything not 0) attached and the game panics.
