### ISSUE TITLE
calculate_flankers: youflanker and youattack both TRUE!

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#397]
```
Suddenly, the dungeon collapses.
calculate_flankers: youflanker and youattack both TRUE!
Generating more information you may report:


(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7360859 in __GI_abort () at abort.c:79
#2  0x0000555555a81123 in NH_abort () at end.c:236
#3  0x0000555555a88121 in panic (str=0x5555565ee0e0 "%s") at end.c:802
#4  0x0000555555ff187e in impossible (
    s=0x5555565956c0 "calculate_flankers: youflanker and youattack both TRUE!") at pline.c:685
#5  0x0000555555d59e90 in calculate_flankers (magr=0x5555568bb560 <youmonst>,
    mdef=0x6110004dde00) at mhitu.c:5733
#6  0x00005555562acf16 in find_roll_to_hit (mtmp=0x6110004dde00, aatyp=1 '\001', weapon=0x0,
    attk_count=0x7fffffffdaf0, role_roll_penalty=0x7fffffffdad0) at uhitm.c:314
#7  0x0000555556316235 in hmonas (mon=0x6110004dde00, as=-1, weapon_attacks=1 '\001')
    at uhitm.c:4333
#8  0x00005555562b4520 in attack (mtmp=0x6110004dde00) at uhitm.c:615
#9  0x0000555555b08263 in domove_core () at hack.c:1750
#10 0x0000555555af0fe0 in domove () at hack.c:1455
#11 0x00005555558977fd in rhack (cmd=0x5555568a6b80 <in_line> "3") at cmd.c:5733
#12 0x000055555578cec6 in moveloop (resuming=0 '\000') at allmain.c:866
#13 0x0000555556470fd2 in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353


(gdb) p u.uz
$1 = {dnum = 0 '\000', dlevel = 2 '\002'}
(gdb) p u.umonster
$2 = 746 (PM_MONK)
(gdb) p u.umonnum
$3 = 174 (PM_DREAM_THIEF)
(gdb) p urace.malenum
$4 = 430 (PM_GIANT)
(gdb) p moves
$5 = 8149016
(gdb) p u.uswallow
$6 = 0
(gdb) p u.ustuck
$7 = (struct monst *) 0x0

(gdb) p toplines
$8 = 0x5555568beee0 <toplines> "You destroy the steam vortex!"

Some info from the leftover graphics:

Wizard the Dream Thief         St:18/08 Dx:4 Co:15 In:3 Wi:17 Ch:18
Chaotic $:0 HP:33(61) Pw:922(1000) AC:7 MC:0 HD:14
Dlvl:2 6491                                        Fly


    MON("dream thief", S_NYMPH,                               /* SpliceHack */
        LVL(14, 15, 4, 40, 0), (G_NOHELL | 1),
        A(ATTK(AT_CLAW, AD_CURS, 0, 0), 
          /*ATTK(AT_MAGC, AD_PSYC, 5, 5),*/
          ATTK(AT_MAGC, AD_CLRC, 5, 5),
          ATTK(AT_CLAW, AD_SITM, 0, 0), 
          /* ATTK(AT_TUCH, AD_MEMR, 0, 0), */
          ATTK(AT_CLAW, AD_SITM, 0, 0), 
          NO_ATTK, NO_ATTK),
        SIZ(600, 300, MS_SEDUCE, MZ_HUMAN), 0, 0,
        M1_HUMANOID | M1_TPORT | M1_FLY,
        M2_HOSTILE | M2_MALE | M2_COLLECT, M3_INFRAVISIBLE, 
        0, 0, 25, CLR_BRIGHT_GREEN),

The dream thief might run into problems with their second steal attack...
```

**Comment by elunna** [comment]
Able to reproduce:
Poly into a dream thief. Unwield any weapons.
Become engulfed by a steam vortex.
Try to kill it from the inside with your magic attack. The rest of the dream thiefs attacks continue triggering this weird error.

I'm not sure why it occurs but I think the fix is to move the magic attack to the end of the attack chain.
