### ISSUE TITLE
map mon (61100008e340) at <1,0> not in fmon list!

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#398]
```
Suddenly, the dungeon collapses.
map mon (61100008e340) at <1,0> not in fmon list!
Generating more information you may report:


(rr) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=139673425000384) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=139673425000384) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=139673425000384, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007f08409e8476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007f08409ce7f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x0000560f194bb4dc in NH_abort () at end.c:236
#6  0x0000560f194c2544 in panic (str=0x560f1a031fe0 "%s") at end.c:802
#7  0x0000560f19a30afe in impossible (s=0x560f19fe3400 "map mon (%s) at <%d,%d> not in fmon list!") at pline.c:685
#8  0x0000560f197fadc9 in mon_sanity_check () at mon.c:178
#9  0x0000560f192ccc9f in sanity_check () at cmd.c:5091
#10 0x0000560f191c3a90 in moveloop (resuming=0 '\000') at allmain.c:835
#11 0x0000560f19eb4cd8 in main (argc=0, argv=0x7ffd414687c8) at ../sys/unix/unixmain.c:353


(rr) p moves
$1 = 591711
(rr) p u.uz
$2 = {dnum = 0 '\000', dlevel = 4 '\004'}
(rr) p u.umonster
$3 = 756
(rr) p u.umonnum
$4 = 756
(rr) p urace.malenum
$5 = 116

$6 = {nmon = 0x611000185140, data = 0x560f1a12ccb8 <mons+56472>, m_id = 556439, mnum = 543, cham = -1, movement = 0, m_lev = 15 '\017', 
  malign = 5 '\005', mx = 1 '\001', my = 0 '\000', mux = 17 '\021', muy = 12 '\f', mtrack = {{x = 0 '\000', y = 0 '\000'}, {x = 1 '\001', 
      y = 0 '\000'}, {x = 0 '\000', y = 0 '\000'}, {x = 12 '\f', y = 5 '\005'}}, mhp = 67, mhpmax = 67, mappearance = 0, rider_id = 0, 
  m_ap_type = 0 '\000', mtame = 0 '\000', mintrinsics = 0, mextrinsics = 0, mspec_used = 0, seen_resistance = 0, female = 0, minvis = 0, 
  invis_blkd = 0, perminvis = 0, mcan = 0, mburied = 0, mundetected = 0, mcansee = 1, mspeed = 0, permspeed = 0, mrevived = 0, mcloned = 0, 
  mavenge = 0, mflee = 0, mfleetim = 0, msleeping = 0, mblinded = 0, mstun = 0, mfrozen = 0, mcanmove = 1, mconf = 0, mreflect = 0, msick = 0, 
  msickbyu = 0, mdiseased = 0, mdiseabyu = 0, mpeaceful = 0, mtrapped = 0, mleashed = 0, uexp = 0, mtraitor = 0, isshk = 0, isminion = 0, isgd = 0, 
  ispriest = 0, isqldr = 0, iscerberus = 0, isvecna = 0, isgrund = 0, iswiz = 0, wormno = 0, mwither_from_u = 0, mstonebyu = 0, mstone = 0, 
  mberserk = 0, mwither = 0 '\000', vuln_fire = 0 '\000', vuln_cold = 0 '\000', vuln_elec = 0 '\000', vuln_acid = 0 '\000', mstrategy = 0, 
  mtrapseen = 0, mlstmv = 591708, mspare1 = 13, minvent = 0x0, mw = 0x0, misc_worn_check = 0, weapon_check = 0 '\000', meating = 0, msummoned = 0, 
  msicktime = 0, mdiseasetime = 0, mreflecttime = 0, mprotection = 0 '\000', mprottime = 0 '\000', former_rank = {lev = 0, mnum = -1, 
    female = 0 '\000'}, mextra = 0x0}

    543 = PM_BANSHEE
    
(rr) p toplines
$7 = "Undead creatures are called forth from the grave!  enexto(\"revenant\",17,12) failed  You survived that attempt on your life.", '\000' <repeats 176 times>


Probably this:
    case MGC_CALL_UNDEAD:
        mm.x = u.ux;   
        mm.y = u.uy;   
        pline("Undead creatures are called forth from the grave!");   
        mkundead(&mm, FALSE, NO_MINVENT);   
        dmg = 0;   
        break;   
        
        

```

**Comment by elunna** [comment]
```

#define MIGR_WITH_HERO 9    /* mon: followers; obj: trap door */


rr) watch -l mtmp->mspare1

(rr) p moves
$8 = 591708

    Old value = 13
    New value = 9
    0x0000560f19875287 in migrate_mon (mtmp=0x61100008e340, target_lev=4 '\004', xyloc=1 '\001') at mon.c:4766
    4766	    mtmp->mstate |= MON_MIGRATING;


(rr) bt
#0  0x0000560f19875287 in migrate_mon (mtmp=0x61100008e340, target_lev=4 '\004', xyloc=1 '\001') at mon.c:4766
    This is the banshee
#1  0x0000560f198751fa in m_into_limbo (mtmp=0x61100008e340) at mon.c:4755
#2  0x0000560f1987c828 in deal_with_overcrowding (mtmp=0x61100008e340) at mon.c:4901
#3  0x0000560f1987d211 in mnearto (mtmp=0x611000117000, x=12 '\f', y=6 '\006', move_other=1 '\001') at mon.c:4975
    This is fuckin... PM_DISPATER	682
#4  0x0000560f19dd3678 in tactics (mtmp=0x611000117000) at wizard.c:571
#5  0x0000560f198c6c15 in dochug (mtmp=0x611000117000) at monmove.c:704
#6  0x0000560f198ba1dc in dochugw (mtmp=0x611000117000) at monmove.c:176
#7  0x0000560f1982a44d in movemon () at mon.c:1620
#8  0x0000560f191bd22c in moveloop (resuming=0 '\000') at allmain.c:247
#9  0x0000560f19eb4cd8 in main (argc=0, argv=0x7ffd414687c8) at ../sys/unix/unixmain.c:353
(rr) p *mtmp
```

**Comment by elunna** [comment]
Stale issue
