### ISSUE TITLE
Found with fuzzer: (has_mname(mtmp)) ? (SUPPRESS_SADDLE | SUPPRESS_BARDING) : 0, FALSE);

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#40]
```

Program received signal SIGSEGV, Segmentation fault.
0x000055555593f38c in mon_nam (mtmp=0x0) at do_name.c:1947
1947	                    (has_mname(mtmp)) ? (SUPPRESS_SADDLE | SUPPRESS_BARDING) : 0, FALSE);
#0  0x000055555593f38c in mon_nam (mtmp=0x0) at do_name.c:1947
#1  0x000055555593f4ba in Monnam (mtmp=0x0) at do_name.c:1968
#2  0x00005555562b2741 in explum (mdef=0x0, mattk=0x55555661e180 <mons+8544>) at uhitm.c:3293
#3  0x0000555555ad1c66 in domove_core () at hack.c:1940
#4  0x0000555555aba20c in domove () at hack.c:1530
#5  0x000055555586885f in rhack (cmd=0x5555567c7d40 <in_line> "F7") at cmd.c:5493
#6  0x0000555555767f7b in moveloop (resuming=0 '\000') at allmain.c:823
#7  0x00005555563d6bcb in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
#0  0x000055555593f38c in mon_nam (mtmp=0x0) at do_name.c:1947
No locals.
#1  0x000055555593f4ba in Monnam (mtmp=0x0) at do_name.c:1968
        bp = 0x0
#2  0x00005555562b2741 in explum (mdef=0x0, mattk=0x55555661e180 <mons+8544>) at uhitm.c:3293
        tmp = 5
#3  0x0000555555ad1c66 in domove_core () at hack.c:1940
        attk = 0x55555661e180 <mons+8544>
        boulder = 0x0
        solid = 1 '\001'
        buf = "the wall", '\000' <repeats 176 times>, "\340\270T\367\377\177\000\000\030\354=VUU", '\000' <repeats 57 times>
        explo = 1 '\001'
        glyph = 4783
        mtmp = 0x0
        tmpr = <optimized out>
        x = 71 'G'
        y = 6 '\006'
        trap = 0x0
        wtcap = 0
        recharged = 0 '\000'
        walk_sewage = 0 '\000'
        chainx = 0 '\000'
        chainy = 0 '\000'
        ballx = 0 '\000'
        bally = 0 '\000'
        bc_control = 0
        cause_delay = 0 '\000'
        u_with_boulder = 0 '\000'
#4  0x0000555555aba20c in domove () at hack.c:1530
        ux1 = 72
        uy1 = 5
#5  0x000055555586885f in rhack (cmd=0x5555567c7d40 <in_line> "F7") at cmd.c:5493
        spkey = 6
        prefix_seen = 0 '\000'
        bad_command = 85 'U'
        firsttime = 1 '\001'
#6  0x0000555555767f7b in moveloop (resuming=0 '\000') at allmain.c:823
        moveamt = 13
        wtcap = 0
        change = 0
        monscanmove = 0 '\000'
        timeout_start = 28965
        past_clock = 1198026
        elf_regen = 1 '\001'
        orc_regen = 1 '\001'
        vamp_regen = 1 '\001'
#7  0x00005555563d6bcb in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
        fd = -1
        dir = 0x0
        exact_username = 0 '\000'
        resuming = 0 '\000'
        plsel_once = 1 '\001'
```

**Comment by elunna** [comment]
This one is popping up a lot:
```

Program received signal SIGSEGV, Segmentation fault.
0x000055555594189f in mon_nam (mtmp=0x0) at do_name.c:1947
1947	                    (has_mname(mtmp)) ? (SUPPRESS_SADDLE | SUPPRESS_BARDING) : 0, FALSE);
#0  0x000055555594189f in mon_nam (mtmp=0x0) at do_name.c:1947
#1  0x00005555559419cd in Monnam (mtmp=0x0) at do_name.c:1968
#2  0x00005555562b7ff9 in explum (mdef=0x0, mattk=0x555556625180 <mons+8544>)
    at uhitm.c:3295
#3  0x0000555555ad43c1 in domove_core () at hack.c:1940
#4  0x0000555555abc967 in domove () at hack.c:1530
#5  0x0000555555869cb6 in rhack (cmd=0x5555567cf540 <in_line> "-2") at cmd.c:5499
#6  0x0000555555768f7b in moveloop (resuming=0 '\000') at allmain.c:823
#7  0x00005555563dd1ee in main (argc=0, argv=0x7fffffffe628)
    at ../sys/unix/unixmain.c:353
#0  0x000055555594189f in mon_nam (mtmp=0x0) at do_name.c:1947
No locals.
#1  0x00005555559419cd in Monnam (mtmp=0x0) at do_name.c:1968
        bp = 0x0
#2  0x00005555562b7ff9 in explum (mdef=0x0, mattk=0x555556625180 <mons+8544>)
    at uhitm.c:3295
        tmp = 3
#3  0x0000555555ad43c1 in domove_core () at hack.c:1940
        attk = 0x555556625180 <mons+8544>
        boulder = 0x0
        solid = 0 '\000'
        buf = "thin air", '\000' <repeats 24 times>, "\263\212\265A\000\000\000\000\200\302OVUU\000\000\230O\326UUU", '\000' <repeats 18 times>, "\220\340\377\377\377\177\000\000\000\301OVUU\000\000\000t\027\000\300`", '\000' <repeats 18 times>, "\263\212\265A\000\000\000\000@\307OVUU\000\000\024e\326UUU", '\000' <repeats 121 times>
        explo = 1 '\001'
        glyph = 4803
        mtmp = 0x0
        tmpr = <optimized out>
        x = 33 '!'
        y = 3 '\003'
        trap = 0x0
        wtcap = 0
        recharged = 0 '\000'
        walk_sewage = 0 '\000'
        chainx = 0 '\000'
        chainy = 0 '\000'
        ballx = 0 '\000'
        bally = 0 '\000'
        bc_control = 0
        cause_delay = 0 '\000'
        u_with_boulder = 0 '\000'
#4  0x0000555555abc967 in domove () at hack.c:1530
        ux1 = 33
        uy1 = 4
#5  0x0000555555869cb6 in rhack (cmd=0x5555567cf540 <in_line> "-2") at cmd.c:5499
        spkey = 7
        prefix_seen = 0 '\000'
        bad_command = 52 '4'
        firsttime = 1 '\001'
#6  0x0000555555768f7b in moveloop (resuming=0 '\000') at allmain.c:823
        moveamt = 13
        wtcap = 0
        change = 0
        monscanmove = 0 '\000'
        timeout_start = 27804
        past_clock = 1014556
        elf_regen = 1 '\001'
        orc_regen = 1 '\001'
        vamp_regen = 1 '\001'
#7  0x00005555563dd1ee in main (argc=0, argv=0x7fffffffe628)
    at ../sys/unix/unixmain.c:353
        fd = -1
        dir = 0x0
        exact_username = 0 '\000'
        resuming = 0 '\000'
        plsel_once = 1 '\001'
```
