### ISSUE TITLE
Bad fruit #0?

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#404]
```
Suddenly, the dungeon collapses.
Bad fruit #0?
Generating more information you may report:

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.

(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7360859 in __GI_abort () at abort.c:79
#2  0x0000555555a81140 in NH_abort () at end.c:236
#3  0x0000555555a8813e in panic (str=0x5555565ef240 "%s") at end.c:802
#4  0x0000555555ff15a8 in impossible (s=0x5555565bc6c0 "Bad fruit #%d?") at pline.c:685
#5  0x0000555555f56f07 in xname_flags (obj=0x60c001008940, cxn_flags=0) at objnam.c:894
#6  0x0000555555f53506 in xname (obj=0x60c001008940) at objnam.c:651
#7  0x0000555555f60270 in cxname (obj=0x60c001008940) at objnam.c:1959
#8  0x0000555555f62a1e in aobjnam (otmp=0x60c001008940, verb=0x555556611fc0 "tumbles")
    at objnam.c:2277
#9  0x00005555560e095e in seffect_cloning (sobjp=0x7fffffffdf50) at read.c:3912
#10 0x00005555560c0687 in seffects (sobj=0x60c000ae7c00) at read.c:2144
#11 0x00005555560a84a3 in doread () at read.c:715
#12 0x0000555555897d0c in rhack (cmd=0x5555568a7e60 <in_line> "r") at cmd.c:5771
#13 0x000055555578cec6 in moveloop (resuming=0 '\000') at allmain.c:866
#14 0x00005555564713ae in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353


(gdb) p moves
$1 = 38565969

(gdb) p *otmp
$3 = {nobj = 0x0, v = {v_nexthere = 0x0, v_ocontainer = 0x0, v_ocarry = 0x0}, cobj = 0x0,
  o_id = 24166816, ox = 24 '\030', oy = 10 '\n', otyp = 394, owt = 5, quan = 1, spe = 0 '\000',
  oclass = 7 '\a', invlet = 0 '\000', oartifact = 0 '\000', altmode = 0 '\000', oprops = 0,
  oprops_known = 0, where = 0 '\000', timed = 0 '\000', cursed = 0, blessed = 0, unpaid = 0,
  no_charge = 0, known = 1, dknown = 1, bknown = 0, rknown = 1, oeroded = 0, oeroded2 = 0,
  oerodeproof = 0, olocked = 0, oticking = 0, obroken = 0, otrapped = 0, recharged = 0,
  lamplit = 0, globby = 0, greased = 0, nomerge = 0, was_thrown = 0, material = 3, in_use = 0,
  bypass = 0, cknown = 0, lknown = 0, yours = 0, corpsenm = -1, wep_kills = 0, spestudied = 0,
  newwarncnt = 0, oeaten = 0, lastwarncnt = 0, age = 38565969, owornmask = 0, oextra = 0x0}

So the object being cloned is a slime mold.
#define	SLIME_MOLD	394
```

**Comment by elunna** [comment]
Pretty easy to reproduce. I started up a game with a scroll of cloning and a standard slime mold, cloned it and got the error right away.
