### ISSUE TITLE
heap-buffer-overflow when "play time" is used as realtime option.

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#408]
Triggers when ASAN is used with this option in the .rc file:
OPTIONS=realtime:play time

The wallclock and disabled options appear to be fine.
```
==32238==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200003ac7a at pc 0x7f419dd5916d bp 0x7fffa5b879b0 sp 0x7fffa5b87158
WRITE of size 11 at 0x60200003ac7a thread T0                 -----------
    #0 0x7f419dd5916c in __interceptor_strcpy ../../../../src/libsanitizer/asan/asan_interceptors.cc:431
    #1 0x55cc144c3f70 in bot_via_windowport /home/user/hackem/src/botl.c:862
    #2 0x55cc144c059f in bot /home/user/hackem/src/botl.c:258
    #3 0x55cc145a01cb in flush_screen /home/user/hackem/src/display.c:1728
    #4 0x55cc144085c5 in newgame /home/user/hackem/src/allmain.c:1137
    #5 0x55cc150eb283 in main ../sys/unix/unixmain.c:348
    #6 0x7f419da96082 in __libc_start_main ../csu/libc-start.c:308
    #7 0x55cc143fcacd in _start (/home/user/games/hackemdir/hackem+0x22facd)

0x60200003ac7a is located 0 bytes to the right of 10-byte region [0x60200003ac70,0x60200003ac7a)
allocated by thread T0 here:
    #0 0x7f419ddca808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x55cc144098ad in alloc /home/user/hackem/src/alloc.c:46
    #2 0x55cc144c7a10 in init_blstats /home/user/hackem/src/botl.c:1221
    #3 0x55cc144c6b99 in status_initialize /home/user/hackem/src/botl.c:1143
    #4 0x55cc14407ab0 in display_gamewindows /home/user/hackem/src/allmain.c:1032
    #5 0x55cc150ead8c in main ../sys/unix/unixmain.c:270
    #6 0x7f419da96082 in __libc_start_main ../csu/libc-start.c:308

SUMMARY: AddressSanitizer: heap-buffer-overflow ../../../../src/libsanitizer/asan/asan_interceptors.cc:431 in __interceptor_strcpy
Shadow bytes around the buggy address:
  0x0c047ffff530: fa fa 00 02 fa fa 00 02 fa fa 00 02 fa fa 00 02
  0x0c047ffff540: fa fa 00 02 fa fa 00 02 fa fa 00 02 fa fa 00 02
  0x0c047ffff550: fa fa 00 02 fa fa 00 02 fa fa 00 02 fa fa 00 02
  0x0c047ffff560: fa fa 00 02 fa fa 00 02 fa fa 00 02 fa fa 00 02
  0x0c047ffff570: fa fa 00 02 fa fa 00 02 fa fa 00 02 fa fa 00 02
=>0x0c047ffff580: fa fa 00 02 fa fa 00 02 fa fa 00 02 fa fa 00[02]
  0x0c047ffff590: fa fa 00 02 fa fa 00 02 fa fa 00 00 fa fa 04 fa
  0x0c047ffff5a0: fa fa 00 fa fa fa 07 fa fa fa fd fa fa fa fd fd
  0x0c047ffff5b0: fa fa fd fa fa fa fd fd fa fa fd fa fa fa fd fa
  0x0c047ffff5c0: fa fa fd fa fa fa 04 fa fa fa 04 fa fa fa 00 00
  0x0c047ffff5d0: fa fa fd fa fa fa fd fa fa fa 04 fa fa fa 04 fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==32238==ABORTING
```

**Comment by elunna** [comment]
cbus tested this issue in EvilHack and found that it was also present.
