### ISSUE TITLE
LeakSanitizer: Object lookup

### ISSUE THREAD

**Issue by hatcatter** [elunna/hackem#412]
Repro:
1. Start new game
2. /? whisperfeet
3. #quit

We are most probably missing a de-alloc for the obj we create using get_faux_artifact_obj.

```
==414737==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x7f8139ce1359 in __interceptor_malloc /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x5584ab5d2b7a in alloc /home/aoeu/code/HackEM/src/alloc.c:46
    #2 0x5584abbe143e in mksobj /home/aoeu/code/HackEM/src/mkobj.c:844
    #3 0x5584ab62ce18 in get_faux_artifact_obj /home/aoeu/code/HackEM/src/artifact.c:165
    #4 0x5584abdfb5cb in checkfile /home/aoeu/code/HackEM/src/pager.c:2213
    #5 0x5584abe005ed in do_look /home/aoeu/code/HackEM/src/pager.c:2827
    #6 0x5584abe02e00 in dowhatis /home/aoeu/code/HackEM/src/pager.c:3108
    #7 0x5584ab6da257 in rhack /home/aoeu/code/HackEM/src/cmd.c:5774
    #8 0x5584ab5cf1b7 in moveloop /home/aoeu/code/HackEM/src/allmain.c:866
    #9 0x5584ac2b7431 in main ../sys/unix/unixmain.c:353
    #10 0x7f81399c284f  (/usr/lib/libc.so.6+0x2384f) (BuildId: 2f005a79cd1a8e385972f5a102f16adba414d75e)

SUMMARY: AddressSanitizer: 128 byte(s) leaked in 1 allocation(s).
```

**Comment by elunna** [comment]
Fixed in 9ef038438
