### ISSUE TITLE
hiding under nothing?

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#414]
```
Suddenly, the dungeon collapses.
hiding under nothing?
Generating more information you may report:

#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737339656128) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737339656128) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737339656128, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff737e476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff73647f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x0000555555a84bd7 in NH_abort () at end.c:236
#6  0x0000555555a8bc3f in panic (str=0x5555565fc4c0 "%s") at end.c:802
#7  0x0000555555ffa5a7 in impossible (s=0x55555659b100 "hiding under nothing?") at pline.c:685
#8  0x0000555555cedf6a in mattacku (mtmp=0x611000460540) at mhitu.c:772
#9  0x0000555555e99bd3 in dochug (mtmp=0x611000460540) at monmove.c:1033
#10 0x0000555555e83b76 in dochugw (mtmp=0x611000460540) at monmove.c:176
#11 0x0000555555df3cf0 in movemon () at mon.c:1620
#12 0x000055555578622c in moveloop (resuming=0 '\000') at allmain.c:247
#13 0x000055555647f50a in main (argc=0, argv=0x7fffffffe4a8) at ../sys/unix/unixmain.c:353
(gdb) up
#7  0x0000555555ffa5a7 in impossible (s=0x55555659b100 "hiding under nothing?") at pline.c:685
685	        panic("%s", pbuf);
(gdb) 
#8  0x0000555555cedf6a in mattacku (mtmp=0x611000460540) at mhitu.c:772
772	                    impossible("hiding under nothing?");

(gdb) p youmonst
$10 = {nmon = 0x0, data = 0x5555566ef820 <mons+26624>, m_id = 0, mnum = 256, cham = 0, movement = 18, m_lev = 0 '\000', malign = 0 '\000',   mx = 0 '\000', my = 0 '\000', mux = 44 ',', muy = 7 '\a', mtrack = {{x = 0 '\000', y = 0 '\000'}, {x = 0 '\000', y = 0 '\000'}, {x = 0 '\000',       y = 0 '\000'}, {x = 0 '\000', y = 0 '\000'}}, mhp = 0, mhpmax = 0, mappearance = 0, rider_id = 0, m_ap_type = 0 '\000', mtame = 0 '\000',   mintrinsics = 0, mextrinsics = 0, mspec_used = 0, seen_resistance = 0, female = 0, minvis = 0, invis_blkd = 0, perminvis = 0, mcan = 0,   mburied = 0, mundetected = 0, mcansee = 0, mspeed = 0, permspeed = 0, mrevived = 0, mcloned = 0, mavenge = 0, mflee = 0, mfleetim = 0,   msleeping = 0, mblinded = 0, mstun = 0, mfrozen = 0, mcanmove = 0, mconf = 0, mreflect = 0, msick = 0, msickbyu = 0, mdiseased = 0, mdiseabyu = 0,   mpeaceful = 0, mtrapped = 0, mleashed = 0, uexp = 0, mtraitor = 0, isshk = 0, isminion = 0, isgd = 0, ispriest = 0, isqldr = 0, iscerberus = 0,   isvecna = 0, isgrund = 0, iswiz = 0, wormno = 0, mwither_from_u = 0, mstonebyu = 0, mstone = 0, mberserk = 0, mwither = 0 '\000',   vuln_fire = 0 '\000', vuln_cold = 0 '\000', vuln_elec = 0 '\000', vuln_acid = 0 '\000', mstrategy = 0, mtrapseen = 0, mlstmv = 0, mspare1 = 0,   minvent = 0x0, mw = 0x0, misc_worn_check = 0, weapon_check = 0 '\000', meating = 0, msummoned = 0, msicktime = 0, mdiseasetime = 0,   mreflecttime = 0, mprotection = 0 '\000', mprottime = 0 '\000', former_rank = {lev = 0, mnum = 0, female = 0 '\000'}, mextra = 0x0}

(gdb) p u.uundetected
$11 = 0

(gdb) p *mtmp
$1 = {nmon = 0x0, data = 0x5555566fb5d8 <mons+75192>, m_id = 641407, mnum = 723, cham = -1, movement = 0, m_lev = 12 '\f', malign = 0 '\000',   mx = 70 'F', my = 4 '\004', mux = 70 'F', muy = 5 '\005', mtrack = {{x = 0 '\000', y = 0 '\000'}, {x = 0 '\000', y = 0 '\000'}, {x = 0 '\000',       y = 0 '\000'}, {x = 0 '\000', y = 0 '\000'}}, mhp = 52, mhpmax = 52, mappearance = 0, rider_id = 0, m_ap_type = 0 '\000', mtame = 0 '\000',   mintrinsics = 0, mextrinsics = 0, mspec_used = 0, seen_resistance = 0, female = 1, minvis = 0, invis_blkd = 0, perminvis = 0, mcan = 0,   mburied = 0, mundetected = 0, mcansee = 1, mspeed = 0, permspeed = 0, mrevived = 0, mcloned = 0, mavenge = 1, mflee = 0, mfleetim = 0,   msleeping = 0, mblinded = 0, mstun = 0, mfrozen = 0, mcanmove = 1, mconf = 0, mreflect = 0, msick = 0, msickbyu = 0, mdiseased = 0, mdiseabyu = 0,   mpeaceful = 0, mtrapped = 0, mleashed = 0, uexp = 0, mtraitor = 0, isshk = 0, isminion = 0, isgd = 0, ispriest = 0, isqldr = 0, iscerberus = 0,   isvecna = 0, isgrund = 0, iswiz = 0, wormno = 0, mwither_from_u = 0, mstonebyu = 0, mstone = 0, mberserk = 0, mwither = 0 '\000',   vuln_fire = 0 '\000', vuln_cold = 0 '\000', vuln_elec = 0 '\000', vuln_acid = 0 '\000', mstrategy = 0, mtrapseen = 0, mlstmv = 0, mspare1 = 0,   minvent = 0x0, mw = 0x0, misc_worn_check = 0, weapon_check = 0 '\000', meating = 0, msummoned = 0, msicktime = 0, mdiseasetime = 0,   mreflecttime = 0, mprotection = 0 '\000', mprottime = 0 '\000', former_rank = {lev = 0, mnum = -1, female = 0 '\000'}, mextra = 0x0}

```
This monster (the one attacking us) is a PM_KOMODO_DRAGON.
mundetected = 0, so it's not hiding?
Monster is at (70, 4)

```
(gdb) p level.locations[70][4].typ
$8 = 25 '\031' (just plain FLOOR)

(gdb) p toplines
$2 = "You see a giant centipede hatch.", '\000' <repeats 267 times>

(gdb) p moves
$3 = 896073

(gdb) p u.uz
$4 = {dnum = 0 '\000', dlevel = 13 '\r'}

(gdb) p u.umonster
$5 = 746 (PM_MONK)

(gdb) p u.umonnum
$6 = 256 (PM_GIANT_CENTIPEDE)

(gdb) p urace.malenum
$7 = 116 (PM_DWARF)


```

Best guess is that we were hiding under a centipede egg and it hatched, with the monster still appearing as hidden. No rr recording with this one though.

**Comment by mobi-leuser** [comment]
Unlikely it has anything to do with the issue, but is it intended that komodo dragons teleport around?

**Comment by elunna** [comment]
Reproduced: Polymorphed into a giant centipede, layed an egg and I automatically hid under the egg. Waited. When the egg hatches, we are still hidden. Error triggers when a monster tries to attack us.
