### ISSUE TITLE
Found with fuzzer: invalid material 6...a cursed kitten corpse (weapon in hand)

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#43]
```
invalid material 6 (otyp 337) obj 60c000846640 invent: a cursed kitten corpse (weapon in hand)
Generating more information you may report:

[0] /lib/x86_64-linux-gnu/libasan.so.5(+0x6cd40) [0x7ffff75f8d40]
[1] /home/lunatunez/games/hackemdir/hackem(+0x4f95c6) [0x555555a4d5c6]
[2] /home/lunatunez/games/hackemdir/hackem(+0x4f94b9) [0x555555a4d4b9]
[3] /home/lunatunez/games/hackemdir/hackem(panic+0x6ab) [0x555555a542db]
[4] /home/lunatunez/games/hackemdir/hackem(impossible+0x2c8) [0x555555fac033]
[5] /home/lunatunez/games/hackemdir/hackem(+0x80f7ed) [0x555555d637ed]
[6] /home/lunatunez/games/hackemdir/hackem(+0x80ef31) [0x555555d62f31]
[7] /home/lunatunez/games/hackemdir/hackem(obj_sanity_check+0x4b9) [0x555555d6255a]
[8] /home/lunatunez/games/hackemdir/hackem(sanity_check+0xd) [0x555555865440]
[9] /home/lunatunez/games/hackemdir/hackem(moveloop+0x6ebc) [0x555555767ae2]
[10] /home/lunatunez/games/hackemdir/hackem(main+0xdda) [0x5555563d7c54]
[11] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7ffff7365083]
[12] /home/lunatunez/games/hackemdir/hackem(_start+0x2e) [0x55555575eace]


Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7363859 in __GI_abort () at abort.c:79
#2  0x0000555555a4d4df in NH_abort () at end.c:236
#3  0x0000555555a542db in panic (str=0x5555565429e0 "%s") at end.c:802
#4  0x0000555555fac033 in impossible (s=0x5555564f6b60 <ofmt0> "%s obj %s %s: %s")
    at pline.c:518
#5  0x0000555555d637ed in insane_object (obj=0x60c000846640, 
    fmt=0x5555564f6b60 <ofmt0> "%s obj %s %s: %s", 
    mesg=0x7fffffffe0c0 "invalid material 6 (otyp 337)", mon=0x0) at mkobj.c:2796
#6  0x0000555555d62f31 in objlist_sanity (objlist=0x60c0008443c0, wheretype=3, 
    mesg=0x5555564f6d60 "invent sanity") at mkobj.c:2714
#7  0x0000555555d6255a in obj_sanity_check () at mkobj.c:2628
#8  0x0000555555865440 in sanity_check () at cmd.c:4856
#9  0x0000555555767ae2 in moveloop (resuming=0 '\000') at allmain.c:792
#10 0x00005555563d7c54 in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {0, 0, 0, 0, 0, 140737335783280, 93824997446065, 335544320, 
            140737341046928, 1073741824, 0, 140737342793376, 4294967295, 140737337360384, 
            140737342776480, 10974449342653729536}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007ffff7363859 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0xffffffff, sa_sigaction = 0xffffffff}, 
          sa_mask = {__val = {140737337360384, 140737342776480, 10974449342653729536, 
              140737488343808, 140737342793376, 18446744073709547520, 140737327104000, 
              140737345462488, 140737488344880, 140737488344880, 140737344331794, 
              17592186042976, 140737488338944, 140737341046928, 10974449342653729536, 
              140737488344208}}, sa_flags = 845482752, sa_restorer = 0x7fffffffd650}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x0000555555a4d4df in NH_abort () at end.c:236
        gdb_prio = 1
        libc_prio = 2
        aborting = 1 '\001'
#3  0x0000555555a542db in panic (str=0x5555565429e0 "%s") at end.c:802
        the_args = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7fffffffd720, 
            reg_save_area = 0x7fffffffd650}}
#4  0x0000555555fac033 in impossible (s=0x5555564f6b60 <ofmt0> "%s obj %s %s: %s")
    at pline.c:518
        pbuf = "invalid material 6 (otyp 337) obj 60c000846640 invent: a cursed kitten corpse (weapon in hand)\000\000\340\332\377\377\377\177\000\000߫b\367\377\177", '\000' <repeats 11 times>, "\ve2\210\023M\230(\000\000\000\060\000\000\000\360\330\377\377\377\177\000\000\060\330\377\377\377\177\000\000\000\ve2\210\023M\230d\000\000\000\000\000\000\000e\246b\367i\177\000\000\200\330\377\377\377\177\000\000\000\ve2\210\023M\230\340vBVUU\000\000@"...
        the_args = {{gp_offset = 40, fp_offset = 48, overflow_arg_area = 0x7fffffffde10, 
            reg_save_area = 0x7fffffffdd30}}
#5  0x0000555555d637ed in insane_object (obj=0x60c000846640, 
    fmt=0x5555564f6b60 <ofmt0> "%s obj %s %s: %s", 
    mesg=0x7fffffffe0c0 "invalid material 6 (otyp 337)", mon=0x0) at mkobj.c:2796
        objnm = 0x5555567ea080 <obufs+576> "a cursed kitten corpse (weapon in hand)"
        monnm = 0x5555564f7460 "null!"
        altfmt = '\000' <repeats 88 times>, "@f\204\000\300`", '\000' <repeats 11 times>, "\ve2\210\023M\230\000\000\000\000\000\000\000\000\b\374\377\377\377\017\000\000@\340\377\377\377\177\000\000 \342\377\377\377\177\000\000@\340\377\377\377\177\000\000\000\000\000\000\000\000\000\000@\342\377\377\377\177\000\000߫b\367\377\177", '\000' <repeats 18 times>, " \000\000\000\060\000\000\000\020"...
#6  0x0000555555d62f31 in objlist_sanity (objlist=0x60c0008443c0, wheretype=3, 
    mesg=0x5555564f6d60 "invent sanity") at mkobj.c:2714
        matbuf = "invalid material 6 (otyp 337)", '\000' <repeats 226 times>
        maskbuf = '\000' <repeats 39 times>
        bc_ok = 0 '\000'
        obj = 0x60c000846640
#7  0x0000555555d6255a in obj_sanity_check () at mkobj.c:2628
        x = 80
        y = 21
        obj = 0x0
#8  0x0000555555865440 in sanity_check () at cmd.c:4856
No locals.
#9  0x0000555555767ae2 in moveloop (resuming=0 '\000') at allmain.c:792
        moveamt = 12
        wtcap = 0
        change = 0
        monscanmove = 0 '\000'
        timeout_start = 30822
        past_clock = 13862
        elf_regen = 1 '\001'
        orc_regen = 1 '\001'
        vamp_regen = 1 '\001'
#10 0x00005555563d7c54 in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
        fd = -1
        dir = 0x0
        exact_username = 0 '\000'
        resuming = 0 '\000'
        plsel_once = 1 '\001'

```

**Comment by elunna** [comment]
Commit 6ebf38621: warp_material would set a random material if a valid one wasn't found after 200 tries. After 200 tries we now use the base material.
