### ISSUE TITLE
LeakSanitizer: exchange_objects_with_mon 

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#46]
```
==4982==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 32 byte(s) in 2 object(s) allocated from:
    #0 0x7f2c2ac34808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x55c6226772f3 in alloc /home/lunatunez/hackem/src/alloc.c:46
    #2 0x55c62330625c in tty_select_menu ../win/tty/wintty.c:3149
    #3 0x55c622e912aa in query_objlist /home/lunatunez/hackem/src/pickup.c:974
    #4 0x55c622e9b03c in exchange_objects_with_mon /home/lunatunez/hackem/src/pickup.c:2122
    #5 0x55c622e9f6a5 in loot_mon /home/lunatunez/hackem/src/pickup.c:2326
    #6 0x55c622e99ab4 in doloot /home/lunatunez/hackem/src/pickup.c:1986
    #7 0x55c62273f363 in doextcmd /home/lunatunez/hackem/src/cmd.c:370
    #8 0x55c622774d6d in rhack /home/lunatunez/hackem/src/cmd.c:5531
    #9 0x55c622673f7a in moveloop /home/lunatunez/hackem/src/allmain.c:823
    #10 0x55c6232e3c53 in main ../sys/unix/unixmain.c:353
    #11 0x7f2c2a900082 in __libc_start_main ../csu/libc-start.c:308

SUMMARY: AddressSanitizer: 32 byte(s) leaked in 2 allocation(s).
```

**Comment by elunna** [comment]
Fixed in commit 07112ef3b
