### ISSUE TITLE
dmonsfree: 36 removed doesn't match 37 pending on Dlvl:13 

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#479]
```
Suddenly, the dungeon collapses.
dmonsfree: 36 removed doesn't match 37 pending on Dlvl:13 
Generating more information you may report:

[0] /lib/x86_64-linux-gnu/libasan.so.6(+0x45c0e) [0x7f50f01c6c0e]
[1] ./hackemdir/hackem(+0x53feb1) [0x559bff900eb1]
[2] ./hackemdir/hackem(+0x53fda1) [0x559bff900da1]
[3] ./hackemdir/hackem(panic+0x6c0) [0x559bff907f3a]
[4] ./hackemdir/hackem(impossible+0x2d1) [0x559bffe8bd70]
[5] ./hackemdir/hackem(dmonsfree+0x2fe) [0x559bffc98b1c]
[6] ./hackemdir/hackem(+0x317afc) [0x559bff6d8afc]
[7] ./hackemdir/hackem(rhack+0x1b6d) [0x559bff70ced9]
[8] ./hackemdir/hackem(moveloop+0x7479) [0x559bff5feff7]
[9] ./hackemdir/hackem(main+0xe0a) [0x559c0031ecd8]
[10] /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f50efc01d90]
[11] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7f50efc01e40]
[12] ./hackemdir/hackem(_start+0x25) [0x559bff5f5ac5]

Program received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=139985596274624) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
(rr) p moves
$1 = 12755198
(rr) p u.uz
$2 = {dnum = 0 '\000', dlevel = 13 '\r'}
(rr) p u.umonster
$3 = 738
(rr) p u.umonnum
$4 = 738
(rr) p urace.malenum
$5 = 116


rr) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=139985596274624) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=139985596274624) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=139985596274624, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007f50efc1a476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007f50efc007f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x0000559bff900dc7 in NH_abort () at end.c:236
#6  0x0000559bff907f3a in panic (str=0x559c0049cca0 "%s") at end.c:803
#7  0x0000559bffe8bd70 in impossible (s=0x559c0044fce0 "dmonsfree: %d removed doesn't match %d pending on %s") at pline.c:685
#8  0x0000559bffc98b1c in dmonsfree () at mon.c:3152
#9  0x0000559bff6d8afc in wiz_makemap () at cmd.c:918
#10 0x0000559bff70ced9 in rhack (cmd=0x559c0075a640 <in_line> "v") at cmd.c:5780
#11 0x0000559bff5feff7 in moveloop (resuming=0 '\000') at allmain.c:873
#12 0x0000559c0031ecd8 in main (argc=0, argv=0x7ffe32501ef8) at ../sys/unix/unixmain.c:353

```

Watched mongone:

- Found a keystone kop that was removed on turn 12755141, 57 turns earlier.
- this was part of kops_gone, called when a shopkeeper is made happy.
- It looks like wiz_makemap isn't called until the crash.
- Was an extra kop removed?

**Comment by elunna** [comment]
Possibly related to 498dc3f13.
