### ISSUE TITLE
Found with fuzzer: Mon zapping wand of healing with 0 charges

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#5]
```
Suddenly, the dungeon collapses.
Generating more information you may report:

[0] /lib/x86_64-linux-gnu/libasan.so.5(+0x6cd40) [0x7ffff75fad40]
[1] /home/lunatunez/games/hackemdir/hackem(+0x4f0d47) [0x555555a44d47]
[2] /home/lunatunez/games/hackemdir/hackem(+0x4f0c3a) [0x555555a44c3a]
[3] /home/lunatunez/games/hackemdir/hackem(panic+0x6ab) [0x555555a4ba5c]
[4] /home/lunatunez/games/hackemdir/hackem(impossible+0x2c8) [0x555555f98c6e]
[5] /home/lunatunez/games/hackemdir/hackem(+0x92be78) [0x555555e7fe78]
[6] /home/lunatunez/games/hackemdir/hackem(use_defensive+0x10989) [0x555555e9aaf5]
[7] /home/lunatunez/games/hackemdir/hackem(dochug+0x46ea) [0x555555e2ed77]
[8] /home/lunatunez/games/hackemdir/hackem(dochugw+0x2a92) [0x555555e2332b]
[9] /home/lunatunez/games/hackemdir/hackem(movemon+0x1903) [0x555555d92b6a]
[10] /home/lunatunez/games/hackemdir/hackem(moveloop+0x615) [0x55555575b28a]
[11] /home/lunatunez/games/hackemdir/hackem(main+0xdda) [0x5555563b4192]
[12] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7ffff7367083]
[13] /home/lunatunez/games/hackemdir/hackem(_start+0x2e) [0x555555758b0e]

#5  0x0000555555e7fe78 in mzapwand (mtmp=0x611000c68e40, otmp=0x60c001662b80, self=1 '\001')
    at muse.c:221
No locals.
#6  0x0000555555e9aaf5 in use_defensive (mtmp=0x611000c68e40) at muse.c:1389
        i = 0
        fleetim = 16
        how = 0
        otmp = 0x60c001662b80
        vis = 2 '\002'
        vismon = 1 '\001'
        oseen = 1 '\001'
        Mnam = 0x55550000000f <error: Cannot access memory at address 0x55550000000f>
#7  0x0000555555e2ed77 in dochug (mtmp=0x611000c68e40) at monmove.c:645
        mdat = 0x555556600c78 <mons+52312>
        tmp = <optimized out>
        mdummy = 0x0
        inrange = 1
        nearby = 0
        scared = 0
        oldx = 32767
        oldy = 1443412282
        mwalk_sewage = 0 '\000'
```

**Comment by elunna** [comment]
**Possibly fixed:** The defines in muse.c are a bit confusing - they overlap and conflict numbers. I separated the offensive and defensive defines so the offensive ones start at 50 in this commit: 13b558c58
