### ISSUE TITLE
Found with fuzzer: invalid material 6 (otyp 540) obj 60c00007f480 invent: an uncursed wand of fear (0:11) (weapon in hand)

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#52]
```

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7363859 in __GI_abort () at abort.c:79
#2  0x0000555555a4fa53 in NH_abort () at end.c:236
#3  0x0000555555a5684f in panic (str=0x555556547c40 "%s") at end.c:802
#4  0x0000555555fae709 in impossible (s=0x5555564fbdc0 <ofmt0> "%s obj %s %s: %s")
    at pline.c:518
#5  0x0000555555d65e8e in insane_object (obj=0x60c00007f480, 
    fmt=0x5555564fbdc0 <ofmt0> "%s obj %s %s: %s", 
    mesg=0x7fffffffe0c0 "invalid material 6 (otyp 540)", mon=0x0) at mkobj.c:2799
#6  0x0000555555d655d2 in objlist_sanity (objlist=0x60c000085540, wheretype=3, 
    mesg=0x5555564fbfc0 "invent sanity") at mkobj.c:2717
#7  0x0000555555d64bfb in obj_sanity_check () at mkobj.c:2631
#8  0x00005555558668fc in sanity_check () at cmd.c:4855
#9  0x0000555555768ae2 in moveloop (resuming=0 '\000') at allmain.c:792
#10 0x00005555563dcba3 in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {0, 0, 0, 0, 0, 140737335783280, 93824997455653, 335544320, 
            140737341046928, 1073741824, 0, 140737342793376, 4294967295, 140737337360384, 
            140737342776480, 16121303210250395648}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007ffff7363859 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0xffffffff, sa_sigaction = 0xffffffff}, 
          sa_mask = {__val = {140737337360384, 140737342776480, 16121303210250395648, 
              140737488343808, 140737342793376, 18446744073709547520, 140737327104000, 
              140737345462488, 140737488344880, 140737488344880, 140737344331794, 
              17592186042976, 140737488338944, 140737341046928, 16121303210250395648, 
              140737488344208}}, sa_flags = -78192640, sa_restorer = 0x7fffffffd650}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x0000555555a4fa53 in NH_abort () at end.c:236
        gdb_prio = 1
        libc_prio = 2
        aborting = 1 '\001'
#3  0x0000555555a5684f in panic (str=0x555556547c40 "%s") at end.c:802
        the_args = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7fffffffd720, 
            reg_save_area = 0x7fffffffd650}}
#4  0x0000555555fae709 in impossible (s=0x5555564fbdc0 <ofmt0> "%s obj %s %s: %s")
    at pline.c:518
        pbuf = "invalid material 6 (otyp 540) obj 60c00007f480 invent: an uncursed wand of fear (0:11) (weapon in hand)\000\000\340V\373\332_\272\337P\002\000\000p`\000\000\000\340V\373\332_\272\337u\001\000\000p`\000\000\360\340\377\377\377\177\000\000u\001\000\000p`\000\000\020\341\377\377\377\177\000\000d\000\000\000\000\000\000\000e\246b\367\377\177\000\000p\006\000\000\060`\000\000\060\341\377\377\377\177\000\000\300\343\377\377\377\177\000\000"...
        the_args = {{gp_offset = 40, fp_offset = 48, overflow_arg_area = 0x7fffffffde10, 
            reg_save_area = 0x7fffffffdd30}}
#5  0x0000555555d65e8e in insane_object (obj=0x60c00007f480, 
    fmt=0x5555564fbdc0 <ofmt0> "%s obj %s %s: %s", 
    mesg=0x7fffffffe0c0 "invalid material 6 (otyp 540)", mon=0x0) at mkobj.c:2799
        objnm = 0x5555567f0324 <obufs+2116> "an uncursed wand of fear (0:11) (weapon in hand)"
        monnm = 0x5555564fc6c0 "null!"
        altfmt = '\000' <repeats 88 times>, "\200\364\a\000\300`", '\000' <repeats 11 times>, "\340V\373\332_\272\337\000\000\000\000\000\000\000\000\b\374\377\377\377\017\000\000@\340\377\377\377\177\000\000 \342\377\377\377\177\000\000@\340\377\377\377\177\000\000\000\000\000\000\000\000\000\000@\342\377\377\377\177\000\000߫b\367\377\177", '\000' <repeats 18 times>, " \000\000\000\060\000\000\000\020"...
#6  0x0000555555d655d2 in objlist_sanity (objlist=0x60c000085540, wheretype=3, 
    mesg=0x5555564fbfc0 "invent sanity") at mkobj.c:2717
        matbuf = "invalid material 6 (otyp 540)", '\000' <repeats 226 times>
        maskbuf = '\000' <repeats 39 times>
        bc_ok = 0 '\000'
        obj = 0x60c00007f480
#7  0x0000555555d64bfb in obj_sanity_check () at mkobj.c:2631
        x = 80
        y = 21
        obj = 0x0
#8  0x00005555558668fc in sanity_check () at cmd.c:4855
No locals.
#9  0x0000555555768ae2 in moveloop (resuming=0 '\000') at allmain.c:792
        moveamt = 12
        wtcap = 0
        change = 0
        monscanmove = 0 '\000'
        timeout_start = 26531
        past_clock = 931693
        elf_regen = 1 '\001'
        orc_regen = 1 '\001'
        vamp_regen = 1 '\001'
#10 0x00005555563dcba3 in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
        fd = -1
        dir = 0x0
        exact_username = 0 '\000'
        resuming = 0 '\000'
        plsel_once = 1 '\001'
```

**Comment by elunna** [comment]
Duplicate of #43, fixed in Commit 6ebf38621: warp_material would set a random material if a valid one wasn't found after 200 tries. After 200 tries we now use the base material.
