### ISSUE TITLE
Found with fuzzer: __asan::MaybeRealStrnlen with shkhealthfoods nameshk

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#54]
```
Generating more information you may report:
Program received signal SIGSEGV, Segmentation fault.
[0] /lib/x86_64-linux-gnu/libasan.so.5(+0x6cd40) [0x7ffff75f8d40]
[1] /home/lunatunez/games/hackemdir/hackem(+0x4fbb3a) [0x555555a4fb3a]ectory.
[2] /home/lunatunez/games/hackemdir/hackem(+0x4fba2d) [0x555555a4fa2d]
[3] /home/lunatunez/games/hackemdir/hackem(+0x4fb83b) [0x555555a4f83b]
[4] /lib/x86_64-linux-gnu/libc.so.6(+0x43090) [0x7ffff7384090]
[5] /lib/x86_64-linux-gnu/libc.so.6(+0x188891) [0x7ffff74c9891]�
[6] /lib/x86_64-linux-gnu/libasan.so.5(__interceptor_strncpy+0xb0) [0x7ffff76465d0]
[7] /home/lunatunez/games/hackemdir/hackem(+0xbc573b) [0x55555611973b]     ���
[8] /home/lunatunez/games/hackemdir/hackem(+0xbc7578) [0x55555611b578]� ������
[9] /home/lunatunez/games/hackemdir/hackem(stock_room+0x131) [0x55555611c649]�
[10] /home/lunatunez/games/hackemdir/hackem(fill_room+0xd2) [0x555556158f1f]��
[11] /home/lunatunez/games/hackemdir/hackem(+0xbf4727) [0x555556148727]
[12] /home/lunatunez/games/hackemdir/hackem(+0xc246c9) [0x5555561786c9]
[13] /home/lunatunez/games/hackemdir/hackem(load_special+0x245) [0x555556178e15]
[14] /home/lunatunez/games/hackemdir/hackem(makemaz+0x8ff) [0x555555d4a5f0]
[15] /home/lunatunez/games/hackemdir/hackem(+0x7dfe93) [0x555555d33e93]
[16] /home/lunatunez/games/hackemdir/hackem(mklev+0x86) [0x555555d374ca]
[17] /home/lunatunez/games/hackemdir/hackem(goto_level+0x1ae8) [0x555555918f99]
[18] /home/lunatunez/games/hackemdir/hackem(deferred_goto+0x15d) [0x55555591cc86]
[19] /home/lunatunez/games/hackemdir/hackem(level_tele+0x2ad0) [0x5555561bd76e]

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7363859 in __GI_abort () at abort.c:79
#2  0x0000555555a4fa53 in NH_abort () at end.c:236
#3  0x0000555555a4f83b in panictrace_handler (sig_unused=11) at end.c:161
#4  <signal handler called>
#5  __strnlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
#6  0x00007ffff76465d0 in __asan::MaybeRealStrnlen (maxlen=32, s=0x0)
    at ../../../../src/libsanitizer/asan/asan_interceptors.cc:57
#7  __interceptor_strncpy (to=0x622000056c24 "", from=0x0, size=32)
    at ../../../../src/libsanitizer/asan/asan_interceptors.cc:473
#8  0x000055555611973b in nameshk (shk=0x611000383c80, nlp=0x55555661df00 <shkhealthfoods>)
    at shknam.c:722
#9  0x000055555611b578 in shkinit (shp=0x55555661e640 <shtypes+960>, 
    sroom=0x5555567d5538 <rooms+11448>, shp_indx=5) at shknam.c:958
#10 0x000055555611c649 in stock_room (shp_indx=5, sroom=0x5555567d5538 <rooms+11448>)
    at shknam.c:1092
#11 0x0000555556158f1f in fill_room (croom=0x5555567d5538 <rooms+11448>, prefilled=0 '\000')
    at sp_lev.c:2582
#12 0x0000555556148727 in fill_rooms () at sp_lev.c:822
#13 0x00005555561786c9 in sp_level_coder (lvl=0x602001065050) at sp_lev.c:6237
#14 0x0000555556178e15 in load_special (name=0x7fffffffd840 "minetn-7.lev") at sp_lev.c:6335
#15 0x0000555555d4a5f0 in makemaz (s=0x603000000e8a "minetn") at mkmaze.c:1027
#16 0x0000555555d33e93 in makelevel () at mklev.c:818
#17 0x0000555555d374ca in mklev () at mklev.c:1255
#18 0x0000555555918f99 in goto_level (newlevel=0x7fffffffdf10, at_stairs=0 '\000', 
    falling=0 '\000', portal=0 '\000') at do.c:1912
#19 0x000055555591cc86 in deferred_goto () at do.c:2295
#20 0x00005555561bd76e in level_tele () at teleport.c:1380
#21 0x000055555583ce7e in wiz_level_tele () at cmd.c:1104
#22 0x000055555586a1c5 in rhack (cmd=0x5555567cf760 <in_line> "\026") at cmd.c:5537
#23 0x0000555555768f7b in moveloop (resuming=0 '\000') at allmain.c:823
#24 0x00005555563dd216 in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {1024, 0, 0, 0, 0, 140737335783280, 93824997455653, 335544320, 
            140737341046928, 1073741824, 0, 140737342793376, 4294967295, 140737337360384, 
            140737342776480, 13005791830970910976}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007ffff7363859 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0xffffffff, sa_sigaction = 0xffffffff}, 
          sa_mask = {__val = {140737337360384, 140737342776480, 13005791830970910976, 
              140737488338720, 140737342793376, 18446744073709547520, 140737327104000, 
              140737345462488, 0, 107889578830884, 140737344331794, 17592186042340, 
              140737488334848, 140737341046928, 13005791830970910976, 32}}, 
          sa_flags = 1001572608, sa_restorer = 0xf}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x0000555555a4fa53 in NH_abort () at end.c:236
        gdb_prio = 1
        libc_prio = 2
        aborting = 1 '\001'
#3  0x0000555555a4f83b in panictrace_handler (sig_unused=11) at end.c:161
        f2 = 18
#4  <signal handler called>
No locals.
#5  __strnlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
No locals.
#6  0x00007ffff76465d0 in __asan::MaybeRealStrnlen (maxlen=32, s=0x0)
    at ../../../../src/libsanitizer/asan/asan_interceptors.cc:57
No locals.
#7  __interceptor_strncpy (to=0x622000056c24 "", from=0x0, size=32)
    at ../../../../src/libsanitizer/asan/asan_interceptors.cc:473
        from_size = <optimized out>
        ctx = <synthetic pointer>
        _ctx = {interceptor_name = 0x7ffff76e6732 "strncpy"}
#8  0x000055555611973b in nameshk (shk=0x611000383c80, nlp=0x55555661df00 <shkhealthfoods>)
    at shknam.c:722
        i = 21845
        trycnt = 1450553104
        names_avail = 21845
        shname = 0x0
        mtmp = 0x6400383c80
        name_wanted = -12480
        sptr = 0x603000000e80
#9  0x000055555611b578 in shkinit (shp=0x55555661e640 <shtypes+960>, 
    sroom=0x5555567d5538 <rooms+11448>, shp_indx=5) at shknam.c:958
        sh = 39
        sx = 53
        sy = 15
        srace = 423
        shk = 0x611000383c80
        eshkp = 0x622000055900
        shkmoney = 1210
#10 0x000055555611c649 in stock_room (shp_indx=5, sroom=0x5555567d5538 <rooms+11448>)
    at shknam.c:1092
        sx = 34
        sy = 17
        sh = 36
        stockcount = 0
        specialspot = 0
        buf = <optimized out>
        rmno = 56
        shp = 0x55555661e640 <shtypes+960>
#11 0x0000555556158f1f in fill_room (croom=0x5555567d5538 <rooms+11448>, prefilled=0 '\000')
    at sp_lev.c:2582
        x = 1001572608
        y = 0
#12 0x0000555556148727 in fill_rooms () at sp_lev.c:822
        tmpi = 0
        m = 12
#13 0x00005555561786c9 in sp_level_coder (lvl=0x602001065050) at sp_lev.c:6237
        nhFunc = "sp_level_coder"
        exec_opcodes = 560
        tmpi = 10
        room_stack = 0
        max_execution = 65536
        coder = 0x60c00178c600
#14 0x0000555556178e15 in load_special (name=0x7fffffffd840 "minetn-7.lev") at sp_lev.c:6335
        fd = 0x604003d227d0
        lvl = 0x602001065050
        result = 1 '\001'
        vers_info = {incarnation = 524544, feature_set = 393280, entity_count = 1646715712, 
          struct_sizes1 = 5921532624, struct_sizes2 = 163840}
#15 0x0000555555d4a5f0 in makemaz (s=0x603000000e8a "minetn") at mkmaze.c:1027
        x = 0
        y = 21845
        protofile = "minetn-7.lev\000\000\000\000\000\333\377\377"
        sp = 0x603000000e80
        mm = {x = 96 '`', y = -40 '\330'}
#16 0x0000555555d33e93 in makelevel () at mklev.c:818
        slev = 0x603000000e80
        croom = 0x603000000e80
        troom = <optimized out>
        tryct = -9280
        i = -9280
        tmonst = 0x5555564628a0
        branchp = 0x41b58ab3
        room_threshold = -9984
        boxtype = 32767
        pos = {x = -104 '\230', y = 70 'F'}
#17 0x0000555555d374ca in mklev () at mklev.c:1255
        croom = 0x7fffffffdbc0
        ridx = 32767
#18 0x0000555555918f99 in goto_level (newlevel=0x7fffffffdf10, at_stairs=0 '\000', 
    falling=0 '\000', portal=0 '\000') at do.c:1912
        fd = 4
        l_idx = 0
        new_ledger = 72 'H'
        cant_go_back = 0 '\000'
        great_effort = 0 '\000'
        up = 1 '\001'
        newdungeon = 0 '\000'
        was_in_W_tower = 0 '\000'
        familiar = 0 '\000'
        new = 0 '\000'
        mtmp = 0x0
        whynot = '\000' <repeats 255 times>
        annotation = 0x0
        dist = -1
        do_fall_dmg = 0 '\000'
#19 0x000055555591cc86 in deferred_goto () at do.c:2295
        dest = {dnum = 2 '\002', dlevel = 3 '\003'}
        typmask = 64
#20 0x00005555561bd76e in level_tele () at teleport.c:1380
        get_there_from = "get there from %s."
        mtmp = 0x0
        newlev = 5
        newlevel = {dnum = 2 '\002', dlevel = 3 '\003'}
        escape_by_flying = 0x0
        buf = '\000' <repeats 168 times>, "\340\270T\367\377\177\000\000cR>VUU", '\000' <repeats 73 times>
        force_dest = 0 '\000'
#21 0x000055555583ce7e in wiz_level_tele () at cmd.c:1104
No locals.
#22 0x000055555586a1c5 in rhack (cmd=0x5555567cf760 <in_line> "\026") at cmd.c:5537
        tlist = 0x55555668c9f0 <extcmdlist+5136>
        res = -7312
        func = 0x55555583ce2f <wiz_level_tele>
        spkey = 0
        prefix_seen = 0 '\000'
        bad_command = 85 'U'
        firsttime = 1 '\001'
#23 0x0000555555768f7b in moveloop (resuming=0 '\000') at allmain.c:823
        moveamt = 12
        wtcap = 0
        change = 0
        monscanmove = 0 '\000'
        timeout_start = 30793
        past_clock = 959485
        elf_regen = 1 '\001'
        orc_regen = 1 '\001'
        vamp_regen = 1 '\001'
#24 0x00005555563dd216 in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
        fd = -1
        dir = 0x0
        exact_username = 0 '\000'
        resuming = 0 '\000'
        plsel_once = 1 '\001'
```
<img width="960" alt="image" src="https://user-images.githubusercontent.com/5000096/200693538-32734899-de39-41e0-9a64-1faf0de0791b.png">

**Comment by elunna** [comment]
Another hit:
```

Program received signal SIGSEGV, Segmentation fault.
__strnlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
65	../sysdeps/x86_64/multiarch/strlen-avx2.S: No such file or directory.
#0  __strnlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
#1  0x00007ffff76465d0 in __asan::MaybeRealStrnlen (maxlen=32, s=0x0)
    at ../../../../src/libsanitizer/asan/asan_interceptors.cc:57
#2  __interceptor_strncpy (to=0x62200036a424 "", from=0x0, size=32)
    at ../../../../src/libsanitizer/asan/asan_interceptors.cc:473
#3  0x000055555611c4b3 in nameshk (shk=0x611000078540, nlp=0x555556623c60 <shkhealthfoods>)
    at shknam.c:722
#4  0x000055555611e2f0 in shkinit (shp=0x5555566245e0 <shtypes+960>, 
    sroom=0x5555567d95f8 <rooms+1944>, shp_indx=5) at shknam.c:958
#5  0x000055555611f3c1 in stock_room (shp_indx=5, sroom=0x5555567d95f8 <rooms+1944>)
    at shknam.c:1092
#6  0x000055555615bc97 in fill_room (croom=0x5555567d95f8 <rooms+1944>, prefilled=0 '\000')
    at sp_lev.c:2582
#7  0x000055555614b37f in fill_rooms () at sp_lev.c:819
#8  0x000055555617b441 in sp_level_coder (lvl=0x6020011686f0) at sp_lev.c:6237
#9  0x000055555617bb8d in load_special (name=0x7fffffffdcf0 "minetn-11.lev") at sp_lev.c:6337
#10 0x0000555555d4b6bd in makemaz (s=0x603000000eba "minetn") at mkmaze.c:1027
#11 0x0000555555d34f4c in makelevel () at mklev.c:819
#12 0x0000555555d38583 in mklev () at mklev.c:1256
#13 0x0000555555919db3 in goto_level (newlevel=0x7fffffffe3c0, at_stairs=0 '\000', 
    falling=1 '\001', portal=0 '\000') at do.c:1914
#14 0x000055555591d69b in deferred_goto () at do.c:2285
#15 0x0000555555769d1d in moveloop (resuming=0 '\000') at allmain.c:828
#16 0x00005555563e1d6e in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
#0  __strnlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
No locals.
#1  0x00007ffff76465d0 in __asan::MaybeRealStrnlen (maxlen=32, s=0x0)
    at ../../../../src/libsanitizer/asan/asan_interceptors.cc:57
No locals.
#2  __interceptor_strncpy (to=0x62200036a424 "", from=0x0, size=32)
    at ../../../../src/libsanitizer/asan/asan_interceptors.cc:473
        from_size = <optimized out>
        ctx = <synthetic pointer>
        _ctx = {interceptor_name = 0x7ffff76e6732 "strncpy"}
#3  0x000055555611c4b3 in nameshk (shk=0x611000078540, nlp=0x555556623c60 <shkhealthfoods>)
    at shknam.c:722
        i = 21845
        trycnt = 1450578384
        names_avail = 21845
        shname = 0x0
        mtmp = 0x6400078540
        name_wanted = -11280
        sptr = 0x603000000eb0
#4  0x000055555611e2f0 in shkinit (shp=0x5555566245e0 <shtypes+960>, 
    sroom=0x5555567d95f8 <rooms+1944>, shp_indx=5) at shknam.c:958
        sh = 7
        sx = 39
        sy = 7
        srace = 604
        shk = 0x611000078540
        eshkp = 0x622000369100
        shkmoney = 2230
#5  0x000055555611f3c1 in stock_room (shp_indx=5, sroom=0x5555567d95f8 <rooms+1944>)
    at shknam.c:1092
        sx = 36
        sy = 10
        sh = 12
        stockcount = 0
        specialspot = 0
        buf = <optimized out>
        rmno = 12
        shp = 0x5555566245e0 <shtypes+960>
#6  0x000055555615bc97 in fill_room (croom=0x5555567d95f8 <rooms+1944>, prefilled=0 '\000')
    at sp_lev.c:2582
        x = -1052557568
        y = 10
#7  0x000055555614b37f in fill_rooms () at sp_lev.c:819
        tmpi = 9
        m = 0
#8  0x000055555617b441 in sp_level_coder (lvl=0x6020011686f0) at sp_lev.c:6237
        nhFunc = "sp_level_coder"
        exec_opcodes = 472
        tmpi = 10
        room_stack = 0
        max_execution = 65536
        coder = 0x60c001781800
#9  0x000055555617bb8d in load_special (name=0x7fffffffdcf0 "minetn-11.lev") at sp_lev.c:6337
        fd = 0x604004a10b90
        lvl = 0x6020011686f0
        result = 1 '\001'
        vers_info = {incarnation = 524544, feature_set = 393280, entity_count = 1646711616, 
          struct_sizes1 = 5921532624, struct_sizes2 = 163840}
#10 0x0000555555d4b6bd in makemaz (s=0x603000000eba "minetn") at mkmaze.c:1027
        x = 0
        y = -1114625935
        protofile = "minetn-11.lev\000\000\000\260\337\377\377"
        sp = 0x603000000eb0
        mm = {x = 16 '\020', y = -35 '\335'}
#11 0x0000555555d34f4c in makelevel () at mklev.c:819
        slev = 0x603000000eb0
        croom = 0x603000000eb0
        troom = <optimized out>
        tryct = -8080
        i = -8080
        tmonst = 0x555556467960
        branchp = 0x41b58ab3
        room_threshold = -8784
        boxtype = 32767
        pos = {x = 5 '\005', y = 37 '%'}
#12 0x0000555555d38583 in mklev () at mklev.c:1256
        croom = 0x7fffffffe070
        ridx = 32767
#13 0x0000555555919db3 in goto_level (newlevel=0x7fffffffe3c0, at_stairs=0 '\000', 
    falling=1 '\001', portal=0 '\000') at do.c:1914
        fd = 4
        l_idx = 0
        new_ledger = 70 'F'
        cant_go_back = 0 '\000'
        great_effort = 0 '\000'
        up = 0 '\000'
        newdungeon = 0 '\000'
        was_in_W_tower = 0 '\000'
        familiar = 0 '\000'
        new = 0 '\000'
        mtmp = 0x555556501600
        whynot = "\000u\326UUU", '\000' <repeats 249 times>
        annotation = 0x0
        dist = 3
        do_fall_dmg = 0 '\000'
#14 0x000055555591d69b in deferred_goto () at do.c:2285
        dest = {dnum = 2 '\002', dlevel = 4 '\004'}
        typmask = 66
#15 0x0000555555769d1d in moveloop (resuming=0 '\000') at allmain.c:828
        moveamt = 10
        wtcap = 0
        change = 0
        monscanmove = 0 '\000'
        elf_regen = 1 '\001'
        orc_regen = 1 '\001'
        vamp_regen = 1 '\001'
#16 0x00005555563e1d6e in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
        fd = -1
        dir = 0x0
        exact_username = 0 '\000'
        resuming = 0 '\000'
        plsel_once = 1 '\001'
```

**Comment by elunna** [comment]
![image](https://user-images.githubusercontent.com/5000096/202862135-a89e2636-688b-4d29-98dc-b2915d835a23.png)
