### ISSUE TITLE
Found with fuzzer: "rn2(0) attempted"

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#66]
```
[0] /lib/x86_64-linux-gnu/libasan.so.5(+0x6cd40) [0x7ffff75f8d40]
[1] /home/lunatunez/games/hackemdir/hackem(+0x4fb6ca) [0x555555a4f6ca]
[2] /home/lunatunez/games/hackemdir/hackem(+0x4fb5bd) [0x555555a4f5bd]
[3] /home/lunatunez/games/hackemdir/hackem(panic+0x6ab) [0x555555a563df]
[4] /home/lunatunez/games/hackemdir/hackem(impossible+0x2c8) [0x555555faf344]
[5] /home/lunatunez/games/hackemdir/hackem(rn2+0x21) [0x5555560afb53]
[6] /home/lunatunez/games/hackemdir/hackem(losespells+0x18c) [0x555556188e37]
[7] /home/lunatunez/games/hackemdir/hackem(forget+0x1c1) [0x555556067c84]
[8] /home/lunatunez/games/hackemdir/hackem(+0x76b36b) [0x555555cbf36b]
[9] /home/lunatunez/games/hackemdir/hackem(mattacku+0xfcb7) [0x555555cb4347]
[10] /home/lunatunez/games/hackemdir/hackem(dochug+0xd966) [0x555555e4ce40]
[11] /home/lunatunez/games/hackemdir/hackem(dochugw+0x2a92) [0x555555e38137]
[12] /home/lunatunez/games/hackemdir/hackem(movemon+0x1903) [0x555555da57b5]
[13] /home/lunatunez/games/hackemdir/hackem(moveloop+0x603) [0x555555762229]
[14] /home/lunatunez/games/hackemdir/hackem(main+0xdda) [0x5555563de214]
[15] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7ffff7365083]
[16] /home/lunatunez/games/hackemdir/hackem(_start+0x2e) [0x55555575face]

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7363859 in __GI_abort () at abort.c:79
#2  0x0000555555a4f5e3 in NH_abort () at end.c:236
#3  0x0000555555a563df in panic (str=0x5555565490a0 "%s") at end.c:802
#4  0x0000555555faf344 in impossible (s=0x55555656f520 "rn2(%d) attempted") at pline.c:518
#5  0x00005555560afb53 in rn2 (x=0) at rnd.c:106
#6  0x0000555556188e37 in losespells () at spell.c:1667
#7  0x0000555556067c84 in forget (howmuch=2) at read.c:1170
#8  0x0000555555cbf36b in hitmu (mtmp=0x6110004ac300, mattk=0x555556628368 <mons+13128>)
    at mhitu.c:1824
#9  0x0000555555cb4347 in mattacku (mtmp=0x6110004ac300) at mhitu.c:1012
#10 0x0000555555e4ce40 in dochug (mtmp=0x6110004ac300) at monmove.c:969
#11 0x0000555555e38137 in dochugw (mtmp=0x6110004ac300) at monmove.c:122
#12 0x0000555555da57b5 in movemon () at mon.c:1529
#13 0x0000555555762229 in moveloop (resuming=0 '\000') at allmain.c:244
#14 0x00005555563de214 in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {0, 0, 0, 0, 0, 140737335783280, 93824997454517, 335544320, 
            140737341046928, 1073741824, 0, 140737342793376, 4294967295, 140737337360384, 
            140737342776480, 367256097142305280}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007ffff7363859 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0xffffffff, sa_sigaction = 0xffffffff}, 
          sa_mask = {__val = {140737337360384, 140737342776480, 367256097142305280, 
              140737488342464, 140737342793376, 18446744073709547520, 140737327104000, 
              140737345462488, 140737488343536, 140737488343536, 140737344331794, 
              17592186042808, 140737488334848, 140737341046928, 367256097142305280, 
              140737488342864}}, sa_flags = 2076406272, sa_restorer = 0x7fffffffd110}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x0000555555a4f5e3 in NH_abort () at end.c:236
        gdb_prio = 1
        libc_prio = 2
        aborting = 1 '\001'
#3  0x0000555555a563df in panic (str=0x5555565490a0 "%s") at end.c:802
        the_args = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7fffffffd1e0, 
            reg_save_area = 0x7fffffffd110}}
#4  0x0000555555faf344 in impossible (s=0x55555656f520 "rn2(%d) attempted") at pline.c:518
        pbuf = "rn2(0) attempted\000\212\265A\000\000\000\000p1^VUU\000\000!C@VUU\000\000\000\061^VUU\000\000G\000\000\000\070\000\000\000\026", '\000' <repeats 48 times>, "r\303{y\301\030\005@\323\377\377\377\177\000\000h\372\377\377\377\017\000\000@\323\377\377\377\177\000\000\360\325\377\377\377\177\000\000\000\324\377\377\377\177\000\000\177\063@VUU\000\000\000\000\000\000\000\000\000\000\b", '\000' <repeats 19 times>, "\377\377\377\377", '\000' <repeats 16 times>...
        the_args = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7fffffffd8d0, 
            reg_save_area = 0x7fffffffd7f0}}
#5  0x00005555560afb53 in rn2 (x=0) at rnd.c:106
No locals.
#6  0x0000555556188e37 in losespells () at spell.c:1667
        n = 9
        nzap = 1
        i = 9
#7  0x0000555556067c84 in forget (howmuch=2) at read.c:1170
No locals.
#8  0x0000555555cbf36b in hitmu (mtmp=0x6110004ac300, mattk=0x555556628368 <mons+13128>)
    at mhitu.c:1824
        mdat = 0x555556628350 <mons+13104>
        uncancelled = 1
        ptmp = 0
        dmg = 0
        armpro = 0
        permdmg = 0
        tmphp = 32767
        buf = "\300\333\377\377\377\177\000\000\t\204\347UUU\000\000\020\000\000\000\060\000\000\000\320\332\377\377\377\177\000\000\320\332\377\377\377\177\000\000\000\303J\000\020a\000\000@\333\377\377\377\177\000\000\300\327/\000\001\000\000\000\377\377\377\377\017\000\000\000\004\000\000\000\003\000\000\000\377\377\377\377k\000\000\000\000\303J\000\020a", '\000' <repeats 19 times>, "\303J\000\020a\000\000\000\303J\000\020a\000\000 \333\377\377\377\177\000\000M\322\060VUU\000\000\000\000\000\000\001\000\b\000\037\000\000\000\351\377\377\377 \027HVUU\000\000\000\000\000\000\000\000\000\000\300\333\377\377\377\177\000\000`\333\377\377\377\177\000\000\360\333\377\377\377\177\000\000"...
        olduasmon = 0x555556638208 <mons+78312>
        res = 0
        burnmsg = 0 '\000'
        armask = 0
        hated_obj = 0x74206472617a6957
        vorpal_wield = 0 '\000'
#9  0x0000555555cb4347 in mattacku (mtmp=0x6110004ac300) at mhitu.c:1012
        mattk = 0x555556628368 <mons+13128>
        alt_attk = {aatyp = 64 '@', adtyp = 222 '\336', damn = 255 '\377', damd = 255 '\377'}
        i = 2
        j = 1
        k = 0
        tmp = 18
        sum = {1, 1, 0, 0, 0, 0}
        mdat = 0x555556628350 <mons+13104>
        marmf = 0x0
        ranged = 0 '\000'
        range2 = 0 '\000'
        foundyou = 1 '\001'
        youseeit = 1 '\001'
        skipnonmagc = 0 '\000'
#10 0x0000555555e4ce40 in dochug (mtmp=0x6110004ac300) at monmove.c:969
        mdat = 0x555556628350 <mons+13104>
        tmp = <optimized out>
        mdummy = 0x55555586803a <randomkey+91>
        inrange = 1
        nearby = 1
        scared = 0
        oldx = 21845
        oldy = 1446217352
        mwalk_sewage = 0 '\000'
#11 0x0000555555e38137 in dochugw (mtmp=0x6110004ac300) at monmove.c:122
        x = 17
        y = 6
        already_saw_mon = 0 '\000'
        rd = 300
#12 0x0000555555da57b5 in movemon () at mon.c:1529
        mtmp = 0x6110004ac300
        nmtmp = 0x6110004ac440
        somebody_can_move = 0 '\000'
#13 0x0000555555762229 in moveloop (resuming=0 '\000') at allmain.c:244
        moveamt = 4
        wtcap = 0
        change = 0
        monscanmove = 0 '\000'
        elf_regen = 1 '\001'
        orc_regen = 1 '\001'
        vamp_regen = 1 '\001'
#14 0x00005555563de214 in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
        fd = -1
        dir = 0x0
        exact_username = 0 '\000'
        resuming = 0 '\000'
        plsel_once = 1 '\001'

```

**Comment by elunna** [comment]
Commit f1f78ef21 fixes this.
