### ISSUE TITLE
Found with fuzzer: Call a scroll of DAIYEN FOOELS

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#67]
```
Generating more information you may report:

[0] /lib/x86_64-linux-gnu/libasan.so.5(+0x6cd40) [0x7ffff75f8d40]
[1] /home/lunatunez/games/hackemdir/hackem(+0x4fb6ca) [0x555555a4f6ca]
[2] /home/lunatunez/games/hackemdir/hackem(+0x4fb5bd) [0x555555a4f5bd]
[3] /home/lunatunez/games/hackemdir/hackem(+0x4fb3cb) [0x555555a4f3cb]
[4] /lib/x86_64-linux-gnu/libc.so.6(+0x43090) [0x7ffff7384090]
[5] /lib/x86_64-linux-gnu/libc.so.6(+0x1886e5) [0x7ffff74c96e5]
[6] /lib/x86_64-linux-gnu/libasan.so.5(strcat+0x6a) [0x7ffff7639baa]
[7] /home/lunatunez/games/hackemdir/hackem(+0x9b882b) [0x555555f0c82b]
[8] /home/lunatunez/games/hackemdir/hackem(xname+0x21) [0x555555f08873]
[9] /home/lunatunez/games/hackemdir/hackem(+0x3e68ae) [0x55555593a8ae]
[10] /home/lunatunez/games/hackemdir/hackem(short_oname+0xe1) [0x555555f15fcc]
[11] /home/lunatunez/games/hackemdir/hackem(safe_qbuf+0x2db) [0x555555f2b1b9]
[12] /home/lunatunez/games/hackemdir/hackem(docall+0x30a) [0x55555593ac4e]
[13] /home/lunatunez/games/hackemdir/hackem(rename_disco+0xb10) [0x555555f063f2]
[14] /home/lunatunez/games/hackemdir/hackem(docallcmd+0x897) [0x55555593a024]
[15] /home/lunatunez/games/hackemdir/hackem(rhack+0x1b5f) [0x555555869f25]
[16] /home/lunatunez/games/hackemdir/hackem(moveloop+0x70b5) [0x555555768cdb]
[17] /home/lunatunez/games/hackemdir/hackem(main+0xdda) [0x5555563de211]
[18] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7ffff7365083]
[19] /home/lunatunez/games/hackemdir/hackem(_start+0x2e) [0x55555575face]


Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7363859 in __GI_abort () at abort.c:79
#2  0x0000555555a4f5e3 in NH_abort () at end.c:236
#3  0x0000555555a4f3cb in panictrace_handler (sig_unused=11) at end.c:161
#4  <signal handler called>
#5  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
#6  0x00007ffff7639baa in __interceptor_strcat (to=0x5555567f22d0 <obufs+2896> "scroll of ", 
    from=0x0) at ../../../../src/libsanitizer/asan/asan_interceptors.cc:380
#7  0x0000555555f0c82b in xname_flags (obj=0x7fffffffdb40, cxn_flags=0) at objnam.c:914
#8  0x0000555555f08873 in xname (obj=0x7fffffffdb40) at objnam.c:581
#9  0x000055555593a8ae in docall_xname (obj=0x7fffffffe150) at do_name.c:1529
#10 0x0000555555f15fcc in short_oname (obj=0x7fffffffe150, func=0x55555593a0ad <docall_xname>, 
    altfunc=0x555555f17ff8 <simpleonames>, lenlimit=121) at objnam.c:1967
#11 0x0000555555f2b1b9 in safe_qbuf (qbuf=0x7fffffffde90 "Call ", 
    qprefix=0x555556493960 "Call ", qsuffix=0x555556493920 ":", obj=0x7fffffffe150, 
    func=0x55555593a0ad <docall_xname>, altfunc=0x555555f17ff8 <simpleonames>, 
    lastR=0x5555564939a0 "thing") at objnam.c:5517
#12 0x000055555593ac4e in docall (obj=0x7fffffffe150) at do_name.c:1548
#13 0x0000555555f063f2 in rename_disco () at o_init.c:744
#14 0x000055555593a024 in docallcmd () at do_name.c:1490
#15 0x0000555555869f25 in rhack (cmd=0x5555567d1880 <in_line> "N") at cmd.c:5537
#16 0x0000555555768cdb in moveloop (resuming=0 '\000') at allmain.c:825
#17 0x00005555563de211 in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {1024, 0, 0, 0, 0, 140737335783280, 93824997454517, 335544320, 
            140737341046928, 1073741824, 0, 140737342793376, 4294967295, 140737337360384, 
            140737342776480, 17774782798768167424}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007ffff7363859 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0xffffffff, sa_sigaction = 0xffffffff}, 
          sa_mask = {__val = {140737337360384, 140737342776480, 17774782798768167424, 
              140737488340768, 140737342793376, 18446744073709547520, 140737327104000, 
              140737345462488, 0, 93825010023056, 140737344331794, 17592186042596, 
              140737488334848, 140737341046928, 17774782798768167424, 93825011753680}}, 
          sa_flags = -666052096, sa_restorer = 0x7fffffffdb40}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x0000555555a4f5e3 in NH_abort () at end.c:236
        gdb_prio = 1
        libc_prio = 2
        aborting = 1 '\001'
#3  0x0000555555a4f3cb in panictrace_handler (sig_unused=11) at end.c:161
        f2 = 18
#4  <signal handler called>
No locals.
#5  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
No locals.
#6  0x00007ffff7639baa in __interceptor_strcat (to=0x5555567f22d0 <obufs+2896> "scroll of ", 
    from=0x0) at ../../../../src/libsanitizer/asan/asan_interceptors.cc:380
        from_length = <optimized out>
        to_length = <optimized out>
        ctx = <synthetic pointer>
        _ctx = {interceptor_name = 0x7ffff76e666b "strcat"}
#7  0x0000555555f0c82b in xname_flags (obj=0x7fffffffdb40, cxn_flags=0) at objnam.c:914
        buf = 0x5555567f22d0 <obufs+2896> "scroll of "
        obufp = 0x0
        typ = 466
        ocl = 0x55555664ba90 <objects+18640>
        nn = 1
        omndx = 0
        orig_opknwn = 0
        actualn = 0x0
        dn = 0x555556444700 "DAIYEN FOOELS"
        un = 0x0
        pluralize = 0 '\000'
        known = 1 '\001'
        dknown = 1 '\001'
        bknown = 0 '\000'
#8  0x0000555555f08873 in xname (obj=0x7fffffffdb40) at objnam.c:581
No locals.
#9  0x000055555593a8ae in docall_xname (obj=0x7fffffffe150) at do_name.c:1529
        otemp = {nobj = 0x0, v = {v_nexthere = 0x0, v_ocontainer = 0x0, v_ocarry = 0x0}, 
          cobj = 0x0, o_id = 0, ox = 0 '\000', oy = 0 '\000', otyp = 0, owt = 0, quan = 0, 
          spe = 0 '\000', oclass = 0 '\000', invlet = 0 '\000', oartifact = 0 '\000', 
          altmode = 0 '\000', oprops = 0, oprops_known = 0, where = 0 '\000', timed = 0 '\000', 
          cursed = 0, blessed = 0, unpaid = 0, no_charge = 0, known = 0, dknown = 0, bknown = 0, 
          rknown = 0, oeroded = 0, oeroded2 = 0, oerodeproof = 0, olocked = 0, oticking = 0, 
          obroken = 0, otrapped = 0, recharged = 0, lamplit = 0, globby = 0, greased = 0, 
          nomerge = 0, was_thrown = 0, odrained = 0, material = 0, in_use = 0, bypass = 0, 
          cknown = 0, lknown = 0, yours = 0, corpsenm = 0, usecount = 0, oeaten = 0, age = 0, 
          owornmask = 0, oextra = 0x0}
#10 0x0000555555f15fcc in short_oname (obj=0x7fffffffe150, func=0x55555593a0ad <docall_xname>, 
    altfunc=0x555555f17ff8 <simpleonames>, lenlimit=121) at objnam.c:1967
        save_obj = {nobj = 0x0, v = {v_nexthere = 0x0, v_ocontainer = 0x0, v_ocarry = 0x0}, 
          cobj = 0x0, o_id = 0, ox = 0 '\000', oy = 0 '\000', otyp = 0, owt = 0, quan = 0, 
          spe = 0 '\000', oclass = 0 '\000', invlet = 0 '\000', oartifact = 0 '\000', 
          altmode = 0 '\000', oprops = 0, oprops_known = 0, where = -115 '\215', 
          timed = -2 '\376', cursed = 0, blessed = 0, unpaid = 1, no_charge = 1, known = 1, 
          dknown = 1, bknown = 0, rknown = 0, oeroded = 3, oeroded2 = 1, oerodeproof = 1, 
          olocked = 1, oticking = 1, obroken = 1, otrapped = 1, recharged = 7, lamplit = 1, 
          globby = 1, greased = 1, nomerge = 1, was_thrown = 1, odrained = 1, material = 31, 
          in_use = 0, bypass = 0, cknown = 0, lknown = 0, yours = 0, corpsenm = 0, usecount = 0, 
          oeaten = 4149405344, age = 159, owornmask = 93825011789440, oextra = 0xd68}
        unamebuf = "p\336\377\377\377\177\000\000\353s", <incomplete sequence \367>
        onamebuf = "\000\000\000\000\000\000\000\000\240\346", <incomplete sequence \367>
        save_oname = 0x0
        save_uname = 0x0
        outbuf = 0x0
#11 0x0000555555f2b1b9 in safe_qbuf (qbuf=0x7fffffffde90 "Call ", 
    qprefix=0x555556493960 "Call ", qsuffix=0x555556493920 ":", obj=0x7fffffffe150, 
    func=0x55555593a0ad <docall_xname>, altfunc=0x555555f17ff8 <simpleonames>, 
    lastR=0x5555564939a0 "thing") at objnam.c:5517
        bufp = 0x1545206568 ""
        endp = 0x7fffffffdf0f ""
        len = 6
        lenlimit = 127
        len_qpfx = 5
        len_qsfx = 1
        len_lastR = 5
#12 0x000055555593ac4e in docall (obj=0x7fffffffe150) at do_name.c:1548
        buf = "\377\377\377\377\000\000\000\000\000\000\000\367\377\177\000\000\240\244R\367\377\177\000\000\000\332L\330Ƕ\254\366\260\002\000\000\320`\000\000\240\346R\367\377\177", '\000' <repeats 11 times>, "\332L\330Ƕ\254\366\300\337\377\377\377\377\377\377\025\000\000\000\000\000\000\000\370\261~VUU\000\000O\000\000\000\000\000\000\000\347\032@VUU\000\000\027\002\000\000\000\000\000\000\300\337\377\377\377\177\000\000\220\265\201UUU\000\000\034\000\000\000\000\000\000\000\025\000\000\000\000\000\000\000\020\340\377\377\377\177\000\000\213\230\217UUU\000\000\340\337\377\377\377\177\000\000=ܰU\001\000\000\000\020\340\377\377\377\177\000\000@\205\217U\025\000\000\000\060\340\377\377\377\177\000\000\000\332L"...
        qbuf = "Call ", '\000' <repeats 122 times>
        str1 = 0x0
#13 0x0000555555f063f2 in rename_disco () at o_init.c:744
        odummy = {nobj = 0x0, v = {v_nexthere = 0x0, v_ocontainer = 0x0, v_ocarry = 0x0}, 
          cobj = 0x0, o_id = 0, ox = 0 '\000', oy = 0 '\000', otyp = 466, owt = 0, quan = 1, 
          spe = 0 '\000', oclass = 9 '\t', invlet = 0 '\000', oartifact = 0 '\000', 
          altmode = 0 '\000', oprops = 0, oprops_known = 0, where = 0 '\000', timed = 0 '\000', 
          cursed = 0, blessed = 0, unpaid = 0, no_charge = 0, known = 1, dknown = 1, bknown = 0, 
          rknown = 0, oeroded = 0, oeroded2 = 0, oerodeproof = 0, olocked = 0, oticking = 0, 
          obroken = 0, otrapped = 0, recharged = 0, lamplit = 0, globby = 0, greased = 0, 
          nomerge = 0, was_thrown = 0, odrained = 0, material = 0, in_use = 0, bypass = 0, 
          cknown = 0, lknown = 0, yours = 0, corpsenm = 0, usecount = 0, oeaten = 0, age = 0, 
          owornmask = 0, oextra = 0x0}
        i = 535
        dis = 466
        ct = 378
        mn = 329
        sl = 1
        s = 0x5555567e4ba0 <flags+96> ""
        oclass = 10 '\n'
        prev_class = 10 '\n'
        tmpwin = 6
        any = {a_void = 0x1eb, a_obj = 0x1eb, a_monst = 0x1eb, a_int = 491, a_char = -21 '\353', 
          a_schar = -21 '\353', a_uchar = 235 '\353', a_uint = 491, a_long = 491, a_ulong = 491, 
          a_iptr = 0x1eb, a_lptr = 0x1eb, a_ulptr = 0x1eb, a_uptr = 0x1eb, 
          a_string = 0x1eb <error: Cannot access memory at address 0x1eb>, a_nfunc = 0x1eb, 
          a_mask32 = 491}
        selected = 0x602000b9bf50
#14 0x000055555593a024 in docallcmd () at do_name.c:1490
        obj = 0x100000000
        win = 6
        any = {a_void = 0x61, a_obj = 0x61, a_monst = 0x61, a_int = 97, a_char = 97 'a', 
          a_schar = 97 'a', a_uchar = 97 'a', a_uint = 97, a_long = 97, a_ulong = 97, 
          a_iptr = 0x61, a_lptr = 0x61, a_ulptr = 0x61, a_uptr = 0x61, 
          a_string = 0x61 <error: Cannot access memory at address 0x61>, a_nfunc = 0x61, 
          a_mask32 = 97}
        pick_list = 0x6020004a20b0
        ch = 100 'd'
        allowall = "\237"
        abc = 1 '\001'
#15 0x0000555555869f25 in rhack (cmd=0x5555567d1880 <in_line> "N") at cmd.c:5537
        tlist = 0x55555668dd70 <extcmdlist+1872>
        res = 688
        func = 0x55555593978d <docallcmd>
        spkey = 0
        prefix_seen = 0 '\000'
        bad_command = -57 '\307'
        firsttime = 1 '\001'
#16 0x0000555555768cdb in moveloop (resuming=0 '\000') at allmain.c:825
        moveamt = 10
        wtcap = 0
        change = 0
        monscanmove = 0 '\000'
        elf_regen = 1 '\001'
        orc_regen = 1 '\001'
        vamp_regen = 1 '\001'
#17 0x00005555563de211 in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
        fd = -1
        dir = 0x0
        exact_username = 0 '\000'
        resuming = 0 '\000'
        plsel_once = 1 '\001'


```

**Comment by elunna** [comment]
Popped up again with a different scroll:
```

Program received signal SIGSEGV, Segmentation fault.
__strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
65	../sysdeps/x86_64/multiarch/strlen-avx2.S: No such file or directory.
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
#1  0x00007ffff7639baa in __interceptor_strcat (to=0x55555680ef50 <obufs+2384> "scroll of ", 
    from=0x0) at ../../../../src/libsanitizer/asan/asan_interceptors.cc:380
#2  0x0000555555f1aa19 in xname_flags (obj=0x7fffffffdb40, cxn_flags=0) at objnam.c:914
#3  0x0000555555f16a61 in xname (obj=0x7fffffffdb40) at objnam.c:581
#4  0x00005555559410ab in docall_xname (obj=0x7fffffffe150) at do_name.c:1529
#5  0x0000555555f241ba in short_oname (obj=0x7fffffffe150, func=0x5555559408aa <docall_xname>, 
    altfunc=0x555555f261e6 <simpleonames>, lenlimit=121) at objnam.c:1967
#6  0x0000555555f393a7 in safe_qbuf (qbuf=0x7fffffffde90 "Call ", 
    qprefix=0x5555564acaa0 "Call ", qsuffix=0x5555564aca60 ":", obj=0x7fffffffe150, 
    func=0x5555559408aa <docall_xname>, altfunc=0x555555f261e6 <simpleonames>, 
    lastR=0x5555564acae0 "thing") at objnam.c:5518
#7  0x000055555594144b in docall (obj=0x7fffffffe150) at do_name.c:1548
#8  0x0000555555f145e0 in rename_disco () at o_init.c:744
#9  0x0000555555940821 in docallcmd () at do_name.c:1490
#10 0x00005555558700a5 in rhack (cmd=0x5555567ee6c0 <in_line> "C") at cmd.c:5553
#11 0x000055555576bcdb in moveloop (resuming=0 '\000') at allmain.c:826
#12 0x00005555563f40f3 in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
No locals.
#1  0x00007ffff7639baa in __interceptor_strcat (to=0x55555680ef50 <obufs+2384> "scroll of ", 
    from=0x0) at ../../../../src/libsanitizer/asan/asan_interceptors.cc:380
        from_length = <optimized out>
        to_length = <optimized out>
        ctx = <synthetic pointer>
        _ctx = {interceptor_name = 0x7ffff76e666b "strcat"}
#2  0x0000555555f1aa19 in xname_flags (obj=0x7fffffffdb40, cxn_flags=0) at objnam.c:914
        buf = 0x55555680ef50 <obufs+2384> "scroll of "
        obufp = 0x0
        typ = 459
        ocl = 0x555556665a18 <objects+18360>
        nn = 1
        omndx = 0
        orig_opknwn = 0
        actualn = 0x0
        dn = 0x55555645ae80 "ELAM EBOW"
        un = 0x0
        pluralize = 0 '\000'
        known = 1 '\001'
        dknown = 1 '\001'
        bknown = 0 '\000'
#3  0x0000555555f16a61 in xname (obj=0x7fffffffdb40) at objnam.c:581
No locals.
#4  0x00005555559410ab in docall_xname (obj=0x7fffffffe150) at do_name.c:1529
        otemp = {nobj = 0x0, v = {v_nexthere = 0x0, v_ocontainer = 0x0, v_ocarry = 0x0}, 
          cobj = 0x0, o_id = 0, ox = 0 '\000', oy = 0 '\000', otyp = 0, owt = 0, quan = 0, 
          spe = 0 '\000', oclass = 0 '\000', invlet = 0 '\000', oartifact = 0 '\000', 
          altmode = 0 '\000', oprops = 0, oprops_known = 0, where = 0 '\000', timed = 0 '\000', 
          cursed = 0, blessed = 0, unpaid = 0, no_charge = 0, known = 0, dknown = 0, bknown = 0, 
          rknown = 0, oeroded = 0, oeroded2 = 0, oerodeproof = 0, olocked = 0, oticking = 0, 
          obroken = 0, otrapped = 0, recharged = 0, lamplit = 0, globby = 0, greased = 0, 
          nomerge = 0, was_thrown = 0, odrained = 0, material = 0, in_use = 0, bypass = 0, 
          cknown = 0, lknown = 0, yours = 0, corpsenm = 0, usecount = 0, oeaten = 0, age = 0, 
          owornmask = 0, oextra = 0x0}
#5  0x0000555555f241ba in short_oname (obj=0x7fffffffe150, func=0x5555559408aa <docall_xname>, 
    altfunc=0x555555f261e6 <simpleonames>, lenlimit=121) at objnam.c:1967
        save_obj = {nobj = 0x0, v = {v_nexthere = 0x0, v_ocontainer = 0x0, v_ocarry = 0x0}, 
          cobj = 0x0, o_id = 0, ox = 0 '\000', oy = 0 '\000', otyp = 0, owt = 0, quan = 0, 
          spe = 0 '\000', oclass = 0 '\000', invlet = 0 '\000', oartifact = 0 '\000', 
          altmode = 0 '\000', oprops = 0, oprops_known = 0, where = -115 '\215', 
          timed = -2 '\376', cursed = 0, blessed = 0, unpaid = 1, no_charge = 1, known = 1, 
          dknown = 1, bknown = 0, rknown = 0, oeroded = 3, oeroded2 = 1, oerodeproof = 1, 
          olocked = 1, oticking = 1, obroken = 1, otrapped = 1, recharged = 7, lamplit = 1, 
          globby = 1, greased = 1, nomerge = 1, was_thrown = 1, odrained = 1, material = 31, 
          in_use = 0, bypass = 0, cknown = 0, lknown = 0, yours = 0, corpsenm = 0, usecount = 0, 
          oeaten = 4149405344, age = 160, owornmask = 93825011907840, oextra = 0xd68}
        unamebuf = "p\336\377\377\377\177\000\000\353s", <incomplete sequence \367>
        onamebuf = "\000\000\000\000\000\000\000\000\240\346", <incomplete sequence \367>
        save_oname = 0x0
        save_uname = 0x0
        outbuf = 0x0
#6  0x0000555555f393a7 in safe_qbuf (qbuf=0x7fffffffde90 "Call ", 
    qprefix=0x5555564acaa0 "Call ", qsuffix=0x5555564aca60 ":", obj=0x7fffffffe150, 
    func=0x5555559408aa <docall_xname>, altfunc=0x555555f261e6 <simpleonames>, 
    lastR=0x5555564acae0 "thing") at objnam.c:5518
        bufp = 0x1541206568 ""
        endp = 0x7fffffffdf0f ""
        len = 6
        lenlimit = 127
        len_qpfx = 5
        len_qsfx = 1
        len_lastR = 5
#7  0x000055555594144b in docall (obj=0x7fffffffe150) at do_name.c:1548
        buf = "\377\377\377\377\000\000\000\000\000\000\000\367\377\177\000\000\240\244R\367\377\177\000\000\000\177\246eE\311\300߰\002\000\000\320`\000\000\240\346R\367\377\177", '\000' <repeats 11 times>, "\177\246eE\311\300\337\300\337\377\377\377\377\377\377\025\000\000\000\000\000\000\000H~\200VUU\000\000\t\000\000\000\000\000\000\000\311yAVUU\000\000m\002\000\000\000\000\000\000\300\337\377\377\377\177\000\000/\023\202UUU\000\000\b\000\000\000\000\000\000\000\025\000\000\000\000\000\000\000\020\340\377\377\377\177\000\000\337\001\220UUU\000\000\340\337\377\377\377\177\000\000\350\\\261U\001\000\000\000\020\340\377\377\377\177\000\000\224\356\217U\025\000\000\000\060\340\377\377\377\177\000\000\000"...
        qbuf = "Call ", '\000' <repeats 122 times>
        str1 = 0x0
#8  0x0000555555f145e0 in rename_disco () at o_init.c:744
        odummy = {nobj = 0x0, v = {v_nexthere = 0x0, v_ocontainer = 0x0, v_ocarry = 0x0}, 
          cobj = 0x0, o_id = 0, ox = 0 '\000', oy = 0 '\000', otyp = 459, owt = 0, quan = 1, 
          spe = 0 '\000', oclass = 9 '\t', invlet = 0 '\000', oartifact = 0 '\000', 
          altmode = 0 '\000', oprops = 0, oprops_known = 0, where = 0 '\000', timed = 0 '\000', 
          cursed = 0, blessed = 0, unpaid = 0, no_charge = 0, known = 1, dknown = 1, bknown = 0, 
          rknown = 0, oeroded = 0, oeroded2 = 0, oerodeproof = 0, olocked = 0, oticking = 0, 
          obroken = 0, otrapped = 0, recharged = 0, lamplit = 0, globby = 0, greased = 0, 
          nomerge = 0, was_thrown = 0, odrained = 0, material = 0, in_use = 0, bypass = 0, 
          cknown = 0, lknown = 0, yours = 0, corpsenm = 0, usecount = 0, oeaten = 0, age = 0, 
          owornmask = 0, oextra = 0x0}
        i = 621
        dis = 459
        ct = 377
        mn = 327
        sl = 1
        s = 0x555556801a00 <flags+96> ""
        oclass = 18 '\022'
        prev_class = 19 '\023'
        tmpwin = 6
        any = {a_void = 0x21a, a_obj = 0x21a, a_monst = 0x21a, a_int = 538, a_char = 26 '\032', 
          a_schar = 26 '\032', a_uchar = 26 '\032', a_uint = 538, a_long = 538, a_ulong = 538, 
          a_iptr = 0x21a, a_lptr = 0x21a, a_ulptr = 0x21a, a_uptr = 0x21a, 
          a_string = 0x21a <error: Cannot access memory at address 0x21a>, a_nfunc = 0x21a, 
          a_mask32 = 538}
        selected = 0x602000527cd0
#9  0x0000555555940821 in docallcmd () at do_name.c:1490
        obj = 0x165a67f00
        win = 6
        any = {a_void = 0x61, a_obj = 0x61, a_monst = 0x61, a_int = 97, a_char = 97 'a', 
          a_schar = 97 'a', a_uchar = 97 'a', a_uint = 97, a_long = 97, a_ulong = 97, 
          a_iptr = 0x61, a_lptr = 0x61, a_ulptr = 0x61, a_uptr = 0x61, 
          a_string = 0x61 <error: Cannot access memory at address 0x61>, a_nfunc = 0x61, 
          a_mask32 = 97}
        pick_list = 0x6020005282f0
        ch = 100 'd'
        allowall = "\205"
        abc = 0 '\000'
#10 0x00005555558700a5 in rhack (cmd=0x5555567ee6c0 <in_line> "C") at cmd.c:5553
        tlist = 0x5555566a9550 <extcmdlist+336>
        res = 2157504
        func = 0x55555593ff8a <docallcmd>
        spkey = 0
        prefix_seen = 0 '\000'
        bad_command = 85 'U'
        firsttime = 1 '\001'
#11 0x000055555576bcdb in moveloop (resuming=0 '\000') at allmain.c:826
        moveamt = 12
        wtcap = 0
        change = 0
        monscanmove = 0 '\000'
        elf_regen = 1 '\001'
        orc_regen = 1 '\001'
        vamp_regen = 1 '\001'
#12 0x00005555563f40f3 in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
        fd = -1
        dir = 0x0
        exact_username = 0 '\000'
        resuming = 0 '\000'
        plsel_once = 1 '\001'
```
