### ISSUE TITLE
Found with fuzzer: flooreffects: obj not free (1, 331, 0)

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#68]
```
Suddenly, the dungeon collapses.
flooreffects: obj not free (1, 331, 0)
Generating more information you may report:

[0] /lib/x86_64-linux-gnu/libasan.so.5(+0x6cd40) [0x7ffff75f8d40]
[1] /home/lunatunez/games/hackemdir/hackem(+0x4fb6ca) [0x555555a4f6ca]
[2] /home/lunatunez/games/hackemdir/hackem(+0x4fb5bd) [0x555555a4f5bd]
[3] /home/lunatunez/games/hackemdir/hackem(panic+0x6ab) [0x555555a563df]
[4] /home/lunatunez/games/hackemdir/hackem(flooreffects+0x207) [0x555555900da4]
[5] /home/lunatunez/games/hackemdir/hackem(throwit+0x92c5) [0x5555559eb2b2]
[6] /home/lunatunez/games/hackemdir/hackem(dovolley+0x1fa) [0x555555fbfacf]
[7] /home/lunatunez/games/hackemdir/hackem(domonability+0xd5) [0x555555836c81]
[8] /home/lunatunez/games/hackemdir/hackem(+0x2e05c1) [0x5555558345c1]
[9] /home/lunatunez/games/hackemdir/hackem(rhack+0x1b5f) [0x555555869f25]
[10] /home/lunatunez/games/hackemdir/hackem(moveloop+0x70b5) [0x555555768cdb]
[11] /home/lunatunez/games/hackemdir/hackem(main+0xdda) [0x5555563de211]
[12] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7ffff7365083]
[13] /home/lunatunez/games/hackemdir/hackem(_start+0x2e) [0x55555575face]


Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7363859 in __GI_abort () at abort.c:79
#2  0x0000555555a4f5e3 in NH_abort () at end.c:236
#3  0x0000555555a563df in panic (str=0x55555648b5e0 "flooreffects: obj not free (%d, %d, %d)")
    at end.c:802
#4  0x0000555555900da4 in flooreffects (
    obj=<error reading variable: Cannot access memory at address 0xffffffffffffffc1>, x=76, 
    y=14, verb=0x5555564a7080 "fall") at do.c:180
#5  0x00005555559eb2b2 in throwit (obj=0x60c0008e3000, wep_mask=0, twoweap=0 '\000')
    at dothrow.c:1690
#6  0x0000555555fbfacf in dovolley () at polyself.c:1358
#7  0x0000555555836c81 in domonability () at cmd.c:722
#8  0x00005555558345c1 in doextcmd () at cmd.c:370
#9  0x0000555555869f25 in rhack (cmd=0x5555567d1880 <in_line> "#") at cmd.c:5537
#10 0x0000555555768cdb in moveloop (resuming=0 '\000') at allmain.c:825
#11 0x00005555563de211 in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {0, 0, 0, 0, 0, 140737335783280, 93824997454517, 335544320, 
            140737341046928, 1073741824, 0, 140737342793376, 4294967295, 140737337360384, 
            140737342776480, 16696366960399857408}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007ffff7363859 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0xffffffff, sa_sigaction = 0xffffffff}, 
          sa_mask = {__val = {140737337360384, 140737342776480, 16696366960399857408, 
              140737488346208, 140737342793376, 18446744073709547520, 140737327104000, 
              140737345462488, 0, 17592186043456, 140737344331794, 17592186043276, 
              140737488338944, 140737341046928, 16696366960399857408, 140737488346608}}, 
          sa_flags = 305379072, sa_restorer = 0x7fffffffdfb0}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x0000555555a4f5e3 in NH_abort () at end.c:236
        gdb_prio = 1
        libc_prio = 2
        aborting = 1 '\001'
#3  0x0000555555a563df in panic (str=0x55555648b5e0 "flooreffects: obj not free (%d, %d, %d)")
    at end.c:802
        the_args = {{gp_offset = 32, fp_offset = 48, overflow_arg_area = 0x7fffffffe080, 
            reg_save_area = 0x7fffffffdfb0}}
#4  0x0000555555900da4 in flooreffects (
    obj=<error reading variable: Cannot access memory at address 0xffffffffffffffc1>, x=76, 
    y=14, verb=0x5555564a7080 "fall") at do.c:180
        t = 0x0
        mtmp = 0x5555558009d9 <acurr+877>
        otmp = <error reading variable otmp (Cannot access memory at address 0xffffffffffffffa1)>
        save_bhitpos = <error reading variable save_bhitpos (Cannot access memory at address 0xffffffffffffff81)>
        tseen = 0 '\000'
        ttyp = 0
        res = 0
#5  0x00005555559eb2b2 in throwit (obj=0x60c0008e3000, wep_mask=0, twoweap=0 '\000')
    at dothrow.c:1690
        mon = 0x0
        range = 9
        urange = 9
        crossbowing = 0 '\000'
        gunning = 0 '\000'
        clear_thrownobj = 0 '\000'
        impaired = 0 '\000'
        tethered_weapon = 0 '\000'
#6  0x0000555555fbfacf in dovolley () at polyself.c:1358
        otmp = 0x60c0008e3000
        mattk = 0x55555662a860 <mons+22592>
        i = 1
        numattacks = 8
#7  0x0000555555836c81 in domonability () at cmd.c:722
No locals.
#8  0x00005555558345c1 in doextcmd () at cmd.c:370
        idx = 38
        retval = 12
        func = 0x555555836bac <domonability>
#9  0x0000555555869f25 in rhack (cmd=0x5555567d1880 <in_line> "#") at cmd.c:5537
        tlist = 0x55555668d620 <extcmdlist>
        res = 688
        func = 0x555555834314 <doextcmd>
        spkey = 0
        prefix_seen = 0 '\000'
        bad_command = 74 'J'
        firsttime = 1 '\001'
#10 0x0000555555768cdb in moveloop (resuming=0 '\000') at allmain.c:825
        moveamt = 12
        wtcap = 0
        change = 0
        monscanmove = 0 '\000'
        elf_regen = 1 '\001'
        orc_regen = 1 '\001'
        vamp_regen = 1 '\001'
#11 0x00005555563de211 in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
        fd = -1
        dir = 0x0
        exact_username = 0 '\000'
        resuming = 0 '\000'
        plsel_once = 1 '\001'

```

**Comment by elunna** [comment]
Polymorphed into a manticore and volleying spikes. I was able to reproduce this by polymorphing into a manicore and #monster (This is also a problem in SpliceHack). After the second spike fell onto the existing spike it crashed.

Manticore has a AT_VOLY attack that volleys spikes.
#define	SPIKE	331

flooreffects gets it and it's not OBJFREE.
