### ISSUE TITLE
Found with fuzzer: map mon (61100009e880) at <16,12> not in fmon list!

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#7]
```
Suddenly, the dungeon collapses.
map mon (61100009e880) at <16,12> not in fmon list!
Generating more information you may report:

#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {0, 0, 0, 0, 0, 140737337632192, 93824997411122, 335544320,
            140737341055120, 1073741824, 0, 140737342801568, 4294967295, 140737337360384,
            140737342784672, 15664674283868739840}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007ffff7365859 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0xffffffff, sa_sigaction = 0xffffffff},
          sa_mask = {__val = {140737337360384, 140737342784672, 15664674283868739840,
              140737488345360, 140737342801568, 18446744073709547520, 140737327112192,
              140737345470680, 140737488346432, 140737488346432, 140737344339986,
              17592186043170, 140737488338944, 140737341055120, 15664674283868739840,
              140737488345760}}, sa_flags = 607213824, sa_restorer = 0x7fffffffdc60}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x0000555555a44c60 in NH_abort () at end.c:236
        gdb_prio = 1
        libc_prio = 2
        aborting = 1 '\001'
#3  0x0000555555a4ba5c in panic (str=0x55555651b6c0 "%s") at end.c:802
        the_args = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7fffffffdd30,
            reg_save_area = 0x7fffffffdc60}}
#4  0x0000555555f98bec in impossible (
    s=0x5555564d3e80 "map mon (%s) at <%d,%d> not in fmon list!") at pline.c:518
        pbuf = "map mon (61100009e880) at <16,12> not in fmon list!\000\000\000\001\000\000\001\000\000\001\000\001\002\000\000\001\001\001\000\000\000\000\001", '\000' <repeats 39 times>, "\001\000\001\001\001\000\000\000\001\000\000\000\000\002\001\000\000\000\000\001", '\000' <repeats 68 times>...
        the_args = {{gp_offset = 32, fp_offset = 48, overflow_arg_area = 0x7fffffffe420,
            reg_save_area = 0x7fffffffe340}}
#5  0x0000555555d64172 in mon_sanity_check () at mon.c:178
        x = 16
        y = 12
        mtmp = 0x61100009e880
        m = 0x0
#6  0x000055555585faad in sanity_check () at cmd.c:4842
No locals.
#7  0x0000555555761767 in moveloop (resuming=0 '\000') at allmain.c:767
        moveamt = 10
        wtcap = 0
        change = 0
        monscanmove = 0 '\000'
        timeout_start = 29817
        y = 12
        mtmp = 0x61100009e880
        m = 0x0
#6  0x000055555585faad in sanity_check () at cmd.c:4842
No locals.
#7  0x0000555555761767 in moveloop (resuming=0 '\000') at allmain.c:767
        moveamt = 10
        wtcap = 0
        change = 0
        monscanmove = 0 '\000'
        timeout_start = 29817
--Type <RET> for more, q to quit, c to continue without paging--
        past_clock = 75896
        elf_regen = 1 '\001'
        orc_regen = 1 '\001'
        vamp_regen = 1 '\001'
#8  0x00005555563b4110 in main (argc=0, argv=0x7fffffffe658) at ../sys/unix/unixmain.c:353
        fd = -1
        dir = 0x0
        exact_username = 0 '\000'
        resuming = 0 '\000'
        plsel_once = 1 '\001'
```

**Comment by elunna** [comment]
This issue has been popping up most frequently. I have tried disabling the betrayed function for pets - I suspect that might have something to do with it. A pet might levelteleport and on the same turn betray and not be found. Requires a lot more fuzzing to confirm.
