### ISSUE TITLE
Found with fuzzer: tport_spell: spellbook full

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#70]
```
tport_spell: spellbook full
Generating more information you may report:

[0] /lib/x86_64-linux-gnu/libasan.so.5(+0x6cd40) [0x7ffff75f8d40]
[1] /home/lunatunez/games/hackemdir/hackem(+0x4fb6ca) [0x555555a4f6ca]
[2] /home/lunatunez/games/hackemdir/hackem(+0x4fb5bd) [0x555555a4f5bd]
[3] /home/lunatunez/games/hackemdir/hackem(panic+0x6ab) [0x555555a563df]
[4] /home/lunatunez/games/hackemdir/hackem(impossible+0x2c8) [0x555555faf356]
[5] /home/lunatunez/games/hackemdir/hackem(tport_spell+0xc5) [0x55555618875b]
[6] /home/lunatunez/games/hackemdir/hackem(dotelecmd+0x767) [0x5555561bb12e]
[7] /home/lunatunez/games/hackemdir/hackem(rhack+0x1b5f) [0x555555869f25]
[8] /home/lunatunez/games/hackemdir/hackem(moveloop+0x70b5) [0x555555768cdb]
[9] /home/lunatunez/games/hackemdir/hackem(main+0xdda) [0x5555563de223]
[10] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7ffff7365083]
[11] /home/lunatunez/games/hackemdir/hackem(_start+0x2e) [0x55555575face]


Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7363859 in __GI_abort () at abort.c:79
#2  0x0000555555a4f5e3 in NH_abort () at end.c:236
#3  0x0000555555a563df in panic (str=0x5555565490a0 "%s") at end.c:802
#4  0x0000555555faf356 in impossible (s=0x55555659c5e0 "tport_spell: spellbook full")
    at pline.c:518
#5  0x000055555618875b in tport_spell (what=1) at spell.c:1578
#6  0x00005555561bb12e in dotelecmd () at teleport.c:932
#7  0x0000555555869f25 in rhack (cmd=0x5555567d1881 <in_line+1> "\024") at cmd.c:5537
#8  0x0000555555768cdb in moveloop (resuming=0 '\000') at allmain.c:825
#9  0x00005555563de223 in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {0, 0, 0, 0, 0, 140737335783280, 93824997454517, 335544320, 
            140737341046928, 1073741824, 0, 140737342793376, 4294967295, 140737337360384, 
            140737342776480, 8907818500652400640}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007ffff7363859 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0xffffffff, sa_sigaction = 0xffffffff}, 
          sa_mask = {__val = {140737337360384, 140737342776480, 8907818500652400640, 
              140737488344832, 140737342793376, 18446744073709547520, 140737327104000, 
              140737345462488, 140737488345904, 140737488345904, 140737344331794, 
              17592186043104, 140737488338944, 140737341046928, 8907818500652400640, 
              140737488345232}}, sa_flags = 252313600, sa_restorer = 0x7fffffffda50}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x0000555555a4f5e3 in NH_abort () at end.c:236
        gdb_prio = 1
        libc_prio = 2
        aborting = 1 '\001'
#3  0x0000555555a563df in panic (str=0x5555565490a0 "%s") at end.c:802
        the_args = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7fffffffdb20, 
            reg_save_area = 0x7fffffffda50}}
#4  0x0000555555faf356 in impossible (s=0x55555659c5e0 "tport_spell: spellbook full")
    at pline.c:518
        pbuf = "tport_spell: spellbook full", '\000' <repeats 1117 times>...
        the_args = {{gp_offset = 8, fp_offset = 48, overflow_arg_area = 0x7fffffffe210, 
            reg_save_area = 0x7fffffffe130}}
#5  0x000055555618875b in tport_spell (what=1) at spell.c:1578
        save_tport = {savespell = {sp_id = 0, sp_lev = 0 '\000', sp_know = 0}, tport_indx = 63}
        i = 63
#6  0x00005555561bb12e in dotelecmd () at teleport.c:932
        tports = {{menulet = 110 'n', 
            menudesc = 0x5555565a24c0 "normal ^T on demand; no spell, obey restrictions"}, {
            menulet = 115 's', 
            menudesc = 0x5555565a2520 "via spellcast; no intrinsic teleport"}, {
            menulet = 116 't', menudesc = 0x5555565a2580 "try ^T without having it; no spell"}, {
            menulet = 119 'w', menudesc = 0x5555565a25e0 "debug mode; ignore restrictions"}}
        i = 2
        tmode = 116
        picks = 0x603000e5db90
        any = {a_void = 0x77, a_obj = 0x77, a_monst = 0x77, a_int = 119, a_char = 119 'w', 
          a_schar = 119 'w', a_uchar = 119 'w', a_uint = 119, a_long = 119, a_ulong = 119, 
          a_iptr = 0x77, a_lptr = 0x77, a_ulptr = 0x77, a_uptr = 0x77, 
          a_string = 0x77 <error: Cannot access memory at address 0x77>, a_nfunc = 0x77, 
          a_mask32 = 119}
        win = 6
        save_HTele = 0
        save_ETele = 0
        res = 1
        added = 0
        hidden = 0
        ignore_restrictions = 0 '\000'
#7  0x0000555555869f25 in rhack (cmd=0x5555567d1881 <in_line+1> "\024") at cmd.c:5537
        tlist = 0x55555668e4f0 <extcmdlist+3792>
        res = 1451040296
        func = 0x5555561ba9c7 <dotelecmd>
        spkey = 8
        prefix_seen = 1 '\001'
        bad_command = 85 'U'
        firsttime = 1 '\001'
#8  0x0000555555768cdb in moveloop (resuming=0 '\000') at allmain.c:825
        moveamt = 12
        wtcap = 0
        change = 0
        monscanmove = 0 '\000'
        elf_regen = 1 '\001'
        orc_regen = 1 '\001'
        vamp_regen = 1 '\001'
#9  0x00005555563de223 in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
        fd = -1
        dir = 0x0
        exact_username = 0 '\000'
        resuming = 0 '\000'
        plsel_once = 1 '\001'
```

**Comment by elunna** [comment]
Should be fixed by commit 7767008ea - Revert "Necromancers are protected from forgetting Necromancy spells". We might just let Necromancers lose their spells to amnesia - they can still rewrite the spellbooks anyway.
