### ISSUE TITLE
Found with fuzzer: minvent (a blessed +1 quarterstaff (weapon in hands) (40 aum)) *not* held by mon

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#75]
```
Suddenly, the dungeon collapses.
minvent sanity obj 60c0003dd680 minvent (a blessed +1 quarterstaff (weapon in hands) (40 aum)) *not* held by mon 6110000f0a40 (a wizard called Meremen the Mage)
Generating more information you may report:

[0] /lib/x86_64-linux-gnu/libasan.so.5(+0x6cd40) [0x7ffff75f8d40]
[1] /home/lunatunez/games/hackemdir/hackem(+0x4fb43a) [0x555555a4f43a]
[2] /home/lunatunez/games/hackemdir/hackem(+0x4fb32d) [0x555555a4f32d]
[3] /home/lunatunez/games/hackemdir/hackem(panic+0x6ab) [0x555555a5614f]
[4] /home/lunatunez/games/hackemdir/hackem(impossible+0x2c8) [0x555555faf112]
[5] /home/lunatunez/games/hackemdir/hackem(+0x811eb5) [0x555555d65eb5]
[6] /home/lunatunez/games/hackemdir/hackem(+0x811918) [0x555555d65918]
[7] /home/lunatunez/games/hackemdir/hackem(obj_sanity_check+0x5b0) [0x555555d64d6b]
[8] /home/lunatunez/games/hackemdir/hackem(sanity_check+0xd) [0x55555586665c]
[9] /home/lunatunez/games/hackemdir/hackem(moveloop+0x6c1c) [0x555555768842]
[10] /home/lunatunez/games/hackemdir/hackem(main+0xdda) [0x5555563dd9fe]
[11] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7ffff7365083]
[12] /home/lunatunez/games/hackemdir/hackem(_start+0x2e) [0x55555575face]


Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7363859 in __GI_abort () at abort.c:79
#2  0x0000555555a4f353 in NH_abort () at end.c:236
#3  0x0000555555a5614f in panic (str=0x5555565490a0 "%s") at end.c:802
#4  0x0000555555faf112 in impossible (
    s=0x7fffffffe080 "%s obj %s %s (%s) *not* held by mon %s (%s)") at pline.c:518
#5  0x0000555555d65eb5 in insane_object (obj=0x60c0003dd680, 
    fmt=0x5555564fd180 <mfmt2> "%s obj %s %s (%s) *not*", mesg=0x5555564fd3c0 "minvent sanity", 
    mon=0x6110000f0a40) at mkobj.c:2796
#6  0x0000555555d65918 in mon_obj_sanity (monlist=0x6110000f0a40, 
    mesg=0x5555564fd3c0 "minvent sanity") at mkobj.c:2740
#7  0x0000555555d64d6b in obj_sanity_check () at mkobj.c:2636
#8  0x000055555586665c in sanity_check () at cmd.c:4855
#9  0x0000555555768842 in moveloop (resuming=0 '\000') at allmain.c:794
#10 0x00005555563dd9fe in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {0, 0, 0, 0, 0, 140737335783280, 93824997453861, 335544320, 
            140737341046928, 1073741824, 0, 140737342793376, 4294967295, 140737337360384, 
            140737342776480, 14022190947955408128}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007ffff7363859 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0xffffffff, sa_sigaction = 0xffffffff}, 
          sa_mask = {__val = {140737337360384, 140737342776480, 14022190947955408128, 
              140737488344320, 140737342793376, 18446744073709547520, 140737327104000, 
              140737345462488, 140737488345392, 140737488345392, 140737344331794, 
              17592186043040, 140737488338944, 140737341046928, 14022190947955408128, 
              140737488344720}}, sa_flags = -644580096, sa_restorer = 0x7fffffffd850}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x0000555555a4f353 in NH_abort () at end.c:236
        gdb_prio = 1
        libc_prio = 2
        aborting = 1 '\001'
#3  0x0000555555a5614f in panic (str=0x5555565490a0 "%s") at end.c:802
        the_args = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7fffffffd920, 
            reg_save_area = 0x7fffffffd850}}
#4  0x0000555555faf112 in impossible (
    s=0x7fffffffe080 "%s obj %s %s (%s) *not* held by mon %s (%s)") at pline.c:518
        pbuf = "minvent sanity obj 60c0003dd680 minvent (a blessed +1 quarterstaff (weapon in hands) (40 aum)) *not* held by mon 6110000f0a40 (a wizard called Meremen the Mage)\000\000\000\000\000\000\000\000\000\000\001\000\377\177\000\000\340|CVUU\000\000\000\000\000\000\000\000\000\000\340\274~VUU\000\000"...
        the_args = {{gp_offset = 48, fp_offset = 48, overflow_arg_area = 0x7fffffffe018, 
            reg_save_area = 0x7fffffffdf30}}
#5  0x0000555555d65eb5 in insane_object (obj=0x60c0003dd680, 
    fmt=0x5555564fd180 <mfmt2> "%s obj %s %s (%s) *not*", mesg=0x5555564fd3c0 "minvent sanity", 
    mon=0x6110000f0a40) at mkobj.c:2796
        objnm = 0x5555567f1dc3 <obufs+1603> "a blessed +1 quarterstaff (weapon in hands) (40 aum)"
        monnm = 0x5555567f1f80 <obufs+2048> "a wizard called Meremen the Mage"
        altfmt = "%s obj %s %s (%s) *not* held by mon %s (%s)\000\020a\000\000\340\340\377\377\377\177\000\000\251\323\004VUU\000\000\r\000\000\000\017\000\000\000\000\375Q\000\020a\000\000\000\375Q\000\020a\000\000\000\375Q\000\020a\000\000\060\341\377\377\377\177\000\000\251\360\343UUU\000\000\000\375Q\000\020a\000\000\000}\224\331_Ԙ\302\000\342\377\377\377\177\000\000\000}\224\331_Ԙ\302\200\206cVUU\000\000\000\344\377\377\377\177\000\000,\374\377\377\377\017\000\000`\341\377\377\377\177\000\000`\341\377\377\377\177\000\000\000\000\000\000\000\000\000\000 \344\377\377\377\177\000\000a\177\063"...
#6  0x0000555555d65918 in mon_obj_sanity (monlist=0x6110000f0a40, 
    mesg=0x5555564fd3c0 "minvent sanity") at mkobj.c:2740
        mon = 0x6110000f0a40
        obj = 0x7fffffffe3f0
        mwep = 0x60c0003dd680
#7  0x0000555555d64d6b in obj_sanity_check () at mkobj.c:2636
        x = 80
        y = 21
        obj = 0x0
#8  0x000055555586665c in sanity_check () at cmd.c:4855
No locals.
#9  0x0000555555768842 in moveloop (resuming=0 '\000') at allmain.c:794
        moveamt = 12
        wtcap = 0
        change = 0
        monscanmove = 0 '\000'
        elf_regen = 1 '\001'
        orc_regen = 1 '\001'
        vamp_regen = 1 '\001'
#10 0x00005555563dd9fe in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
        fd = -1
        dir = 0x0
        exact_username = 0 '\000'
        resuming = 0 '\000'
        plsel_once = 1 '\001'
```

**Comment by elunna** [comment]
Not limited to player monsters it seems?
```

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7363859 in __GI_abort () at abort.c:79
#2  0x0000555555a5e1d4 in NH_abort () at end.c:236
#3  0x0000555555a65063 in panic (str=0x555556572e40 "%s") at end.c:802
#4  0x0000555555fca61d in impossible (
    s=0x7fffffffe080 "%s obj %s %s (%s) *not* held by mon %s (%s)") at pline.c:518
#5  0x0000555555d781d3 in insane_object (obj=0x60c00099e440, 
    fmt=0x5555565255a0 <mfmt2> "%s obj %s %s (%s) *not*", mesg=0x5555565257e0 "minvent sanity", 
    mon=0x6110001ba980) at mkobj.c:2842
#6  0x0000555555d77c36 in mon_obj_sanity (monlist=0x6110001ba980, 
    mesg=0x5555565257e0 "minvent sanity") at mkobj.c:2786
#7  0x0000555555d77089 in obj_sanity_check () at mkobj.c:2682
#8  0x00005555558744b8 in sanity_check () at cmd.c:4892
#9  0x00005555557738d1 in moveloop (resuming=0 '\000') at allmain.c:795
#10 0x00005555563fe8c6 in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {0, 0, 0, 0, 0, 140737335783280, 93824997514918, 335544320, 
            140737341046928, 1073741824, 0, 140737342793376, 4294967295, 140737337360384, 
            140737342776480, 5240326033953393152}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007ffff7363859 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0xffffffff, sa_sigaction = 0xffffffff}, 
          sa_mask = {__val = {140737337360384, 140737342776480, 5240326033953393152, 
              140737488344320, 140737342793376, 18446744073709547520, 140737327104000, 
              140737345462488, 140737488345392, 140737488345392, 140737344331794, 
              17592186043040, 140737488338944, 140737341046928, 5240326033953393152, 
              140737488344720}}, sa_flags = 1896221184, sa_restorer = 0x7fffffffd850}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x0000555555a5e1d4 in NH_abort () at end.c:236
        gdb_prio = 1
        libc_prio = 2
        aborting = 1 '\001'
#3  0x0000555555a65063 in panic (str=0x555556572e40 "%s") at end.c:802
        the_args = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7fffffffd920, 
            reg_save_area = 0x7fffffffd850}}
#4  0x0000555555fca61d in impossible (
    s=0x7fffffffe080 "%s obj %s %s (%s) *not* held by mon %s (%s)") at pline.c:518
        pbuf = "minvent sanity obj 60c00099e440 minvent (an uncursed +0 silver elven short sword (weapon in hand)) *not* held by mon 6110001ba980 (a soldier)", '\000' <repeats 11 times>, "\037\000\000\000\002", '\000' <repeats 13 times>, "\001\000\000\000\000\000\240nEVUU", '\000' <repeats 11 times>, "-\202VUU\000\000"...
        the_args = {{gp_offset = 48, fp_offset = 48, overflow_arg_area = 0x7fffffffe018, 
            reg_save_area = 0x7fffffffdf30}}
#5  0x0000555555d781d3 in insane_object (obj=0x60c00099e440, 
    fmt=0x5555565255a0 <mfmt2> "%s obj %s %s (%s) *not*", mesg=0x5555565257e0 "minvent sanity", 
    mon=0x6110001ba980) at mkobj.c:2842
        objnm = 0x555556829261 <obufs+577> "an uncursed +0 silver elven short sword (weapon in hand)"
        monnm = 0x555556829320 <obufs+768> "a soldier"
        altfmt = "%s obj %s %s (%s) *not* held by mon %s (%s)", '\000' <repeats 212 times>
#6  0x0000555555d77c36 in mon_obj_sanity (monlist=0x6110001ba980, 
    mesg=0x5555565257e0 "minvent sanity") at mkobj.c:2786
        mon = 0x6110001ba980
        obj = 0x7fffffffe3f0
        mwep = 0x60c00099e440
#7  0x0000555555d77089 in obj_sanity_check () at mkobj.c:2682
        x = 80
        y = 21
        obj = 0x0
#8  0x00005555558744b8 in sanity_check () at cmd.c:4892
No locals.
#9  0x00005555557738d1 in moveloop (resuming=0 '\000') at allmain.c:795
        moveamt = 12
        wtcap = 0
        change = 0
        monscanmove = 0 '\000'
        elf_regen = 1 '\001'
        orc_regen = 1 '\001'
        vamp_regen = 1 '\001'
#10 0x00005555563fe8c6 in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
        fd = -1
        dir = 0x0
        exact_username = 0 '\000'
        resuming = 0 '\000'
        plsel_once = 1 '\001'
```

**Comment by elunna** [comment]
Likely fixed in 7aed83fd3. I had enabled player monsters to generate as MH_VAMPIRE - and it's possible there were issues with silver weapons/items being assigned to vampires and they couldn't handle them, resulting in this issue.

**Comment by elunna** [comment]
Caused by issues with monsters reading scrolls of cloning.

**Comment by elunna** [comment]
The error only occurs when I clone an mplayer wielding a weapon.

Stuff related to mplayer creation.

makemon() makes monsters, which includes mplayers.
It calls init_mplayer_erac() after most of the work is done.

Stepping through clone_mon:

```
$2 = {nmon = 0x0, data = 0x555556709d90 <mons+77168>, m_id = 74, mnum = 742, cham = -1, movement = 0, m_lev = 2 '\002', malign = 0 '\000',   mx = 9 '\t', my = 7 '\a', mux = 11 '\v', muy = 7 '\a', mtrack = {{x = 9 '\t', y = 8 '\b'}, {x = 0 '\000', y = 0 '\000'}, {x = 0 '\000',       y = 0 '\000'}, {x = 0 '\000', y = 0 '\000'}}, mhp = 12, mhpmax = 12, mappearance = 0, rider_id = 0, m_ap_type = 0 '\000', mtame = 0 '\000',   mintrinsics = 0, mextrinsics = 0, mspec_used = 0, seen_resistance = 0, female = 1, minvis = 0, invis_blkd = 0, perminvis = 0, mcan = 0,   mburied = 0, mundetected = 0, mcansee = 1, mspeed = 0, permspeed = 0, mrevived = 0, mcloned = 0, mavenge = 0, mflee = 0, mfleetim = 0,   msleeping = 0, mblinded = 0, mstun = 0, mfrozen = 0, mcanmove = 1, mconf = 0, mreflect = 0, msick = 0, msickbyu = 0, mdiseased = 0, mdiseabyu = 0,   mpeaceful = 0, mtrapped = 0, mleashed = 0, uexp = 0, mtraitor = 0, isshk = 0, isminion = 0, isgd = 0, ispriest = 0, isqldr = 0, iscerberus = 0,   isvecna = 0, isgrund = 0, iswiz = 0, wormno = 0, mwither_from_u = 0, mstonebyu = 0, mstone = 0, mberserk = 0, mwither = 0 '\000',   vuln_fire = 0 '\000', vuln_cold = 0 '\000', vuln_elec = 0 '\000', vuln_acid = 0 '\000', mstrategy = 0, mtrapseen = 0, mlstmv = 0, mspare1 = 0,   minvent = 0x60c000003580, mw = 0x0, misc_worn_check = 536870916, weapon_check = 0 '\000', meating = 0, msummoned = 0, msicktime = 0,   mdiseasetime = 0, mreflecttime = 0, mprotection = 0 '\000', mprottime = 0 '\000', former_rank = {lev = 0, mnum = -1, female = 0 '\000'},   mextra = 0x606000001700}

(gdb) p *m2
$3 = {nmon = 0xbebebebebebebebe, data = 0xbebebebebebebebe, m_id = 3200171710, mnum = -16706, cham = -16706, movement = -16706, m_lev = 190 '\276',   malign = -66 '\276', mx = -66 '\276', my = -66 '\276', mux = -66 '\276', muy = -66 '\276', mtrack = {{x = -66 '\276', y = -66 '\276'}, {      x = -66 '\276', y = -66 '\276'}, {x = -66 '\276', y = -66 '\276'}, {x = -66 '\276', y = -66 '\276'}}, mhp = -1094795586, mhpmax = -1094795586,   mappearance = 3200171710, rider_id = 3200171710, m_ap_type = 190 '\276', mtame = -66 '\276', mintrinsics = 13744632839234567870,   mextrinsics = 13744632839234567870, mspec_used = -1094795586, seen_resistance = 13744632839234567870, female = 0, minvis = 1, invis_blkd = 1,   perminvis = 1, mcan = 1, mburied = 1, mundetected = 0, mcansee = 1, mspeed = 2, permspeed = 3, mrevived = 1, mcloned = 1, mavenge = 0, mflee = 1, 
  mfleetim = 62, msleeping = 1, mblinded = 62, mstun = 1, mfrozen = 62, mcanmove = 1, mconf = 0, mreflect = 1, msick = 3, sickbyu = 1,   mdiseased = 1, mdiseabyu = 0, mpeaceful = 1, mtrapped = 0, mleashed = 1, uexp = 1, mtraitor = 1, isshk = 1, isminion = 1, isgd = 0, ispriest = 1,   isqldr = 0, iscerberus = 1, isvecna = 1, isgrund = 1, iswiz = 1, wormno = 30, mwither_from_u = 1, mstonebyu = 0, mstone = 5, mberserk = 1,   mwither = 190 '\276', vuln_fire = 190 '\276', vuln_cold = 190 '\276', vuln_elec = 190 '\276', vuln_acid = 190 '\276',   mstrategy = 13744632839234567870, mtrapseen = -4702111234474983746, mlstmv = -4702111234474983746, mspare1 = -4702111234474983746,   minvent = 0xbebebebebebebebe, mw = 0xbebebebebebebebe, misc_worn_check = -4702111234474983746, weapon_check = -66 '\276', meating = -1094795586,   msummoned = -1094795586, msicktime = -1094795586, mdiseasetime = -1094795586, mreflecttime = -1094795586, mprotection = 190 '\276',   mprottime = 190 '\276', former_rank = {lev = -1094795586, mnum = -16706, female = -66 '\276'}, mextra = 0xbebebebebebebebe}

```
