### ISSUE TITLE
Found with fuzzer: Mysterious material/object in searmsg

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#8]
`Program received signal SIGSEGV, Segmentation fault.
0x0000555555ef35bf in xname_flags (obj=0x555556456940 <zeroobj>, cxn_flags=0) at objnam.c:631
631	        obj->dknown = 1;
Continuing.

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.

#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7365859 in __GI_abort () at abort.c:79
#2  0x0000555555a44c60 in NH_abort () at end.c:236
#3  0x0000555555a44a48 in panictrace_handler (sig_unused=11) at end.c:161
#4  <signal handler called>
#5  0x0000555555ef35bf in xname_flags (obj=0x555556456940 <zeroobj>, cxn_flags=0)
    at objnam.c:631
#6  0x0000555555ef2d85 in xname (obj=0x555556456940 <zeroobj>) at objnam.c:581
#7  0x0000555555eff5a3 in cxname (obj=0x555556456940 <zeroobj>) at objnam.c:1876
#8  0x00005555562defa9 in searmsg (magr=0x611000482dc0, mdef=0x5555567b8fc0 <youmonst>, 
    obj=0x555556456940 <zeroobj>, minimal=0 '\000') at weapon.c:601
#9  0x0000555555cb9ef5 in hitmu (mtmp=0x611000482dc0, mattk=0x5555566032b8 <mons+62104>)
    at mhitu.c:2622
#10 0x0000555555ca3de6 in mattacku (mtmp=0x611000482dc0) at mhitu.c:1172
#11 0x0000555555e37eaf in dochug (mtmp=0x611000482dc0) at monmove.c:964
#12 0x0000555555e2331f in dochugw (mtmp=0x611000482dc0) at monmove.c:122
#13 0x0000555555d92b5e in movemon () at mon.c:1509
#14 0x000055555575b28a in moveloop (resuming=0 '\000') at allmain.c:244
#15 0x00005555563b4110 in main (argc=0, argv=0x7fffffffe658) at ../sys/unix/unixmain.c:353

Full Backtrace:

#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {1024, 0, 0, 0, 0, 140737337632192, 93824997411122, 335544320, 
            140737341055120, 1073741824, 0, 140737342801568, 4294967295, 140737337360384, 
            140737342784672, 7917269912298179840}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007ffff7365859 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0xffffffff, sa_sigaction = 0xffffffff}, 
          sa_mask = {__val = {140737337360384, 140737342784672, 7917269912298179840, 
              140737488341408, 140737342801568, 18446744073709547520, 140737327112192, 
              140737345470680, 0, 93825009803712, 140737344339986, 17592186042676, 
              140737488334848, 140737341055120, 7917269912298179840, 93825011573648}}, 
          sa_flags = -1452552960, sa_restorer = 0x555556456940 <zeroobj>}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x0000555555a44c60 in NH_abort () at end.c:236
        gdb_prio = 1
        libc_prio = 2
        aborting = 1 '\001'
#3  0x0000555555a44a48 in panictrace_handler (sig_unused=11) at end.c:161
        f2 = 18
#4  <signal handler called>
No locals.
#5  0x0000555555ef35bf in xname_flags (obj=0x555556456940 <zeroobj>, cxn_flags=0)
    at objnam.c:631
        buf = 0x5555567c6390 <obufs+1360> ""
        obufp = 0x7fffffffd770 "P\331\377\377\377\177"
        typ = 0
        ocl = 0x5555566161c0 <objects>
        nn = 1
        omndx = 0
        orig_opknwn = 0
        actualn = 0x555556410820 "strange object"
        dn = 0x555556410820 "strange object"
        un = 0x0
        pluralize = 1 '\001'
        known = 0 '\000'
        dknown = 0 '\000'
        bknown = 0 '\000'
#6  0x0000555555ef2d85 in xname (obj=0x555556456940 <zeroobj>) at objnam.c:581
No locals.
#7  0x0000555555eff5a3 in cxname (obj=0x555556456940 <zeroobj>) at objnam.c:1876
No locals.
#8  0x00005555562defa9 in searmsg (magr=0x611000482dc0, mdef=0x5555567b8fc0 <youmonst>, 
    obj=0x555556456940 <zeroobj>, minimal=0 '\000') at weapon.c:601
        onamebuf = "\377\377\377\377\377\177\000\000\006\000\000\000\000\000\000\000\200\377G\000\020a\000\000`\305R\367\377\177", '\000' <repeats 11 times>, "\315k\251\t\313\337m\200\377G\000\020a\000\000\000\315k\251\t\313\337m\340\337\377\377\377\177\000\000`\336\377\377\377\177\000\000\340\337\377\377\377\177\000\000\200\336\377\377\377\177\000\000@\341\377\377\377\177\000\000e\306b\367\377\177", '\000' <repeats 34 times>, "\060\337\377\377\000\000\000\000`\232QVUU\000\000\000\000\000\000 `\000\000\242\205n\367\377\177\000\000t\001\000\000p`\000\000 \000\000\000\060\000\000\000`\337\377\377\377\177\000\000"...
        whose = "\001\200\255\373p`\000\000t\001\000\000p`\000\000t\001\000\000p`\000\000t\001\000\000p`\000\000t\001\000\000p`\000\000v\001\000\000p`\000\000\377\377\377\377\377\377\377\377I+`\367\377\177\000\000\377\377\377\377\377\377\377\377", '\000' <repeats 40 times>, "\377\377\377\377", '\000' <repeats 14 times>, "\377\377\377\377\377\377\000\000\000\000\000\000\000\000\377\377\377\377\060`\000\000\020\202rVUU\000\000@\327\377\377\377\177\000\000F\270\bVUU\000\000\000\000\000\000\000\000\000\000`\305R\367\003\000\000\000P\327\377\377\377\177\000\000"...
        mat = 0
        whom = 0x0
        matname = 0x5555564573a0 "mysterious"
        cxnameobj = 0x6ddfcb09a96bcd00 <error: Cannot access memory at address 0x6ddfcb09a96bcd00>
        youattack = 0 '\000'
        youdefend = 0 '\000'
        has_flesh = 0 '\000'
#9  0x0000555555cb9ef5 in hitmu (mtmp=0x611000482dc0, mattk=0x5555566032b8 <mons+62104>)
    at mhitu.c:2622
        mdat = 0x5555566032a8 <mons+62088>
        uncancelled = 1
        ptmp = 0
        dmg = 17
        armpro = 0
        permdmg = 0
        tmphp = 0
        buf = "\000\334\377\377\377\177\000\000\230+\346UUU\000\000\000\000\000\000\000\000\000\000\020\333\377\377\377\177\000\000\200\333\377\377\377\177\000\000\300-H\000\020a\000\000\000\000\000\000\000\000\000\000\360\332\377\000\002\000\000\000\377\377\377\377\377\017\000\000\000\000\000\000\001\000\000\000\263\212\265Ai\000\000\000\300-H\000\020a", '\000' <repeats 18 times>, "\300-H\000\020a\000\000\300-H\000\020a\000\000`\333\377\377\377\177\000\000\316S.VUU\000\000\000\000\000\000\001\000\067\000\037\000\000\000\350\377\377\377@iEVUU", '\000' <repeats 11 times>, "\334\377\377\377\177\000\000\240\333\377\377\377\177\000\000\060\334\377\377\377\177\000\000"...
        olduasmon = 0x5555566071a0 <mons+78208>
        res = 21845
        burnmsg = 0 '\000'
        armask = 393232
        hated_obj = 0x555556456940 <zeroobj>
        vorpal_wield = 0 '\000'
#10 0x0000555555ca3de6 in mattacku (mtmp=0x611000482dc0) at mhitu.c:1172
        hittmp = 0
        mattk = 0x5555566032b8 <mons+62104>
        alt_attk = {aatyp = 0 '\000', adtyp = 0 '\000', damn = 0 '\000', damd = 0 '\000'}
        i = 0
        j = 20
        k = 0
        tmp = 37
        sum = {0, 32767, 1435436062, 21845, -8800, 448}
        mdat = 0x5555566032a8 <mons+62088>
        marmf = 0x0
        ranged = 0 '\000'
        range2 = 0 '\000'
        foundyou = 1 '\001'
        youseeit = 1 '\001'
        skipnonmagc = 0 '\000'
#11 0x0000555555e37eaf in dochug (mtmp=0x611000482dc0) at monmove.c:964
        mdat = 0x5555566032a8 <mons+62088>
        tmp = <optimized out>
        mdummy = 0x0
        inrange = 1
        nearby = 1
        scared = 0
        oldx = 0
        oldy = 0
        mwalk_sewage = 0 '\000'
#12 0x0000555555e2331f in dochugw (mtmp=0x611000482dc0) at monmove.c:122
        x = 69
        y = 3
        already_saw_mon = 0 '\000'
        rd = 300
#13 0x0000555555d92b5e in movemon () at mon.c:1509
        mtmp = 0x611000482dc0
        nmtmp = 0x611000482c80
        somebody_can_move = 1 '\001'
#14 0x000055555575b28a in moveloop (resuming=0 '\000') at allmain.c:244
        moveamt = 24
        wtcap = 0
        change = 0
        monscanmove = 0 '\000'
        timeout_start = 25287
        past_clock = 90148
        elf_regen = 0 '\000'
        orc_regen = 1 '\001'
        vamp_regen = 1 '\001'
#15 0x00005555563b4110 in main (argc=0, argv=0x7fffffffe658) at ../sys/unix/unixmain.c:353
        fd = -1
        dir = 0x0
        exact_username = 0 '\000'
        resuming = 0 '\000'
        plsel_once = 1 '\001'

`

**Comment by elunna** [comment]
Fixed in this commit https://github.com/elunna/hackem/commit/8833b209f54ec106dbee0a06935990ee9235fc63

Thank you qt!
