### ISSUE TITLE
Found with fuzzer: invalid material 4 (otyp 612) obj 60c000437e00 invent: 2 uncursed rocks (wielded)

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#81]
```
Suddenly, the dungeon collapses.
invalid material 4 (otyp 612) obj 60c000437e00 invent: 2 uncursed rocks (wielded)
Generating more information you may report:

[0] /lib/x86_64-linux-gnu/libasan.so.5(+0x6cd40) [0x7ffff75f8d40]
[1] /home/lunatunez/games/hackemdir/hackem(+0x4fccdf) [0x555555a50cdf]
[2] /home/lunatunez/games/hackemdir/hackem(+0x4fcbd2) [0x555555a50bd2]
[3] /home/lunatunez/games/hackemdir/hackem(panic+0x6ab) [0x555555a579f4]
[4] /home/lunatunez/games/hackemdir/hackem(impossible+0x2c8) [0x555555fb2c9d]
[5] /home/lunatunez/games/hackemdir/hackem(+0x8137c8) [0x555555d677c8]
[6] /home/lunatunez/games/hackemdir/hackem(+0x812f0c) [0x555555d66f0c]
[7] /home/lunatunez/games/hackemdir/hackem(obj_sanity_check+0x4b9) [0x555555d66535]
[8] /home/lunatunez/games/hackemdir/hackem(sanity_check+0xd) [0x555555867f01]
[9] /home/lunatunez/games/hackemdir/hackem(moveloop+0x6c1c) [0x555555769842]
[10] /home/lunatunez/games/hackemdir/hackem(main+0xdda) [0x5555563e367c]
[11] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7ffff7365083]
[12] /home/lunatunez/games/hackemdir/hackem(_start+0x2e) [0x555555760ace]


Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7363859 in __GI_abort () at abort.c:79
#2  0x0000555555a50bf8 in NH_abort () at end.c:236
#3  0x0000555555a579f4 in panic (str=0x55555654f720 "%s") at end.c:802
#4  0x0000555555fb2c9d in impossible (s=0x5555565036e0 <ofmt0> "%s obj %s %s: %s") at pline.c:518
#5  0x0000555555d677c8 in insane_object (obj=0x60c000437e00, 
    fmt=0x5555565036e0 <ofmt0> "%s obj %s %s: %s", 
    mesg=0x7fffffffe0d0 "invalid material 4 (otyp 612)", mon=0x0) at mkobj.c:2799
#6  0x0000555555d66f0c in objlist_sanity (objlist=0x60c000437e00, wheretype=3, 
    mesg=0x5555565038e0 "invent sanity") at mkobj.c:2717
#7  0x0000555555d66535 in obj_sanity_check () at mkobj.c:2631
#8  0x0000555555867f01 in sanity_check () at cmd.c:4855
#9  0x0000555555769842 in moveloop (resuming=0 '\000') at allmain.c:794
#10 0x00005555563e367c in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {0, 0, 0, 0, 0, 140737335783280, 93824997460170, 335544320, 
            140737341046928, 1073741824, 0, 140737342793376, 4294967295, 140737337360384, 
            140737342776480, 10200967854838143232}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007ffff7363859 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0xffffffff, sa_sigaction = 0xffffffff}, 
          sa_mask = {__val = {140737337360384, 140737342776480, 10200967854838143232, 
              140737488343824, 140737342793376, 18446744073709547520, 140737327104000, 
              140737345462488, 140737488344896, 140737488344896, 140737344331794, 
              17592186042978, 140737488338944, 140737341046928, 10200967854838143232, 
              140737488344224}}, sa_flags = -1999742720, sa_restorer = 0x7fffffffd660}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x0000555555a50bf8 in NH_abort () at end.c:236
        gdb_prio = 1
        libc_prio = 2
        aborting = 1 '\001'
#3  0x0000555555a579f4 in panic (str=0x55555654f720 "%s") at end.c:802
        the_args = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7fffffffd730, 
            reg_save_area = 0x7fffffffd660}}
#4  0x0000555555fb2c9d in impossible (s=0x5555565036e0 <ofmt0> "%s obj %s %s: %s") at pline.c:518
        pbuf = "invalid material 4 (otyp 612) obj 60c000437e00 invent: 2 uncursed rocks (wielded)", '\000' <repeats 15 times>, "\004", '\000' <repeats 15 times>, "\b", '\000' <repeats 15 times>, " ", '\000' <repeats 15 times>, "\001", '\000' <repeats 15 times>, "\002", '\000' <repeats 15 times>, "@", '\000' <repeats 17 times>, "\002", '\000' <repeats 15 times>...
        the_args = {{gp_offset = 40, fp_offset = 48, overflow_arg_area = 0x7fffffffde20, 
            reg_save_area = 0x7fffffffdd40}}
#5  0x0000555555d677c8 in insane_object (obj=0x60c000437e00, 
    fmt=0x5555565036e0 <ofmt0> "%s obj %s %s: %s", 
    mesg=0x7fffffffe0d0 "invalid material 4 (otyp 612)", mon=0x0) at mkobj.c:2799
        objnm = 0x5555567f98c5 <obufs+581> "2 uncursed rocks (wielded)"
        monnm = 0x555556503fe0 "null!"
        altfmt = "\320\336\377\377\377\177\000\000@\212B\000\300`\000\000\005", '\000' <repeats 15 times>, "\263\212\265A\000\000\000\000`@PVUU\000\000\036~\326UUU\000\000@\024\n\000\020a\000\000\020\337\377\377\377\177\000\033\005\001\000\000U\033\005\001containe\000~C\000\300`\000\000sanity\000\000\000YΈ7\036\221\215\000\000\000\000\000\000\000\000\n\374\377\377\377\017\000\000P\340\377\377\377\177\000\000\060\342\377\377\377\177\000\000P\340\377\377\377\177\000\000\000\000\000\000\000\000\000\000P\342\377\377\377\177\000\000߫b\367\377\177\000\000\000\374\377\377\377\017\000\000\000\000\000\000\000\000\000\000 \000\000\000\060\000\000\000 \340"...
#6  0x0000555555d66f0c in objlist_sanity (objlist=0x60c000437e00, wheretype=3, 
    mesg=0x5555565038e0 "invent sanity") at mkobj.c:2717
        matbuf = "invalid material 4 (otyp 612)\000\000\000\060\341\377\377\377\177\000\000\020\342\377\377\377\177\000\000\000\342\377\377\377\177\000\000\360\341\377\377\377\177\000\000\340\300cVUU\000\000<\000\000\000\a\000\000\000\070\374\377\377\377\017\000\000@\024\n\000\020a\000\000\260\343\377\377\377\177\000\000\034\332\344UUU\000\000\000\000\000\000\000\000\000\000\300\341\377\377\377\177", '\000' <repeats 50 times>, "\300\241cVUU", '\000' <repeats 50 times>...
        maskbuf = "\377\377\377\377\377\377\377\377@\024\n\000\020a\000\000\260\340\377\377\377\177\000\000\203\\\342UUU\000\000\001\000\000\000!\000\000"
        bc_ok = 0 '\000'
        obj = 0x60c000437e00
#7  0x0000555555d66535 in obj_sanity_check () at mkobj.c:2631
        x = 80
        y = 21
        obj = 0x0
#8  0x0000555555867f01 in sanity_check () at cmd.c:4855
No locals.
#9  0x0000555555769842 in moveloop (resuming=0 '\000') at allmain.c:794
        moveamt = 24
        wtcap = 0
        change = 0
        monscanmove = 1 '\001'
        elf_regen = 1 '\001'
        orc_regen = 1 '\001'
        vamp_regen = 1 '\001'
#10 0x00005555563e367c in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
        fd = -1
        dir = 0x0
        exact_username = 0 '\000'
        resuming = 0 '\000'
        plsel_once = 1 '\001'
```

**Comment by elunna** [comment]
Material 4 = FLESH.
ROCK is usually made of MINERAL.

Possibilities:
* Scroll of transmogrify while wielding rocks (should have been fixed already)
* Wishing for a flesh stone? 
  "For what do you wish? fleshy rock" - But this didn't hard crash like the issue does.
* Hitting an egg with a cockatrice egg? (This seems to be impossible)

**Comment by elunna** [comment]
Tried wishing for dozens of b/c/u scrolls of transmogrify, wielding 2 rocks, and reading the scrolls - but no effect. The material would not set to anything but 21.

**Comment by elunna** [comment]
Stale issue
