### ISSUE TITLE
LeakSanitizer: Bomb throwing?

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#87]
```
Direct leak of 120 byte(s) in 1 object(s) allocated from:
    #0 0x7f9242707808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x561b74fc70bb in alloc /home/lunatunez/hackem/src/alloc.c:46
    #2 0x561b755b7ec0 in splitobj /home/lunatunez/hackem/src/mkobj.c:462
    #3 0x561b7522f164 in throw_obj /home/lunatunez/hackem/src/dothrow.c:289
    #4 0x561b7522f950 in dothrow /home/lunatunez/hackem/src/dothrow.c:357
    #5 0x561b750c80a4 in rhack /home/lunatunez/hackem/src/cmd.c:5553
    #6 0x561b74fc3cda in moveloop /home/lunatunez/hackem/src/allmain.c:826
    #7 0x561b75c4c009 in main ../sys/unix/unixmain.c:353
    #8 0x7f92423d3082 in __libc_start_main ../csu/libc-start.c:308
```

**Comment by elunna** [comment]
Can't reproduce
