### ISSUE TITLE
Found with fuzzer: Confused Scroll of cloning

### ISSUE THREAD

**Issue by elunna** [elunna/hackem#88]
```

Program received signal SIGSEGV, Segmentation fault.
0x00005555560ac4a1 in seffect_cloning (sobjp=0x7fffffffdf70) at read.c:3901
3901	                mtmp->mpeaceful = 1; 
#0  0x00005555560ac4a1 in seffect_cloning (sobjp=0x7fffffffdf70) at read.c:3901
#1  0x000055555608d6fe in seffects (sobj=0x60c0009f8e00) at read.c:2273
#2  0x0000555556070c5a in doread () at read.c:676
#3  0x00005555558700a5 in rhack (cmd=0x5555567ee6c0 <in_line> "r") at cmd.c:5553
#4  0x000055555576bcdb in moveloop (resuming=0 '\000') at allmain.c:826
#5  0x00005555563f40d2 in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
#0  0x00005555560ac4a1 in seffect_cloning (sobjp=0x7fffffffdf70) at read.c:3901
        mndx = 743
        sobj = 0x60c0009f8e00
        otmp = 0x0
        otmp2 = 0x7fffffffe0f0
        mtmp = 0x0
        otyp = 448
        otyp2 = 1434455463
        sblessed = 0 '\000'
        scursed = 0 '\000'
        confused = 1 '\001'
        already_known = 1 '\001'
#1  0x000055555608d6fe in seffects (sobj=0x60c0009f8e00) at read.c:2273
        obj = 0x0
        cost = 0
        cval = 0
        otyp = 448
        confused = 1 '\001'
        sblessed = 0 '\000'
        scursed = 0 '\000'
        already_known = 1 '\001'
        old_erodeproof = 0 '\000'
        new_erodeproof = 0 '\000'
        otmp = 0x0
        mtmp = 0x0
        mtmp2 = 0x0
        pseudo = 0x0
#2  0x0000555556070c5a in doread () at read.c:676
        scroll = 0x60c0009f8e00
        confused = 1 '\001'
        nodisappear = 0 '\000'
        mesg = 0x0
#3  0x00005555558700a5 in rhack (cmd=0x5555567ee6c0 <in_line> "r") at cmd.c:5553
        tlist = 0x5555566a9e20 <extcmdlist+2592>
        res = 688
        func = 0x55555606ccdc <doread>
        spkey = 0
        prefix_seen = 0 '\000'
        bad_command = 116 't'
        firsttime = 1 '\001'
#4  0x000055555576bcdb in moveloop (resuming=0 '\000') at allmain.c:826
        moveamt = 12
        wtcap = 0
        change = 0
        monscanmove = 0 '\000'
        elf_regen = 1 '\001'
        orc_regen = 1 '\001'
        vamp_regen = 1 '\001'
#5  0x00005555563f40d2 in main (argc=0, argv=0x7fffffffe628) at ../sys/unix/unixmain.c:353
        fd = -1
        dir = 0x0
        exact_username = 0 '\000'
        resuming = 0 '\000'
        plsel_once = 1 '\001'
```

**Comment by elunna** [comment]
#define	PM_ARCHEOLOGIST	743

Can't reproduce by starting an archeologist and reading an uncursed scroll of cloning confused.

Maybe archeologists were extinct, or the race it's trying to clone is extinct or genocided?
